### ISSUE TITLE
Admin user "datahub" has no admin rights in demo

### ISSUE THREAD

**Issue by ethaden** [datahub-project/datahub#10053]
**Describe the bug**
After having started the demo locally using the pythonic way, logging in with the datahub user is possible. But that user has no access permissions at all (even though it should have admin rights). It is not possible to evaluate the platform therefore.

**To Reproduce**
1. Start the demo
2. Log in with your browser with the "datahub" user
3. Try to change something

**Comment by mkaramuk** [comment]
I've deployed DataHub with helm chart and I am in the same way. It only gets admin rights after restarting the pods.
![Screenshot_20240316_183103](https://github.com/datahub-project/datahub/assets/39464118/7943c1c1-372b-446f-be52-3ab35857a6ad)
