### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by kingkong2019** [datahub-project/datahub#10078]
Describe the bug
Trying to follow dev tutorial - https://datahubproject.io/docs/developers/

To Reproduce

git clone https://github.com/datahub-project/datahub
cd datahub
./gradlew build
Error:
Task :buildSrc:compileJava FAILED
D:\datahub\buildSrc\src\main\java\io\datahubproject\OpenApiEntities.java:11: error: package com.linkedin.metadata.models.registry.config does not exist
import com.linkedin.metadata.models.registry.config.Entities;

Compiling with toolchain '/opt/jdk-17.0.9'.
Compiling with JDK Java compiler API.
/opt/datahub-master/buildSrc/src/main/java/io/datahubproject/OpenApiEntities.java:11: error: package com.linkedin.metadata.models.registry.config does not exist
import com.linkedin.metadata.models.registry.config.Entities;
                                                   ^
/opt/datahub-master/buildSrc/src/main/java/io/datahubproject/OpenApiEntities.java:12: error: package com.linkedin.metadata.models.registry.config does not exist
import com.linkedin.metadata.models.registry.config.Entity;
                                                   ^
/opt/datahub-master/buildSrc/src/main/java/io/datahubproject/OpenApiEntities.java:43: error: cannot find symbol
    private Map<String, Entity> entityMap;
                        ^
  symbol:   class Entity
  location: class OpenApiEntities
/opt/datahub-master/buildSrc/src/main/java/io/datahubproject/OpenApiEntities.java:191: error: cannot find symbol
    private ObjectNode buildEntitySchema(Entity entity, Set<String> aspectDefinitions, boolean isResponse) {

Expected behavior
Code compiled, auto-generated and so on, no any errors

Desktop (please complete the following information):

windows 11 and linux 7

**Comment by hsheth2** [comment]
@kingkong2019 unfortunately we don't actively support Windows https://datahubproject.io/docs/next/developers/#windows-compatibility 

Are you using WSL?

**Comment by jkeerthi-hbk** [comment]
@hsheth2 Hi! I'm also on windows 11, and facing the same issue. Is it not even supported on WSL? Because even on WSL I face the same errors. 
![image](https://github.com/datahub-project/datahub/assets/142390237/7b5802a0-bd6e-4d76-92bf-e4ecf4b0195c)

**Comment by hsheth2** [comment]
@jkeerthi-hbk can you try running `./gradlew build` from the WSL side? The fact that the path has `\` suggests that it's running in windows, not WSL.

**Comment by jkeerthi-hbk** [comment]
@hsheth2  Ran  `./gradlew build` from WSL, and same error exists.
![image](https://github.com/datahub-project/datahub/assets/142390237/44355903-9651-4de3-985b-da16bc2319d7)

**Comment by jkeerthi-hbk** [comment]
@hsheth2 Could you kindly help?
