### ISSUE TITLE
Custom Properties are deleted when a dataset is re-ingested

### ISSUE THREAD

**Issue by BrendanPC** [datahub-project/datahub#10094]
**Describe the bug**
After adding custom properties to a dataset, the properties all disappear the next time the ingestion runs for that dataset.

**To Reproduce**
1. Ingest a dataset. (I have verified the bug with source types Kafka and Clickhouse, but I believe it is independent of source type)
2. Add custom properties to the dataset. [Example code adding properties](https://github.com/datahub-project/datahub/blob/9659d6086739990dff7aa4551361b30a9e7993ee/metadata-ingestion/examples/library/dataset_add_properties.py#L37)
3. Verify that the custom properties have appeared in the DataHub UI for that dataset.
4. Trigger an ingestion run of the dataset.
5. Observe that all the custom properties have disappeared.

**Expected behavior**
Custom properties should not disappear.

**Setup:**
 - DataHub v.0.12.1

**Comment by ylwi** [comment]
We experience this with a Postgres source and we can't find this behaviour documented anywhere.

As mentioned in [this question on Slack](https://datahubspace.slack.com/archives/CUMUWQU66/p1715164498576389) there's an option in another source type ([Hive Metastore](https://datahubspace.slack.com/archives/CUMUWQU66/p1715164498576389)) to enable properties merge. It would be useful to have a similar option for other sources.

The workaround [mentioned in the same Slack thread](https://datahubspace.slack.com/archives/CUMUWQU66/p1717181871587249?thread_ts=1715164498.576389&cid=CUMUWQU66) about using a transformer works for us:
```
transformers:
  - type: "simple_add_dataset_properties"
    config:
      semantics: PATCH
      properties: {}
```
