### ISSUE TITLE
[java.lang.IllegalArgumentException: No patches specified] when using Java SDK DatasetPropertiesPatchBuilder

### ISSUE THREAD

**Issue by matzheng** [datahub-project/datahub#10122]
**Describe the bug**
When I was trying to using Java SDK 0.10.4 to add custom properties programaticly, I got the exception   **_java.lang.IllegalArgumentException: No patches specified_**

**To Reproduce**
1. Follow the official guide https://docs-website-1gv2yzn9d-acryldata.vercel.app/docs/api/tutorials/custom-properties 
2. Using Java SDK
`	
	public void DataHub_Emitter_Test() throws IOException, ExecutionException, InterruptedException {

		RestEmitter emitter = RestEmitter.create(b ->
				b.server("http://10.xxx.xxx.xxx:9002/"));

		Map<String, String> properties = new HashMap<>();
		properties.put("owner", "testowner");

		MetadataChangeProposal mcpw =
				new DatasetPropertiesPatchBuilder()
						.addCustomProperty("cluster_name", "datahubproject.acryl.io")
						.addCustomProperty("retention_time", "2 years")
						.urn(UrnUtils.toDatasetUrn("mssql", "XXXX.db_owner.XXXX", "PROD"))
						.build();`
}
`

**Expected behavior**
There should be no exceptions using Java SDK.

**Screenshots**

**Additional context**

**Comment by mithilajoshi** [comment]
Faced this issue on `v0.13.2` of the datahub-client
