### ISSUE TITLE
[Tableau] workbook fetches the `id` field when the rest of project/dashboard/chart fetches the `luid` field

### ISSUE THREAD

**Issue by hhong96** [datahub-project/datahub#10124]
**Describe the bug**
There are two id fields that can be obtained from Tableau API. one is `id` and the other is `luid`. During Tableau ingestion, each level of entity (project, dashboard, and chart) follows a pattern where `id` field goes to the part of urn (i.e., urn:li:container:c1ab242005aa37f71b5927f399797c6c) and `luid` is appended to the property of an entity (i.e., project_id: '6ed17450-0108-4234-903f-23bf7d7f70ae'). Only the Workbook entity does not follow this pattern. The urn seems to be randomly generated, and `id` field is being appended to the property. This leaves us without having `luid` field for workbook, which is what Tableau REST API only accepts as unique identifier.

**To Reproduce**
1. Ingest Tableau data source.
2. Compare the urn/property with the actual Tableau API query result.

**Expected behavior**
Workbook should have `id` field as urn, append `luid` to the property, keeping the consistency with the other entities.

**Screenshots**

**Desktop (please complete the following information):**
- Mac OS
 - Chrome
 - 0.13.0

**Additional context**

**Comment by hsheth2** [comment]
@hhong96 the workbook urns are a guid generated by combining the platform, platform instance, and id (not luid)

I'd rather not change the way to construct urns since that'd be a breaking change, but I would definitely be open to adding some custom properties to the workbook container

Is that something you could open a PR for?
