### ISSUE TITLE
Where is the code base for the "acryl-executor" package? 

### ISSUE THREAD

**Issue by red8888** [datahub-project/datahub#10185]
**Describe the bug**
Sorry if this isn't really a "bug", but I can't find the actual code for this package on github https://pypi.org/project/acryl-executor/

Where is it? I had to install the package locally to see the code.

Thanks!

**Comment by hsheth2** [comment]
@red8888 unfortunately it's not open-source yet. The code is still pretty poorly written / not documented, so we've been hesitant to open the floodgates just yet.
