### ISSUE TITLE
Glossary term mismatch between the classifier and UI

### ISSUE THREAD

**Issue by ms32035** [datahub-project/datahub#10225]
**Describe the bug**
When I use the Snowflake field classification feature during metadata ingestion, the assigned terms have URNs like
`urn:li:glossaryTerm:IP%20Address` and these are not visible in the UI.

When I manually create create a term from the UI, the URN uses UIDs, for example:
`urn:li:glossaryTerm:6782cc0a-b9c3-451a-a523-f21692ef401f`

As a result the whole automatic classification feature is kind of useless

**To Reproduce**
Ingest snowflake data with classification enabled

**Expected behavior**
Consistent term URNs between the ui and the classified.

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/5060473/70bf253c-784a-4b03-9010-aea0d3cfc63f)

**Desktop (please complete the following information):**
 - Datahub 0.13
 - (https://pypi.org/project/acryl-datahub/0.13.1.3rc10/)

**Comment by hsheth2** [comment]
@ms32035 you can use the "advanced" section to ensure that the urns match. You can also managed the terms generated by the classifier in the UI.

<img width="518" alt="image" src="https://github.com/datahub-project/datahub/assets/12566801/c181aca8-da17-42f3-ae0a-07a05178822b">

**Comment by ms32035** [comment]
@hsheth2 thank's for the suggestion with a custom term ID. My term had a space in the classifier, so that's a case that can't be input through the UI, but I can replace with an underscore. At the same, the autogenerated terms don't show up in the UI.

**Comment by hsheth2** [comment]
@ms32035 that piece of it should be fixed by this https://github.com/datahub-project/datahub/pull/10249
