### ISSUE TITLE
Starburst/Trino integration not working properly

### ISSUE THREAD

**Issue by ishtartec** [datahub-project/datahub#10326]
Hi!,
when ingesting the audit data from Starburst, the integration fails silently with the following error:

```
- Error while parsing TrinoJoinedAccessEvent: 1 validation error for TrinoJoinedAccessEvent
create_time
  none is not an allowed value (type=type_error.none.not_allowed)
```
This integration executes a query that returns a ```create_time``` field with a DateTime format, but the code only returns the value if it is an string:

https://github.com/datahub-project/datahub/blob/d3fb698d8d9f50a56c14ed0172975f27f5c6567d/metadata-ingestion/src/datahub/ingestion/source/usage/starburst_trino_usage.py#L190

To fix this, I have slightly modified the code to return a value if the value is a DateTime type:

```python
def _convert_str_to_datetime(self, v):
        if isinstance(v, str):
            isodate = parser.parse(v)  # compatible with Python 3.6+
            return isodate
        if isinstance(v, datetime):
            return v
```

After this change, the integration works as expected.

Should I PR this or is it enough with this issue?

Thanks!

**Comment by pedro93** [comment]
Hello Sergio.

Please open a PR. cc @hsheth2

**Comment by hsheth2** [comment]
Closed by https://github.com/datahub-project/datahub/pull/10345
