### ISSUE TITLE
SiblingAssociationHook creates incorrect siblings for dbt entities

### ISSUE THREAD

**Issue by maiarareinaldo** [datahub-project/datahub#10406]
**Describe the bug**
dbt ingestion creates wrong siblings for dbt models that are also defined as sources in the dbt project. Like in the picture, there were suppose to be only `l4b_flags` Athena and dbt entities in the `Composed Of` section, instead there are 2 extra dbt models that shouldn't be there. (Note: the 2 extra models are downstream to the `l4b_flags` one.)

![Screenshot 2024-05-01 at 10 47 36](https://github.com/datahub-project/datahub/assets/72740386/f2f1da15-812c-439e-9449-6f8e82b42bf6)

**To Reproduce**
Steps to reproduce the behavior (a prerequisite is to have a dbt model that is also defined as a source in the dbt project):
1. Have separate recipes: one to ingest dbt sources only and the other to ingest models only (instead of having a single recipe to ingest the both, this is needed to ensure the models keep their upstream lineage).
2. Run the sources recipe ingestion
3. Run the models recipe ingestion
4. Run the sources recipe ingestion a second time (this is when the bug is introduced).

**Expected behavior**
The dbt siblings are created correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Comment by hsheth2** [comment]
@maiarareinaldo make sure you're following the best practices for multiple dbt projects https://datahubproject.io/docs/generated/ingestion/sources/dbt/#multiple-dbt-projects
