### ISSUE TITLE
Quoted searches with underscores return non-exact matches

### ISSUE THREAD

**Issue by murdo-moj** [datahub-project/datahub#10505]
Hello, the DataHub demo instance's search appears to be broken. I am looking at [an example from the docs](https://datahubproject.io/docs/how/search/#advanced-queries):

> If you want to:
>- Exact match on term or phrase
>    - "datahub_schema" [Sample results](https://demo.datahubproject.io/search?>page=1&query=%22datahub_schema%22)
>    - datahub_schema [Sample results](https://demo.datahubproject.io/search?page=1&query=datahub_schema)
>    - Enclosing one or more terms with double quotes will enforce exact matching on these terms, preventing further tokenization.

Both of the results here are the same with 393 results. The quotes aren't doing anything. Perhaps they are being stripped somewhere before the query is passed to elasticsearch?

**Comment by tom-webber** [comment]
Further context from some experimentation:

The underscore character does appear to be adding some wildcard functionality that spaces do not.
Here are some example searches in the demo instance and the number of results returned:

| Search term | Demo Link | Number of results |
|-|-|-|
| `"datahub_schema"` | ([demo](https://demo.datahubproject.io/search?page=1&query=%2522datahub_schema%2522&unionType=0)) | `393` |
|`datahub_schema` | ([demo](https://demo.datahubproject.io/search?page=1&query=datahub_schema&unionType=0)) | `393` |
| `"datahub schema"` | ([demo](https://demo.datahubproject.io/search?page=1&query=%2522datahub%2520schema%2522&unionType=0)) | `2` |
| `datahub schema` | ([demo](https://demo.datahubproject.io/search?page=1&query=datahub%2520schema&unionType=0)) | `42` |
| | | |
| `datahub \| schema` | ([demo](https://demo.datahubproject.io/search?page=1&query=datahub%2520%257C%2520schema&unionType=0)) | `393` |
| | | |
| `datahub` | ([demo](https://demo.datahubproject.io/search?page=1&query=datahub&unionType=0)) | `51` |
| `schema` | ([demo](https://demo.datahubproject.io/search?page=1&query=schema&unionType=0)) | `384` |

**It appears as though the underscore character is forcing an 'OR' search** for the words it separates, regardless of the presence of quotes (whereas a space character leads to an 'AND' search without quotes, and a 'EXACT' search with quotes)
