### ISSUE TITLE
datahub-upgrade process aborts after 8 hours.

### ISSUE THREAD

**Issue by vejeta** [datahub-project/datahub#10557]
**Describe the bug**

We have DataHub deployed in K8s using custom manifests.

When Datahub is upgraded from one version to another, the `datahub-upgrade` process is run.

This will perform a reindex in Elastic Search. In systems with a lot of data, that process can take more than 8 hours, even days.

The process is not completed, it is aborted with this exception:
```
[main] ERROR c.l.m.s.e.i.ESIndexBuilder:438 - Index: dataprocessinstanceindex_v2 - 
Post-reindex document count is different, source_doc_count: 276893693 reindex_doc_count: 34953865"
```

**To Reproduce**

We are migrating DataHub from 0.12.0 to 0.13.0, this will trigger the `datahub-upgrade` process, that will perform
an Elastic Search reindex.

The reason why it's failing it's because we hit [the maximum 8 hours limit](
https://github.com/datahub-project/datahub/blob/8b6790e936d1201d87244bffe616cc41cad2c9c0/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java#L345):
``` 
final int maxReindexHours = 8;
```

[The process runs ](https://github.com/datahub-project/datahub/blob/8b6790e936d1201d87244bffe616cc41cad2c9c0/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java#L378) while it is under the 8 hours limit

[After running for more than 8 hours and the reindex is not complete](https://github.com/datahub-project/datahub/blob/8b6790e936d1201d87244bffe616cc41cad2c9c0/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java#L428), it will check the document count of the source index with the new index, and because they don't match (the reindex only reached 12%) it marks the job as failed.

```
[main] ERROR c.l.m.s.e.i.ESIndexBuilder:438 - Index: dataprocessinstanceindex_v2 - 
Post-reindex document count is different, source_doc_count: 276893693 reindex_doc_count: 34953865"
```

**Expected behavior**

We would expect the reindex work to complete successfully, instead of aborting at 8 hours.

Make [maxReindexHours](https://github.com/datahub-project/datahub/blob/8b6790e936d1201d87244bffe616cc41cad2c9c0/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java#L345) configurable.

So everyone can set their custom time limits for the upgrade process.

**Desktop (please complete the following information):**
Datahub version 0.13.0

**Additional context**

The dataprocessinstanceindex_v2 seems to have almost 93 million entities. We tried several runs of the upgrade job and The job will restart from the beginning after each failure.

Related files:
https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
https://github.com/datahub-project/datahub/blob/master/docker/datahub-upgrade/README.md#L32

**Comment by vejeta** [comment]
This was tested in Datahub version 0.13.0. 
The code in DataHub is still the same for 0.13.3.
See: https://github.com/datahub-project/datahub/blob/v0.13.3/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/indexbuilder/ESIndexBuilder.java#L345

**Comment by david-leifker** [comment]
That should take care of the timeout. Thanks!

**Comment by vejeta** [comment]
Thanks @david-leifker! 🚀

**Comment by matthew-coudert-cko** [comment]
We have a similar problem with dataProcessInstances, our solution has been to just go into the mysql DB and delete them ourselves before performing a reindex.
