### ISSUE TITLE
After connecting airflow, the platform of trino operator's in/outlet is changed to presto.

### ISSUE THREAD

**Issue by shepherd44** [datahub-project/datahub#10558]
**Describe the bug**
Integrate using the airflow plugin v2 and then, TrinoOperator to run a query and see that the task flow and dataset are opened.
However, the dataset was linked to presto instead of trino, so it was being captured as a different dataset than the trino dataset I had linked to.

OL_SCHEME_TWEAKS seems to change trino to presto, but why is it like this?
I am having a problem with dataset separation when writing trino ingestion together.
Is it not possible to make the dataset platform of airflow Trino Operator come out as trino in order to use trino ingestion together?

**To Reproduce**
1. airflow plugin v2 integration
2. use TrinoOperator
3. inlet/outlet dataset comes out as presto

**Expected behavior**
I want the platform of the TrinoOperator to come out as trino.

**Comment by hsheth2** [comment]
I'm not sure why that mapping is on `OL_SCHEME_TWEAKS`. Presto was the old name of trino, but we use trino throughout our codebase. 

Would you be up for creating a PR to remove that from the mapping?

**Comment by shepherd44** [comment]
Yes. Let's modify it and create a PR.
