### ISSUE TITLE
Add pydantic v2 support

### ISSUE THREAD

**Issue by svdimchenko** [datahub-project/datahub#10708]
**Problem statement:**
I was trying to install acryl-datahub together with pyiceberg library but got a conflict due to pydantic dependency.
The [issue](https://github.com/pydantic/pydantic/issues/4887) mentioned in the [acryl-datahub code ref](https://github.com/datahub-project/datahub/blob/bb44c4c265e26ff19a27b76bd96231e7862c233d/metadata-ingestion/setup.py#L60) seems to be already resolved.
It would be nice to add pydantic v2 support to acryl-datahub library.

**Comment by hsheth2** [comment]
I believe this was fixed in #10614

**Comment by svdimchenko** [comment]
@hsheth2 seems yes, thanks for rapid fix 💯 
looking forward for the nearest release then 🚀
