### ISSUE TITLE
datahub user has no admin role and has no privileges 

### ISSUE THREAD

**Issue by uselessidbr** [datahub-project/datahub#10719]
**Describe the bug**
A fresh Helm install of datahub version 0.13.2 does not provide an user with admin role. The default user does not have any privileges and so cannot see any tabs/pages other than the main page and it’s own profile page. The data ingested also presents “unauthorized” error when accessed.

**To Reproduce**
Simply install datahub using helm

**Expected behavior**
It was expected the datahub user to have admin privileges and access all tabs.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari or Chrome

**Comment by uselessidbr** [comment]
datahub-gms logs:

`Tried to get entity privileges for entity type corpuser`

**Comment by uselessidbr** [comment]
We managed to solve this, We had to enable “datahubSystemUpdate” and “datahubUpgrade”, “systemUpdate”, “nonblocking” that were previously disabled.

Also we’ve changed two settings, so, i’m not sure of which one fixed the problem:

- SET KAFKA ENV for KERBEROS and also the volumes and volumemounts on “datahubSystemUpdate” and “datahubUpgrade”;
- SET to “true” the ENV REST_API_AUTHORIZATION_ENABLED on “datahub-gms”.

**Comment by uselessidbr** [comment]
Don’t forget to run the “datahub-restore-indices-adhoc” job :)

**Comment by vpipkt** [comment]
In datahub version 1.0.0 I had the same bug as described above, installing the Helm chart using ArgoCD. I fixed this by starting fresh with my prerequisites  (not sure how much this matters), setting helm values `global.datahub.systemUpdate.enabled: true` , and rolling out the helm chart again in argoCD.
