### ISSUE TITLE
[bug] There is max_retries option for Tableau ingestion but it won't work

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#10760]
**Describe the bug**
In the docs:

max_retries
integer
Number of retries for failed requests.
Default: 3

In fact:

```
configured successfully. DataHubRestEmitter: configured '
           'to talk to http://datahub-gms-datahub-gms:8080 with token: eyJh**********_1YA\n'
           'Failed to configure the source (tableau): 1 validation error for TableauConfig\n'
           'max_retries\n'
           '  extra fields not permitted (type=value_error.extra)\n',
           "2024-06-21 08:59:32.429377 [exec_id=9debef30-5ba0-4a53-911c-a111147fe483] INFO: Failed to execute 'datahub ingest'",
```

Tried this way:
```
source:
    type: tableau
    config:
        ingest_owner: false
        platform_instance: tableau_prod
        connect_uri: 'https://tableau.XX.XX'
        ingest_tables_external: false
        ingest_tags: false
        page_size: 2
        max_retries: 7
        workbook_page_size: 1
        stateful_ingestion:
            enabled: true
            remove_stale_metadata: true
```

**To Reproduce**

**Expected behavior**

options to configure retries 

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. ]

**Additional context**

Datahub version 0.12

**Comment by mayurinehate** [comment]
`max_retries` was introduced in 0.12.1.1 and is available all versions thereafter. Please update datahub CLI version to use this config.

You can refer to versioned docs on datahub to confirm config options available in particular DataHub version. 
![image](https://github.com/datahub-project/datahub/assets/33225191/8ebb0124-4690-43a6-8200-60d0c4877ced)

**Comment by YuriyGavrilov** [comment]
Thx 🙏 @mayurinehate
