### ISSUE TITLE
Need information about the ElasticSearch version as free license

### ISSUE THREAD

**Issue by spicoflorin** [datahub-project/datahub#10806]
Hello!
I would like to clarify if the used version of ElasticSerach is the open source free one and not the one that has the ElasticSearch license (commercial).

I've search over the provided documentation and issues and unfortunately I could not find any information about the license if this component. Maybe I'm not looking on the right place or I missed something.

Therefore, can you please help me to find the place where this aspect is clarified in your documentation?

I'm in the process of evaluation of a data catalog solution I would like to have the full understating of license involved.

Thank you.
 Florin

**Comment by hsheth2** [comment]
We mainly use Elastic 7.10, which is the last version to use the Apache License. We also support OpenSearch, which is a permissively licensed fork of ElasticSearch.
