### ISSUE TITLE
acryl-datahub-airflow-plugin 0.13.3.2 ImportError: cannot import name 'CustomAssertionInfoClass' from 'datahub.metadata.schema_classes' 

### ISSUE THREAD

**Issue by am2222** [datahub-project/datahub#10889]
**Describe the bug**
Hi,
After upgrading the version of the plugin to ` 0.13.3.2` I keep getting this error

```
ImportError: cannot import name 'CustomAssertionInfoClass' from 'datahub.metadata.schema_classes' (/home/***/python3.10/site-packages/datahub/metadata/schema_classes.py)
```

Is there any way I can debug to find potential conflicting packages?

**Comment by hsheth2** [comment]
@am2222 `acryl-datahub-airflow-plugin` and `acryl-datahub` should have the same version number. It seems like you might have a discrepancy somehow.

**Comment by am2222** [comment]
Thanks @hsheth2 I have updated both of their versions in my requirments.txt file. Does it matter if their order change in the text file? The interesting part is that I don't get any errors during package installation

**Comment by hsheth2** [comment]
@am2222 the order shouldn't matter. Not sure why you didn't get errors, but `pip` should've complained.

In any case, going to close this out.
