### ISSUE TITLE
GMS urn is not equal to ingestion for Lineage. 

### ISSUE THREAD

**Issue by zeta9044** [datahub-project/datahub#10969]
In version 0.13.3 of sqlglot_lineage.py, the parameters of the create_lineage_sql_parsed_result function are as follows: query, graph, platform, platform_instance, env, default_db, and default_schema. For proper mapping of the ingestion values to the actual URN in gms data, platform_instance should correspond to the database name, default_db to the DB schema, and default_schema should be left empty. This has been verified with Snowflake and Postgres. Are the developers currently aware of this?

**Comment by treff7es** [comment]
@zeta9044 Ideally, `platform_instance` should be the platform instance in the parameter and not the `database_name`, and `default_db` should be the default database name, which will be used if the referenced table doesn't contain the database part in the SQL.
Please, can you elaborate on what issue you see exactly?

**Comment by zeta9044** [comment]
This is GMS of mine - postgres. ``` urn:li:dataset:(urn:li:dataPlatform:postgres,postgres.admin.board_contents,PROD) ```
This is ingestion.yml of postgres.
```source:
  type: postgres
  config:
    # Coordinates
    host_port: KANGYOU:5432
    database: postgres

    # Credentials
    username: postgres
    password: postgres

    schema_pattern:
      allow:
        - "dlusr.*"
        - "admin.*" ```.   I tried to get metadata by sql_lineage.py. function ```create_lineage_sql_parsed_result```, when I input default_db:postgres,default_schema:admin,plantform_instance:postgres, I saw log of GMS 404. but when I input default_db:dlusr,plantform_instance:postgres, I saw ParseResult found by GMS.

**Comment by zeta9044** [comment]
if I add platform_instance, it was not happened. sorry. I should close.
