### ISSUE TITLE
Spark Agent: partition_regexp_pattern config doesn't work for paths without platform

### ISSUE THREAD

**Issue by hariishaa** [datahub-project/datahub#11024]
**Describe the bug**
I am trying to get lineage for Spark applications and HDFS directories via `acryl-spark-lineage:0.2.15` agent with `spark.datahub.partition_regexp_pattern` option enabled, but getting full path in Datahub without partition pruning. It seems that the problem is in [this line of code](https://github.com/datahub-project/datahub/blob/a09575fb6f00c9a3f372ef5938a6ac971b877f12/metadata-integration/java/openlineage-converter/src/main/java/io/datahubproject/openlineage/dataset/HdfsPathDataset.java#L60). It fails if there is no platform specification in a dataset path. My datasets are in format `"/aaa/bbb/ccc/p1=xxx/p2=yyy"` (no platform specified) and `spark.datahub.partition_regexp_pattern` is `"/[^/]+=.*|/$"` and it worked out with a deprecated `datahub-spark-agent` with `spark.datahub.metadata.remove_partition_pattern` option, but it doesn't with the new `acryl-spark-lineage` and `spark.datahub.partition_regexp_pattern` configuration.

**Expected behavior**
For an HDFS dataset with a path like `"/aaa/bbb/ccc/p1=xxx/p2=yyy"` and `spark.datahub.partition_regexp_pattern="/[^/]+=.*|/$"`  I would like to see a dataset `"/aaa/bbb/ccc"` in Datahub.

**Comment by steffengr** [comment]
I'm having the same issue but it looks like I do have platform in my uris:  `Dataset URN: Optional[urn:li:dataset:(urn:li:dataPlatform:s3,` but it always ignores that config option. It means that I have to specifically configure spark.datahub.platform.s3.path_spec_list for every output.

**Comment by steffengr** [comment]
I believe the issue to be this line https://github.com/datahub-project/datahub/blob/a09575fb6f00c9a3f372ef5938a6ac971b877f12/metadata-integration/java/openlineage-converter/src/main/java/io/datahubproject/openlineage/dataset/HdfsPathDataset.java#L83

It fetches the raw name and does not apply the regex if it was not null. I suspect the condition should be rawName != null.

**Comment by steffengr** [comment]
I spent some time digging in the sources and I found a working test case for using a regex to remove date partitioning: 
https://github.com/datahub-project/datahub/blob/a09575fb6f00c9a3f372ef5938a6ac971b877f12/metadata-integration/java/acryl-spark-lineage/src/test/java/datahub/spark/HdfsPathDatasetTest.java#L80

The test is working but it references a different config option than mentioned in the documentation:
https://github.com/datahub-project/datahub/blob/a09575fb6f00c9a3f372ef5938a6ac971b877f12/metadata-integration/java/acryl-spark-lineage/src/main/java/datahub/spark/conf/SparkConfigParser.java#L73

This means the config to be set should be spark.datahub.file_partition_regexp.
