### ISSUE TITLE
Error running ingest-sample-data

### ISSUE THREAD

**Issue by awkwardd** [datahub-project/datahub#11107]
After I followed the official quickstart documentation to complete the container configuration and successfully run it, an error occurred when executing ingest-sample-data.

The error log is as fellows:

ERROR    {datahub.ingestion.run.pipeline:738} - Pipeline Error: Ingestion pipeline raised an unexpected exception!Pipeline Error: Ingestion pipeline raised an unexpected exception!: 'Did not find a registered class for c'
Pipeline finished with at least 1 failures; produced 0 events in 0 seconds.

 - OS:Windows 11
 - Version:0.13.46
 - Python Version:3.10.11

How can I fix it?

**Comment by byqsri** [comment]
I have the same error...How do you have resolved it?
Thanks

**Comment by brintadis** [comment]
I have the same error is there a solution?

**Comment by DaNnyKg07** [comment]
Is this issue resolved?

**Comment by oshadhidksr** [comment]
Hi @awkwardd, I  got the same error.  Have you resolved it ?  Thanks

**Comment by datamacgyver** [comment]
If you are here I suspect you are running in Windows. I would suggest running in WSL/Linux/Mac

**Comment by cedricp24** [comment]
Running it on Ubuntu (WSL) worked for me
