### ISSUE TITLE
Unity catalog fails with databricks-sdk==0.30.0

### ISSUE THREAD

**Issue by ssequ** [datahub-project/datahub#11173]
**Describe the bug**
Unity catalog ingestion fails with databricks-sdk==0.30.0. `databricks.sdk.service.sql.ExecuteStatementResponse` is removed in 0.30.0 but the datahub unity-catalog plugin expects it - hence the plugin throws an error on initialization.

See [databricks changelog](https://github.com/databricks/databricks-sdk-py/blob/main/CHANGELOG.md)

**To Reproduce**
Run `datahub docker quickstart` and create a unity-catalog ingestion. Ensure that the latest databricks-sdk version (0.30.0) is used. The ingestion should then fail, already during the plugin initialization phase. Checking the venv in the `datahub-actions` container and downgrading the databricks-sdk to <0.30.0 then make the ingestion work again.

**Expected behavior**
Either pin databrick-sdk to <0.30.0 or don't depend on ExecuteStatementResponse

**Screenshots**
![image](https://github.com/user-attachments/assets/fd5c58da-b8b6-4745-baa4-2e9dc7589e3b)

**Desktop (please complete the following information):**
Docker, Ubuntu 20.04 host.

**Comment by hsheth2** [comment]
This was fixed by https://github.com/datahub-project/datahub/pull/11158 and is part of datahub cli 0.14.0
