### ISSUE TITLE
Power BI Ingestion (Reports and Lineage)

### ISSUE THREAD

**Issue by aaverbec** [datahub-project/datahub#11204]
**Describe the bug**
We have been trying to ingest power bi reports into our datahub instance with mixed results.  The biggest issue which I have not been able to determine a work around for is that Power BI reports/dashboards show up without any lineage or names.  And you can't click on them in the search UI. The only way to determine which is which is to look at the code behind to UI page.    Power BI datasets and Power BI pages import correctly.  But the report name itself, the object that the end users would know, isn't appearing.

I have tried asking in the Slack channel and I also tried using the csv-enricher to populate the description and potentially figure out manual lineage.  But they do not seem to work either.

**To Reproduce**
I have created a recipe file that looks like this

`source:
  type: "powerbi"
  config:
    tenant_id: XXXXX
    client_id: XXXXX  
    client_secret: XXXXX

    workspace_id_pattern:
      allow:
        - 123123123-abcd-1234-abcd-123412342134

    extract_lineage: true
    extract_reports: true`

**Expected behavior**
Ideally I'd be able to see the lineage from the Snowflake table all the way to the Power BI report that the end user would see in Azure.

**Screenshots**

![image](https://github.com/user-attachments/assets/5526c3f8-39b0-4082-bc4a-08899a880d6a)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari]  Chrome

**Additional context**

**Comment by aaverbec** [comment]
Also, can you confirm that you can not use the csv enricher to add objects/descriptions for dashboards?  Only datasets?

**Comment by chrijun** [comment]
This has hopefully been fixed in #10910

**Comment by aaverbec** [comment]
Thanks Chris, Do you happen to know how to download that version?
When I execute   pip install 'acryl-datahub[powerbi, snowflake, dbt]'

It installs acryl-datahub, version 0.13.3

**Comment by chrijun** [comment]
When I run that command it installs version 0.14.0.3 as that is now the latest version. Otherwise, you can try and setting it manually via: `pip install 'acryl-datahub[powerbi, snowflake, dbt]==0.14.0.2'`

**Comment by aaverbec** [comment]
Thanks.  

pip install 'acryl-datahub[powerbi, snowflake, dbt]' --upgrade  

also worked.  I didn't realize it didn't check for the latest version if you already had it.

It does now bring in the Report name.  Lineage back to the Snowflake table is still a mixed bag, but I will close this issue and try to figure out if there's any specific scenarios that the parser is having problems with.
