### ISSUE TITLE
acryldata/datahub-kafka-setup image is missing a tag for v0.14.0.1 for the recent fix release.

### ISSUE THREAD

**Issue by chenteddybear** [datahub-project/datahub#11217]
acryldata/datahub-kafka-setup image is missing a tag for v0.14.0.1 for the recent fix release.

**Comment by david-leifker** [comment]
This image failed to build as the upstream dependency was removed. The follow-up image v0.14.0.2 updates this dependency and has a `datahub-kafka-setup` image.
