### ISSUE TITLE
33 open vulnerabilities (16 High & 17 Moderate)

### ISSUE THREAD

**Issue by mars-lan** [datahub-project/datahub#11233]
**Describe the bug**

As titled. See [this post](https://metaphor.io/blog/is-open-source-software-more-secure) for additional context.

**To Reproduce**
1. Fork the repo
2. Turn on `Dependency graph` & `Dependabot alerts` in `Code security and analysis`
3. View the alerts under `Security` tab
 
**Expected behavior**
0 vulnerability

**Screenshots**

<img width="1109" alt="Screenshot 2024-08-23 at 5 23 05 AM" src="https://github.com/user-attachments/assets/3e5fbee7-ea4d-459f-aea5-ce0a9c2f2132">

**Comment by david-leifker** [comment]
Our security stance is clearly documented [here](https://github.com/datahub-project/datahub/blob/master/docs/SECURITY_STANCE.md) for reference: - please review the reporting issues section. 

The team regularly reviews these findings for validity and fixes them if they impact DataHub’s operational environment. In addition, we routinely undergo thorough security review as a prerequisite to deployment at enterprises around the world.
 
As of today, there are 0 unresolved issues from dependabot. All issues have been triaged, vetted and resolved by the committers - this is something that is not visible on project forks.

![Screenshot 2024-09-20 at 4 19 28 PM](https://github.com/user-attachments/assets/b80dd7ca-7c6d-4d8d-b98d-44732410d34e)
