### ISSUE TITLE
python3 -m datahub docker quickstart command returns "No such file or directory: 'docker-compose': 'docker-compose'" error

### ISSUE THREAD

**Issue by CollinKendor** [datahub-project/datahub#11316]
I am trying to set up datahub for a prototype we are making for my company. However, after installing the datahub cli, executing the python3 -m datahub docker quickstart command returns the following error:

`[2024-09-06 05:40:39,004] ERROR    {datahub.entrypoints:189} - Command failed with [Errno 2] No such file or directory: 'docker-compose': 'docker-compose'. Run with --debug to get full trace`

I have verified that i have docker up and docker compose is installed:
![image](https://github.com/user-attachments/assets/e83c0d0e-8379-423d-ab41-3982bb537d74)

![image](https://github.com/user-attachments/assets/44a4c50d-b165-4a03-9d98-d4054b140570)

The error is achieved after running the following command:
1. run `python3 -m datahub docker quickstart`

Base on the documentations, I expected datahub to be up and running in a docker container after I run this command.

Below is the screenshot of the error:
![image](https://github.com/user-attachments/assets/2eb215e5-76e6-49fc-aec0-66c2ea0c32f1)

attached is the full stacktrace:
[log.txt](https://github.com/user-attachments/files/16903496/log.txt)

Server information:
 - OS: Red Hat Enterprise Linux
 - Version 8.10

What am I missing in the setup or config? Hope to hear from the team soon as I urgently need to get this up and running by next week.

**Comment by hsheth2** [comment]
@CollinKendor your datahub cli is extremely outdated. Please upgrade to the latest (0.14.0.4)

**Comment by KewMannDev** [comment]
HI just a little update, I discovered that my phthon3 was actually python 3.6 and that was causing the issue. I've since upgraded python to v3.8 and things are working now.

**Comment by hsheth2** [comment]
@KewMannDev that would do it. 

I'll close this issue out for now.

**Comment by KewMannDev** [comment]
quick question, where can I find the application.yaml for the metadata service to enable PATs? I can't seem to find it in the datahub-gms container
