### ISSUE TITLE
Request: Updating the sqlglotrs dependency

### ISSUE THREAD

**Issue by chriscc2** [datahub-project/datahub#11320]
Hi Datahub team, 

Currently we are facing issues with adopting your library due to upstream dependencies. Currently your team is using sqlglotrs 0.2.8, which does not have a license in pypi: https://pypi.org/project/sqlglotrs/0.2.8/ and the licensing document was excluded from the library download. My team has requested that the sqlglotrs team update their download with the license agreement in version 0.2.10 and forward. I was wondering if you team could also update the dependency to pull from 0.2.10 or 0.2.11? My team is hoping to release relatively soon, but can not do so due to this. We are trying to do some legal reviews for our launch by September 14th and would love to continue using datahub. 

Thanks,
Chris Chan

**Comment by shirshanka** [comment]
Hi @chriscc2 - could you contact @hsheth2 on [DataHub Slack](https://datahubproject.io/slack/) to carry this conversation further?

**Comment by hsheth2** [comment]
This PR https://github.com/datahub-project/datahub/pull/11331 will bump us to sqlglotrs 0.2.12

**Comment by dbjnbnrj** [comment]
Thanks for the help @hsheth2. How can we track if the latest version with the dependency is available on pypi?

**Comment by hsheth2** [comment]
@dbjnbnrj @chriscc2 this is part of acryl-datahub v0.14.0.5
