### ISSUE TITLE
SQL Column Level Lineage Case Sensitivity

### ISSUE THREAD

**Issue by ActiveIntJeremy** [datahub-project/datahub#11322]
**Describe the bug**
The column level lineage for SQL table/views does not work when a column name contains uppercase characters.  Ingestion was from a Microsoft SQL Server db and had `convert_urns_to_lowercase: true` enabled to improve table level lineage.  However, still not seeing column level lineage matching when a column contains any uppercase characters.

Example View Code:
`CREATE schema.view
AS
SELECT Source
FROM schema.table`

Checking in the metadata I see the following in the upstreamLineage aspect for this view:
`{"downstreamType":"FIELD","confidenceScore":1.0,"downstreams":["urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:mssql,instance.db.schema.view,PROD),source)"],"upstreamType":"FIELD_SET","upstreams":["urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:mssql,instance.db.schema.table,PROD),source)"]},`

However, the schemaMetadata for both the table and view have the field name in uppercase still, which seems to be the source of the lineage not showing.

**To Reproduce**
1. Create view which contains a column that includes an uppercase name.
2. Create SQL based ingestion with convert_urns_to_lowercase enabled.
3. Navigate to graph lineage page for the View and enable show columns
 
**Expected behavior**
Would be great if column level lineage can be shown even if a column name contains uppercase characters.  

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
This is based on the v0.14.0.2 docker image for Datahub.

**Comment by vladm** [comment]
any updates / plans to address this?
