### ISSUE TITLE
Looker query API breaking change

### ISSUE THREAD

**Issue by jrhode2** [datahub-project/datahub#11358]
**Describe the bug**
Looker metadata ingestion is failing with a 404 error when `extract_independent_looks` is set to `true`. The cause seems to be a Looker API change to disallow getting queries by numeric query IDs https://www.googlecloudcommunity.com/gc/Developing-Applications/queries-endpoint-always-returning-404/m-p/716679. Getting queries by slug still works.

**To Reproduce**
1. Create a Looker instance on the latest version of Looker with at lease 1 independent look
2. Try to run the Looker ingestion recipe with `extract_independent_looks` set to `true`

**Expected behavior**
Expected behavior is the recipe extracts metadata on Looker's looks without error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] N/A
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] I am running the recipe on the image `acryldata/datahub-ingestion:a3ef587f`

**Comment by hsheth2** [comment]
I believe this was fixed by https://github.com/datahub-project/datahub/pull/9865 - could you test with a more recent version?

**Comment by jrhode2** [comment]
That did it, thank you!
