### ISSUE TITLE
version 14.0  ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.8

### ISSUE THREAD

**Issue by zypjava** [datahub-project/datahub#11397]
ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.5 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.5 used for parser compilation does not match the current runtime version 4.8

**Comment by david-leifker** [comment]
The project does use a newer version of antlr exclusively, specifically 4.9 now. However an upstream project introduces 4.5 as a transitive depndency. The pegasus/rest.li libraries specifically. This hasn't caused an operational issue as the versions seem to be compatible enough. Restli seems to use this as part of its serialization/deserialization processes.

**Comment by zypjava** [comment]
谢谢，我已经收到你的邮件，我会尽快回复您！
