### ISSUE TITLE
Upgrade to pydantic 2

### ISSUE THREAD

**Issue by schoeberlt** [datahub-project/datahub#11394]
Hi, we are using pydantic 2 in our orchestration but noticed that datahub requires pydantic <2. Is there a plan to upgrade to pydantic 2? When can we expect it? Downgrading currently is not an option for us.

**Comment by schoeberlt** [comment]
`dagster._core.errors.DagsterImportError: Encountered ImportError: `cannot import name 'model_validator' from 'pydantic' (/opt/conda/lib/python3.10/site-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)` while importing module active_metadata_hub. Local modules were resolved using the working directory `/opt/dagster/dagster_home/src/active_metadata_hub`. If another working directory should be used, please explicitly specify the appropriate path using the `-d` or `--working-directory` for CLI based targets or the `working_directory` configuration option for workspace targets.`

This is the error that is caused by pydantic 2.

**Comment by Ohad-upriver** [comment]
I have the same problem.
Is that in the roadmap?

**Comment by hsheth2** [comment]
Take a look at the note we added to our docs here https://github.com/datahub-project/datahub/pull/11423
