### ISSUE TITLE
when will be release generative-ai?

### ISSUE THREAD

**Issue by johnfelipe** [datahub-project/datahub#11409]
https://www.youtube.com/watch?v=_7DieZeZspY

i want to test with my bigquery datalake

**Comment by johnfelipe** [comment]
??

**Comment by jjoyce0510** [comment]
Hey there! 

Thanks for your interest. AI-related features in the DataHub UI are currently only available in [DataHub Cloud](https://datahubproject.io/cloud). Please let me know if you'd like me to put you in touch with the team at Acryl to setup a trial account. 

Cheers
John
