### ISSUE TITLE
Quickstart starts a Datahub version without matching PyPi packages

### ISSUE THREAD

**Issue by edwinvehmaanpera** [datahub-project/datahub#11416]
**Describe the bug**
When running the `datahub docker quickstart` it seems it now uses `acryldata/datahub-frontend-react:head` (which seems to be v0.14.1?) and the when trying to use ingestion it cannot create a virtual env since there is no corresponding PyPi packages. Below is how this problem presents itself when trying to ingest metadata from Postgres.

**To Reproduce**
1. Follow [Datahub Quickstart](https://datahubproject.io/docs/quickstart)
2. Login using demo "datahub" account
3. Optional: to generate the below logs: Try to run metadata ingestion for Postgres

```
~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': '1d1c49ba-6f39-4b31-8601-56dd6ac5143a',
 'infos': ['2024-09-18 11:02:38.902353 INFO: Starting execution for task with name=RUN_INGEST',
           "2024-09-18 11:02:43.006269 INFO: Failed to execute 'datahub ingest', exit code 1",
           '2024-09-18 11:02:43.008867 INFO: Caught exception EXECUTING task_id=1d1c49ba-6f39-4b31-8601-56dd6ac5143a, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/datahub-ingestion/.venv/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 139, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/datahub-ingestion/.venv/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 400, in '
           'execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Logs ~~~~
Obtaining venv creation lock...
Acquired venv creation lock
venv doesn't exist.. minting..
Using Python 3.10.12 interpreter at: /usr/bin/python3
Creating virtualenv at: /tmp/datahub/ingest/venv-postgres-3cbb1ad0ed8a0388
Resolved 3 packages in 690ms
Prepared 3 packages in 268ms
Installed 3 packages in 972ms
 + pip==24.2
 + setuptools==75.1.0
 + wheel==0.44.0
+ uv pip install 'acryl-datahub[datahub-rest,datahub-kafka,postgres]==0.14.1'
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of acryl-datahub[postgres]==0.14.1 and
      you require acryl-datahub[postgres]==0.14.1, we can conclude that your
      requirements are unsatisfiable.
```

**Expected behavior**
Ingestion in the quickstart version works. Quickstart uses a fully supported version. Alternatively update the documentation to cover this issue.

**Desktop (please complete the following information):**
 - OS: Windows 11 using WSL
 - Browser Microsoft Edge Version 128.0.2739.79

**Comment by edwinvehmaanpera** [comment]
The issue itself resolved as the PyPi packages were updated with the 0.14.1 version. However the root cause still exists and should be fixed.

**Comment by james-larsen** [comment]
I'm getting the same issue when using Quickstart and trying to perform a dbt ingestion:

`~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': '20240006-70db-45c4-958f-daae42ca1dcd',
 'infos': ['2025-01-31 15:40:26.524331 INFO: Starting execution for task with name=RUN_INGEST',
           "2025-01-31 15:40:30.775089 INFO: Failed to execute 'datahub ingest', exit code 1",
           '2025-01-31 15:40:30.776539 INFO: Caught exception EXECUTING task_id=20240006-70db-45c4-958f-daae42ca1dcd, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/datahub-ingestion/.venv/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 139, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/datahub-ingestion/.venv/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 402, in '
           'execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Logs ~~~~
Obtaining venv creation lock...
Acquired venv creation lock
venv doesn't exist.. minting..
Using CPython 3.10.12 interpreter at: /usr/bin/python
Creating virtual environment at: /tmp/datahub/ingest/venv-dbt-9c8a88a4b3d58d78
Resolved 3 packages in 237ms
Prepared 3 packages in 2ms
Installed 3 packages in 2.66s
 + pip==25.0
 + setuptools==75.8.0
 + wheel==0.45.1
+ uv pip install 'acryl-datahub[datahub-rest,datahub-kafka,dbt]==1.0.0rc1'
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of acryl-datahub[dbt]==1.0.0rc1 and
      you require acryl-datahub[dbt]==1.0.0rc1, we can conclude that your
      requirements are unsatisfiable.`
