### ISSUE TITLE
Filter autocomplete doesn't show exact matches first and is limited to 10

### ISSUE THREAD

**Issue by pankajmahato-visa** [datahub-project/datahub#11411]
**Describe the bug**
This is a sample for container filter, but it is applicable for all filters.
When I filter by “opfrd” (or any schema: cscdl, aucdl)
 
The list returns with all partial matches first but not the exact match.
The list is also limited so I do not have the option to find my exact match.

**To Reproduce**
1. Go to 'Explore All'
2. Click on 'Container Filter'
3. Type "opfrd"
4. Only 10 results but not the exact match. Only partial matches showing first

**Comment by deepgarg-visa** [comment]
Attaching the screenshot for call made in Graphiql.

As we can see the exact matches "aucdl" are bottom in the list of "suggestions"

<img width="1590" alt="Screenshot 2024-10-08 at 2 14 18 PM" src="https://github.com/user-attachments/assets/dd0fb2f7-b0a2-44ff-bcbd-1ee6dbe81aa3">

**Comment by deepgarg-visa** [comment]
@david-leifker, Need your opinion on this

**Comment by david-leifker** [comment]
Resolved! Thanks @deepgarg-visa !
