### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by Jad-hamad** [datahub-project/datahub#11439]
(org.apache.zookeeper.ClientCnxn)
broker-1         | [2024-09-18 15:15:53,556] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)

Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-12752434521885606652, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -

| [2024-09-18 15:16:46,091] TRACE [Controller id=1 epoch=1] Received response UpdateMetadataResponseData(errorCode=0) for request UPDATE_METADATA with correlation id 0 sent to broker broker:29092 (id: 1 rack: null) (state.change.logger)

<img width="864" alt="image" src="https://github.com/user-attachments/assets/c319fe92-0697-41ef-846a-71e3a5f36364">

**Comment by jjoyce0510** [comment]
Hi there, do you mind providing some additional context around this request? This will help us to support you more effectively. 

I'm going to go ahead and close the issue until we have a 

1. Proper title
2. More detailed description of the issue 
3. Attached log file

Thank you!
