### ISSUE TITLE
git tool missing from the ingestion-base image

### ISSUE THREAD

**Issue by andor-pierdelacabeza** [datahub-project/datahub#11474]
**Describe the bug**
Since 2066f1f the `git` binary is missing from the `datahub-ingestion-base` images, making ingestions that import the `gitpython` module fail.

In 2066f1f the base image changed from `python:3.10` to `ubuntu:22.04`. The Python image includes `git`, but the Ubuntu doesn't, so after upgrading to the latest 0.14 Datahub version ingestions started to fail.

- `datahub-actions` image in versions 0.1.0 and 0.1.1 *doesn't* have `git`
  base image: `acryldata/datahub-ingestion-base:2066f1f` 
- `datahub-actions` image in version <=0.0.18 *does* have git
  base image: `acryldata/datahub-ingestion-base:3903b17`

Error message:

```
<class 'ImportError'>: Failed to initialize: Bad git executable. The git executable must be specified in one of the following ways: - be included in your $PATH - be set via $GIT_PYTHON_GIT_EXECUTABLE - explicitly set via git.refresh(<full-path-to-git-executable>) All git commands will error until this is rectified. This initial message can be silenced or aggravated in the future by setting the $GIT_PYTHON_REFRESH environment variable. Use one of the following values: - quiet|q|silence|s|silent|none|n|0: for no message or exception - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default) - error|e|exception|raise|r|2: for a raised exception Example: export GIT_PYTHON_REFRESH=quiet
```

**To Reproduce**
1. Get a Datahub deployment that uses a `datahub-actions` image with version >= 0.1.0
2. create an ingest job that _imports_ the `gitpython` module
3. Run the job

**Expected behavior**
`git`is available on the path

**Screenshots**

![missinggit](https://github.com/user-attachments/assets/f0dcbab2-c6cf-4010-8bf3-310dc357978a)

**Comment by andor-pierdelacabeza** [comment]
Nice, now the latest `ingestion-base` has `git` included... ❤️ 

@hsheth2 , maybe now a build of the `datahub-actions` image should be triggered so it builds on the new base?

**Comment by hsheth2** [comment]
@andor-pierdelacabeza yup - I just cut datahub-actions v0.1.2, which will have git in the image.

**Comment by hsheth2** [comment]
Now that https://github.com/acryldata/datahub-actions/pull/134 is merged, the datahub-actions `head` tag should also have git.
