### ISSUE TITLE
How to add a functionScore to boost Data Products?

### ISSUE THREAD

**Issue by echai58** [datahub-project/datahub#11483]
The Search documentation (https://datahubproject.io/docs/how/search/) has a bit of information on how to do a custom config. I am interested in doing a functionScore filter that applies a boost to Data Products in search. How can that be achieved?

**Comment by jjoyce0510** [comment]
This should be possible. @david-leifker can provide some additional info.

Alternatively, you could try to use Search Views to create a space narrowly focused on Data Product entities, hiding all other assets.

Cheers
John

**Comment by david-leifker** [comment]
Please see this example -> https://github.com/datahub-project/datahub/pull/11511

Using prefix of `urn:li:dataProduct:` and applying a boot based on the urn prefix should work.

**Comment by echai58** [comment]
@david-leifker Thank you, I will try this.
