### ISSUE TITLE
Failed to pull image "docker.io/acryldata/datahub-postgres-setup:v0.14.1"

### ISSUE THREAD

**Issue by fstln-joe** [datahub-project/datahub#11668]
Failed to pull image "docker.io/acryldata/datahub-postgres-setup:v0.14.1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/acryldata/datahub-postgres-setup:v0.14.1": failed to resolve reference "docker.io/acryldata/datahub-postgres-setup:v0.14.1": docker.io/acryldata/datahub-postgres-setup:v0.14.1: not found

**Comment by Linux-oiD** [comment]
Looks like the same as mine: https://github.com/datahub-project/datahub/issues/11655

**Comment by david-leifker** [comment]
While we're working on adding the tag, there is a hash tag `6a165a8` for the v0.14.1 release.

**Comment by david-leifker** [comment]
Closing as duplicate
