### ISSUE TITLE
acryl-datahub-airflow-plugin fails on airflow 2.10.2

### ISSUE THREAD

**Issue by gschuurman** [datahub-project/datahub#11685]
**Describe the bug**
The acryl-datahub airflow plugin v2 fails on airflow 2.10.2 due to the deprication of the `airflow-openlineage` package. 
The plugin has to start supporting the official `apache-airflow-providers-openlineage` plugin [apache-airflow-providers-openlineage](https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/index.html)

**To Reproduce**
Build and run a docker image fot the airflow webserver with `RUN python3 -m pip install --upgrade 'acryl-datahub-airflow-plugin[plugin-v2]'` included
Open the webserver: and observe the import error.

In the logs there will be at least two errors:  
`ModuleNotFoundError: No module named 'airflow.providers.common.compat.openlineage.utils'`
```
OpenLineage support for Airflow version 2.10.2 is REMOVED.
For Airflow 2.7 and later, use the native Airflow Openlineage provider package.
Documentation can be found at https://airflow.apache.org/docs/apache-airflow-providers-openlineage
```

**Expected behavior**
No errors and succesfull import of the plugin
**Screenshots**
![image](https://github.com/user-attachments/assets/e866e84d-3328-48db-ada3-7d2ec7c37c57)

**Comment by Linux-oiD** [comment]
We are on 2.9.3 yet. And I see deprecation warnings in logs about openlineage plugin.
So looks like it will be blocker to upgrade for us.

**Comment by hsheth2** [comment]
@gschuurman what's the full stack trace from that error?

Note that we test against Airflow 2.10.2 in our CI https://github.com/datahub-project/datahub/blob/master/.github/workflows/airflow-plugin.yml#L58

**Comment by gschuurman** [comment]
Weird, it might be a bug in airflow. The entire integration just kept working. Just updated to Airflow 2.10.3, and the error is now gone.
