### ISSUE TITLE
(Frontend) Unable to add lineage to dataset in web UI

### ISSUE THREAD

**Issue by peamboon** [datahub-project/datahub#11713]
**Describe the bug**
Unable to add lineage to dataset in web UI

Datahub v0.14.1

**To Reproduce**
1. Go to Datahub frontend web UI
2. Go to a dataset (in my case the dataplatform is SQL server)
3. Click on 'Lineage' at the top right to visualize lineage 
<img width="2024" alt="image" src="https://github.com/user-attachments/assets/c82ad64a-5985-4b6d-b29a-dd844e049bba">
4. Click on Three dots on the dataset wanted to add lineage 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/8623d1da-2078-4074-bb52-541135a4f0ef">
5. Click on 'Edit Upstream'
6. Fill in the Manage upstream lineage dataset then 'Save Changes'
7.  "Updated lineage!" will pop up.
8. Everything looks fine here. Upstream lineage and Upstream dataset is visualized.
9. Refresh the page
10. The recently added lineage not shown.

**Expected behavior**
1. number of upstream should be added.
<img width="1826" alt="image" src="https://github.com/user-attachments/assets/b7feb2ef-e45a-4da7-bdfa-ce46fb9257f7">
2. The recently added lineage should be visualized after refresh the page. 
<img width="1814" alt="image" src="https://github.com/user-attachments/assets/4c167f65-f536-400f-b5a7-33fc0da278b6">

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 22H2
 - Browser Chrome

**Additional context**

**Comment by jjoyce0510** [comment]
Hi there - this appears to me to be an issue with your search index / search service.

Either it is:

1. Slow - It may take some time for the change to propagate through the system. Increasing memory and CPU for elasticsearch and datahub-gms should help here.

2, Dropping writes - If writes to elastcisearch are failing, you'll see this in the logs of datahub-gms container. Please check to make sure there are no issues there!

**Comment by peamboon** [comment]
This is currently solve!! It's a soft deleted entities.

Thank you for your suggestions.
