### ISSUE TITLE
No custom options for env parameter in ingestions

### ISSUE THREAD

**Issue by SergeyMaslikhov** [datahub-project/datahub#11865]
**Describe the bug**
I have several instances of Kafka running in different geographic regions. Some of them have the same naming of datasets, so without using `env` parameter only one of those datasets can be fetched. However `env` has only these options :  {'STG', 'NON_PROD', 'RVW', 'UAT', 'PROD', 'TEST', 'PRE', 'CORP', 'QA', 'DEV', 'EI'} and trying to set another value in config leads to `value_error`. The issue is that I need to separate Kafka(and any other platform) environments by other value such as "GER", "FRA", etc., otherwise choosing from  the listed values misleads users as all of the Kafka instances are actually 'PROD' but in its own region.
**To Reproduce**
1. Go to Ingestion
2. Click on Create new Kafka source
3. In connection configuration choose YAML and set env : GER

**Expected behavior**
Setting custom `env` parameter without type_error

**Screenshots**
<img width="943" alt="Снимок экрана 2024-11-15 в 13 48 37" src="https://github.com/user-attachments/assets/500a4b05-7245-4dff-93ec-c50161c22fed">

<img width="732" alt="Снимок экрана 2024-11-15 в 13 45 46" src="https://github.com/user-attachments/assets/6f7f3666-0236-4ec0-926d-0ca0a4cbe158">

**Comment by deepgarg-visa** [comment]
@SergeyMaslikhov, As you mention that they all are PROD but differ in regions. You can actually leverage "platform_instance" key for this. 

```
source:
    type: kafka
    config:
        platform_instance: GER
        env: PROD
        connection:
            bootstrap: ' '
            schema_registry_url: ''
```
Then the expected urn for the dataset becomes:

`urn:li:dataset:(urn:li:dataPlatform:kafka,GER.my-dataset, PROD)`

**Comment by SergeyMaslikhov** [comment]
Thank you so much, must've missed in docs
