### ISSUE TITLE
Prefect integration doesn't exist?

### ISSUE THREAD

**Issue by DbCrWk** [datahub-project/datahub#12221]
**Describe the bug**
[This integration](https://datahubproject.io/docs/lineage/prefect/) is mentioned in the docs, but doesn't look like it actually exists? In particular:
* I can't run `pip install 'prefect-datahub'`
* It's [not on PyPI](https://pypi.org/project/prefect-datahub/)
* [The repository seems empty on Github](https://github.com/acryldata/prefect-datahub), but has a commit that seems to implement everything?

I seem not to be the only [person confused by this](https://www.reddit.com/r/dataengineering/comments/1fz72hs/datahub_prefect_integration_question/).

**To Reproduce**
Run:
```
pip install 'prefect-datahub'
```

**Expected behavior**
It should install the prefect datahub integration.

**Desktop (please complete the following information):**
 - OS: macOS, 15.2 Sequoia, 24C101)
 - Browser Chrome, 131.0.6778.205 (Official Build) (arm64)

**Comment by hsheth2** [comment]
The code does exist - it lives here https://github.com/datahub-project/datahub/tree/master/metadata-ingestion-modules/prefect-plugin

The publishing piece looks like an oversight on our part - should be resolved by https://github.com/acryldata/datahub/pull/303

**Comment by DbCrWk** [comment]
> The code does exist - it lives here https://github.com/datahub-project/datahub/tree/master/metadata-ingestion-modules/prefect-plugin
> 
> The publishing piece looks like an oversight on our part - should be resolved by [acryldata#303](https://github.com/acryldata/datahub/pull/303)

Dope, thanks for jumping on this! It might be a good idea to update the README of the [acryldata/prefect-datahub](https://github.com/acryldata/prefect-datahub) repository to point to where the code lives, and also to archive it, so people know where to look.

**Comment by hsheth2** [comment]
@DbCrWk updated and archived that repo.

Also, we should have something published to pypi now - https://pypi.org/project/prefect-datahub/  v0.15.0.1rc8

**Comment by DbCrWk** [comment]
> @DbCrWk updated and archived that repo.
> 
> Also, we should have something published to pypi now - https://pypi.org/project/prefect-datahub/ v0.15.0.1rc8

That's great! I'm going to close out this issue, since https://github.com/acryldata/datahub/pull/303 is closed.
