### ISSUE TITLE
For Inactive owners special character( , ) is coming after every owner's name.

### ISSUE THREAD

**Issue by Shikha-Trivedi-Saxo** [datahub-project/datahub#2030]
**Describe the bug**
After version upgrade from v3.0.0 to v5.0.0, if there is any inactive owner in the metadata then on the frontend there is a special character ( , ) following every owner's name is being displayed.

**To Reproduce**
1. Go to Datahub frontend
2. Click on ownership aspect
3. Scroll down to Inactive owners name
4. See error that ' , ' is coming after inactive owners name

**Expected behavior**
The inactive owners should be strikethrough without any special character ( , ) succeeding that.

**Screenshots**
![image](https://user-images.githubusercontent.com/73520444/101142685-f5382580-363b-11eb-9221-23ab01ba4084.png)

**Desktop (please complete the following information):**
 - Browser -chrome

**Additional context**

**Comment by Shikha-Trivedi-Saxo** [comment]
If you think this bug is valid, I would like to volunteer for the fix.

**Comment by nagarjunakanamarlapudi** [comment]
Looks like a bug for me. 

cc: @cptran777

**Comment by anshbansal** [comment]
Closing as old issue. Please open a new bug if still happening on latest versions.
