### ISSUE TITLE
Using a corpGroup as an owner for a dataset breaks the frontend

### ISSUE THREAD

**Issue by frsann** [datahub-project/datahub#2138]
**Describe the bug**
Setting a corpGroup as the owner of a Dataset will cause the frontend, and consequently the web UI, to error out. It basically come down to the error:
```
[application-akka.actor.default-dispatcher-5720] ERROR c.l.datahub.dao.view.OwnerViewDao - CorpuserUrn syntax error
java.net.URISyntaxException: Urn entity type should be ‘corpuser’.: urn:li:corpGroup:mygroup
```

**To Reproduce**
1. Create a group
2. Create a dataset with above mentioned group as owner
3. Try to explore the dataset in the UI.

**Expected behavior**
To either be able to use corpGroup as an owner (as stated in the Owner-model), have the frontend not crash due to this, or cause a FailedMetadataChangeEvent when the dataset/aspect is created. 

**Screenshots**
 -

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari and chrome 

**Additional context**

**Comment by thomasplarsson** [comment]
@frsann This can be closed right? I believe it has been fixed since a while back. At least if works for me on 0.8.16.

**Comment by frsann** [comment]
Yes, i've confirmed it myself.
