### ISSUE TITLE
how to make metadata ingestion from clickhouse

### ISSUE THREAD

**Issue by bobliugq** [datahub-project/datahub#2381]
I want to use clickhouse as source data to import dataHub? Someone can Help?

**Comment by hsheth2** [comment]
Hi @bobliugq - once #2389 is merged in, you should be able to easily define a custom SQL-based source. 

For clickhouse, you can combine https://github.com/xzkostyan/clickhouse-sqlalchemy with a fairly simple config to make it work. Let me know if you run into any issues.

**Comment by bobliugq** [comment]
> Hi @bobliugq - once #2389 is merged in, you should be able to easily define a custom SQL-based source.
> 
> For clickhouse, you can combine https://github.com/xzkostyan/clickhouse-sqlalchemy with a fairly simple config to make it work. Let me know if you run into any issues.

Thanks for you help! But I could not find the plugins of sqlalchemy when I finished updated datahub(version 0.1.1)

Command I use:
pip install 'acryl-datahub[sqlalchemy]'

Warning Information:
WARNING: acryl-datahub 0.1.1 does not provide the extra 'sqlalchemy'

**Comment by hsheth2** [comment]
Just uploaded the new version to PyPI - https://pypi.org/project/acryl-datahub/0.1.2/

Can you try re-running `pip install --upgrade 'acryl-datahub[sqlalchemy]'` - it should get version 0.1.2

**Comment by bobliugq** [comment]
Unfortunately! I got same warning when I update my dataHub to version 0.1.2.

Warning Information:
WARNING: acryl-datahub 0.1.2 does not provide the extra 'sqlalchemy'

**Comment by hsheth2** [comment]
Ah I missed a line - sorry about that! I made a quick PR (#2409) to fix that.

In the meantime, you can manually install it by running `pip install sqlalchemy` as well, and then `datahub check plugins` should show sqlalchemy as enabled.

**Comment by shirshanka** [comment]
@bobliugq : just checking if you were able to get this working.

**Comment by sandeep-devarapalli** [comment]
> Hi @bobliugq - once #2389 is merged in, you should be able to easily define a custom SQL-based source.
> 
> For clickhouse, you can combine https://github.com/xzkostyan/clickhouse-sqlalchemy with a fairly simple config to make it work. Let me know if you run into any issues.

Hi Team, any update regarding this? It would be great to use ClickHouse with Datahub

**Comment by wangqinghuan** [comment]
we just implemented it @sandeep-devarapalli   
https://github.com/open-botech/datahub/blob/hb-datahub/metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py

**Comment by sandeep-devarapalli** [comment]
@wangqinghuan This is amazing, thanks a lot, and can you please let me know if this is available in DataHub too?

**Comment by grumbler** [comment]
I've got it working with dependencies:
```
clickhouse-driver                  0.2.2
clickhouse-sqlalchemy              0.1.7
```
and then with generic sqlalchemy recipe:
```
source:
  type: sqlalchemy
  config:
    platform: ClickHouse
    # Coordinates
    connect_uri: "clickhouse+native://username:password@clickhouse-host.example.com:9000/"
```

**Comment by ramakrishnabolisetty007** [comment]
@wangqinghuan I tried applying your changes from [this commit](https://github.com/wangqinghuan/datahub/commit/26a8f8bf261340551bf6f8b9abc0c7cf3baded83) on current master and when I do `./gradlew metadata-ingestion:build`

I'm getting the following error:
```
> Task :metadata-ingestion:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':metadata-ingestion:lint'.
> Process 'command 'bash'' finished with non-zero exit value 1
```

Is datahub integration with clickhouse working with [your branch](https://github.com/open-botech/datahub/tree/hb-datahub)?
If yes, can you suggest what I'm missing?

TIA!

**Comment by ramakrishnabolisetty007** [comment]
> we just implemented it @sandeep-devarapalli https://github.com/open-botech/datahub/blob/hb-datahub/metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py

> @wangqinghuan I tried applying your changes from [this commit](https://github.com/wangqinghuan/datahub/commit/26a8f8bf261340551bf6f8b9abc0c7cf3baded83) on current master and when I do `./gradlew metadata-ingestion:build`
> 
> I'm getting the following error:
> 
> ```
> > Task :metadata-ingestion:lint FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':metadata-ingestion:lint'.
> > Process 'command 'bash'' finished with non-zero exit value 1
> ```
> 
> Is datahub integration with clickhouse working with [this branch](https://github.com/open-botech/datahub/tree/hb-datahub)? If yes, can you suggest what I'm missing?
> 
> TIA!

**Comment by wangqinghuan** [comment]
> > we just implemented it @sandeep-devarapalli https://github.com/open-botech/datahub/blob/hb-datahub/metadata-ingestion/src/datahub/ingestion/source/sql/clickhouse.py
> 
> > @wangqinghuan I tried applying your changes from [this commit](https://github.com/wangqinghuan/datahub/commit/26a8f8bf261340551bf6f8b9abc0c7cf3baded83) on current master and when I do `./gradlew metadata-ingestion:build`
> > I'm getting the following error:
> > ```
> > > Task :metadata-ingestion:lint FAILED
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':metadata-ingestion:lint'.
> > > Process 'command 'bash'' finished with non-zero exit value 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is datahub integration with clickhouse working with [this branch](https://github.com/open-botech/datahub/tree/hb-datahub)? If yes, can you suggest what I'm missing?
> > TIA!
avoid lint
./gradlew  :metadata-ingestion:build -x lint

**Comment by anshbansal** [comment]
New clickhouse source is present. Closing this
