### ISSUE TITLE
User profile does not update list of entities owned unless manually refreshed

### ISSUE THREAD

**Issue by bboylen** [datahub-project/datahub#2487]
**Describe the bug**
When the UI is used to remove ownership of an entity for the logged in user, the entity does not disappear from the list of entities owned on the user's profile. The entity does disappear when the webpage is manually refreshed, however.

The same problem occurs when adding ownership of an entity - it doesn't show up until the webpage is refreshed. 

**To Reproduce**
1. Navigate to an entity owned by logged in user
2. Remove the logged in user as an owner of the entity
3. Navigate to the user profile 

**Expected behavior**
The entity should automatically be removed from the user profile list without needing a refresh

**Screenshots**
The user has been removed as an owner of "fct-users-created", but it still shows up.
![image](https://user-images.githubusercontent.com/52515015/116955747-0754d900-ac59-11eb-8e56-bdc3c377c1ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox

**Comment by anshbansal** [comment]
Can you please share whether the issue persists on the latest DataHub versions?

**Comment by jjoyce0510** [comment]
This should be addressed in the recent release of DataHub. Closing the issue.
