### ISSUE TITLE
Exception while fetching data (/search) : 'query' parameter cannot be null or empty

### ISSUE THREAD

**Issue by linhantao** [datahub-project/datahub#2733]
Repetition steps

1、Search for data through the search box on the interface
2、Clear the search criteria, enter the search, switch to the DataSets error report
3、Fill in the search condition again, cannot search and still report an error
![image](https://user-images.githubusercontent.com/56330004/122898544-8d4df000-d37d-11eb-9ba7-a5aac92bb991.png)

![image](https://user-images.githubusercontent.com/56330004/122898205-465ffa80-d37d-11eb-986b-bc043b975ec9.png)
Temporary treatment:
Manually fill in the search criteria in the address bar, for example: /search/dataset?page=1&query=aa

**Comment by anshbansal** [comment]
Should be fixed. Please open new issue if issue persists with latest releases
