### ISSUE TITLE
GMS logs elasticsearch basic auth credentials straight to the console

### ISSUE THREAD

**Issue by dingobar** [datahub-project/datahub#2933]
**Describe the bug**
When using basicauth, and the request fails (in this case because it does not expect a port), GMS (and the elasticsearch setup job too) logs the credentials to the console, like so:
```
2021/07/22 15:14:44 Problem with request: Get https://myuser:mypassword@mydomain.eu-central-1.es.amazonaws.com:9200: dial tcp 00.11.22.33:9200: i/o timeout. Sleeping 1s
```

**To Reproduce**
1. Start GMS pointed at elasticsearch with basic auth, but use the wrong uri
2. Observe password in logs

**Expected behavior**
I think it should either mask the password or not log the uri at all.

**Comment by jjoyce0510** [comment]
Hi @dingobar. Thanks for reporting.

Agree this is concerning. We are triaging this on our side. Will report back soon. 

Thanks
John

cc. @dexter-mh-lee

**Comment by anshbansal** [comment]
Should be fixed now. If still an issue please open a new issue.
