### ISSUE TITLE
same dataset in inputs and outputs of datajob breaks dataset view and lineage

### ISSUE THREAD

**Issue by guentherhackl-wgs** [datahub-project/datahub#2954]
**Describe the bug**
When I have a datajob where one of the datasets appears in the inputs and outputs (e.g. when a datajob reads from a dataset (and some others), modifies a few fields and saves it back with a new version), the dataset entity can't be loaded by the frontend. This results in two problems:
- the dataset can't be viewed anymore in the dataset-browser
- the expansion of the lineage is weird (graphql returns 200 for everything but the graph is not updating)

**To Reproduce**
1. datahub docker nuke
2. datahub docker quickstart
3. datahub docker ingest-sample-data
4. ingest: 
```
{
    "auditHeader": null,
    "proposedSnapshot": {
        "com.linkedin.pegasus2avro.metadata.snapshot.DataJobSnapshot": {
            "urn": "urn:li:dataJob:(urn:li:dataFlow:(airflow,dag_abc,PROD),task_123)",
            "aspects": [
                {
                    "com.linkedin.pegasus2avro.common.Ownership": {
                        "owners": [
                            {
                                "owner": "urn:li:corpuser:datahub",
                                "type": "DATAOWNER",
                                "source": null
                            }
                        ],
                        "lastModified": {
                            "time": 1581407189000,
                            "actor": "urn:li:corpuser:datahub",
                            "impersonator": null
                        }
                    }
                },
                {
                    "com.linkedin.pegasus2avro.datajob.DataJobInfo": {
                        "name": "User Creations",
                        "description": "Constructs the fct_users_created from logging_events",
                        "type": "SQL",
                        "flowUrn": "urn:li:dataFlow:(airflow,dag_abc,PROD)"
                    }
                },
                {
                    "com.linkedin.pegasus2avro.datajob.DataJobInputOutput": {
                        "inputDatasets": [
                            "urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD)"
                        ],
                        "outputDatasets": [
                            "urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_created,PROD)",
                            "urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD)"
                        ]
                    }
                }
            ]
        }
    },
    "proposedDelta": null
}
```
5. Dataset entity can't be loaded at: [http://localhost:9002/dataset/urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD)](http://localhost:9002/dataset/urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD))
6. Lineage can't be expanded for logging_events at:  [http://localhost:9002/tasks/urn:li:dataJob:(urn:li:dataFlow:(airflow,dag_abc,PROD),task_123)/ownership?is_lineage_mode=true](http://localhost:9002/tasks/urn:li:dataJob:(urn:li:dataFlow:(airflow,dag_abc,PROD),task_123)/ownership?is_lineage_mode=true)

**Expected behavior**
- The dataset should be accessible via the Browser
- Not sure how to fix the lineage best, maybe having one arrow dataset -> datajob and one in reverse, but I'm not sure how well this works with the current graph view

**Screenshots**
Dataset Browser Error:
![dataset](https://user-images.githubusercontent.com/83572690/126978705-63fa9598-1cfe-4b2e-8fac-d3d6107a330f.PNG)

Lineage:
![lineage](https://user-images.githubusercontent.com/83572690/126978739-c815afbd-cc2b-4368-8e71-2660e6bc485f.PNG)

**Desktop (please complete the following information):**
 - OS: Docker on Windows
 - Browser Edge
 - Version 89.0.774.77 (64-Bit)

**Comment by jjoyce0510** [comment]
Hi @guentherhackl-wgs ! 

Thanks for reporting. The team is taking a look. Will report back soon!

Thanks,
John
