### ISSUE TITLE
Issue with MongoDB request payloads

### ISSUE THREAD

**Issue by Nagendrakumar127** [datahub-project/datahub#2970]
Describe the bug
When I crawl MongoDb data into datahub crawler adds some additional data to request payloads making it huge. 

**To Reproduce**
1. Crawl Document size more than 5MB. 
2. Try to view crawled data in datahub UI.

**Expected behavior**
Ui is expected to handle large request payload.

Datahub UI
![image](https://user-images.githubusercontent.com/85788697/127277147-2668d7fb-e1e8-4f09-b69c-e984b0d29a9a.png)

File sink data of MongoDB

![image](https://user-images.githubusercontent.com/85788697/127278040-bf23419e-adbf-4434-b125-0ac36e27c1d5.png)

**Comment by jjoyce0510** [comment]
Wow! This is not ideal. 5MB is a pretty large document. Would you be willing to see partial schemas in the case that the size exceeds some determined threshold?

**Comment by Nagendrakumar127** [comment]
Yeah, that's fine. However, we do have data more than 5MB. Not sure what to do in that case. I gave all the details to Srishanka and Harshal.

**Comment by shirshanka** [comment]
Fixed (mitigated) via #3153 using a schema truncation approach. Default `maxSchemaSize` is 300 fields.
