### ISSUE TITLE
Datasets not showing in list views (available in search)

### ISSUE THREAD

**Issue by mhensley-cls** [datahub-project/datahub#2992]
**Describe the bug**
Hello, 

I am syncing data in from a mysql database. The meta data is ingested and visible via search, however it is not available in the list views within datasets.

**Expected behavior**
Imported data should be navigable without searching.

**Screenshots**
![image](https://user-images.githubusercontent.com/76120104/127549663-5c9cfc65-7235-4d49-baf5-80f4515d86e8.png)

![image](https://user-images.githubusercontent.com/76120104/127549762-38f577dd-f2d3-44a7-b47c-8e761717624b.png)

**Comment by jjoyce0510** [comment]
Hi @mhensley-cls. This is definitely a bug. Are you able to get into your MySQL DB to do some digging for me?

**Comment by anshbansal** [comment]
Seems using the old issue. Please open a new issue if the issue persists in the latest versions.
