### ISSUE TITLE
unable to map type JSON() to metadata schema

### ISSUE THREAD

**Issue by mhensley-cls** [datahub-project/datahub#2993]
**Describe the bug**
JSON datatype causing ingestion error.

**To Reproduce**
1. Ingest mysql 8.0 table with json() column
2. See error in ingestion logs
3. also see unknown type in metadata view within datahub front end.

**Expected behavior**
JSON datatypes should be first class citizens in schemas.

```
'dev_db_3gtbpq.User': ['unable to map type JSON() to metadata schema'],
              'dev_db_3gtbpq.audit': ['unable to map type JSON() to metadata schema'],
              'dev_db_3gtbpq.facility': ['unable to map type JSON() to metadata schema'],
```

**Screenshots**
![image](https://user-images.githubusercontent.com/76120104/127550254-63680d58-bbdc-430e-ac58-d51a00d5534b.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by jjoyce0510** [comment]
Thanks for reporting ! Agree this is a bug we should address in ingestion. @shirshanka @chinmay-bhat
