### ISSUE TITLE
Neo4jGraphSearch mixes up `"null"` with `null` entity type

### ISSUE THREAD

**Issue by EnricoMi** [datahub-project/datahub#3121]
The `findRelatedEntities` method of the Neo4J implementation of `GraphService` interprets a source or destination type `"null"` as the `null` value, which means _any_ type. With `"null"` you restrict the result to only get entities related to / of type `"null"`, not _any_.

There are tests in #3011 that test this behaviour.

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by anshbansal** [comment]
Closing as no response in a while and I believe the PR deals with it
