### ISSUE TITLE
Neo4jGraphService does not apply source / destination type for findRelatedEntities

### ISSUE THREAD

**Issue by EnricoMi** [datahub-project/datahub#3123]
The `GraphService` API provides method `findRelatedEntities` to find (destination) entities related to source entities. The Neo4J implementation does not apply the given source and destination types properly.

Example:

The graph:

    dataset one --HasOwner-> user one

The call:

    findRelatedEntities(
        null, EMPTY_FILTER,
        "dataset", EMPTY_FILTER,
        ["HasOwner"], RelationshipFilter.setDirection(RelationshipDirection.OUTGOING),
        0, 100
    )

returns `RelatedEntity("HasOwner", "user one")`, even though the destination type is set to "dataset", but a "user" is returned. It looks like the destination type has not been restricted to `"dataset"`.

Providing a source type exhibits the same problem.

There are tests in #3011 that reproduce this behaviour.

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by anshbansal** [comment]
Closing as no response in a while. Please open another issue if you believe this is still an issue
