### ISSUE TITLE
Neo4jGraphService has problems adding edges concurrently

### ISSUE THREAD

**Issue by EnricoMi** [datahub-project/datahub#3141]
Adding edges concurrently to the Neo4jGraphService does not succeed with all edges available. In #3011 such a concurrency test fails with Neo4jGraphService. The test is skipped there and can be used to reproduce this behaviour. Maybe `Neo4jGraphServiceTest` needs a `syncAfterWrite` implementation after all.

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by anshbansal** [comment]
Closing as no response in a while. Please open another issue if you believe this is still an issue
