### ISSUE TITLE
Get vesion of the datahub installed in UI

### ISSUE THREAD

**Issue by milan-sahu-kavak** [datahub-project/datahub#3151]
Hello Team 

Good morning . Here I would like to  add a feature request to see the datahub  version installed from UI .  I could not able to see the current version of product installed  in UI or in analytics console . 

IN command line we have the version : **datahub --version** but when the product is installed in kubernetes this feature will bring value 

**What benefits will bring  :**
      As we are in version 0.8.** and the versions are changing rapidly the users need to be aware which version they are working on .

**Comment by anshbansal** [comment]
The version shows up in the UI in right side dropdown
