### ISSUE TITLE
Race condition around ingesting aspect

### ISSUE THREAD

**Issue by xdl** [datahub-project/datahub#3231]
I think there's a race condition in the current ingestion implementation that would cause a version to be lost in the version history during an aspect update; it goes something like:

Thread A and Thread B both want to update the metadata of the aspect with key (urn=u0, aspect=a0, version=0)

| urn | aspect | version | metadata |
|-----|--------|---------|----------|
| u0  | a0     |       0 | m0       |

* Thread A reads (urn=u0, aspect=a0, version=0, metadata=m0) into memory
* Thread B reads (urn=u0, aspect=a0, version=0, metadata=m0) into memory
* Thread A reads the highest version existing in DB (0) in preparation to make backup (1)
* Thread A writes the original aspect into version=1

| urn | aspect | version | metadata |
|-----|--------|---------|----------|
| u0  | a0     |       0 | m0       |
| u0  | a0     |       1 | m0       |

* Thread A writes her new metadata into version=0

| urn | aspect | version | metadata |
|-----|--------|---------|----------|
| u0  | a0     |       0 | mA       |
| u0  | a0     |       1 | m0       |

* Thread B reads the highest version existing in DB (1) in preparation to make backup (2)
* Thread B writes the original aspect into version=2

| urn | aspect | version | metadata |
|-----|--------|---------|----------|
| u0  | a0     |       0 | mA       |
| u0  | a0     |       1 | m0       |
| u0  | a0     |       2 | m0       |

* Thread B writes his new metadata into version=0

| urn | aspect | version | metadata |
|-----|--------|---------|----------|
| u0  | a0     |       0 | mB       |
| u0  | a0     |       1 | m0       |
| u0  | a0     |       2 | m0       |

The issue can be solved by issuing a `FOR UPDATE` in the SELECT at the beginning of the transaction (e.g. see https://stackoverflow.com/a/6068392), although I haven't done any testing on what performance implications this will have; alternatively if all the versions are fetched in one read (to determine both the most recent version and number of versions), the retry logic will kick in on the thread that failed to write the backup.

There's a snippet which broadly emulates how the current `EbeanEntityService.ingestAspectToLocalDB` method works which can be used to reproduce this (and a fix for it) which I can try to provide for this too.

**UPDATE**: This is a manifestation of the lost update phenomena which the repeatable read isolation level would protect against; although it's noted in https://datahubproject.io/docs/advanced/aspect-versioning/#transaction-isolation-1 that MySQL should default to this level for transactions, it looks like ebean defaults to read committed isolation level (rationale given here https://archive-avaje-org.github.io/transiso.html) so the fix would be to pass in `TxIsolation.REPEATABLE_READ` to `ebeanServer.beginTransaction` in the `EbeanAspectDao`.

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by xdl** [comment]
Ah this was addressed in this PR: https://github.com/datahub-project/datahub/pull/3285 - happy to close!
