### ISSUE TITLE
handle errors from kafka_connect gracefully

### ISSUE THREAD

**Issue by chinmay-bhat** [datahub-project/datahub#3240]
**Describe the bug**
Throws KeyError when connector is not found. Handle it, so that ingestion may continue.

**Expected behavior**
A clear warning/info on the error and continue ingesting data from other available connectors.
Also use this opportunity to review and improve error handling in kafka_connect.py

**Comment by frsann** [comment]
Does this fix it: https://github.com/linkedin/datahub/pull/3148 ?

**Comment by chinmay-bhat** [comment]
To an extent, yes. However, we do come across KeyErrors when a field doesn't exist in a dict object, especially the JDBC source.

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.
