### ISSUE TITLE
Frontend throws unknown error for Analytics tab if it is disabled

### ISSUE THREAD

**Issue by DSchmidtDev** [datahub-project/datahub#3257]
**Describe the bug**
If Datahub analytics is disabled by deployment config:
```yaml
global:
  graph_service_impl: elasticsearch
  datahub_analytics_enabled: false
```
and Elasticsearch is used as graph service the corresponding Elasticsearch index (`datahub_usage_event`) is not created.
Therefore the frontend throws an `unknown error` when users click on the analytics button.

`ERROR c.l.d.g.a.service.AnalyticsService - Search query failed: Elasticsearch exception [type=index_not_found_exception, reason=no such index [datahub_usage_event]]`

**To Reproduce**
1. Deploy Datahub with config above
2. login to the frontend
3. Click on Analytics in the above right corner

**Expected behavior**
I would expect to disable/hide the button in the frontend so users cannot click on it or alternatively show a message and explain that this feature is not enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/11814088/133748368-9e1a44b0-8f6c-40d5-b52f-9056d11a3a37.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave
 - Version 0.8.13

**Comment by shirshanka** [comment]
@gabe-lyons : you might want to take a look at this one

**Comment by jjoyce0510** [comment]
The button should indeed be disabled when you disable analytics. Will take a look!

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.
