### ISSUE TITLE
Ingesting Azure AD records without permission will end up in endless loop

### ISSUE THREAD

**Issue by DSchmidtDev** [datahub-project/datahub#3374]
**Describe the bug**
If you are trying to ingest Azure AD user/group memberships but do not have the permission to read groups it will stuck in an endless loop trying to fetch the data.

**To Reproduce**
Use AzureADSource to ingest groups without the permission to read groups. 

**Expected behavior**
Should somehow stop/terminate the ingestion or try next resource.

**Screenshots**
Code from `azure_ad.py` continues to the next iteration if status code is not `200` but without adapting the URL.

https://github.com/linkedin/datahub/blob/104b331a2ec397febd14887b5a33328a4cc59dec/metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py#L248-L271

**Comment by DSchmidtDev** [comment]
Thanks. We tried the options but we would need to get the permissions as we want to get only the users for one specific group. And this filter is not possible if we don't ingest/read all groups. Not sure if it makes sense to refactor this part as well.

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by DSchmidtDev** [comment]
It's no actual issue anymore. So can be closed
