### ISSUE TITLE
Mismatch between upstream lineage count and actual display on lineage view in case of duplicate lineage

### ISSUE THREAD

**Issue by atulsaurav** [datahub-project/datahub#3380]
**Describe the bug**
When there is duplicate lineage present for a dataset, (may have been published by more than one ingestion source or job), it apparently leads to duplicate underlying edge in the graphDB. While while visualizing the lineage on the lineage pane, the frontend hides the duplicate nodes and edges, which is great, however the display on top still shows the duplicated upstream count. This inconsistency can lead to confusion and lack of trust in the users not knowing which of those are accurate. This is actually clear from the lineage facet where the duplicate upstreams are visible. This behavior needs to be refined.

**To Reproduce**
1. Use `builder.make_lineage_mce()` to create and emit duplicate lineage between 2 datasets.
2. Locate the downstream dataset
3. Click on Lineage view button
4. the upstream count will show as 2 in this case, whereas lineage display will show just one upstream dataset. 

**Expected behavior**
2 behaviors are valid:
1. In simplistic scenarios where I dont care about pipeline information/context and just worry about dataset level lineage, the whenever source and target are same, the grapdb doesnt need to store duplicate lineage - this will keep everything consistent.
2. In cases where we also case about the pipeline involved in populating from a source to target, like pipeline A is use to populate from X to Y but in a different scenario, pipeline B is used to populate/update X to Y, the lineage is not duplicate if the edge information(pipeline details) are also captured. In that scenario, it may make sense to show both the pathways to create a more holistic picture.

**Screenshots**
<img width="686" alt="image" src="https://user-images.githubusercontent.com/7138162/137053405-695cf068-4476-4710-a85f-e1c4b7ca4066.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Firefox
 - Version 90.0.1

**Additional context**

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by jjoyce0510** [comment]
I think we do this de-duplication intentionally. The original assumption, however, is that there are not duplicate edges being produced in the exact same UpstreamLineage aspect. This is because our backend is really agnostic to the semantics of this aspect, and just stores it as is. One action item for us may be to considering deduping before writing to the edge store. Something we will certainly look into on our side. For now, closing the ticket due to inactivity.

**Comment by jjoyce0510** [comment]
Just confirmed that in our default distribution of datahub (using Elasticsearch without Neo4j) we do seem to deduplicate lineage correctly. 

Thanks
John
