### ISSUE TITLE
datahub-frontend-react    | Caused by: play.core.server.common.ServerResultException: HTTP 1.0 client does not support chunked response

### ISSUE THREAD

**Issue by liuxiaojun** [datahub-project/datahub#3382]
when i install, 
source ./quickstart.sh.  found a proplem.  The "datahub-frontend-react " color is yellow.

datahub-frontend-react    | ! @7lbn1hho5 - Internal server error, for (GET) [/] ->
datahub-frontend-react    |
datahub-frontend-react    | play.api.UnexpectedException: Unexpected exception[ServerResultException: HTTP 1.0 client does not support chunked response]
datahub-frontend-react    | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:247)
datahub-frontend-react    | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:176)
datahub-frontend-react    | 	at play.core.server.common.ServerResultUtils.validateResult(ServerResultUtils.scala:64)
datahub-frontend-react    | 	at play.core.server.akkahttp.AkkaModelConversion$$anonfun$convertResult$1.apply(AkkaModelConversion.scala:199)
datahub-frontend-react    | 	at play.core.server.akkahttp.AkkaModelConversion$$anonfun$convertResult$1.apply(AkkaModelConversion.scala:196)
datahub-frontend-react    | 	at play.core.server.common.ServerResultUtils.resultConversionWithErrorHandling(ServerResultUtils.scala:180)
datahub-frontend-react    | 	at play.core.server.akkahttp.AkkaModelConversion.convertResult(AkkaModelConversion.scala:219)
datahub-frontend-react    | 	at play.core.server.AkkaHttpServer$$anonfun$15.apply(AkkaHttpServer.scala:367)
datahub-frontend-react    | 	at play.core.server.AkkaHttpServer$$anonfun$15.apply(AkkaHttpServer.scala:365)
datahub-frontend-react    | 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
datahub-frontend-react    | 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
datahub-frontend-react    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
datahub-frontend-react    | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
datahub-frontend-react    | 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:92)
datahub-frontend-react    | 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:92)
datahub-frontend-react    | 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:92)
datahub-frontend-react    | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
datahub-frontend-react    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
datahub-frontend-react    | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
datahub-frontend-react    | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
datahub-frontend-react    | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
datahub-frontend-react    | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
datahub-frontend-react    | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
datahub-frontend-react    | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
datahub-frontend-react    | Caused by: play.core.server.common.ServerResultException: HTTP 1.0 client does not support chunked response
datahub-frontend-react    | 	at play.core.server.common.ServerResultUtils.validateResult(ServerResultUtils.scala:63)
datahub-frontend-react    | 	... 21 common frames omitted
datahub-frontend-react    | 12:52:58 [application-akka.actor.default-dispatcher-6] ERROR application -
datahub-frontend-react    |
datahub-frontend-react    | ! @7lbn1hi41 - Internal server error, for (GET) [/favicon.ico] ->
datahub-frontend-react    |

**Comment by jjoyce0510** [comment]
@liuxiaojun Hi there - a couple questions to help me diagnose.

Are you putting datahub-frontend behind a proxy like Nginx or the like?
Is datahub-frontend serving the UI at localhost:9002/ or displaying an error screen? 

Feel free to reach out on Slack for more speedy support!

**Comment by anshbansal** [comment]
Is this still an issue? If not, will close it in a few days due to inactivity.

**Comment by nate-browne** [comment]
I've run into a similar issue. Using `haproxy` behind the scenes, I get this stack trace
```
18/10/2022, 08:55:26! @7pbaf4b81 - Internal server error, for (GET) [/] ->
18/10/2022, 08:55:26
18/10/2022, 08:55:26play.api.UnexpectedException: Unexpected exception[ServerResultException: HTTP 1.0 client does not support chunked response]
18/10/2022, 08:55:26	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:340)
18/10/2022, 08:55:26	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:263)
18/10/2022, 08:55:26	at play.core.server.common.ServerResultUtils.validateResult(ServerResultUtils.scala:69)
18/10/2022, 08:55:26	at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$1(AkkaModelConversion.scala:193)
18/10/2022, 08:55:26	at play.core.server.common.ServerResultUtils.resultConversionWithErrorHandling(ServerResultUtils.scala:195)
18/10/2022, 08:55:26	at play.core.server.akkahttp.AkkaModelConversion.convertResult(AkkaModelConversion.scala:215)
18/10/2022, 08:55:26	at play.core.server.AkkaHttpServer.$anonfun$runAction$5(AkkaHttpServer.scala:447)
18/10/2022, 08:55:26	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
18/10/2022, 08:55:26	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
18/10/2022, 08:55:26	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
18/10/2022, 08:55:26	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
18/10/2022, 08:55:26	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
18/10/2022, 08:55:26	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
18/10/2022, 08:55:26	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
18/10/2022, 08:55:26	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
18/10/2022, 08:55:26	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
18/10/2022, 08:55:26	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
18/10/2022, 08:55:26	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
18/10/2022, 08:55:26	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
18/10/2022, 08:55:26	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
18/10/2022, 08:55:26	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18/10/2022, 08:55:26Caused by: play.core.server.common.ServerResultException: HTTP 1.0 client does not support chunked response
```
docker image being used is: `linkedin/datahub-frontend-react:${DATAHUB_VERSION:-head}`

**Comment by nate-browne** [comment]
Update: Figured out the issue. In the `nginx` configurations, this setting must be enabled
```nginx
http {
  server {
    # whatever other settings here
    location / {
      proxy_http_version 1.1;
    }
  }
}
```

**Comment by anshbansal** [comment]
Thanks for sharing this @nate-browne
