### ISSUE TITLE
certain tags returns no search results

### ISSUE THREAD

**Issue by xiphl** [datahub-project/datahub#3400]
**Describe the bug**
If you add a tag with spaces to a dataset, you will not be able to return any datasets with the tag. Also, tags starting with "tag:xxx" also cannot be found.

**To Reproduce**
1. add/create a tag and add it to a dataset
2. search for the tag
3. the entity count is 0

**Expected behavior**
it should read at least 1 since you applied it to at least 1 dataset.

Not sure if the "create tag" panel should catch for illegal characters. Should spaces count as one?

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by xiphl** [comment]
tags with spaces have been addressed and solved. Tags with colon inside, however, remains buggy

**Comment by jjoyce0510** [comment]
This appears to be a problem when the tag contains a DataHub entity name at the start. Examples of things that don't work:

- tag:test
- dataset:test
- dataJob:test

and so on. Leaving this issue open to debug further
