### ISSUE TITLE
Bigquery ingest fails if include_table_lineage set to false

### ISSUE THREAD

**Issue by tha23rd** [datahub-project/datahub#3425]
**Describe the bug**
Testing datahub out locally, using the quickstart guide. After installing the bigquery plugin we attempted to run an ingest job with `include_table_lineage` set to `false`. The job correctly grabs a single table, but then fails with:

`/datahub/ingestion/source/sql/bigquery.py", line 237, in get_lineage_mcp
    assert self.lineage_metadata is not None`

I believe this is related to this PR: https://github.com/linkedin/datahub/pull/3389

**To Reproduce**
1. Run Bigquery ingestion job with `include_table_lineage` set to False

**Expected behavior**
Bigquery ingestion should succeed with `include_table_lineage` set to False.

**Comment by shirshanka** [comment]
fixed via #3428 and released via `0.8.15.10`
