### ISSUE TITLE
How can I install datahub without using Docker

### ISSUE THREAD

**Issue by rilweic** [datahub-project/datahub#3504]
I'm in a situation where I can't use docker, and I'd like to know how to install datahub without using docker.

**Comment by dexter-mh-lee** [comment]
Hi. We don't officially support non-docker based installation, but I would recommend taking a look at how the docker image is running the datahub containers. https://github.com/linkedin/datahub/blob/master/docker/datahub-gms/Dockerfile You can use gradlew to build the war executable and run it directly in your local environment.

**Comment by rilweic** [comment]
Can you go into more detail about how this works?

**Comment by anshbansal** [comment]
For discussions please head to slack https://slack.datahubproject.io/
