### ISSUE TITLE
User picture from Azure is not correctly requested

### ISSUE THREAD

**Issue by vlavorini** [datahub-project/datahub#3512]
**Describe the bug**
While loading the UI, the request made to MS Graph about the picture of the user is not correctly formatted. Check shapshot

**To Reproduce**
1. Enable Azure OIDC
2. open the UI

**Screenshots**
<img width="1712" alt="Screenshot 2021-11-04 at 15 04 18" src="https://user-images.githubusercontent.com/8724860/140333736-871bf163-bd48-4e78-9952-64419fde3b4a.png">

**Desktop (please complete the following information):**
 - OS: docker
 - Browser Firefox
 - Version 0.8.16

**Comment by anshbansal** [comment]
Is this still an issue? If not, we will close this issue due to inactivity.
