### ISSUE TITLE
Clicking on hyperlink in field's Description column doesn't open the link

### ISSUE THREAD

**Issue by pramodbiligiri** [datahub-project/datahub#3613]
**Describe the bug**
Clicking on a hyperlink in the "Description" column of a field does not open the hyperlink at all. It only works if you copy paste the link into another tab, or Right Click and do "Open in New Tab".

**To Reproduce**
You can reproduce this in the Datahub demo site by clicking the link provided in the place_id field of the mobility_report dataset - https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,bigq[…]bility.mobility_report,PROD)/Schema?is_lineage_mode=false

**Expected behavior**
The provided hyperlink to developers.google.com should work.

**Desktop (please complete the following information):**
Verified on Chrome and Firefox on Windows, Safari on iOS

**Comment by gabe-lyons** [comment]
@shirshanka this is good to close 👍
