### ISSUE TITLE
User urn based on email should not be case-sensitive

### ISSUE THREAD

**Issue by dingobar** [datahub-project/datahub#3615]
**Describe the bug**

**To Reproduce**
1. Go to datahub and have the identity provider create your user
2. Ingest some metadata into datahub using the CLI, but have username email in all caps
3. Observe you are not owner of the dataset you just ingested because it's case-sensitive

**Expected behavior**
II think `user@user.com` and `user@USER.COM` should be the same. In general, we should not allow usernames that only differ in the casing.

**Possible solution**
Lower-case all usernames that are emails.

If user `user@domain.com` adds themselves as a dataset owner in an ingestion recipe, the dataset is not owned by them if their email in the identity provider is something like `user@DOMAIN.COM` even though in terms of email address this is the same. I think in the case of users, the behavior should be to always lowercase, and we should not allow duplicate usernames in datahub which only differ by casing.

**Comment by jjoyce0510** [comment]
The challenge here is that determining whether the username is an email or a normal username is non-trivial. We actually don't know! For usernames, case sensitivity may in fact be a good thing

**Comment by iasoon** [comment]
I'm also running into this issue. My org doesn't use a consistent casing for primary email identifiers in Azure AD, so it is not possible to transform ingested emails to the correct form without doing lookups.
Being able to downcase usernames would solve this, either in all ingestion sources and identity providers, or as a setting in datahub itself.
Alternatively, maybe we could have an option to use the 'mail' field that exists today in datahub as an identifier as well? In this case we'd know for sure that it's an email and shouldn't be case-sensitive.

**Comment by jjoyce0510** [comment]
Yes you should be able to use mail.

We allow you to customize the "user name claim" that is used at login time. We should also do this in our batch connectors for AzureAD and Okta!

John

**Comment by dingobar** [comment]
I don't use DataHub anymore :( If anyone faces this issue I assume they will create their own ticket on the new issue tracker.

**Comment by mkih** [comment]
This issue is very nasty when using any SSO integration, as any changes in email casing almost irreversibly screws up Datahub. Worst case you have to manually transfer all user associations whenever email case changes for any reason, because each time a new user is created.

Additionally it seems that the cases are inconsistently handled in the backend, because some of the duplicate users don't appear in the user list.
