### ISSUE TITLE
How to create user

### ISSUE THREAD

**Issue by vincent045** [datahub-project/datahub#3623]
How can I create the user in datahub

**Comment by xiphl** [comment]
Are you looking for ways to login new users to datahub, or search for more users in datahub?

**Comment by vincent045** [comment]
> Are you looking for ways to login new users to datahub, or search for more users in datahub?

I want to create new user to login datahub, not only the datahub user.

**Comment by xiphl** [comment]
there is a user.props file that you can add users so that you can login to datahub.
/datahub/datahub-frontend/conf/user.props  
refer to https://datahubproject.io/docs/how/auth/jaas/#modify-userprops-file-directly-local-testing

**Comment by xiphl** [comment]
If you're looking to add users as entities into datahub, yes, the rest call works. However, logging into datahub is either via oidc, ldap or the default login portal that datahub offers. The last option uses user.props to login.

**Comment by duylamvo-wefox** [comment]
@xiphl thanks. You are right, I can only add entity/user to datahub, not able to login.

**Comment by anshbansal** [comment]
Please see https://datahubproject.io/docs/authentication/guides/add-users for adding users. For questions slack is a better option.
