### ISSUE TITLE
Can I use the model.json CDM (Common Data Model) file to ingest metadata into Datahub?

### ISSUE THREAD

**Issue by girishkumaar** [datahub-project/datahub#3692]
I was testing with the metadata-ingestion feature in Datahub, and was not able to find the documentation or .yml file to ingest the metadata in the model.json CDM (Common Data Model) folder to ingest metadata into Datahub? Kindly help me with these two questions or any other sources which can explain the answers to the question would be really appreciated. Thanks for your time and support!

**Comment by joshsh** [comment]
Hi @girishkumaar. I have not looked closely at CDM, but this would be interesting to explore. In what repository is the folder you are referring to?

**Comment by girishkumaar** [comment]
Hello @joshsh, thanks for your reply! To give a little context about the CDM, you can refer: https://github.com/microsoft/CDM.git repository

The main concept of CDM is to have the metadata stored to use for other applications if needed like ingesting data to Power BI etc, which saves the processing time and other benefits. Currently, we have files coming into the Azure Data Lake Gen 2 container, and I create the CDM file (model.json), which can then be used in Power BI to pull data clean data with few advantages. 

So, I was curious and wondering if the CDM metadata file can be ingested into Datahub, and that would be a nice feature as well, I suppose!

**Comment by anshbansal** [comment]
For questions/discussions please head to https://slack.datahubproject.io/
