### ISSUE TITLE
ui: expanding the documentation editor results in strange state

### ISSUE THREAD

**Issue by jjoyce0510** [datahub-project/datahub#3719]
**Describe the bug**
when you click the "expand" icon in the description editor on dataset documentation tab, you will see the following odd state: 
![Screen Shot 2021-12-10 at 12 53 45 PM](https://user-images.githubusercontent.com/17549204/145640113-db9734c2-489b-4414-a2ca-dc4a3f9192ca.png)

**Comment by Vladislaff** [comment]
I have the same issue. 
When I click "fullscreen" in the documentaion editor the right pane is kept open and "floats" over the editor.
Maybe it is due to the resolution of my laptop.

**Comment by akurnosov** [comment]
I confirm the issue.

**Comment by paul-izum** [comment]
I confirm the issue too
