### ISSUE TITLE
UI only shows up to 99 inputDatasets of a DataJob in lineage

### ISSUE THREAD

**Issue by karoliskascenas** [datahub-project/datahub#3751]
UI only shows up to 99 `inputDatasets` (probably the same for `outputDatasets`) of a DataJob in lineage. You can see that grahql returns two arrays though.

**Expected behavior**
Displays as many input/output datasets as the DataJob has.

**Screenshots**
![image](https://user-images.githubusercontent.com/26895203/146180527-30c08642-2b74-4071-91e2-fbb18542ce29.png)
![image](https://user-images.githubusercontent.com/26895203/146180538-e8da719c-bbbf-4edb-98bd-83d84eb94793.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version 96.0.4664.93 (Official Build) (x86_64)

**Additional context**
Running v0.8.19

**Comment by jjoyce0510** [comment]
This should be addressed in the latest release via the Lineage-Search UI :)
