### ISSUE TITLE
How to use data lineage

### ISSUE THREAD

**Issue by liyuhui666** [datahub-project/datahub#3795]
How to use data lineage
why there is no data in my Neo4J

**Comment by maggiehays** [comment]
Hi @liyuhui666 - apologies for the delay!

Check out [this lineage tutorial](https://www.youtube.com/watch?v=rONGpsndzRw&ab_channel=DataHub) and these [lineage code examples](https://datahubproject.io/docs/lineage/sample_code).

**Comment by liyuhui666** [comment]
![image](https://user-images.githubusercontent.com/71497399/148169885-c9169eb1-0ea4-46af-a18b-d7a5e8761d66.png)

Thank you very much for your answer. I have seen these examples before, including regularly executing metadata intake scheduling and obtaining the blood map of table C from tables A and B. I think it is necessary to define upstream and downstream relationships by myself, rather than through metadata or query SQL statements. I got my blood relationship by defining "inlets outlets". I don't know whether this is correct

**Comment by RyanHolstien** [comment]
Hi! What source are you trying to ingest your lineage from and what method are you using to do so (i.e. modified python script example, GraphQL API, etc.)?

Have you defined some sort of custom relationship called a "blood map"? I'm not familiar with this term with regards to Datahub.

**Comment by anshbansal** [comment]
Is this still an issue? If not, we will close this issue due to inactivity.
