### ISSUE TITLE
Failed to load resource: the server responded with a status of 505 (HTTP Version Not Supported)

### ISSUE THREAD

**Issue by suishaojian** [datahub-project/datahub#3884]
Hi I use nginx to forward the 9002 port with following config:

```
server{
  listen 80;
  server_name  datahub.demo.com;
  index  index.php index.html index.htm;

  location / {  
    proxy_pass  http://DatahubServerIP:9002; 
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```
But I got the following error...
![image](https://user-images.githubusercontent.com/20984440/149248116-eea1af89-aeb9-4ee2-8e12-6950aee4e1ea.png)
![image](https://user-images.githubusercontent.com/20984440/149248252-291beb31-1609-4831-af17-a20126e6e5cd.png)

**Comment by jjoyce0510** [comment]
Hi @suishaojian ! 

We've had this issue before. See this thread: https://datahubspace.slack.com/archives/CV2UXSE9L/p1630056938000500

**Comment by suishaojian** [comment]
> Hi @suishaojian !
> 
> We've had this issue before. See this thread: https://datahubspace.slack.com/archives/CV2UXSE9L/p1630056938000500

Thanks John. But I cannot join this slack workspace cause some unknown reason. Could you invit me with my email: suishaojian@gmail.com  or  could you pls give me another way to solve this problem ?

**Comment by jjoyce0510** [comment]
Yes sent the invite!

**Comment by suishaojian** [comment]
> Yes sent the invite!
@jjoyce0510  Thanks a lot. But another problem .. 
![image](https://user-images.githubusercontent.com/20984440/151640329-fe7e174d-1c54-4442-a350-120e717b7840.png)

My SlackUsername is suishaojian. Could you pls invit me with this username? thank you

**Comment by suishaojian** [comment]
> Yes sent the invite!

Thanks  a lot . Join successfully ~~
