### ISSUE TITLE
No way to exclude distinct_counts from profile plugin

### ISSUE THREAD

**Issue by tha23rd** [datahub-project/datahub#3887]
**Describe the bug**
The profiling config does not allow you to disable distinct_counts

For super large tables this is an extremely expensive operation.

**Expected behavior**
There should be a configuration option to disable the collection of distinct_counts from tables

Bonus:
Would be awesome to enable an "approx count" vs distinct count for large tables. BQ for instance has a hyperloglog implementation built for this: 
https://cloud.google.com/bigquery/docs/reference/standard-sql/hll_functions
https://cloud.google.com/bigquery/docs/reference/standard-sql/approximate_aggregate_functions

**Comment by treff7es** [comment]
If you try out with the latest version it will use approximate queries at BQ, Snowflake, Redshift.

**Comment by anshbansal** [comment]
Closing as this should be fixed now
