### ISSUE TITLE
Owners that are groups are not showing displayName in either entity view page or search results page

### ISSUE THREAD

**Issue by thomasplarsson** [datahub-project/datahub#3909]
**Describe the bug**
When owners are visualized, users and groups behave differently. Users show displayName as the name but Groups show the name. Since group names can be non-human-friendly, it would be better if display name was used.

**To Reproduce**
1. Navigate to a dataset that has a group as an owner
2. See what the owner text is, i.e it's not the display name.

**Expected behavior**
Display name should be used when visualizing a group as an owner.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jjoyce0510** [comment]
This is now addressed via the displayName in Groups entity!
