### ISSUE TITLE
The Spark-Lineage should choose environment.

### ISSUE THREAD

**Issue by wulianghui** [datahub-project/datahub#3923]
**Describe the bug**
When you get lineage via spark-lineage module, the env is always 'PROD' and couldn't be changed

**To Reproduce**
The env of DatasetUrn is fixed to "FabricType.PROD", but It's not always right.

**Expected behavior**
We can choose which env to ingeset to.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MugdhaHardikar-GSLab** [comment]
This case is now supported on datahub

**Comment by shirshanka** [comment]
Supported since https://datahubproject.io/docs/releases#v0-8-30 
Docs: https://datahubproject.io/docs/metadata-integration/java/spark-lineage/#configuration-details
