### ISSUE TITLE
0.8.23.1 failed to ingest redshift metadata

### ISSUE THREAD

**Issue by jasgok** [datahub-project/datahub#3936]
after upgrade to acryl-datahub-0.8.23.1 
while ingesting  **redshift metadata** by `datahub ingrest -c metadata_redshift.yml`  with `type: redshift` in it
get a lot messages like
```shell
WARNING: Only s3 source supported with copy. The source was: .  .

/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:3198: SAWarning: Did not recognize type 'map<character varying,int>' of column 'XXX'
```
many other claimed unsupported type, and no metadata ingested.

fixed by downgrade to 0.8.11.0

**Comment by rslanka** [comment]
Several enhancements happened to this connector since the issue was reported. Don't think this is still an issue. Closing.
