### ISSUE TITLE
Lineage submission with MCP creates no ingest run

### ISSUE THREAD

**Issue by DSchmidtDev** [datahub-project/datahub#3978]
**Describe the bug**
When using the MetadataChangeProposalWrapper to submit dataset lineage information with the REST emitter it does not assign a runId for this ingestion. So no rollback is possible. Even when attaching the systemMetadata it does not pick it up. It seems that these changes are handled different from other submissions.

**To Reproduce**
1. create a lineage MCP based on the documentation [here](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/library/lineage_emitter_mcpw_rest.py) like the example below
```
    lineage_mcp = MetadataChangeProposalWrapper(
        entityType="dataset",
        changeType=ChangeTypeClass.UPSERT,
        entityUrn=mce_builder.make_dataset_urn("bigquery", "downstream", "DEV"),
        aspectName="upstreamLineage",
        aspect=upstream_lineage,
        systemMetadata=SystemMetadata(runId="my_lineage_ingestion_test")
    )
```
2. send the mcp via datahub rest emitter
3. check the latest runs with the cli

**Expected behavior**
I expect to see a run with the custom runId from above or at least a generated one so I can track and rollback the changes.

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Brave
 - Version: acryl-datahub==0.8.23.1

**Comment by jjoyce0510** [comment]
@DSchmidtDev  - Hi there! Is this still an issue?
