### ISSUE TITLE
Glossary special characters affect search results

### ISSUE THREAD

**Issue by Huyueeer** [datahub-project/datahub#3989]
I found several features in use:
1. Urn contains `:`,(Cause word segmentation failure, Associations cannot be searched through rest / graphql)
2. Urn contains `spaces`,(Cause word segmentation failure, Associations cannot be searched through rest / graphql)
`:`I can understand that it is caused by the prefix, but does `space` need to be supported or escaped? Otherwise, it will make the search strange under the non-standard name.

**Comment by jjoyce0510** [comment]
Hi there ! Thank you for reporting this. 

Spaces should not be breaking characters, as long as they are between other non-space characters (urns are trimmed before storing.) Colons (:) must be escaped in the search bar using \ in search. Or enclosed in double quotes ("). For example: `dbt\:schema` or `tags:dbt\:schema`

However, commas and parentheses are reserved characters, which means embedding them in URNs can cause problems. 

URL-encoded URN fields is something we've considered doing for some time, but have not yet gotten to. You're correct that this can cause incorrect behavior in search. However, within the product we do our best to minimize impact of this by quoting or escaping search strings

**Comment by Huyueeer** [comment]
Thank you for your reply. There is another small detail. I found in the verification, I constructed four types of glossaryterm including (space) and (:), and found that some of them cannot be queried when the page is associated; 
Associate four terms：
![image](https://user-images.githubusercontent.com/40758588/151478913-39218774-9418-4bac-9d7a-a2a9ee4eee57.png)
![image](https://user-images.githubusercontent.com/40758588/151479249-bfe306fd-3ba3-45cc-90e0-b97fa700b551.png)
Finally, it is found that only `urn:li:glossaryTerm:test huyue` can be queried in the association query. At the same time, I also query through graphql, which is the same result.
I very much agree with what you said about adding \ to escape in the search, but are there still some problems in the related part of the query?

**Comment by cccs-eric** [comment]
I'm also having issues with both `space` and `:`.  I can associate a glossary term with an entity, but when I look at that glossary term and its associated entities, the list is empty (even though I do have entities associated with that term):
![image](https://user-images.githubusercontent.com/56447460/152191501-1ff236ec-153d-4d4b-82fc-5c164f78df99.png)
<img width="528" alt="image" src="https://user-images.githubusercontent.com/56447460/152192173-0fc01509-17df-4c17-b43c-e9f145aff557.png">

Could this be a problem with the `graphql` query being done by this page?

**Comment by Huyueeer** [comment]
@cccs-eric Therefore, I doubt that `space` and `:` have an impact on entity Association query, I think the names containing the above characters are incorrectly divided in word segmentation retrieval. Therefore, there will be problems when the interface is called (whether rest or graphql).

**Comment by Huyueeer** [comment]
@jjoyce0510 OK，I also reproduced a case on the demo page. You can have a look，
https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,bigquery-public-data.covid19_geotab_mobility_impact.airport_traffic,PROD)/Schema?is_lineage_mode=false
click`huyue.cc  &  huyue.cc cc  & huyue.cc:cc `

**Comment by jjoyce0510** [comment]
Thanks for the further investigation! We are aware of the issue and working to understand the best path forward here. It's due to how we query the search index in the presence of special characters. Will update the thread once we have more!

**Comment by Huyueeer** [comment]
> Thanks for the further investigation! We are aware of the issue and working to understand the best path forward here. It's due to how we query the search index in the presence of special characters. Will update the thread once we have more!

I have found the problem and will help deal with it in the near future.

**Comment by jjoyce0510** [comment]
Thanks @Huyueeer ! Checking in - did we ever merge in fixes to address these issues (as far as you're aware)?
