### ISSUE TITLE
Columns with a dot in the name are not displayed fully in the UI

### ISSUE THREAD

**Issue by ne1r0n** [datahub-project/datahub#4004]
**Describe the bug**
UI doesn't show the full column name which contains a dot. Original discussion in [slack](https://datahubspace.slack.com/archives/C029A3M079U/p1642601100186100).

**To Reproduce**
1. Create the following table and ingest it to the datahub:
```
CREATE TABLE test_dot
(
    `col1.a` Int,
    `col2.a` Int,
    `col3.a` Int
);
```
2. Navigate to the created table in UI

**Expected behavior**
Display full column name.

**Screenshots**
<img width="133" alt="image" src="https://user-images.githubusercontent.com/6350825/151552485-9cf4354a-5b8c-448a-ba2e-a362e2b90bb0.png">

 - Version v0.8.24

**Comment by maggiehays** [comment]
Hi @ne1r0n! Thanks so much for raising this - we'll tackle this as soon as possible!

**Comment by jjoyce0510** [comment]
This is addressed in recent versions thanks to my lovely friend @gabe-lyons! With a snazzy haircut :) 

John
