### ISSUE TITLE
Open in a new Tab/ Window for "View in [airflow/metabase/redash]" button

### ISSUE THREAD

**Issue by yourssvk** [datahub-project/datahub#4046]
Problem Statement:

Open in a new Tab/ Window for "View in [airflow/metabase/redash]" button

Actual behavior:

The button opens the link in the same window

Expected behavior:

Open the link on a separate tab/ window

**Comment by anshbansal** [comment]
Please use https://feature-requests.datahubproject.io/ for feature requests
