### ISSUE TITLE
How datahub supports data from unknown source

### ISSUE THREAD

**Issue by Cascol-SCUT** [datahub-project/datahub#4066]
When dealing with the idea of data lake, we consider most data are unknown with arbitrary type. However, datahub looks like we have to declare each contributes type. Is datahub a powerful relational database ?

**Comment by pedro93** [comment]
Hello @Cascol-SCUT,

I apologize but do not follow your question. Could you elaborate?
What I can tell you is that DataHub is able to consume metadata from a number of different technologies are make those searchable for you in a Web UI or programatically via GraphQL APIs.
You can see the data sources that are supported here: https://datahubproject.io/docs/metadata-ingestion/source_docs/athena

If you are talking about "random" data files that can be found in a data lake, DataHub supports the following raw file formats:
 - CSV
 - TSV
 - Parquet
 - JSON
 - Apache Avro

Using the [data-lake ingestion source](https://datahubproject.io/docs/metadata-ingestion/source_docs/data_lake).
If you happened too already have a data catalog like Hive or AWS Glue for these files, I would suggest you use the respective sources instead. They are substantially faster, and extract more useful metadata.

**Comment by pedro93** [comment]
Hello @Cascol-SCUT 

Any updates on this? Is the data-lake ingestion source enough for you?

**Comment by Cascol-SCUT** [comment]
Some errors occur when I try to ingest data. 
![image](https://user-images.githubusercontent.com/51443787/159247430-e9a69760-c69a-40a2-a39a-e9463351a8f2.png)

**Comment by pedro93** [comment]
How are you deploying datahub @Cascol-SCUT ?

Could you also share the ingestion yaml file you are using?

**Comment by Cascol-SCUT** [comment]
Sorry for mistakes, I change the server adress and now it has another error.
![image](https://user-images.githubusercontent.com/51443787/159250476-3ad4bf51-f80a-420c-af36-0444f01e551c.png)

**Comment by pedro93** [comment]
Please share your deployment and ingestion configurations, it will be easier to analyse and debug that way.

**Comment by Cascol-SCUT** [comment]
The error was because of the exhausted resource on the server.

**Comment by Cascol-SCUT** [comment]
@pedro93 Datahub can extract schema info from json files, however, does it support json files like the one bellow, or how shall I modify it? More generally, when users are uploading random json files, how does datahub deal with them
![image](https://user-images.githubusercontent.com/51443787/161524365-ef7467b4-7d92-4044-b9d5-73b53c4faa5f.png)

**Comment by pedro93** [comment]
DataHub itself does not extract schema info from json files, we delegate that responsibility. If you are using the [data lake ingestion source](https://datahubproject.io/docs/generated/ingestion/sources/data-lake-files) then we use the logic defined here: https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/schema_inference/json.py to infer the json schema.
