### ISSUE TITLE
invalid variable names in docker/elasticsearch/env/docker.env when using docker compose v2

### ISSUE THREAD

**Issue by nikmartin** [datahub-project/datahub#4070]
Installing the latest docker compose (v2) will cause the dev.sh script to throw errors:

```
unexpected character "." in variable name near "discovery.type=single-node\nxpack.security.enabled=false\nES_JAVA_OPTS=-Xms256m -Xmx256m -Dlog4j2.formatMsgNoLookups=true\n"
```

**Comment by pedro93** [comment]
@dexter-mh-lee could you take a look at this please?

@nikmartin are you using a custom docker-compose file? 
Where are you getting it from?
Which version of DataHub are you trying to deploy?

**Comment by nikmartin** [comment]
Am using https://github.com/linkedin/datahub/blob/master/docker/docker-compose-without-neo4j.yml, and the env file for elastic search is the offending file. The issue is most definitely with docker compose v2, as switching back to compose v1 works ok.

**Comment by dexter-mh-lee** [comment]
@nikmartin Seems like we need to put quotes around variables. Can you try putting quotes around the value side of this variable and see if that works with docker compose v2? https://github.com/linkedin/datahub/blob/master/docker/elasticsearch/env/docker.env#L3 Feel free to put out a PR with the change if that solves it!

**Comment by nikmartin** [comment]
I didn't mention it in my original issue, but I had done a bit of research and saw a few posts about similar issues, but the issue was the '.' in the key name, and no amount or flavor of escaping could get it to pass.

**Comment by dexter-mh-lee** [comment]
So 
```ES_JAVA_OPTS="-Xms256m -Xmx256m -Dlog4j2.formatMsgNoLookups=true"```
doesn't work?

**Comment by nikmartin** [comment]
yes that works fine, but the first two lines in the default env file have "." In the key name. Those I can't get escaped:
 
 ​discovery.type=single-node

**Comment by pedro93** [comment]
@nikmartin I'm very sorry for not replying sooner!
Could you please share the command you are using to launch DataHub and your version of docker-compose so I can try to repo locally?

**Comment by yactouatfuture** [comment]
hello everyone ! I'm having the same issue than @nikmartin just after having downloaded and trying to run https://github.com/temporalio/docker-compose
