### ISSUE TITLE
Validation error of type FieldUndefined: Field 'upstreamDatasources' in type 'Sheet' is undefined"

### ISSUE THREAD

**Issue by yourssvk** [datahub-project/datahub#4119]
**Problem description:**

Error while ingesting from Tableau:

Source (tableau) report:
{'failures': {'tableau-metadata': ["Unable to retrieve metadata from tableau. Information: Connection: workbooksConnection Error: [{'message': "
                                   '"Validation error of type FieldUndefined: Field \'upstreamDatasources\' in type \'Sheet\' is undefined @ '
                                   '\'workbooksConnection/nodes/sheets/upstreamDatasources\'", \'locations\': [{\'line\': 30, \'column\': 9, '
                                   '\'sourceName\': None}], \'description\': "Field \'upstreamDatasources\' in type \'Sheet\' is undefined", '
                                   "'validationErrorType': 'FieldUndefined', 'queryPath': ['workbooksConnection', 'nodes', 'sheets', "
                                   "'upstreamDatasources'], 'errorType': 'ValidationError', 'extensions': None, 'path': None}]"]},

**Steps to reproduce the behavior:**

Do not have clear steps to reproduce the issue, however can answer questions to resolve the issue

**Expected behavior**

Ingestion succeeds

**Comment by mayurinehate** [comment]
Hello @yourssvk , can you please mention which tableau version you are using.

**Comment by mjatharmyobgit** [comment]
We are also facing same error while ingesting from Tableau. 

Our Tableau version we have is: 
Tableau Server Version: 2021.1.10 (20211.21.1217.2241) 64-bit Windows

Error text:
Source (tableau) report:
{'workunits_produced': 0,
 'workunit_ids': [],
 'warnings': {},
 'failures': {'tableau-metadata': ["Unable to retrieve metadata from tableau. Information: Connection: workbooksConnection Error: [{'message': "
                                   '"Validation error of type FieldUndefined: Field \'upstreamDatasources\' in type \'Sheet\' is undefined @ '
                                   '\'workbooksConnection/nodes/sheets/upstreamDatasources\'", \'locations\': [{\'line\': 30, \'column\': 9, '
                                   '\'sourceName\': None}], \'description\': "Field \'upstreamDatasources\' in type \'Sheet\' is undefined", '
                                   "'validationErrorType': 'FieldUndefined', 'queryPath': ['workbooksConnection', 'nodes', 'sheets', "
                                   "'upstreamDatasources'], 'errorType': 'ValidationError', 'path': None, 'extensions': None}]"]}}
Sink (datahub-rest) report:
{'records_written': 0,
 'warnings': [],
 'failures': [],
 'downstream_start_time': None,
 'downstream_end_time': None,
 'downstream_total_latency_in_seconds': None}
