### ISSUE TITLE
Can't create Elasticsearch ingestion due to lack of scheme

### ISSUE THREAD

**Issue by chenray** [datahub-project/datahub#4145]
**Describe the bug**

**To Reproduce**
1. Create a custom ingestion with elasticsearch as type
2. Using the following configuration:
source:
    type: elasticsearch
    config:
        host: '192.168.0.1:9200'
        username: ""
        password: ""
        env: PROD
        index_pattern:
            allow:
                - '.*test*'
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-datahub-gms:8080'
3. it ended up with failure, scheme is missing:
raise ValueError(\n'
           '    199              "URL must include a \'scheme\', \'host\', and \'port\' component (ie \'https://localhost:9200\')"\n'
           '    ..................................................\n'
           "     url = '192.168.0.1:9200'\n"
           "     NodeConfig = <class 'elastic_transport.NodeConfig'>\n"
           '     parsed_url.scheme = None\n'
           "     parsed_url.host = '192.168.0.1'\n"
           '     parsed_url.port = 9200\n'
           '    ..................................................\n'

**Expected behavior**
An elasticsearch ingestion can be created successfully.

**Comment by kizy008** [comment]
I meet the same problem. And I upgrade datahub to v0.8.27.1 . Then the ingestion is successful.

**Comment by meagher43** [comment]
Also experiencing this issue, the workaround described by kizy008 didn't work for me.

**Comment by kizy008** [comment]
您的邮件我已收到，我会尽快给您回复，谢谢！

**Comment by rslanka** [comment]
Looks stale. Does not repro on the latest build. Closing.
