### ISSUE TITLE
UI: Related entities not returned on TagProfile

### ISSUE THREAD

**Issue by dyanarose** [datahub-project/datahub#4183]
**Describe the bug**
DataHub version v0.8.26

Given a tag page like: localhost/tag/urn:li:tag:dbt:foo=bar

The [entityAndSchemaQuery](https://github.com/linkedin/datahub/blob/master/datahub-web-react/src/app/entity/tag/TagProfile.tsx#L89) graphQL query comes out as:
`tags:"undefined" OR fieldTags:"undefined" OR editedFieldTags:"undefined"`

However where the [tag name is set as title text](https://github.com/linkedin/datahub/blob/master/datahub-web-react/src/app/entity/tag/TagProfile.tsx#L122), this does output `dbt:foo=bar` to the page

I think the fact that the `dbt:` prefix is part of the name is also going to be a problem, because the tag isn't searchable on `dbt:foo=bar` but is searchable on `foo=bar`

For example this produces 0 results:
```
curl --location --request POST 'http://localhost:8080/api/graphql' \
--header 'X-DataHub-Actor: urn:li:corpuser:datahub' \
--header 'Content-Type: application/json' \
--data-raw '{ "query":"{ search(input: { type: DATASET, query: \"tags:\\\"dbt:foo=bar\\\"\", start: 0, count: 10 }) { start count total searchResults { entity { urn type ...on Dataset { name tags { tags { tag { urn name } } } } } } } }", "variables":{}}'
```

And this produces the expected results
```
curl --location --request POST 'http://localhost:8080/api/graphql' \
--header 'X-DataHub-Actor: urn:li:corpuser:datahub' \
--header 'Content-Type: application/json' \
--data-raw '{ "query":"{ search(input: { type: DATASET, query: \"tags:\\\"foo=bar\\\"\", start: 0, count: 10 }) { start count total searchResults { entity { urn type ...on Dataset { name tags { tags { tag { urn name } } } } } } } }", "variables":{}}'
```

So even if the query contained the expected value `dbt:foo=bar` it still wouldn't return results.

**Expected behavior**
I expect the related entities section of the Tag page to contain the entities tagged by the tag.
I don't expect the tag name to contain the `dbt:` prefix when this is not how the tag appears in dbt

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Comment by shirshanka** [comment]
@dyanarose : one solve for the secondary issue you mentioned is to set the `tag_prefix` to empty string, as long as you are okay with colliding with the global tag space.

As the config page mentions, the default is `dbt:`, https://datahubproject.io/docs/metadata-ingestion/source_docs/dbt/#config-details

| tag_prefix |   | dbt: | Prefix added to tags during ingestion.

**Comment by jjoyce0510** [comment]
Hopefully this helped to address the DBT prefix. 

I've tried to reproduce this on the latest version of DataHub unsuccessfully, including:

1. Tag named dbt:test
2. Tag named dbt:test=something

And failed to reproduce the issue. 

Closing this ticket, as there appears to be a solve. 

Thanks
John
