### ISSUE TITLE
Embedding via i-frame

### ISSUE THREAD

**Issue by abisz** [datahub-project/datahub#4211]
I'm trying to embed datahub as an i-frame, but ran into some issues.
After the successful `/logIn` request I noticed that the call to `/api/v2/graphql` fails with a 401 error.
I'm assuming that this is a CORS issue, because opening the site normally works fine.

Does anyone have done this before and can point me in the right direction on how to change the graphql CORS settings?

**Comment by wangqinghuan** [comment]
You can set a Nginx proxy to point your datahub, then embed Nginx proxy url.

**Comment by amravazzi** [comment]
+1

**Comment by jjoyce0510** [comment]
Yes, this is correct. Since this is not a product issue with DataHub, we are going to close this ticket.
