### ISSUE TITLE
Link of table of plugins in metadata ingestion page is broken

### ISSUE THREAD

**Issue by zjffdu** [datahub-project/datahub#4222]
**Describe the bug**

Document error,  the link of table of plugins in metadata ingestion page is broken, see the following screenshot.

**Screenshots**

<img width="837" alt="image" src="https://user-images.githubusercontent.com/164491/155271955-5428c30a-8be9-4bcc-8bae-5ec772044aef.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by anshbansal** [comment]
This is now fixed
