### ISSUE TITLE
Wrong capitalization scheme when importing SQL source using Python-based metadata ingestion / make_dataset_urn

### ISSUE THREAD

**Issue by dariuschiu-personal** [datahub-project/datahub#4224]
**Describe the bug**
I'm following this example to ingest a MSSQL source: https://datahubproject.io/docs/metadata-ingestion#install-from-pypi

The URN imported this way is capitalized : urn:li:dataPlatform:mssql,Analytics.dbo.Date,PROD

However, when I use the REST emitter (https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/library/lineage_emitter_rest.py) to create lineage between datasets I imported by using the above method, the capitalization in the URN is all lowercase. This causes the lineage import to fail.

This is because in mce_builder.py, line 75 and 94 convert the URN to lower case

#Use lower-case name for all SQL style datasets
        if platform in SQL_STYLE_PLATFORMS:
            name = name.lower()

I commented out this code and adding the lineage subsequently works.

**To Reproduce**
1. import using CLI and a yml file, loading from a sql source.
2. Note that dataset URN may have capital letters
3. Use https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/library/lineage_emitter_rest.py to establish lineage between 2 datasets
4. note that URN created by make_dataset_urn() is all lower case
5. verify lineage is not created, by looking at UI

**Comment by rslanka** [comment]
hi @dariuschiu-personal, the change  in mce_builder.py, line 75 and 94 convert the URN to lower case that has cause the issue has been reverted. You should no longer be seeing this.

**Comment by dariuschiu-personal** [comment]
Thanks
