### ISSUE TITLE
Wrong "ACTIVE" status for user who has logged in

### ISSUE THREAD

**Issue by jieni0123** [datahub-project/datahub#4251]
I have created and managed to login with the new user named 'Test'. When I click on the 'Users & Groups' section, the active status is shown on 'Datahub' user account but not 'Test'.
![image](https://user-images.githubusercontent.com/90783708/155638375-1863e79e-5991-4793-aeaa-ea6d18b7e626.png)

**Comment by jjoyce0510** [comment]
Hi @jieni0123 - Is this for a user you've added via the `user.props` file?

**Comment by jieni0123** [comment]
Hi @jjoyce0510 , yes I added in the user via the _user.props_ file, then invoke the _dev.sh_ command

**Comment by jjoyce0510** [comment]
Hi - thanks for the response. Unfortunately, this is a known issue. This status is only being flipped for folks who log in via SSO. That being said, we are aware of it and its on our backlog of items.

**Comment by jjoyce0510** [comment]
This has been addressed with the new Username / Password login supported by DataHub. If you invite new users, they will correctly be attributed.

Closing this ticket with a resolution.

John
