### ISSUE TITLE
[Question] Can I use wildcard when I query for BrowseResults ?

### ISSUE THREAD

**Issue by kizy008** [datahub-project/datahub#4270]
A few days ago, I asked a question for searching tables with keyword. [here](https://github.com/linkedin/datahub/issues/4240).
I learned the search guid document. But now I have another problem.

Similarly, I may have a lot of databse under platform instance. I want to search some database  with keyword. The [document ](https://datahubproject.io/docs/how/search) is searching for dataset. So I may get many dataset with the same database. I think I may need `BrowseResults` and I notice that `browse`  query method in search.graphql. And `BrowseInput` has a parameter called `filters` with type FacetFilterInput. Can I use it to query with wildcard. If so, how can I use it?

![企业微信截图_16460516781377](https://user-images.githubusercontent.com/12572997/155984404-c06f8b44-a0e7-4336-babc-7d48dbbea57e.png)

**Comment by kizy008** [comment]
Take mysql for example. If I have hundreds of database and I want to search a database with keyword (not exact database name). 
For example, I want to search a database called "db_example_test", and my input may be "example". I expected to get database list like "db_example_test", "db_example_dev", "db_example_pro" and so on.

I read the search guid document. And I foud the result is dataset or other entities. That is to say I will get table list but not database list. I think BrowseResults gives a databases list.

In genral, I want to search a database with keyword.
![image](https://user-images.githubusercontent.com/12572997/156507816-5d597c24-28cc-4a27-b2fe-7dc09d24a3b9.png)

**Comment by kizy008** [comment]
> 15 hours ago

Take mysql for example. If I have hundreds of database and I want to search a database with keyword (not exact database name).
For example, I want to search a database called "db_example_test", and my input may be "example". I expected to get database list like "db_example_test", "db_example_dev", "db_example_pro" and so on.

I read the search guid document. And I foud the result is dataset or other entities. That is to say I will get table list but not database list. I think BrowseResults gives a databases list.

In genral, I want to search a database with keyword.

[](https://user-images.githubusercontent.com/12572997/156507816-5d597c24-28cc-4a27-b2fe-7dc09d24a3b9.png)

**Comment by kizy008** [comment]
> Hi there - is your goal to filter down the browse results to contain less things? Why would you want to query results with a wildcard query? (*) -- Wouldn't this fetch all results, the same as is happening today?

Take mysql for example. If I have hundreds of database and I want to search a database with keyword (not exact database name). 
For example, I want to search a database called "db_example_test", and my input may be "example". I expected to get database list like "db_example_test", "db_example_dev", "db_example_pro" and so on.

I read the search guid document. And I foud the result is dataset or other entities. That is to say I will get table list but not database list. I think BrowseResults gives a databases list.

In genral, I want to search a database with keyword.
![image](https://user-images.githubusercontent.com/12572997/156507816-5d597c24-28cc-4a27-b2fe-7dc09d24a3b9.png)

**Comment by kizy008** [comment]
Tanks for your reply.  I found database entity page and there is a serach bar in 【Filters】.
![image](https://user-images.githubusercontent.com/12572997/157362176-b739a41d-74be-471b-85a8-3ec10cfcc099.png)
And I want to ask will every instance have a container ? How can I know the mapping relation between container and instance ?

**Comment by jjoyce0510** [comment]
Typically the container should have a name - In this case your Database should have a name. If it does not, then that's another bug :(.

I'm going to go ahead and close this issue for now since you've found a workaround.

John

**Comment by kizy008** [comment]
您的邮件我已收到，我会尽快给您回复，谢谢！

**Comment by kizy008** [comment]
您的邮件我已收到，我会尽快给您回复，谢谢！
