### ISSUE TITLE
React render error on GlossaryTerm/RelatedTerms/Inherits

### ISSUE THREAD

**Issue by guentherhackl-wgs** [datahub-project/datahub#4277]
**Describe the bug**
On a GlossaryTerm that contains two other terms and inherits from one term i get a blank page when i click on "Inherits" in the related terms tab. In the console i can see an error from react (Following the link to react error decoder: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.)

**To Reproduce**
On newly pulled images (version0.8.27) and started with docker-compose-without-neo4j.yaml (+override) i used this minimal nesseccary python script to ingest a term to reproduce the scenario:
```Python
from datahub.metadata.schema_classes import (
    GlossaryTermSnapshotClass,
    GlossaryTermInfoClass,
    GlossaryRelatedTermsClass,
    MetadataChangeEventClass
)

from datahub.emitter.rest_emitter import DatahubRestEmitter

info = GlossaryTermInfoClass("level1", "INTERNAL")
rel = GlossaryRelatedTermsClass(
    isRelatedTerms=["urn:li:glossaryTerm:test.level0"],
    hasRelatedTerms=["urn:li:glossaryTerm:test.level2_1",
                     "urn:li:glossaryTerm:test.level2_2"]
)
s = GlossaryTermSnapshotClass("urn:li:glossaryTerm:test.level1", [rel, info])


gms_url = "http://localhost:8080"

emitter = DatahubRestEmitter(gms_url)
emitter.emit_mce(MetadataChangeEventClass(proposedSnapshot=s))
```

**Expected behavior**
Not getting an error

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Comment by jjoyce0510** [comment]
Thank you! Can you confirm this is still an issue? We are investigating on our side.

**Comment by jjoyce0510** [comment]
One easy suggestion is to produce GlossaryTermInfo aspects for ALL the terms in your glossary (including level0, level2_1, level2_2)

**Comment by jjoyce0510** [comment]
Going to close this ticket due to inactivity. Please feel free to reopen for additional support.

Thanks
John
