### ISSUE TITLE
Calling graph.get_aspect(aspect='dataJobInfo' ) causes avro.schema.AvroException: ('Datum union type not in schema: %s', None) 

### ISSUE THREAD

**Issue by lhvubtqn** [datahub-project/datahub#4289]
**Describe the bug**
I'm using DataHubGraph API to update a datajob information, but when calling `graph.get_aspect(aspect='dataJobInfo')`, it causes `avro.schema.AvroException: ('Datum union type not in schema: %s', None)`.

**To Reproduce**
Here the code to reproduce the error (replace cookie with your cookie when accessing `demo.datahubproject.io`).
```python
graph = DataHubGraph(config=DatahubClientConfig(
    server='https://demo.datahubproject.io/api/gms',
    extra_headers={'cookie': f'{cookie}'}
))

job_info = graph.get_aspect(
    entity_urn='urn:li:dataJob:(urn:li:dataFlow:(spark,orders_cleanup_flow,PROD),orders_dedupe_job)',
    aspect='dataJobInfo',
    aspect_type=DataJobInfoClass,
)
```

**Expected behavior**
A `DataJobInfoClass` instance.

**Stacktrace**
```sh
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    aspect_type=DataJobInfoClass,
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/datahub/ingestion/graph/client.py", line 119, in get_aspect
    return aspect_type.from_obj(aspect_json, tuples=True)
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/avrogen/dict_wrapper.py", line 41, in from_obj
    return conv.from_json_object(obj, cls.RECORD_SCHEMA)
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/avrogen/avrojson.py", line 99, in from_json_object
    return self._generic_from_json(json_obj, writers_schema, readers_schema)
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/avrogen/avrojson.py", line 252, in _generic_from_json
    result = self._record_from_json(json_obj, writers_schema, readers_schema)
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/avrogen/avrojson.py", line 340, in _record_from_json
    field_value = self._generic_from_json(json_obj[field.name], writers_field.type, field.type)
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/avrogen/avrojson.py", line 250, in _generic_from_json
    result = self._union_from_json(json_obj, writers_schema, readers_schema)
  File "/home/ubuntu/Desktop/work/vulh4/datahub/env/lib/python3.6/site-packages/avrogen/avrojson.py", line 309, in _union_from_json
    raise schema.AvroException('Datum union type not in schema: %s', value_type)
avro.schema.AvroException: ('Datum union type not in schema: %s', None)
```

**Environment:**
 - OS: Ubuntu 18.04.6 LTS (Windows subsystem)
 - Python: 3.6.9
 - acryl-datahub: v0.8.27.1

**Comment by lhvubtqn** [comment]
I suspect that the problem lies on the `type` field, which should be either `string` or `AzkabanJobType`, but has the value `{"string": "spark"}`. So it fail when the program call `AvroJsonConverter.validate()` & produce the error.
```json
{"version":0,"aspect":{"com.linkedin.datajob.DataJobInfo":{"name":"orders_cleanup_flow:orders_dedupe_job","type":{"string":"spark"},"customProperties":{"transformType":"SelectField"}}}}
```

I've skimmed though the source code and find that the class [com.linkedin.datahub.graphql.generated.DataJobInfo](https://github.com/linkedin/datahub/blob/77a27359f2fdddacb537b5a79fa46bea24bd2e0a/datahub-graphql-core/src/main/resources/entity.graphql#L3861) (which is deprecated & replaced by `DataJobProperties`) has no field named `type`. Meanwhile, the class [com.linkedin.datajob.DataJobInfo](https://github.com/linkedin/datahub/blob/520968b2478aa62e4f82e12b5619fa0fae8c0b53/metadata-models/src/main/pegasus/com/linkedin/datajob/DataJobInfo.pdl#L39) still has (but with the deprecated `AzkabanJobType`).

And in [DataJobSnapshotMapper](https://github.com/linkedin/datahub/blob/a2a939d406949dec3d57b74789c4084f6a095599/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/datajob/mappers/DataJobMapper.java#L59), when get `DataJobInfo` aspect from snapshot, it simply ignore the field `type` in `com.linkedin.datajob.DataJobInfo`.

There's seem a little inconsistence between those classes?

**Comment by jjoyce0510** [comment]
Going to close this due to inactivity. Please reopen if you feel its still relevant!

**Comment by nmolinier** [comment]
Hello.

I'd like to reaopen this issue. I have been struggling trying to create a "DataJobInfo" using the rest API.

I get either a 500: "org.springframework.web.client.HttpClientErrorException$UnprocessableEntity: 422 Failed to validate record with class com.linkedin.datajob.DataJobInfo: ERROR :: /type :: union type is not backed by a DataMap or null\n"

```
[
    {
        "aspect": {
            "__type": "DataJobInfo",
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": "OTHERS"
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]
```

or a 400 Bad request

```
[
    {
        "aspect": {
            "__type": "DataJobInfo",
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": {"string": "test"}
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]
```


```
[
    {
        "aspect": {
            "__type": "DataJobInfo",
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": {"AzkabanJobType": "COMMAND"}
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]
```

This was tested on datahub demo environment this day.

I don't mind to have a workaround
