### ISSUE TITLE
Term path case effect

### ISSUE THREAD

**Issue by Huyueeer** [datahub-project/datahub#4355]
Now there is a thorny problem. In our previous use, the path has uppercase letters, but after the new version, the path becomes lowercase by default after term is created, which has an impact on the previous data.
I want to know if there is any configuration for the case of paths? Or will there be other solutions?
![image](https://user-images.githubusercontent.com/40758588/157379427-45a30d9a-041d-4a22-8251-6ee1fdb4586e.png)

**Comment by Huyueeer** [comment]
I found the PR at that time: #3477

**Comment by jjoyce0510** [comment]
Hi @Huyueeer - We did indeed change casing. Apologies for the extra trouble this may have caused.

In recent versions, you can manage the entire Glossary via the UI without worrying about this. We recommend you upgrade to that!

Thanks
John
