### ISSUE TITLE
datahub-ingestion not support sudo!

### ISSUE THREAD

**Issue by hhofchina** [datahub-project/datahub#4384]
The docker image of "linkedin/datahub-ingestion:head" does not support the user of datahub to run SUDO privilege. 
How can I run "apt-get install" ?
In order to solve the problem, I have to build my own docker image from zero. 
The build costs several hours.
The image is so complex and large, we need more privilege to custom it!

**Comment by anshbansal** [comment]
The linked issue suggested a workaround which should be sufficient for this. Please create a new issue if this is not solved.
