### ISSUE TITLE
How use hdfs in datahub

### ISSUE THREAD

**Issue by Kitter** [datahub-project/datahub#4420]
Datahub can ingest from hdfs,but I don't konw how to use in datahub. Who can tell me the guide of hdfs ingestion? Thanks!

**Comment by maggiehays** [comment]
Hi @Kitter, if you have a [Hive metastore](https://datahubproject.io/docs/metadata-ingestion/source_docs/hive/), we support ingestion HDFS metadata through the Hive connector. We don't yet support the raw files & folders. 

I'll close this out for now, but feel free to join our Slack with additional questions! slack.datahubproject.io
