### ISSUE TITLE
PLAY_TOKEN cookie rejected because userprofile exceeds 4096 chars

### ISSUE THREAD

**Issue by mariusingjer** [datahub-project/datahub#4448]
**Describe the bug**

The datahub page just keeps refreshing after enabling OIDC

Docker logs from the frontend is just repeating:

```
ERROR auth.sso.oidc.OidcCallbackLogic - Unable to renew the session. The session store may not support this feature
```

Config:

```
'AUTH_OIDC_ENABLED': 'true',
'AUTH_OIDC_CLIENT_ID': ...,
'AUTH_OIDC_CLIENT_SECRET': ....
'AUTH_OIDC_DISCOVERY_URI': 'https://cognito-idp.xxx.amazonaws.com/xxx/.well-known/openid-configuration',
'AUTH_OIDC_BASE_URL': 'https://...',
'AUTH_OIDC_USER_NAME_CLAIM': 'email',
'AUTH_OIDC_USER_NAME_CLAIM_REGEX': '([^@]+)',
'AUTH_OIDC_SCOPE': 'email openid profile'
```

Frontend container version:

```
linkedin/datahub-frontend-react:11f809a
```
![datahub_network_oidc_error](https://user-images.githubusercontent.com/65291983/159017418-cc3f4a17-0879-45a4-8234-dc20e22b15d2.png)

.well-known:

```
{
  "authorization_endpoint": "https://xxxxxxxxx/oauth2/authorize",
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "issuer": "https://cognito-idp.xxxxxx.amazonaws.com/xxxxxx",
  "jwks_uri": "https://cognito-idp.xxxxxx.amazonaws.com/xxxxxx/.well-known/jwks.json",
  "response_types_supported": [
    "code",
    "token"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "phone",
    "profile"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint": "https://xxxxxx.amazoncognito.com/oauth2/token",
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "userinfo_endpoint": "https://xxxxxx.amazoncognito.com/oauth2/userInfo"
}
```

**Comment by HagunKim** [comment]
I'm not sure if this is helpful. In my case, the same issue occured since the response cookie size was larger than 4096 bytes. To reduce the size, I reduced the number of claims on OIDC.

**Comment by mariusingjer** [comment]
The PLAY_SESSION token is 984 bytes, I can also mention that the user who opens the DataHub frontpage is automatically provisioned in the database (he/she appears in metadata_aspect_v2;), so the OIDC integration is working up until that point.

**Comment by mariusingjer** [comment]
This is the code which is complaining btw:

```
https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultCallbackLogic.java

protected void renewSession(final WebContext context, final SessionStore sessionStore, final Config config) {
        final var oldSessionId = sessionStore.getSessionId(context, true).get();
        final var renewed = sessionStore.renewSession(context);
        if (renewed) {
            final var newSessionId = sessionStore.getSessionId(context, true).get();
            LOGGER.debug("Renewing session: {} -> {}", oldSessionId, newSessionId);
            final var clients = config.getClients();
            if (clients != null) {
                final var clientList = clients.getClients();
                for (final var client : clientList) {
                    final var baseClient = (BaseClient) client;
                    baseClient.notifySessionRenewal(oldSessionId, context, sessionStore);
                }
            }
        } else {
            LOGGER.error("Unable to renew the session. The session store may not support this feature");
        }
    }
```

and the token in the PLAY_SESSION looks like this:

```
{
  "actorType": "USER",
  "actorId": "datahub",
  "type": "SESSION",
  "version": "1",
  "exp": 1647690589,
  "jti": "xxxxxxxxxxxxx",
  "sub": "datahub",
  "iss": "datahub-metadata-service"
}
```

**Comment by mariusingjer** [comment]
..and I found the problem. The cookie returned after completing the oidc flow is indeed greater than 4096 characters and thus rejected by the browser. I've peeked at the id and auth token returned from cognito and they are pretty slim, same goes for the user-information returned by the userinfo endpoint. The "pac4j_pac4jUserProfiles" part in the PLAY_SESSION is however "gigantic" (3972 chars). Its not base64 encoded, so I can't peek into it.

Does anyone know the encoding on the pac4juserProfiles part, or if there are any others ways of trimming the userprofile than trimming the id/access token?

**Comment by mariusingjer** [comment]
For others: I had requested 3 claims:

```
'AUTH_OIDC_SCOPE': 'email openid profile'
```

I removed the profile claim, this trimmed the PLAY_TOKEN < 4096 chars

**Comment by mariusingjer** [comment]
I have to reopen this. We have multiple users who are rejected because they have too many claims. We provision groups in datahub based on claims and we have a oauth server which passes along active directory group membership as claims, so we get into this situation quite quickly. Is there any way to further trim the PLAY_TOKEN?

**Comment by jjoyce0510** [comment]
Hi folks,

We've recently submitted a fix to address this which uses a server-side cache for storing the session state. This comes with some caveats - you are not able to scale datahub-frontend beyond a single pod (which is fine for most deployments). 

See this PR, which is present in the latest release (v0.8.40): https://github.com/datahub-project/datahub/pull/5114

In the future, some work can still be completed to reduce the attributes which are cached from the OIDC profile, to only those required to make auth work.

Because there is a deployed solution, going to close out the issue.

Thanks
John
