### ISSUE TITLE
database_alias on mssql

### ISSUE THREAD

**Issue by datatimnih** [datahub-project/datahub#4449]
**Describe the bug**
i'm trying to ingest my mssql to datahub with this config
```
source:
  type: mssql
  config:
    uname,pas,port
    database: db_name
    database_alias: db_alias
```
but doesn't use the database_alias like db_alias.dbo.table its still using the database name db_name.dbo.table

**To Reproduce**
1. creating the mssql config file with databse_alias
2. idatahub -c ingest config_file.yml
3. see on the datahub its stil using the original database name

**Expected behavior**
expected result:  db_alias.dbo.table (using database_alias from config file)
actual result: db_name.dbo.table (ignoring the database_alias)

**Additional context**
after following some instruction from slack forum to add code similar to[this](https://github.com/datahub-project/datahub/blob/430ca10c15dd74c6470385a1ac44f136e9c23e44/metadata-ingestion/src/datahub/ingestion/source/sql/mysql.py#L36-L37) after [this line](https://github.com/datahub-project/datahub/blob/430ca10c15dd74c6470385a1ac44f136e9c23e44/metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py#L44).
its still using db_name and still ignoring the db_alias in the config file.

**Comment by maggiehays** [comment]
Hi @kevinhu! Can you take a look at this one?

**Comment by kevinhu** [comment]
Sure!

**Comment by kevinhu** [comment]
@datatimnih should be fixed! See https://github.com/datahub-project/datahub/pull/4523
