### ISSUE TITLE
run quickstart :ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443)

### ISSUE THREAD

**Issue by younevergiveup** [datahub-project/datahub#4454]
when I use "python3 -m  datahub docker quickstart" to run
my system is liunx
Terminal shows:
ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /linkedin/datahub/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe6251dfa00>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by maggiehays** [comment]
@anshbansal Can you take a look at this one?

**Comment by anshbansal** [comment]
Hi @younevergiveup Can you please try again? During the past few weeks Github had many incidents due to which you might have faced this issue. Since then Github has been working properly so Quickstart should work for you now.

**Comment by younevergiveup** [comment]
OK!Thank you for your reply.I tried again&nbsp; and have solved it .Have a good day!






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aseem ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [datahub-project/datahub] run quickstart :ConnectionError: HTTPSConnectionPool(host=&#39;raw.githubusercontent.com&#39;, port=443) (Issue #4454)





 
Hi @younevergiveup Can you please try again? During the past few weeks Github had many incidents due to which you might have faced this issue. Since then Github has been working properly so Quickstart should work for you now.

**Comment by anshbansal** [comment]
@maggiehays This can be closed now.
