### ISSUE TITLE
ML Feature Table Tabs not being enabled

### ISSUE THREAD

**Issue by RyanHolstien** [datahub-project/datahub#4458]
**Describe the bug**
Currently the Sources and Ownership tabs are not being populated in the DataHub UI despite data being available

**To Reproduce**
1. Ingest data into ML Feature Table sources or ownership
2. Navigate to the Entity Profile page for the ingested ML Feature Table

**Expected behavior**
Tabs should be enabled and populated

**Screenshots**

**Additional context**
[Slack Thread](https://datahubspace.slack.com/archives/CV2UXSE9L/p1647767336977909)

**Comment by gabe-lyons** [comment]
Resolved!
