### ISSUE TITLE
Delete CLI does not handle case sensitivity for DataFlow & DataJob

### ISSUE THREAD

**Issue by RyanHolstien** [datahub-project/datahub#4461]
**Describe the bug**
The delete CLI does a exact match on "dataflow" and "datajob" which results in confusion when users input the entity_type as "dataJob" or "dataFlow"

**To Reproduce**
Use datahub delete  --entity_type dataFlow --platform airflow

**Expected behavior**
Should allow the command

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**
[Slack Thread](https://datahubspace.slack.com/archives/C029A3M079U/p1647714893769409)

**Comment by shirshanka** [comment]
fixed by #4492
