### ISSUE TITLE
DatahubRestEmitter.test_connection() not validating datahub-gms token

### ISSUE THREAD

**Issue by eeepmb** [datahub-project/datahub#4465]
Hi there, 
when running the code below I'd expect `test_connection()` to validate datahub-gms token as well. However running this w/o token still passes the connection test.

```python
emitter = DatahubRestEmitter(gms_server, datahub_token)

try:
    print('Testing connection...')
    emitter.test_connection()
except Exception as err:
    print(f'Error occurred: {err}')
    sys.exit(1)

print('Passed.')
```

* DataHub GMS/Fronted v0.8.31
* acryl-datahub v0.8.31

**Comment by mohdsiddique** [comment]
Hi @eeepmb 
Could you please try the latest version of DataHub?
