### ISSUE TITLE
Managed Ingestion does not add requisite Oracle Libraries to Datahub Actions

### ISSUE THREAD

**Issue by RyanHolstien** [datahub-project/datahub#4486]
**Describe the bug**
Running UI ingestion for an Oracle instance fails with:

```
Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared '
           'object file: No such file or directory"
```

**To Reproduce**
1. Set up an Oracle Database
2. Run ingestion for this database through the UI

**Expected behavior**
Ingestion should complete successfully

**Desktop (please complete the following information):**
N/A

**Additional context**
[Slack Thread](https://datahubspace.slack.com/archives/CUMUWQU66/p1647969995814549)

**Comment by hsheth2** [comment]
In order to solve this, we'll need to modify the datahub-action Dockerfile to install the Oracle instant client - not sure we want that sort of bloat for everyone to solve this specific issue. Thoughts?

**Comment by Amanda-Chgar** [comment]
I have encountered similar problems posted #4514. Our technicians tried to rely on local updates and found it very difficult to achieve:( hope u guys give some suggestions and solutions. THX a lot!

**Comment by jjoyce0510** [comment]
@Amanda-Chgar Were you able to make progress using the CLI alone? If not please ping us on Slack

**Comment by anshbansal** [comment]
This should be fixed in https://github.com/acryldata/datahub-actions/pull/24
