### ISSUE TITLE
"Copy URN" button in UI throws exception on "reading writeText"

### ISSUE THREAD

**Issue by andres-lowrie** [datahub-project/datahub#4509]
**Describe the bug**
When clicking on the "Copy URN" button in the UI, the urn is not placed into clipboard and instead the UI throws an exception

**To Reproduce**
1. Open Developer Tools (or something to see javascript console)
2. Go to to a screen that has the button
3. Click on the button
4. See following exception: 
```
react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick (EntityHeader.tsx:180:45)
    at J (button.js:233:57)
    at Object.qe (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at wr (react-dom.production.min.js:100:68)
    at Sr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at je (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
```

**Expected behavior**
The URN should be placed into clipboard

**Screenshots**
<img width="636" alt="copy_urn_button" src="https://user-images.githubusercontent.com/6182700/160422868-0ca32164-afca-45b6-964f-8b371d6d721d.png">

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.7
 - Google Chrome  
 - 99.0.4844.83 (Official Build) (x86_64)

**Comment by jjoyce0510** [comment]
We have not seen this. What version of chrome are you on?

**Comment by jjoyce0510** [comment]
If possible, would you mind sharing a video / gif to help us debug further?

**Comment by andres-lowrie** [comment]
> If possible, would you mind sharing a video / gif to help us debug further?

Version 100.0.4896.127 (Official Build) (x86_64) of Google Chrome...
 in terms of a video, it's gonna take me a bit to do that ... I'll try and set aside some time to knock that out

**Comment by YTQ419** [comment]
I have the same problem，Have you solved it

**Comment by YTQ419** [comment]
I have the same problem，Have you solved it

**Comment by YTQ419** [comment]
I have the same problem，Have you solved it

Chrome-version 101.0.4951.67

**Comment by jjoyce0510** [comment]
Hi folks.

This has been _Resolved_ in recent versions of DataHub.

Closing the ticket as fixed.

Thanks
John
