### ISSUE TITLE
DataHub is unable to search/list all datasets more than 10k datasets

### ISSUE THREAD

**Issue by nickwu241** [datahub-project/datahub#4575]
**Describe the bug**
DataHub is unable to search/list all datasets more than 10k datasets

**To Reproduce**

1. Have a DataHub instance with more than 10k datasets.
2. Run a search query on the UI e.g. `*` or `snowflake` if there are more than 10k snowflake datasets, it only displays up to 10k results.
3. This happens similarly for a [GraphQL search query](https://datahubproject.io/docs/graphql/queries#search), the [searchResult](https://datahubproject.io/docs/graphql/objects/#searchresults) `total` returned is `10000` but there exists more than `10000` datasets.
```graphql
query {
  search(input: {
    type: DATASET,
    query: "*",
    count: 500,
    start: 0,
  }) {
    total
    searchResults {
      entity {
        ... on Dataset {
          urn
        }
      }
    }
  }
}
```

**Expected behavior**
DataHub should be able to list / search for more than 10k datasets.

**Screenshots**
Unable to post.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 99.0.4844.84 (Official Build) (x86_64)

**Additional context**
We are using the [search query](https://datahubproject.io/docs/graphql/queries#search) to list all the datasets we have, but due to this limitation, we are unable to list all the datasets.

Use Case
We have a scheduled job to generate a report of all datasets. The scheduled job calls the [GaphQL Search API](https://datahubproject.io/docs/graphql/queries/#search) to list all of the datasets and relevant information we need. Our requirements is to catalog all of the datasets and some relevant information such as field tags / terms.

Problem
Our datahub instance has more than 10k datasets. So we there is no way to pull all of the datasets via an API.

We tried using the Search API but since we have more than 10k datasets, it does not work. To clarify, we are paging through 500 datasets each call, but the [searchResults](https://datahubproject.io/docs/graphql/objects/#searchresults) only allow you to get you a `total` of the first 10k results, even with pagination.

So e.g. if there are 25k datasets, the `searchResults` `total` will be `10000` still and there's no way to get the remaining 15k datasets.

**Potential Solutions**
If DataHub has another API to get all of the datasets rather than a "search" API.

Or if DataHub should have an API to list all the URNs, then we can query each dataset individually (https://datahubproject.io/docs/graphql/queries#dataset)

Or if using search API, we can segment the search api call such that the results are under 10k each call by providing different "filters" for the search term. But not as reliable because:
1. May not ensure coverage of all datasets
2. Requires manual updates to the search filters as the number of datasets increase

**Comment by treff7es** [comment]
Hey @nickwu241 ,
Please, can you elaborate a bit for me what is your use case where you had this limitation?
Do you have some special use cases where you need to list all the entities and it is not enough to have this max 10k?

**Comment by nickwu241** [comment]
> Hey @nickwu241 , Please, can you elaborate a bit for me what is your use case where you had this limitation? Do you have some special use cases where you need to list all the entities and it is not enough to have this max 10k?

Use Case: We have a scheduled job to generate a report of all datasets. The scheduled job calls the [GaphQL Search API](https://datahubproject.io/docs/graphql/queries/#search) to list all of the datasets, 

Problem: Our datahub instance we have more than 10k datasets. So we can not pull all of the datasets via the search API since we have more than 10k datasets. To clarify, we are paging through 500 results/datasets each call, but the [searchResults](https://datahubproject.io/docs/graphql/objects/#searchresults) only allow you to get the first 10k results even with pagination.

Potential Workaround: Segment the search results to under 10k by providing different "filters" for the search term, but this is not as reliable, and requires manual updates as the number of datasets increase.

**Comment by xiphl** [comment]
feels like it would be easier to just query the DB for the urns first :)

**Comment by dexter-mh-lee** [comment]
Hi. This is a limitation of Elasticsearch. https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html Elasticsearch was never designed to fetch all but instead cut the search space using the query or filters to find the document of choice. What is the use case you have in mind?

**Comment by nickwu241** [comment]
> feels like it would be easier to just query the DB for the urns first :)

Theoretically possible but it'd be preferred to use DataHub's APIs since the DB is internal to DataHub, it shouldn't be accessed by other services / users.

Our use case is a scheduled report of our data catalog, so this scheduled job shouldn't be reaching into DataHub internals as it's just a client.

> Hi. This is a limitation of Elasticsearch. https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html Elasticsearch was never designed to fetch all but instead cut the search space using the query or filters to find the document of choice. What is the use case you have in mind?

Hey @dexter-mh-lee , does https://github.com/datahub-project/datahub/issues/4575#issuecomment-1090452586 help explain our use case? We have a scheduled job to generate a report of data catalog basically, and it's unable to do this because there are more than 10k datasets.

**Comment by dexter-mh-lee** [comment]
Try using this rest endpoint which goes through all entities in mysql
```
curl --location --request POST 'http://localhost:8080/entities?action=listUrns' \
--header 'X-RestLi-Protocol-Version: 2.0.0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "entity": "dataset",
    "start": 0,
    "count": 10
}'
```

Note we do not have any guarantees on the latency of this endpoint. We have seen that it could take order of minutes when there are more than a million datasets.

**Comment by nickwu241** [comment]
> Try using this rest endpoint which goes through all entities in mysql
> 
> ```
> curl --location --request POST 'http://localhost:8080/entities?action=listUrns' \
> --header 'X-RestLi-Protocol-Version: 2.0.0' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "entity": "dataset",
>     "start": 0,
>     "count": 10
> }'
> ```
> 
> Note we do not have any guarantees on the latency of this endpoint. We have seen that it could take order of minutes when there are more than a million datasets.

Got it, we'll give this a shot, thanks :)

**Comment by shyandsy** [comment]
> oint which goes through all entities

thanks so much for your reply
it's exactly what I try to find on this week

**Comment by anshbansal** [comment]
This issue has more context https://github.com/datahub-project/datahub/issues/5928 on the problems being faced.

**Comment by hsheth2** [comment]
To close the loop here: we released a "scrollAcrossEntities" graphql endpoint a few months ago that supports listing over 10k+ entities.

**Comment by cccs-Dustin** [comment]
> To close the loop here: we released a "scrollAcrossEntities" graphql endpoint a few months ago that supports listing over 10k+ entities.

Was this endpoint included in one of the recent releases? I'm still running into the same issue mentioned in #6720 on v0.10.5.

**Comment by hsheth2** [comment]
@cccs-Dustin I think the UI still uses the original search endpoint - so you'll run into that 10k limitation in the UI.

The scrollAcrossEntities is mainly targeted towards programmatic use-cases, and should work correctly there.

**Comment by cccs-Dustin** [comment]
@hsheth2 Is there a plan to update the endpoint that's used by the UI?

**Comment by hsheth2** [comment]
@cccs-Dustin not sure - we haven't had a reason to do it yet. I do want to understand a bit more about _why_ you might need 10k+ results in paginated search, vs applying more filters to find the things you're looking for.

**Comment by cccs-Dustin** [comment]
@hsheth2 applying more filters is definitely the optimal solution, however, would it be possible to add a more detailed error message instead of a generic 500 response page (for this particular use case)? Something along the lines of it saying that there are too many results and you have to refine your search.
