### ISSUE TITLE
unable to run quickstart, datahub-gms is running but not healthy

### ISSUE THREAD

**Issue by Morefarther** [datahub-project/datahub#4606]
datahub version

> DataHub CLI version: 0.8.31.6
> Python version: 3.8.13 (default, Apr  1 2022, 11:29:53) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

run shell

> datahub docker quickstart --quickstart-compose-file ./docker/quickstart/docker-compose-without-neo4j.quickstart.yml

show this

![pic1](https://user-images.githubusercontent.com/49953642/162155759-86f623b1-db11-44ca-8225-56e90852278b.png)

![pic2](https://user-images.githubusercontent.com/49953642/162155771-06c7bc13-4be6-4cfe-9565-a013d8df1869.png)

unable to run quickstart, datahub-gms is running but not healthy. 
run shell
> docker container ls

![pic3](https://user-images.githubusercontent.com/49953642/162155779-42ddcbd1-3eea-45e9-91df-e2f2395cc490.png)

run shell

> docker logs 46735e503222

![pic3 5](https://user-images.githubusercontent.com/49953642/162155776-af1589c1-a2e6-4037-8358-f1eb2f2f9773.png)

Problem with request: Get "http://elasticsearch:9200": dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
and java.util.zip.ZipException: invalid entry CRC.

check elasticsearch. it is healthy, no index. run shell

> curl 172.18.0.2:9200/
> curl 172.18.0.2:9200/_cat/health
> curl 172.18.0.2:9200/_cat/indices?v

![pic4](https://user-images.githubusercontent.com/49953642/162155786-e22ea49f-2063-4918-ac5a-04c48ee2f1f6.png)

datahub-gms container log file is
[tmpiduh6x9k.log](https://github.com/datahub-project/datahub/files/8441019/tmpiduh6x9k.log)

and the all log file is
[46735e5032224e151be6e54e841cd534f212763d79d133ab86359b3f55c76b93-json.log](https://github.com/datahub-project/datahub/files/8441021/46735e5032224e151be6e54e841cd534f212763d79d133ab86359b3f55c76b93-json.log)

**Comment by jjoyce0510** [comment]
What type of machine are you running on? 

 We have recently been seeing issues on CentOS

**Comment by pedro93** [comment]
Hello @younevergiveup 

Could you share your datahub-gms logs? 
Thank you

**Comment by younevergiveup** [comment]
> 

<img width="823" alt="1652829853(1)" src="https://user-images.githubusercontent.com/101927667/168928165-feb0b479-48d3-4d00-876f-3c0800e2f186.png">
<img width="822" alt="1652829882(1)" src="https://user-images.githubusercontent.com/101927667/168928189-49f70b41-29dd-4696-9686-96586fe9bb3e.png">
<img width="824" alt="1652829902(1)" src="https://user-images.githubusercontent.com/101927667/168928200-9109a9d9-bbfa-4fc7-a85b-2779932d9b0d.png">

**Comment by younevergiveup** [comment]
By the way,it was the second time I "datahub docker quickstart ",I succeeded the first time and powered off.I want to  operate "datahub docker ingest-sample-data",so I operate "datahub docker quickstart " again.I wonder if it is becaused my storage.When I  operate "datahub docker quickstart ",my Ubuntu shows low storage.

> 你好@younevergiveup
> 
> 你能分享你的datahub-gms日志吗？ 谢谢

**Comment by yangyangss** [comment]
Hi, I got same issue as well, my tech spec as below:
MacOS Monterey 12.3.1
Python 3.8.5
Docker 20.10.6, build 370c289
I've tried to quick start directly and clone the project to my local pc and start from docker-compose file, got same error. Full log has been attached .
[datahub_20220518.log](https://github.com/datahub-project/datahub/files/8713801/datahub_20220518.log)

**Comment by younevergiveup** [comment]
This is complete datahub-gms  log file.
[outfile.log](https://github.com/datahub-project/datahub/files/8714249/outfile.log)
 The three pictures are just a part of them.
And my tech spec are following:
Ubuntu 20.04.4 LTS,
Python 3.8.10,
Docker version 20.10.13,
acryl-datahub, version 0.8.34.2
Thanks!

**Comment by younevergiveup** [comment]
I finally solve this issue!!!My memory and hard disk are not  large enough to support running quickstart .I adjust my memory to 8G and  hard disk to 29G.
<img width="344" alt="255e5fd91ed0f466faca4619ab68768" src="https://user-images.githubusercontent.com/101927667/169024457-55a132ce-00a3-409c-987e-169c8c80c796.png">

> This is complete datahub-gms log file. [outfile.log](https://github.com/datahub-project/datahub/files/8714249/outfile.log) The three pictures are just a part of them. And my tech spec are following: Ubuntu 20.04.4 LTS, Python 3.8.10, Docker version 20.10.13, acryl-datahub, version 0.8.34.2 Thanks!

**Comment by yangyangss** [comment]
Hi,
My issue still in there. my docker resources meet the datahub quickstart requirements:
CPU :  3
Memory: 8.5GB
Swap: 2 GB
Disk image size: 64GB(28.6GB used)


<img width="971" alt="image" src="https://user-images.githubusercontent.com/3345653/169189410-feea3622-62f7-466e-b6f8-bb73875c7861.png">

**Comment by younevergiveup** [comment]
Could you operate "cat /proc/meminfo" Cause I found if operate "quickstart" more than once,the available memory will decrease rapidly.And then I used snapshot to roll back to before quickstart and adjusted my memory and made it finally.



---Original---
From: ***@***.***&gt;
Date: Thu, May 19, 2022 10:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [datahub-project/datahub] unable to run quickstart, datahub-gms is running but not healthy (Issue #4606)




 
Hi,
 My issue still in there. my docker resources meet the datahub quickstart requirements:
 CPU :  3
 Memory: 8.5GB
 Swap: 2 GB
 Disk image size: 64GB(28.6GB used)

**Comment by yangyangss** [comment]
@younevergiveup  thank you for your suggestion. I've tried but still got same issue, I will wait for next release and try again.

**Comment by anshbansal** [comment]
@yangyangss Did you get a chance to try it with a new version? If this is no longer an issue we will close this issue in few days due to inactivity.

**Comment by cresny** [comment]
Hi I'm having the same problem. I notice kafka-setup continuously re-runs, event though it seems to be successful. running on MacOs Monterey, dacker has 4 cpus 8G RAM, 128G disk

**Comment by pedro93** [comment]
Hello @cresny 

Quickstart requires that docker have at least 12GB of RAM.

Thank you

**Comment by cresny** [comment]
ok, thanks for the quick response.  I tried again with 12G but got the same result. I'm guessing it has something to do with MacOs having non-native Docker Desktop.

**Comment by cresny** [comment]
btw, this worked like a charm a couple of months ago. It seems like some services cannot see others, triggering restart loops. I'm not too experienced with Docker Compose but I'm happy to troubleshoot if you have any suggestions.

**Comment by cresny** [comment]
ok, checked Slack, found "set DATAHUB_TELEMETRY_ENABLED=true" fixes this

**Comment by anshbansal** [comment]
Good to know this worked

**Comment by anshbansal** [comment]
For anyone else seeing quickstart not running please head to DataHub slack

**Comment by leandro-ferreira-farm** [comment]
I had the same problem. When a run Datahub Quickstart the massage is print to me: "Docker is not ready:
- quickstart.sh or dev.sh is not running"
