### ISSUE TITLE
Random JSON Files

### ISSUE THREAD

**Issue by Cascol-SCUT** [datahub-project/datahub#4628]
Datahub can extract schema info from json files, however, does it support json files like the one bellow, or how shall I modify it?
![image](https://user-images.githubusercontent.com/51443787/161524365-ef7467b4-7d92-4044-b9d5-73b53c4faa5f.png) More generally, when users are uploading random json files, how does datahub deal with them

**Comment by maggiehays** [comment]
Hi @Cascol-SCUT! DataHub doesn't currently support detecting JSON schemas from random json files, but it's a great suggestion! If this is something you'd like to see supported, please feel free to open a feature request [here](https://feature-requests.datahubproject.io/); I'll close out this issue in the meantime!
