### ISSUE TITLE
[Data Quality]: Support Spark excution engine?

### ISSUE THREAD

**Issue by ddsr-ops** [datahub-project/datahub#4630]
Hello, I have known about data quality validation does not suppurt Spark engine.
```
Limitations[​](https://datahubproject.io/docs/metadata-ingestion/integration_docs/great-expectations#limitations)
This integration does not support

v2 Datasources such as SqlAlchemyDataset
v3 Datasources using execution engine other than SqlAlchemyExecutionEngine (Spark, Pandas)
Cross-dataset expectations (those involving > 1 table)
```

However, how to do data quality validation for iceberg table using Spark engine.
Thanks for your advices.

**Comment by maggiehays** [comment]
Hi @ddsr-ops, we have a feature request for adding in support for Spark & Pandas execution engine for data quality [here](https://feature-requests.datahubproject.io/b/feedback/p/great-expectations-support-different-execution-engines); please feel free to upvote/subscribe to the post to stay up to date with dev progress. In the meantime, I'll close out this issue.
