### ISSUE TITLE
Unable to connect to home page

### ISSUE THREAD

**Issue by SamerHameed** [datahub-project/datahub#4641]
I followed the installation procedure  and execute the run command of DataHub.
https://datahubproject.io/docs/quickstart/

But Im unable to connect to the home page of the port 9002 as I got Unable to connect.

Note:- below is the version fo the DataHub

datahub version
DataHub CLI version: 0.8.32.4
Python version: 3.10.0 (default, Apr  7 2022, 11:11:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]

**Comment by maggiehays** [comment]
Hi @SamerHameed! The team will need more detail about your environment & this is better addressed in the DataHub Slack! Please join us at slack.datahubproject.io and we'll help you out there. I'll close this out in the meantime :)
