### ISSUE TITLE
Unable to add a new source

### ISSUE THREAD

**Issue by putnam120** [datahub-project/datahub#4675]
**Describe the bug**
As part of the Quickstart I was playing around with the UI and CLI and wanted to add a new ingestion (MongoDB to be specific). However, no matter what I tried I encountered a "Connection refused" error related to GMS.

**To Reproduce**
1. Follow the steps in the Quickstart and and observe that `datahub docker check` returns that there are no issues detected.
2. In the UI click on Ingestion.
3. Click Create new source and select Mongo.
4. Enter `mongodb://localhost` for the connect_uri (I have Mongo running locally on port 27017), and also the correct credentials for the username and password fields.
5. Leave the sink's server address as `http://localhost:9002/api/gms`
6. Skip setting up a schedule and finish the setup.
7. Click execute within the UI.

After a few seconds the job fails and from the logs I see the following.
```
"establish a new connection: [Errno 111] Connection refused')': /api/gms/config\n"
           '[2022-04-14 23:03:53,631] WARNING  {urllib3.connectionpool:810} - Retrying (Retry(total=1, connect=None, read=None, redirect=None, '
           "status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f153f0d64c0>: Failed to "
           "establish a new connection: [Errno 111] Connection refused')': /api/gms/config\n"
           '[2022-04-14 23:04:01,618] WARNING  {urllib3.connectionpool:810} - Retrying (Retry(total=0, connect=None, read=None, redirect=None, '
           "status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f153f0d6310>: Failed to "
           "establish a new connection: [Errno 111] Connection refused')': /api/gms/config\n"
```

If I change the server's sink address to `http://localhost:8080` I get the same error but instead of `/api/gms/config` the logs contain `/config`.

**Expected behavior**
The ingestion of the data in my MongoDB would be successful and I'd see the data in the UI.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.2
 - Browser: Chrome Version 100.0.4896.88 (Official Build) (x86_64)

**Comment by nj7** [comment]
@putnam120 I think you are doing it wrong, instead of using "localhost:9002/api/gms" and "localhost:8080" you should use 'http://datahub-gms:8080'

Since you have not enabled Access token functionality you are unauthorized to make a request.

When you enable access token generation in your you can use "localhost:9002/api/gms" with token config.

**Comment by nj7** [comment]
You can refer to this link for more details : https://datahubproject.io/docs/ui-ingestion/

**Comment by jjoyce0510** [comment]
Yes - That is the correct solution. 

Thanks @nj7 for replying, and thanks @putnam120 for raising the issue.

Closing this one out.

John
