### ISSUE TITLE
Use extended metadata model

### ISSUE THREAD

**Issue by Huyueeer** [datahub-project/datahub#4688]
I installed the instance with extended metadata and added some search tags in it. I found some writing and reading about aspects in the document, but how can search be supported? for example
```
  @Searchable = {
    "fieldType": "TEXT_PARTIAL",
    "enableAutocomplete": true,
    "boostScore": 10.0
  }
  cnName: optional string
```
Or do you need to configure or develop other places

**Comment by jjoyce0510** [comment]
@Huyueeer Have you tried adding this annotation to your extended aspect? Is it appearing in the search index?

**Comment by Huyueeer** [comment]
I added it to the extended data. In addition, I want to know, for example, if I add it to the glossary term, will the index appear in the glossaryTermIndex?

**Comment by jjoyce0510** [comment]
Yes it will. This annotation is the exact solution you are looking for.

Due to inactivity, I'm going to close the issue. Please feel free to reopen, or reach out on slack, if you feel there is still a problem.

Thanks
John
