### ISSUE TITLE
Java Emitter coding problem 

### ISSUE THREAD

**Issue by Huyueeer** [datahub-project/datahub#4700]
Chinese character problem encountered when calling ingestProposal interface and using java emitter；
`
"message": "Parameters of method 'ingestProposal' failed validation with error 'ERROR :: /proposal/aspect/value :: \" {\"usName\":\"eng\",\"cnDefinition\":\"\",\"cnName\":\"中文\",\"usDefinition\":\"Test data to test whether Chinese word segmentation has a good return effect\",\"status\":\"Draft\"}\" is not a valid string representation of bytes\n'"
`

**Comment by jjoyce0510** [comment]
@MugdhaHardikar-GSLab Can you take a look here?

**Comment by zheyu001** [comment]
Any updates on this? We are seeing similar issue if contains Japenese character.

**Comment by shirshanka** [comment]
We should have a fix for this bug this week.
