### ISSUE TITLE
Lineage, BigQuery - lineage extraction breaks at table/view names not being wrapped in backticks

### ISSUE THREAD

**Issue by vgaidass** [datahub-project/datahub#4714]
**Describe the bug**
BigQuery metadata extraction breaks when trying to process SQL queries like
```
CREATE OR REPLACE TABLE project.dataset.table AS
SELECT *
FROM `project.dataset.src_table_A`
UNION
SELECT *
FROM project.dataset.src_table_B
```

**To Reproduce**
1. Prepare a query as shown above, leave some table/view names not wrapped in backticks - BigQuery will allow such formatting
2. Execute Datahub metadata ingestion with `use_exported_bigquery_audit_metadata: true`

**Expected behavior**
Metadata ingestion mechanism should wrap table/view names in backticks so that sqllineage could parse the queries

**Comment by vgaidass** [comment]
I'm working on this bug myself

**Comment by jjoyce0510** [comment]
Here's where we are doing the SQL parsing: https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py#L545

**Comment by jjoyce0510** [comment]
Can we try to determine whether there's a native way to determine this that avoids SQL parsing?

**Comment by vgaidass** [comment]
@jjoyce0510 Haven't found anything OOTB. Seems like that queries that are passable in BigQuery are actually bad for sqllineage.
That applies not only to table/view names not being wrapped in backticks but also to the presence of keywords that one can use as a column name (e.g., SELECT x.from FROM project.dataset.table AS x).

So far, seems like we need to have a multi-step cleaning of SQL queries via regex like it's being done now, but with extra steps
