### ISSUE TITLE
metadata-ingestion entrypoints.py complie question

### ISSUE THREAD

**Issue by iosMental** [datahub-project/datahub#4734]
git clone https://github.com/datahub-project/datahub
cd datahub
./gradlew build

When I open metadata-ingestion module
![image](https://user-images.githubusercontent.com/10148880/164861414-2fcb3f75-bc6e-4dc0-a9fc-aa929d492670.png)

I want to know how to handle the datahub error prompt in metadata-ingestion module

**Comment by xiphl** [comment]
Run ./gradlew :metadata-ingestion:codegen

**Comment by iosMental** [comment]
> ./gradlew :metadata-ingestion:codegen

thanks  i run   ./gradlew :metadata-ingestion:codegen  but still prompt error when  runPreFlightScript


 Task :metadata-ingestion:runPreFlightScript
🔎 Checking if current directory is metadata-ingestion folder
✅ Current folder is metadata-ingestion (/Users/wangdongkun/chj/github/datahub/metadata-ingestion) folder
👟 Running preflight for m1 mac
✨ Creating/activating Virtual Environment🔎 Checking if Scipy installed
Scipy not installed
⛅ Installing prerequisities for scipyWarning: openblas 0.3.20 is already installed and up-to-date.
To reinstall 0.3.20, run:
  brew reinstall openblas
WARNING: Skipping numpy as it is not installed.
WARNING: Skipping pythran as it is not installed.
Requirement already satisfied: cython in ./venv/lib/python3.8/site-packages (0.29.28)
Requirement already satisfied: pybind11 in ./venv/lib/python3.8/site-packages (2.9.2)
Collecting numpy
  Downloading numpy-1.22.3.zip (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Skipping wheel build for numpy, due to binaries being disabled for it.
Installing collected packages: numpy
  Running setup.py install for numpy: started
  Running setup.py install for numpy: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for numpy did not run successfully.
  │ exit code: 1
  ╰─> [1333 lines of output]
      Running from numpy source directory.
      
      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:
      
        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)
      
      ...
      ....






INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: aarch64
        Compiler    : clang
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : none
        Flags       : none
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : none
        Generated   : none
      INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /private/var/folders/3k/pjpmrxl91gsfwl734jv4lf4w0000gp/T/pip-install-7kw6mvmw/numpy_4b454323da914776959040d1c193c05c/build/temp.macosx-10.14-arm64-3.8/ccompiler_opt_cache_ext.py
      INFO:
      ########### CLIB COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: aarch64
        Compiler    : clang
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : none
        Flags       : none
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : none
        Generated   : none
      INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /private/var/folders/3k/pjpmrxl91gsfwl734jv4lf4w0000gp/T/pip-install-7kw6mvmw/numpy_4b454323da914776959040d1c193c05c/build/temp.macosx-10.14-arm64-3.8/ccompiler_opt_cache_clib.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> numpy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

> Task :metadata-ingestion:runPreFlightScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':metadata-ingestion:runPreFlightScript'.
> Process 'command 'scripts/datahub_preflight.sh'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 1s
23 actionable tasks: 8 executed, 15 up-to-date

**Comment by iosMental** [comment]
> > ./gradlew :metadata-ingestion:codegen
> 
> thanks i run ./gradlew :metadata-ingestion:codegen but still prompt error when runPreFlightScript
> 
> Task :metadata-ingestion:runPreFlightScript 🔎 Checking if current directory is metadata-ingestion folder ✅ Current folder is metadata-ingestion (/Users/wangdongkun/chj/github/datahub/metadata-ingestion) folder 👟 Running preflight for m1 mac ✨ Creating/activating Virtual Environment🔎 Checking if Scipy installed Scipy not installed ⛅ Installing prerequisities for scipyWarning: openblas 0.3.20 is already installed and up-to-date. To reinstall 0.3.20, run: brew reinstall openblas WARNING: Skipping numpy as it is not installed. WARNING: Skipping pythran as it is not installed. Requirement already satisfied: cython in ./venv/lib/python3.8/site-packages (0.29.28) Requirement already satisfied: pybind11 in ./venv/lib/python3.8/site-packages (2.9.2) Collecting numpy Downloading numpy-1.22.3.zip (11.5 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 5.9 MB/s eta 0:00:00 Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'done' Skipping wheel build for numpy, due to binaries being disabled for it. Installing collected packages: numpy Running setup.py install for numpy: started Running setup.py install for numpy: finished with status 'error' error: subprocess-exited-with-error
> 
> × Running setup.py install for numpy did not run successfully. │ exit code: 1 ╰─> [1333 lines of output] Running from numpy source directory.
> 
> ```
>   Note: if you need reliable uninstall behavior, then install
>   with pip instead of using `setup.py install`:
>   
>     - `pip install .`       (from a git repo or downloaded source
>                              release)
>     - `pip install numpy`   (last NumPy release on PyPi)
>   
>   ...
>   ....
> ```
> 
> INFO: ########### EXT COMPILER OPTIMIZATION ########### INFO: Platform : Architecture: aarch64 Compiler : clang
> 
> ```
>   CPU baseline  :
>     Requested   : 'min'
>     Enabled     : none
>     Flags       : none
>     Extra checks: none
>   
>   CPU dispatch  :
>     Requested   : 'max -xop -fma4'
>     Enabled     : none
>     Generated   : none
>   INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /private/var/folders/3k/pjpmrxl91gsfwl734jv4lf4w0000gp/T/pip-install-7kw6mvmw/numpy_4b454323da914776959040d1c193c05c/build/temp.macosx-10.14-arm64-3.8/ccompiler_opt_cache_ext.py
>   INFO:
>   ########### CLIB COMPILER OPTIMIZATION ###########
>   INFO: Platform      :
>     Architecture: aarch64
>     Compiler    : clang
>   
>   CPU baseline  :
>     Requested   : 'min'
>     Enabled     : none
>     Flags       : none
>     Extra checks: none
>   
>   CPU dispatch  :
>     Requested   : 'max -xop -fma4'
>     Enabled     : none
>     Generated   : none
>   INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /private/var/folders/3k/pjpmrxl91gsfwl734jv4lf4w0000gp/T/pip-install-7kw6mvmw/numpy_4b454323da914776959040d1c193c05c/build/temp.macosx-10.14-arm64-3.8/ccompiler_opt_cache_clib.py
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> × Encountered error while trying to install package. ╰─> numpy
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.
> 
> > Task :metadata-ingestion:runPreFlightScript FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':metadata-ingestion:runPreFlightScript'.
> 
> > Process 'command 'scripts/datahub_preflight.sh'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 1m 1s 23 actionable tasks: 8 executed, 15 up-to-date

i am trying to   pip3 install numpy  and retry

**Comment by iosMental** [comment]
i am trying to run:  pip3 install numpy 
and then run:  ./gradlew :metadata-ingestion:codegen  still prompt error when runPreFlightScript


 Task :metadata-ingestion:runPreFlightScript
🔎 Checking if current directory is metadata-ingestion folder
✅ Current folder is metadata-ingestion (/Users/wangdongkun/chj/github/datahub/metadata-ingestion) folder
👟 Running preflight for m1 mac
✨ Creating/activating Virtual Environment🔎 Checking if Scipy installed
Scipy not installed
⛅ Installing prerequisities for scipyWarning: openblas 0.3.20 is already installed and up-to-date.
To reinstall 0.3.20, run:
  brew reinstall openblas
Found existing installation: numpy 1.22.3
Uninstalling numpy-1.22.3:
  Successfully uninstalled numpy-1.22.3
WARNING: Skipping pythran as it is not installed.
Requirement already satisfied: cython in ./venv/lib/python3.8/site-packages (0.29.28)
Requirement already satisfied: pybind11 in ./venv/lib/python3.8/site-packages (2.9.2)
Collecting numpy
  Using cached numpy-1.22.3.zip (11.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Skipping wheel build for numpy, due to binaries being disabled for it.
Installing collected packages: numpy
  Running setup.py install for numpy: started
  Running setup.py install for numpy: finished with status 'error'
  error: subprocess-exited-with-error

**Comment by iosMental** [comment]
run ./gradlew :metadata-ingestion:codegen  success
but in the project module（metadata-ingestion）my idea still prompt 
![image](https://user-images.githubusercontent.com/10148880/164915542-9c793d54-5082-4b21-ad2e-c32953db462f.png)
