### ISSUE TITLE
How can I debug the local meta-ingestion code in order to get familiar with the code better

### ISSUE THREAD

**Issue by iosMental** [datahub-project/datahub#4736]
i want to debug the ingestion code local

i run
../gradlew :metadata-ingestion:installDev
source venv/bin/activate
datahub version 

What should I do next please,and my code my local code tips
no module named 'datahub' in entrypoints.py

**Comment by maggiehays** [comment]
Hi @iosMental! For debugging support, please join our [Slack community](https://slack.datahubproject.io/) so we can rally support from the broader community. In the meantime, I'll close this out!
