### ISSUE TITLE
dead link in contributing docs

### ISSUE THREAD

**Issue by vifly** [datahub-project/datahub#4737]
Hello, I found a dead link in [CONTRIBUTING.md](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md), the link to [DataHub Feature Requests](https://feature-requests.datahubproject.io/) return 404.

**Comment by anshbansal** [comment]
I tried it just now 
![image](https://user-images.githubusercontent.com/4127841/165057663-47e40ee6-2746-4d4b-a166-cd7b3735e7e9.png)
and the page is working
![image](https://user-images.githubusercontent.com/4127841/165057709-37d560a2-c56b-4b71-828f-52bf5fbbbf5a.png)

Not able to reproduce. Please let me know if it works for you. Maybe it was a temporary error?

**Comment by vifly** [comment]
I try it again, and find it's working. It may be a temporary error, I close this issue now.
