### ISSUE TITLE
ubuntu datahub docker start error

### ISSUE THREAD

**Issue by quanhuanhuan** [datahub-project/datahub#4757]
**note: ubuntu   datahub  docker start  error**

![截图 2022-04-27 11-17-24](https://user-images.githubusercontent.com/30468100/165433673-16f9265a-03c0-471a-ba19-69ec7c728717.png)
![截图 2022-04-27 11-32-03](https://user-images.githubusercontent.com/30468100/165434470-a282891c-4056-4185-a763-6edb9652e877.png)

**Comment by suishaojian** [comment]
> **note: ubuntu datahub docker start error**
> 
> ![截图 2022-04-27 11-17-24](https://user-images.githubusercontent.com/30468100/165433673-16f9265a-03c0-471a-ba19-69ec7c728717.png) ![截图 2022-04-27 11-32-03](https://user-images.githubusercontent.com/30468100/165434470-a282891c-4056-4185-a763-6edb9652e877.png)

From the error I think it's the docker service problem...could you pls show the status of docker with command "service docker status" and check if docker is active ....

**Comment by quanhuanhuan** [comment]
docker service no problem， other docker can start， but datahub docker start error

![截图 2022-04-28 09-59-56](https://user-images.githubusercontent.com/30468100/165661618-58622341-ce56-4bcc-b6cf-4fbb884ad2ec.png)

**Comment by anshbansal** [comment]
Can you try running `docker ps -a` without sudo? If you are not able to run it without sudo that means the user that is running `datahub` does not have access to docker.

**Comment by aditya-radhakrishnan** [comment]
Please let us know if that works!

**Comment by quanhuanhuan** [comment]
![图片](https://user-images.githubusercontent.com/30468100/165878222-2ac626bc-0c5a-48a2-9557-50dfd6f46623.png)

**Comment by aditya-radhakrishnan** [comment]
This looks like a permissions issue. Would you be able to run `sudo chmod 666 /var/run/docker.sock` and then rerun `docker ps -a`? If this works then you should be able to run `datahub docker quickstart`

**Comment by quanhuanhuan** [comment]
This problem has been solved, but a new problem has emerged 。

The metadata can be synchronized normally with the command "datahub ingest -c hive-recipe.yml", but the execution fails on the web page。

![image](https://user-images.githubusercontent.com/30468100/167248480-be692b8d-4589-412b-aead-4c55216b48c1.png)

**Comment by quanhuanhuan** [comment]
resolved
