### ISSUE TITLE
datahub delete --env $ENV --platform "foo bar" would delete foo and bar platforms as well

### ISSUE THREAD

**Issue by eeepmb** [datahub-project/datahub#4759]
**Describe the bug**
When running `datahub delete --env $ENV --platform "foo bar"` the platforms `foo` and `bar` would 

**To Reproduce**
1. Create datasets for `foo` and `bar` under `$ENV`.
2. Run `datahub delete --env $ENV --platform "foo bar" --dry-run`
3. Find `foo` and `bar` datasets in the output.

**Expected behavior**
I would expect that the command only selects datasets under `foo bar`.

```
$ datahub version
DataHub CLI version: 0.8.31
Python version: 3.7.10 (default, Jun  3 2021, 00:02:01) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
```

**Comment by rslanka** [comment]
Hi @eeepmb, the behavior you are seeing is actually an artifact of how urns are searched in datahub's ElasticSearch. I'm curious what is the use-case for this? Are there any platforms with a space in their name?

**Comment by eeepmb** [comment]
Hi @rslanka we experienced this due to some input error. However I think it should be covered to not delete other platforms than the one you’re searching for. Even if there are spaces in the name.
