### ISSUE TITLE
Datahub-GMS service not running getting javax.servlet.ServletException: javax.servlet.UnavailableException: Servlet Not Initialized error

### ISSUE THREAD

**Issue by Shib12** [datahub-project/datahub#4785]
I am trying to up the Datahub release v0.8.33 code base using local build. But for Datahub gms it is giving me javax.servlet.UnavailableException: Servlet Not Initialized error. I am using dev-without-neo4j.sh to up the services also did ./gradlew build & separately ./gradlew :metadata-service:war:build to build the datahub gms service still getting the same servlet Not Initialzed error and the datahub service is not running.

Below are the code snippet for quick reference:
 
datahub-gms               | 2022-04-29 02:53:58.357:WARN:oejs.HttpChannel:qtp544724190-11: /health
datahub-gms               | javax.servlet.ServletException: javax.servlet.UnavailableException: Servlet Not Initialized
datahub-gms               |     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
datahub-gms               |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
datahub-gms               |     at org.eclipse.jetty.server.Server.handle(Server.java:494)
datahub-gms               |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
datahub-gms               |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
datahub-gms               |     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
datahub-gms               |     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
datahub-gms               |     at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
datahub-gms               |     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
datahub-gms               |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
datahub-gms               |     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
datahub-gms               |     at java.lang.Thread.run(Thread.java:748)
datahub-gms               | Caused by:
datahub-gms               | javax.servlet.UnavailableException: Servlet Not Initialized
datahub-gms               |     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:822)
datahub-gms               |     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
datahub-gms               |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
datahub-gms               |     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
datahub-gms               |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
datahub-gms               |     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
datahub-gms               |     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
datahub-gms               |     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
datahub-gms               |     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
datahub-gms               |     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
datahub-gms               |     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
datahub-gms               |     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
datahub-gms               |     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
datahub-gms               |     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
datahub-gms               |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
datahub-gms               |     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
datahub-gms               |     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
datahub-gms               |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
datahub-gms               |     at org.eclipse.jetty.server.Server.handle(Server.java:494)
datahub-gms               |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
datahub-gms               |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
datahub-gms               |     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
datahub-gms               |     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
datahub-gms               |     at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
datahub-gms               |     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
datahub-gms               |     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
datahub-gms               |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
datahub-gms               |     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
datahub-gms               |     at java.lang.Thread.run(Thread.java:748)
datahub-actions_1         | 2022/04/29 02:53:58 Received 503 from http://datahub-gms:8080/health. Sleeping 1s

Please guide how to fix the issue. I also notice the same error is in v0.8.32 release as well. 
Thanks.

**Comment by aditya-radhakrishnan** [comment]
Hi there, have you tried using the [Docker quickstart](https://datahubproject.io/docs/quickstart/) instead? That might be easier. You can run `datahub docker quickstart --version v0.8.33` to use the latest version.

**Comment by Shib12** [comment]
Hi Datahub-Project/Datahub,

Thanks for the update. But I am trying to do some local development that's
why using dev-with-out-neo4j.sh. Can you please let me know why this
Servlet Not Initialized error encounter and how to fix that.

Thanks for your help,

Regards,
Shib

**Comment by shirshanka** [comment]
Hi Shib,
  Does this guide: https://datahubproject.io/docs/developers work for you?

**Comment by Shib12** [comment]
Hi Datahub-Project/Datahub,

Ya tried that, did ./gradlew build also did separately build of ./gradlew
:metadata-service:war:build & ./gradlew :datahub-frontend:build -x yarnTest
-x yarnLint.
My build were successful but when I was trying to up the docker services
using dev-with-out-neo4j.sh file, all the services were running healthy
except datahub-gms which was unhealthy and not running properly and in the
log It was showing this Servlet Not Initialized error. I tried the same
steps for v0. 8.32 release getting the same error. But it was running fine
with v0.8.29 release.

Thanks for your help.

Regards,
Shib

**Comment by aditya-radhakrishnan** [comment]
Hey Shib, were you ever able to sort this issue out?

**Comment by jjoyce0510** [comment]
Ping! 

This ticket has been inactive for some time. I'm going to go ahead and close it due to inactivity. @Shib12 please feel free to reopen if necessary. 

Thanks
John
