### ISSUE TITLE
Python package is incompatibility with Airflow 2.3.0

### ISSUE THREAD

**Issue by Tonkonozhenko** [datahub-project/datahub#4809]
**Describe the bug**
[sqlalchemy==1.3.24](https://github.com/datahub-project/datahub/blob/c15b44a/metadata-ingestion/setup.py#L72) is incompatible with Airflow 2.3.0 [(1)](https://github.com/apache/airflow/pull/22114), [(2)](https://github.com/apache/airflow/blame/1e87f51/setup.cfg#L164)

**Comment by KulykDmytro** [comment]
is it possible to up version pin ?
this one is stopping us to move forwards with airflow (tend to stick on airflow:2.2.5)

**Comment by KulykDmytro** [comment]
Due to rollback via #5289 @treff7es please reopen this one

**Comment by koconder** [comment]
This is screwing up my current Airflow installs, need to resolve the rollback

**Comment by KulykDmytro** [comment]
> This is screwing up my current Airflow installs, need to resolve the rollback

the only way is to use apache-airflow:2.2.5
or try to loose airflow-to-sqlalchemy dependency

**Comment by mirobertod** [comment]
Hi, we are using Airflow 2.3 and we are unable to install the Python package `acryl-datahub[bigquery]`.
Any plan to upgrade the dependency `sqlalchemy`?
Thanks!

**Comment by colinfernandes87** [comment]
Hello, 

Airflow rolls back to older version when we install datahub bigquery plugin. if anyone has a workaround to enable bigquery and not downgrade airflow. Please let me know.

**Comment by shicholas** [comment]
please do not close, this is still an issue.

**Comment by Vimpy** [comment]
Hey with latest datahub release i.e. 0.8.45 still we are getting same incompatibility issue with sqlalchemy

**Comment by KulykDmytro** [comment]
Airflow 2.4.1 has been released - same stuff

**Comment by pedro-iatzky** [comment]
I'm facing the same error. I cannot use the plugin on our Airflow 2.3 because of this.
Could you provide some ETA for this?

**Comment by hsheth2** [comment]
Update here: I'm working on loosening our SQLAlchemy dependency in https://github.com/datahub-project/datahub/pull/6204.

**Comment by tommy-watts-depop** [comment]
Hi, Do we have an ETA for this fix?
