### ISSUE TITLE
Inappropriate use of catalog_id when extracting glue jobs in 0.8.33

### ISSUE THREAD

**Issue by hugh-nguyen** [datahub-project/datahub#4812]
**Describe the bug**
I have found that when i set extract_transforms to True in my Glue ingestion recipe that I receeve the following error.
![image](https://user-images.githubusercontent.com/30641101/166616604-d15b1e15-938a-4996-83d8-0a7bce5f0322.png)

The code appears to passing ConfigId into paginate() which does not support it.
![image](https://user-images.githubusercontent.com/30641101/166616667-ad5ba876-6d19-4add-bf59-88f7a697111e.png)

Check the doco for paginate here
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.paginate

**Comment by maggiehays** [comment]
Hi @hugh-nguyen! I noticed this is an open thread in the DataHub Slack ([link](https://datahubspace.slack.com/archives/CUMUWQU66/p1651629847920729)) as well -- let's continue the conversation there; it would be helpful if you could post the full stack trace as well. 

I'll close out this issue in the meantime!
