### ISSUE TITLE
Issue in showing lineage of tasks in pipeline

### ISSUE THREAD

**Issue by pavanmallepudi** [datahub-project/datahub#4814]
Hi Team,

we have emitted some metadata regarding a job  as a pipeline to datahub . but in ui one to many mapping is showing between job tasks . Kindly help us to resolve the issue . 

![image](https://user-images.githubusercontent.com/30781339/166659056-4435b09e-6b50-43a9-9a8e-bb448867257c.png)

**Comment by maggiehays** [comment]
Hi @pavanmallepudi! Would you mind sharing a snippet of the code you're using to generate this graph? A reproducible set of metadata events file would be helpful for us to help us debug.

**Comment by rslanka** [comment]
Did not hear back from the reporter in a while with a request for sample metadata to reproduce the issue. Closing.
