### ISSUE TITLE
Wechat Group|创建了一个初学者微信群，一起讨论datahub学习过程的问题

### ISSUE THREAD

**Issue by looperEit** [datahub-project/datahub#4851]
创建一个微信群，来一起讨论datahub搭建过程中初学者遇到的问题；互相学习；
I have created a WeChat group to discuss the problems encountered by beginners in the process of building datahub; learn from each other;
![IMG_0873(20220506-155157)](https://user-images.githubusercontent.com/46367388/167090994-84673622-fa04-4bf1-8ff4-775df46e936b.JPG)

**Comment by redgreat** [comment]
add me 
wechatid: redgreat

**Comment by yinxiangbo** [comment]
再发一下群二维码吧，谢谢了

**Comment by looperEit** [comment]
> 再发一下群二维码吧，谢谢了

![Uploading IMG_0451(20220727-232403).JPG…]()
