### ISSUE TITLE
no feedback on Policies - Activate/Deactivate

### ISSUE THREAD

**Issue by twuyts** [datahub-project/datahub#4852]
**Describe the bug**
In the Policies UI, clicking 'Deactivate' has no apparent effect. It's only when you refresh the page that you see the policy is deactivated, and the button is changed to 'Activate'

**To Reproduce**
1. Go to https://demo.datahubproject.io/policies
2. Click on `Deactivate` (any active policy)
3. Nothing happens
4. Refresh the page
5. The button text is changed to `Activate` and the policy's state is changed to `Inactive`

**Expected behavior**
I expect some feedback that the action succeeded, more precisely the State field should change to `Inactive` and the button to `Activate`

**Screenshots**
![Peek 2022-05-06 09-53](https://user-images.githubusercontent.com/3224432/167090755-7faa828e-b763-41a6-9a83-43f06a12fe10.gif)

**Desktop :**
 - OS: Ubuntu 20.04.4 LTS
 - Browser:  Chrome
 - Version 101.0.4951.54 (Official Build) (64-bit)

- Browser: Firefox
- Version 99.0 (64-bit)

**Additional context**
https://datahubspace.slack.com/archives/CV2UXSE9L/p1651820335622889

**Comment by maggiehays** [comment]
Hi @chriscollins3456 - please take a look at this one!

**Comment by xiphl** [comment]
Addressed in https://github.com/datahub-project/datahub/pull/5107?

**Comment by chriscollins3456** [comment]
^ yup this is definitely it. closing for now, but if I'm wrong we can re-open!
