### ISSUE TITLE
Can not log out when using OIDC

### ISSUE THREAD

**Issue by twuyts** [datahub-project/datahub#4854]
**Describe the bug**
I enabled OIDC authentication using Google. I can log in using my Google account. However, when I try to log out, I am immediately logged back in. There is no way of selecting a different account.

**To Reproduce**
1. Enable [Google Authentication](https://datahubproject.io/docs/how/auth/sso/configure-oidc-react-google/)
2. Log in
3. select `Logout` in the top right  dropdown menu
4. you are redirected to the homepage and still logged in

**Expected behavior**
I would expect a page stating that I was logged out successfully, preferably with a link allowing me to log back in. When logging back in, I should be able to select the previous account, or use a different one.

**Screenshots**
![logout](https://user-images.githubusercontent.com/3224432/167105519-4a111b9b-8e3a-42dc-aff8-f691b851e023.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser Firefox
 - Version 99.0 (64-bit)

**Additional context**
Same behaviour in other browsers.

**Comment by twuyts** [comment]
might be related to https://github.com/datahub-project/datahub/issues/2735 ?

**Comment by xiphl** [comment]
related to https://datahubspace.slack.com/archives/CV2UVAPPG/p1650916737226709.
i do get redirected to the keycloak login page in my case though.

**Comment by jjoyce0510** [comment]
This there, can you please send the link for your Oidc Discovery URL? I want to confirm that it contains the "end_session_endpoint" param, which we use to log folks out when logout is clicked.

**Comment by jjoyce0510** [comment]
I notice that there is a revoke token endpoint present in some cases, which is not being used. My thought it that fixing this will be a matter of supporting token revocation, but still doing some investigation

**Comment by sunli1223** [comment]
I have a workaround solution, just only edit the code(change the href url)
```html
<li class="ant-dropdown-menu-item ant-dropdown-menu-item-danger ant-dropdown-menu-item-only-child sc-pNWdM XJxhY" role="menuitem" tabindex="0" data-menu-id="rc-menu-uuid-97193-1-logout"><a href="/">Sign Out</a></li>
```
 to 
```html
<li class="ant-dropdown-menu-item ant-dropdown-menu-item-danger ant-dropdown-menu-item-only-child sc-pNWdM XJxhY" role="menuitem" tabindex="0" data-menu-id="rc-menu-uuid-97193-1-logout"><a href="/logOut">Sign Out</a></li>
```

**Comment by pdraguiar** [comment]
I tested the workaround suggested by @sunli1223 and the problem was solved.

**Comment by jjoyce0510** [comment]
Thank you! I will raise a PR with this change.

**Comment by jjoyce0510** [comment]
This will be included in the next release.

Thanks for your input in helping solve this folks!

John

**Comment by vmm-afonso** [comment]
Currently running latest version v.0.13.2 and I'm still having this problem. I'm hitting Sign Out and I get redirected back to the home page. Is anyone else still having this issue?

**Comment by feder89** [comment]
> Currently running latest version v.0.13.2 and I'm still having this problem. I'm hitting Sign Out and I get redirected back to the home page. Is anyone else still having this issue?

yes the same for me

**Comment by gtato** [comment]
Same here (`0.13.2`), i think this issue needs to be reopned.

**Comment by livelace** [comment]
i've thought this issue fixed long ago (was a big break between datahub usage).

**Comment by rafaelsmf** [comment]
Still an issue, tested on 0.14.1
