### ISSUE TITLE
Want to raise a new pr to make datahub support more commands when integrate datahub with spark jobs

### ISSUE THREAD

**Issue by maggie-zhu** [datahub-project/datahub#4877]
Since datahub only support the following commands when integrated with spark jobs:
InsertIntoHadoopFsRelationCommand
SaveIntoDataSourceCommand (jdbc)
CreateHiveTableAsSelectCommand
InsertIntoHiveTable

When I try to integrate my spark job with datahub, I found that many other commands are not supported when generating lineage in datahub like operating iceberg tables. So I add some code to support more commands like using iceberg, using cache() in spark sql and so on. I wonder if I can raise a pr to the project?

**Comment by maggiehays** [comment]
Hi @maggie-zhu! Please feel free to raise a PR. @MugdhaHardikar-GSLab should be able to help with any questions that come up
