### ISSUE TITLE
Mysql | Ingesting my host's database into the virtual machine datahub failed.

### ISSUE THREAD

**Issue by looperEit** [datahub-project/datahub#4894]
Injecting my host's database into the virtual machine datahub failed.
![image](https://user-images.githubusercontent.com/46367388/167763950-c7bff9f6-a672-4f95-8a21-84cbfca0f4ae.png)

recipe.yml：
![image](https://user-images.githubusercontent.com/46367388/167763899-fccd4eaf-c711-498c-94cf-d1cc63213394.png)

my datahub version
![image](https://user-images.githubusercontent.com/46367388/167764001-a240a282-120a-45b9-8f14-a8ec1b701734.png)

i have realised the datahub --version is not similar to the gms config datahub version.
![image](https://user-images.githubusercontent.com/46367388/167764141-32e26f8d-c1f6-4276-acbb-febf4b8396e6.png)

**Comment by xiphl** [comment]
to clarify, so 
1. you're running datahub on your local PC, 
2. and you're running the <datahub ingest -c recipe> command on the command line, 
3. and ingestion is supposed to be able read a MySQL DB that is installed on the PC?

**Comment by looperEit** [comment]
> 澄清，所以
> 
> 1. 您在本地PC上运行数据中心，
> 2. 并且您正在命令行上运行<datahub est -c recipe>命令，
> 3. 并且摄取应该能够读取安装在PC上的MySQL数据库？

yes,as you said.  my pc have a mysql, i want Ingest my pc's mysql data to my vm datahub.
is this a wrong thought?

**Comment by looperEit** [comment]
I already have some eyebrows:
1. If the client version and the gms version are different, if the import is performed, the metadata import will fail:
![image](https://user-images.githubusercontent.com/46367388/167792595-ecf5dc16-5f1f-44dd-a948-105384d6e4c4.png)

And the import of metadata will make the attribute not displayed:
![image](https://user-images.githubusercontent.com/46367388/167792098-c482638d-da52-4c57-bd26-14016c0997a4.png)

Just reinstalling the client to 0.8.24 fixed the issue:
Uninstall previous version: `python3 -m pip uninstall datahub acryl-datahub`
Install the required version: `python3 -m pip install acryl-datahub==0.8.24`

**Comment by xiphl** [comment]
in newer versions, there may be newer metadata objects being generated that GMS do not recognize (which is what happened here), hence you should always keep GMS and the python library version the same

**Comment by RyanHolstien** [comment]
@looperEit so this is working for you now that you are using the same version Python client and GMS? DataHub does not support cross versions between the CLI client and the server.

**Comment by looperEit** [comment]
> 

thanks for your replying, i think so.
