### ISSUE TITLE
WebUi  Error adding data source hive 

### ISSUE THREAD

**Issue by YTQ419** [datahub-project/datahub#4896]
'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in '
           '__connect\n'
           '    648  def __connect(self, first_connect_check=False):\n'
           ' (...)\n'
           '    652      # creator fails, this attribute stays None\n'
           '    653      self.connection = None\n'
           '    654      try:\n'
           '    655          self.starttime = time.time()\n'
           '--> 656          connection = pool._invoke_creator(self)\n'
           '    657          pool.logger.debug("Created new connection %r", connection)\n'
           '    ..................................................\n'
           '     self = <sqlalchemy.pool.base._ConnectionRecord object at 0x7fcc9dd78310>\n'
           '     first_connect_check = True\n'
           '     self.connection = None\n'
           '     self.starttime = 1652256727.4983974\n'
           "     pool._invoke_creator = <function 'DefaultEngineStrategy.create.<locals>.connect' strategies.py:106>\n"
           "     pool.logger.debug = <method 'Logger.debug' of <Logger sqlalchemy.pool.impl.QueuePool (WARNING)> __init__.py:1424>\n"
           '    ..................................................\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line '
           '114, in connect\n'
           '    106  def connect(connection_record=None):\n'
           ' (...)\n'
           '    110                  dialect, connection_record, cargs, cparams\n'
           '    111              )\n'
           '    112              if connection is not None:\n'
           '    113                  return connection\n'
           '--> 114      return dialect.connect(*cargs, **cparams)\n'
           '    ..................................................\n'
           '     connection_record = <sqlalchemy.pool.base._ConnectionRecord object at 0x7fcc9dd78310>\n'
           '     dialect = <pyhive.sqlalchemy_hive.HiveDialect object at 0x7fcc9dda66a0>\n'
           '     cargs = []\n'
           "     cparams = {'host': '192.168.99.106',\n"
           "                'port': 9831,\n"
           "                'username': 'biyao',\n"
           "                'password': 'biyao}',\n"
           "                'database': 'default',\n"
           "                'auth': 'LDAP'}\n"
           "     dialect.connect = <method 'DefaultDialect.connect' of <pyhive.sqlalchemy_hive.HiveDialect object at 0x7fcc9dda66a0> "
           'default.py:506>\n'
           '    ..................................................\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, '
           'in connect\n'
           '    506  def connect(self, *cargs, **cparams):\n'
           '    507      # inherits the docstring from interfaces.Dialect.connect\n'
           '--> 508      return self.dbapi.connect(*cargs, **cparams)\n'
           '    ..................................................\n'
           '     self = <pyhive.sqlalchemy_hive.HiveDialect object at 0x7fcc9dda66a0>\n'
           '     cargs = ()\n'
           "     cparams = {'host': '192.168.99.106',\n"
           "                'port': 9831,\n"
           "                'username': 'biyao',\n"
           "                'password': 'biyao}',\n"
           "                'database': 'default',\n"
           "                'auth': 'LDAP'}\n"
           "     self.dbapi.connect = <function 'connect' hive.py:120>\n"
           '    ..................................................\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/pyhive/hive.py", line 126, in connect\n'
           '    120  def connect(*args, **kwargs):\n'
           ' (...)\n'
           '    122      arguments.\n'
           '    123  \n'
           '    124      :returns: a :py:class:`Connection` object.\n'
           '    125      """\n'
           '--> 126      return Connection(*args, **kwargs)\n'
           '    ..................................................\n'
           '     args = ()\n'
           "     kwargs = {'host': '192.168.99.106',\n"
           "               'port': 9831,\n"
           "               'username': 'biyao',\n"
           "               'password': 'biyao}',\n"
           "               'database': 'default',\n"
           "               'auth': 'LDAP'}\n"
           "     Connection = <class 'pyhive.hive.Connection'>\n"
           '    ..................................................\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/pyhive/hive.py", line 267, in __init__\n'
           '    132  def __init__(\n'
           '    133      self,\n'
           '    134      host=None,\n'
           '    135      port=None,\n'
           '    136      scheme=None,\n'
           '    137      username=None,\n'
           "    138      database='default',\n"
           '    139      auth=None,\n'
           '    140      configuration=None,\n'
           '    141      kerberos_service_name=None,\n'
           '    142      password=None,\n'
           '    143      check_hostname=None,\n'
           '    144      ssl_cert=None,\n'
           "    145      http_path='/cliservice/',\n"
           '    146      thrift_transport=None\n'
           '    147  ):\n'
           ' (...)\n'
           '    263      # "V6 uses binary type for binary payload (was string) and uses columnar result set"\n'
           '    264      protocol_version = ttypes.TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V6\n'
           '    265  \n'
           '    266      try:\n'
           '--> 267          self._transport.open()\n'
           '    268          open_session_req = ttypes.TOpenSessionReq(\n'
           '    ..................................................\n'
           '     self = <pyhive.hive.Connection object at 0x7fcc9dd78130>\n'
           "     host = '192.168.99.106'\n"
           '     port = 9831\n'
           '     scheme = None\n'
           "     username = 'biyao'\n"
           "     database = 'default'\n"
           "     auth = 'LDAP'\n"
           '     configuration = {}\n'
           '     kerberos_service_name = None\n'
           "     password = 'biyao}'\n"
           '     check_hostname = None\n'
           '     ssl_cert = None\n'
           "     http_path = '/cliservice/'\n"
           '     thrift_transport = None\n'
           '     protocol_version = 5\n'
           '     ttypes.TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V6 = 5\n'
           "     self._transport.open = <method 'TSaslClientTransport.open' of <thrift_sasl.TSaslClientTransport object at 0x7fcc9dd73400> "
           '__init__.py:72>\n'
           "     ttypes.TOpenSessionReq = <class 'TCLIService.ttypes.TOpenSessionReq'>\n"
           '    ..................................................\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/thrift_sasl/__init__.py", line 95, in '
           'open\n'
           '    72   def open(self):\n'
           ' (...)\n'
           '    91     # SASL negotiation loop\n'
           '    92     while True:\n'
           '    93       status, payload = self._recv_sasl_message()\n'
           '    94       if status not in (self.OK, self.COMPLETE):\n'
           '--> 95         raise TTransportException(type=TTransportException.NOT_OPEN,\n'
           '    96           message=("Bad status: %d (%s)" % (status, payload)))\n'
           '    ..................................................\n'
           '     self = <thrift_sasl.TSaslClientTransport object at 0x7fcc9dd73400>\n'
           '     status = 3\n'
           "     payload = b'Error validating the login'\n"
           "     self._recv_sasl_message = <method 'TSaslClientTransport._recv_sasl_message' of <thrift_sasl.TSaslClientTransport object at "
           '0x7fcc9dd73400> __init_\n'
           '                                _.py:111>\n'
           '     self.OK = 2\n'
           '     self.COMPLETE = 5\n'
           "     TTransportException = <class 'thrift.transport.TTransport.TTransportException'>\n"
           '     TTransportException.NOT_OPEN = 1\n'
           '    ..................................................\n'
           '\n'
           '---- (full traceback above) ----\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/entrypoints.py", line 149, in '
           'main\n'
           '    sys.exit(datahub(standalone_mode=False, **kwargs))\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/core.py", line 1130, in __call__\n'
           '    return self.main(*args, **kwargs)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/core.py", line 1055, in main\n'
           '    rv = self.invoke(ctx)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/core.py", line 1404, in invoke\n'
           '    return ctx.invoke(self.callback, **ctx.params)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/core.py", line 760, in invoke\n'
           '    return __callback(*args, **kwargs)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/click/decorators.py", line 26, in '
           'new_func\n'
           '    return f(get_current_context(), *args, **kwargs)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line '
           '317, in wrapper\n'
           '    raise e\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line '
           '269, in wrapper\n'
           '    res = func(*args, **kwargs)\n'
           'File '
           '"/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/utilities/memory_leak_detector.py", '
           'line 102, in wrapper\n'
           '    res = func(*args, **kwargs)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 128, in '
           'run\n'
           '    raise e\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 114, in '
           'run\n'
           '    pipeline.run()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line '
           '214, in run\n'
           '    for wu in itertools.islice(\n'
           'File '
           '"/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/ingestion/source/sql/sql_common.py", '
           'line 705, in get_workunits\n'
           '    for inspector in self.get_inspectors():\n'
           'File '
           '"/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/ingestion/source/sql/sql_common.py", '
           'line 509, in get_inspectors\n'
           '    with engine.connect() as conn:\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2263, '
           'in connect\n'
           '    return self._connection_cls(self, **kwargs)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 104, in '
           '__init__\n'
           '    else engine.raw_connection()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2369, '
           'in raw_connection\n'
           '    return self._wrap_pool_connect(\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, '
           'in _wrap_pool_connect\n'
           '    return fn()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 304, in '
           'unique_connection\n'
           '    return _ConnectionFairy._checkout(self)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in '
           '_checkout\n'
           '    fairy = _ConnectionRecord.checkout(pool)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in '
           'checkout\n'
           '    rec = pool._do_get()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 140, in '
           '_do_get\n'
           '    self._dec_overflow()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line '
           '68, in __exit__\n'
           '    compat.raise_(\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in '
           'raise_\n'
           '    raise exception\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 137, in '
           '_do_get\n'
           '    return self._create_connection()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in '
           '_create_connection\n'
           '    return _ConnectionRecord(self)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in '
           '__init__\n'
           '    self.__connect(first_connect_check=True)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in '
           '__connect\n'
           '    pool.logger.debug("Error on connect(): %s", e)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line '
           '68, in __exit__\n'
           '    compat.raise_(\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in '
           'raise_\n'
           '    raise exception\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in '
           '__connect\n'
           '    connection = pool._invoke_creator(self)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line '
           '114, in connect\n'
           '    return dialect.connect(*cargs, **cparams)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, '
           'in connect\n'
           '    return self.dbapi.connect(*cargs, **cparams)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/pyhive/hive.py", line 126, in connect\n'
           '    return Connection(*args, **kwargs)\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/pyhive/hive.py", line 267, in __init__\n'
           '    self._transport.open()\n'
           'File "/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/thrift_sasl/__init__.py", line 95, in '
           'open\n'
           '    raise TTransportException(type=TTransportException.NOT_OPEN,\n'
           '\n'
           "TTransportException: Bad status: 3 (b'Error validating the login')\n"
           '[2022-05-11 08:12:08,295] INFO     {datahub.entrypoints:176} - DataHub CLI version: 0.8.34.1 at '
           '/tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/lib/python3.9/site-packages/datahub/__init__.py\n'
           '[2022-05-11 08:12:08,295] INFO     {datahub.entrypoints:179} - Python version: 3.9.9 (main, Dec 21 2021, 10:03:34) \n'
           '[GCC 10.2.1 20210110] at /tmp/datahub/ingest/venv-1652100c-2a46-4666-8519-3ecd2b12cba1/bin/python3 on '
           'Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.31\n'
           "[2022-05-11 08:12:08,295] INFO     {datahub.entrypoints:182} - GMS config {'models': {}, 'versions': {'linkedin/datahub': {'version': "
           "'v0.8.34', 'commit': '5c64e9d5419afc85343307a7cfdc51b90c6f5e68'}}, 'managedIngestion': {'defaultCliVersion': '0.8.34.1', 'enabled': "
           "True}, 'statefulIngestionCapable': True, 'supportsImpactAnalysis': True, 'telemetry': {'enabledCli': True, 'enabledIngestion': False}, "
           "'datasetUrnNameCasing': False, 'retention': 'true', 'noCode': 'true'}\n",
           "2022-05-11 08:12:09.294404 [exec_id=1652100c-2a46-4666-8519-3ecd2b12cba1] INFO: Failed to execute 'datahub ingest'",
           '2022-05-11 08:12:09.294758 [exec_id=1652100c-2a46-4666-8519-3ecd2b12cba1] INFO: Caught exception EXECUTING '
           'task_id=1652100c-2a46-4666-8519-3ecd2b12cba1, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/default_executor.py", line 119, in execute_task\n'
           '    self.event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete\n'
           '    return f.result()\n'
           '  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result\n'
           '    raise self._exception\n'
           '  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step\n'
           '    result = coro.send(None)\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 115, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"]}
Execution finished with errors.

**Comment by YTQ419** [comment]
python -m datahub ingest -c hive_to_datahub_rest.yml  no problem

**Comment by RyanHolstien** [comment]
It looks like a connection error is happening, what is the difference between the recipe you ran that failed and your other recipe? Are you able to share the recipe files you are using? Also be sure to mask any sensitive information in stack traces/shared files 😄

**Comment by YTQ419** [comment]
> It looks like a connection error is happening, what is the difference between the recipe you ran that failed and your other recipe? Are you able to share the recipe files you are using? Also be sure to mask any sensitive information in stack traces/shared files 😄

I've solved it. Thank you

**Comment by wtspring** [comment]
可以问一下如何解决的吗？我现在用ui界面创建也报错

**Comment by YTQ419** [comment]
这个是解决办法已经在github上写过了你可以查看一下，地址:https://github.com/datahub-project/datahub/issues/4955



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 20, 2022 15:56 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [datahub-project/datahub] WebUi  Error adding data source hive  (Issue #4896)




 
可以问一下如何解决的吗？我现在用ui界面创建也报错
