### ISSUE TITLE
UI not keeping field order as defined in custom aspects

### ISSUE THREAD

**Issue by fprima** [datahub-project/datahub#4907]
**Describe the bug**
When extending the metadata model following the steps in https://github.com/datahub-project/datahub/blob/master/metadata-models-custom/README.md, the field order is not as entered in the pdl file.  

**To Reproduce**
1. Follow the steps to extend the metadata model as described in https://github.com/datahub-project/datahub/blob/master/metadata-models-custom/README.md

**Expected behavior**
In the UI I expect the fields to keep the order as defined in the array.

**Screenshots**

PDL:
![Screen Shot 2022-05-12 at 14 04 26](https://user-images.githubusercontent.com/52747129/168140139-4ec05cd0-d139-47d2-8c26-b45f3fb978d0.png)

UI:
<img width="1050" alt="Screen Shot 2022-05-12 at 14 05 06" src="https://user-images.githubusercontent.com/52747129/168140175-32fbdc2b-0660-45e3-87f4-83ceb8034254.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterrey
 - Browser Safari
 - Version 15.4

**Comment by jjoyce0510** [comment]
This does seem a bit counterintuitive. In this case, I can see why it might be a problem. We need the field index to be provided with the response with custom aspects from our server -- this is work to be scheduled
