### ISSUE TITLE
When could I get the review opinions of my pr https://github.com/datahub-project/datahub/pull/4882

### ISSUE THREAD

**Issue by maggie-zhu** [datahub-project/datahub#4920]
I found that my pr was assigned to [MugdhaHardikar-GSLab](https://github.com/MugdhaHardikar-GSLab). So when could I get the response and how could I contact with the reviewer of my pr?

**Comment by maggiehays** [comment]
Hi @maggie-zhu! You're always welcome to add comments & tag folks in your PRs, but GitHub notifications can get a bit tough to follow. The [DataHub Slack channel](https://slack.datahubproject.io/) is a great way to get immediate Q&A support.

Looks like your PR has been merged in; I'll close out this issue in the meantime!
