### ISSUE TITLE
Configure Hive/mysql Recipe    unable to load

### ISSUE THREAD

**Issue by quanhuanhuan** [datahub-project/datahub#4955]
![image](https://user-images.githubusercontent.com/30468100/169255757-c5cad207-9a9b-419e-843e-fc2d68c599b8.png)

**Comment by maggiehays** [comment]
Hi @quanhuanhuan, we aren't able to produce this on our end without more details about your deployment/version. I'll close this out for now, but please feel free to reopen with more details.

**Comment by quanhuanhuan** [comment]
deployment command ： datahub docker quicestart  

I can only see these error messages
![image](https://user-images.githubusercontent.com/30468100/169429611-a07eab90-0f51-4946-a41c-e44045eaccc3.png)

docker info:
![9d19e0faa8b14dd974dceb3bdce19af](https://user-images.githubusercontent.com/30468100/169430082-3e380a6b-7ded-4fc0-a0f7-20954df18b62.jpg)

**Comment by 852096932** [comment]
> Hi @quanhuanhuan, 修改源码文件datahub-web-react/node_modules/@monaco-editor/loader/lib/es/config/index.js，将第三行的’https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs’修改为“https://unpkg.com/monaco-editor@0.28.1/min/vs/loader.js”，重新编译datahub-web-react前端模块
