### ISSUE TITLE
RestEmitter in java datahub client does not provide option for action?ingest

### ISSUE THREAD

**Issue by mithunsinghtocode** [datahub-project/datahub#4959]
When creating a dataset lineage using MetadataChangeProposalWrapper and entity type as "dataset", the action supported is only "ingestProposal" and "ingest" is not supported which is provided in rest_emitter.py. Also support for MetadataChangeEvent is not present in the java client

**Comment by maggiehays** [comment]
Hi @mithunsinghtocode! I'm not sure I understand your use case - can you explain a bit more what functionality you're looking for within the Java DataHub client?

**Comment by mohdsiddique** [comment]
Hi @mithunsinghtocode 
Is this still an issue? If not , will close it after some days of inactivity

**Comment by hsheth2** [comment]
The `MetadataChangeEvent` is actually deprecated in favor of `MetadataChangeProposal` - everything that you can do MCEs can also be done with MCPs and the ingestProposal endpoint. Given that we're pushing to remove MCEs, we won't add this functionality to the java client.
