### ISSUE TITLE
[Develop]: Can not find reference datahub.metadata in idea IDE

### ISSUE THREAD

**Issue by ddsr-ops** [datahub-project/datahub#5009]
I follow the steps described in the url `https://datahubproject.io/docs/developers`. 
When I open `datahub.ipr`  in idea IDE, `datahub.metadata` reference can not be found.
![image](https://user-images.githubusercontent.com/63837681/170446476-bcb04663-779c-403e-ad91-692c8178045d.png)

Thank you for your friendly help.

**Comment by treff7es** [comment]
These are generated classes. 
Did you run this `./scripts/codegen.sh`?
https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/developing.md#sanity-check-code-before-committing

**Comment by mohdsiddique** [comment]
Hi @ddsr-ops 
Is this still an issue? If not, will close it after a few days of inactivity
