### ISSUE TITLE
The ingested LDAP user cannot log in the UI, but can be displayed in the user list

### ISSUE THREAD

**Issue by xingzhoutan** [datahub-project/datahub#5059]
The ingested LDAP user cannot log in the UI, but can be displayed in the user list

**Comment by xingzhoutan** [comment]
I have no configured. I would like to ask how to configure it？Can you provide documentation please?

**Comment by xingzhoutan** [comment]
> 从 LDAP 摄取的用户并不自动意味着用户可以登录到 datahub -> 您是否已将前端配置为使用 ldap 进行身份验证？



> I have no configured. I would like to ask how to configure it？Can you provide documentation please?


I have no configured. I would like to ask how to configure it？Can you provide documentation please?

**Comment by xingzhoutan** [comment]
> ingested users from LDAP does not automatically mean the user can login to datahub -> have you configured frontend to authenticate using ldap?


I have no configured. I would like to ask how to configure it？Can you provide documentation please?

**Comment by xiphl** [comment]
There is a rare sample of how jaas.conf is configured for ldap here:
https://datahubspace.slack.com/archives/C029A3M079U/p1654023422543579?thread_ts=1653479830.793139&cid=C029A3M079U
Then you need to mount the jaas.conf in the frontend react container. https://datahubproject.io/docs/how/auth/jaas
