### ISSUE TITLE
Is it possible to modify schemetadata and properties in Dataset?

### ISSUE THREAD

**Issue by Cascol-Chen** [datahub-project/datahub#5062]
I have found out how to modify editableSchemadata and editableProperties for Dataset via graphql. However, they don't provide the aspect of "value" and can be hardly useful. Therefore, I wish to know if it is possible to modify schemetadata and properties in Dataset.

**Comment by maggiehays** [comment]
Hi @Cascol-SCUT! This isn't currently supported but it's a great suggestion. Would you mind opening a [feature request](https://feature-requests.datahubproject.io/) so we can gauge community interest & level of impact? I'll close this issue out in the meantime!
