### ISSUE TITLE
mysql-setup is broken in the quickstart command

### ISSUE THREAD

**Issue by Lgueg28** [datahub-project/datahub#5068]
**Describe the bug**
When trying to run the datahub docker quickstart command there is an error with the mysql-setup command

**To Reproduce**
https://datahubproject.io/docs/quickstart/

**Expected behavior**
The init.sh script should run and properly create the tables needed for the metadata store

**Screenshots**
![Screen Shot 2022-06-01 at 3 41 40 PM](https://user-images.githubusercontent.com/11949632/171506743-a4241e6c-6906-4dd8-80bd-f6b6f4ac8761.png)

![Screen Shot 2022-06-01 at 3 42 37 PM](https://user-images.githubusercontent.com/11949632/171506869-ca1eb516-90ed-452d-81ed-1162b422b9e2.png)

![Screen Shot 2022-06-01 at 3 43 26 PM](https://user-images.githubusercontent.com/11949632/171506967-9b494305-3630-46ad-bb7e-d9b40faaa986.png)

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
Just started happening around noon, which is when the smoke test started breaking as well

**Comment by jjoyce0510** [comment]
Thank you for reporting! We are taking a look.
