### ISSUE TITLE
mypy failed during building ingestion task

### ISSUE THREAD

**Issue by hawkwang** [datahub-project/datahub#5069]
just run "gradlew build" and get following errors:
-----------------------------------------------------------------------
mypy src/ tests/ examples/
src/datahub/emitter/rest_emitter.py:33: error: On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"; use "{!r}" if this is desired behavior src/datahub/emitter/mce_builder.py:43: error: Incompatible types in assignment (expression has type "Literal[0, 1]", variable has type "bool")
src/datahub/ingestion/source/looker.py:859: error: Argument 2 to "submit" of "Executor" has incompatible type "Optional[str]"; expected "str"
Found 3 errors in 3 files (checked 430 source files)

> Task :metadata-ingestion:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':metadata-ingestion:lint'.
> Process 'command 'bash'' finished with non-zero exit value 1

--------------------------------------------------------

BTW, my machine os is CentOS 7, and python version is 3.7.0, the mypy should be installed by the building procedure, and I found the version is 0.690.

**Comment by xiphl** [comment]
i think your code version is behind the master branch, so as python libraries update, it will use the newer versions of the libraries and introduce new linting errors. Check the repo for the changes necessary to resolve, especially setup.py, as the developers will lock the versions to install.

**Comment by maggiehays** [comment]
Thanks for jumping in here, @xiphl!! 

@hawkwang keep us posted on outcomes - we're here to help!

**Comment by maggiehays** [comment]
Hi @hawkwang! Going to close this out for now, but please feel free to re-open if the issue persists
