### ISSUE TITLE
Glossary Sort in UI

### ISSUE THREAD

**Issue by fprima** [datahub-project/datahub#5078]
**Describe the bug**
Not sure if this is a bug or enhancement. 
When I load using the rest API terms they will not display in the order provided in the yaml file in the UI once I include 1000+ terms. Smaller numbers will be sorted as input. 

**To Reproduce**
1. Ingest a yaml file with less than 200 terms
2. In the UI they will show as listed in the yaml file
3. Ingest a yaml file with more than 1000 terms
4. In the UI will not list as listed in the yaml file

**Expected behavior**
List in the UI in the order provided in the yaml file or have the UI list them in alphabetical order 

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Safari
 - Version 15.4

**Comment by maggiehays** [comment]
Hey @chriscollins3456! Can you take a look at this one?

**Comment by fprima** [comment]
Closing and adding enhancement: https://feature-requests.datahubproject.io/p/glossary-sort-in-ui
