### ISSUE TITLE
Unable to ingest data from Hive with Kerberos authentication

### ISSUE THREAD

**Issue by Shib12** [datahub-project/datahub#5131]
Hi,

I am trying ingest Hive data to datahub. In my case Hive is running in Linux VM with Kerberos authentication enable.
My recipe file for Hive ingestion is as followed:
-------------------------------------------------------------
source:
    type: hive
    config:
        host_port: 'xxxxx:10000'
        database: 'datahub'
        username: 'test'
        scheme: 'hive+http'
        options:
            connect_args:
                auth: KERBEROS
                kerberos_service_name: hive
sink:
    type: datahub-rest
    config:
        server: 'http://x.x.x.x:8080'
-------------------------------------------------------------

While running from I am getting the below error:

File "/root/datahub/datahub-venv/lib/python3.6/site-packages/pyhive/hive.py", line 313, in _set_kerberos_header
    kerberos.authGSSClientStep(krb_context, "")

GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))**

Can you please look into this error and let me know the steps for successful Hive ingestion.

Thanks in advance.

Regards,
Shib

**Comment by Shib12** [comment]
Hi All,

With the continuation on my previous issue reported. Now I have added my KDC server details in my client server hosts file. After that I am getting a new error while creating **TCookieHttpClient** object in hive.py file.

I am getting a "**ConnectionResetError: [Errno 104] Connection reset by peer**" error from 
 **File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)**
file.

Can anyone please look into the issue and let me know if any resolution we can try.
Thanks in advance.

Regrads,
Shib

**Comment by cassiemudan** [comment]
I met the same issue today in v0.10.4, and finally I got it through by removing "scheme" or setting "sheme" to "hive".  The official guide is misleading us to set it to "hive+http".
