### ISSUE TITLE
How to generate a personal access token？

### ISSUE THREAD

**Issue by xingzhoutan** [datahub-project/datahub#5133]
**Describe the bug**
How to generate a personal access token？

**Comment by jjoyce0510** [comment]
Have you checked out this doc? https://datahubproject.io/docs/introducing-metadata-service-authentication/#personal-access-tokens 

You need to first enable metadata service authentication using the following environment variable in `datahub-gms` and `datahub-frontend` pods:

```
METADATA_SERVICE_AUTH_ENABLED=true
```

Note that users must also have the Platform Privilege 'Generate Personal Access Tokens' to generate them!

John
