### ISSUE TITLE
Profiling fails for MySQL against databases using v8 or less

### ISSUE THREAD

**Issue by hugh-nguyen** [datahub-project/datahub#5144]
**Describe the bug**
Profiling for MySQL fails when external database uses version less than 8.0

We are specifically running 5.7, but we can see that there is a syntax error occurring due the use of WITH statements which were introduced in v8.

Below is some of the logging. Notice how profiling is involved.
`
(Background on this error at: http://sqlalche.me/e/13/f405)\n'
           '[2022-06-07 02:52:26,434] INFO     {datahub.ingestion.source.ge_data_profiler:835} - Finished profiling '
           'socialgoo.client_subscription_cycle; took 0.410 seconds\n'
           '[2022-06-07 02:52:26,595] INFO     {datahub.ingestion.source.ge_data_profiler:817} - Profiling socialgoo.client_subscription_invoice\n'
           '[2022-06-07 02:52:26,631] ERROR    {datahub.utilities.sqlalchemy_query_combiner:388} - Failed to execute queue using combiner: '
           '(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server '
           "version for the right syntax to use near 'pklpswaykbrjduuv AS \\n(SELECT count(*) AS count_1 \\nFROM socialgoo.client_subscrip' at line "
           '1")\n'
           '[SQL: WITH pklpswaykbrjduuv AS \n'
           '(SELECT count(*) AS count_1 \n'
           'FROM socialgoo.client_subscription_invoice)\n'
           ' SELECT pklpswaykbrjduuv.count_1 \n'
           'FROM pklpswaykbrjduuv]\n'
           '(Background on this error at: http://sqlalche.me/e/13/f405)\n'
`

**Additional context**
I was asked to raise this issue by @anshbansal and @dexter-mh-lee

**Comment by khoramism** [comment]
Same Problem, Can we reopen this?
