### ISSUE TITLE
LADP authentication BUG

### ISSUE THREAD

**Issue by jyRMc** [datahub-project/datahub#5146]
**Describe the bug**
When using an LDAP source with JAAS, Any non-user of LADP can log in. Which means that I can log in with any input if I want.

My JASS configuration is AS follow:
```
WHZ-Authentication {
    com.sun.security.auth.module.LdapLoginModule required
    userProvider="ldap://192.168.26.136:636"
    authIdentity="uid={USERNAME},ou=datahub-unit,dc=uniplore,dc=cn"
    java.naming.security.authentication="simple"
    debug="true"
  };
```

**Comment by pedro93** [comment]
Hello jyRMc,

How are non LDAP users logging in?
Do you have the environment variable `AUTH_JAAS_ENABLED` set to true in datahub-frontend?
