### ISSUE TITLE
Delete Glossary Term Group Raise 500 Error on UI

### ISSUE THREAD

**Issue by smartnewsdingli** [datahub-project/datahub#5147]
**Describe the bug**
Delete Glossary Term Group Raise 500 Error on UI

**To Reproduce**
1. Go to Glossary Term, create a new term group
2. Click Create
3. Delete this term group

**Expected behavior**
Can be delete and there is no error

**Actual behavior**
This is deleted, go to main page, raise 500 error.

On backend log:
Failed to load Entities of type: GlossaryNode, keys: [urn:li:glossaryNode:f28d4871-7ed0-47e2-b01e-392dd278cf77]
This is still exist in ES.

**Comment by chriscollins3456** [comment]
Hi @smartnewsdingli! I'm having some trouble reproducing this myself, so I'm going to ask for some more details.

Were you on the home glossary page when you created this term group, or within another term group?

What version of datahub are you running?

Do you have any issues deleting Glossary Terms? (not the term group)

Were there other Terms or Term Groups in your Glossary?

You're deleting through the UI and not CLI right?

**Comment by smartnewsdingli** [comment]
hi @chriscollins3456 
I created term group from UI, and within another term group. I delete from UI as well.
Delete terms is OK.
I deploy with code, and version is on day June 1 (not sure which commit id).
Yes, we do have other terms and term groups, for over 200+. 

I try to delete term group again and this issue still there.

Please let me know if you need more information.

**Comment by chriscollins3456** [comment]
@smartnewsdingli thanks for the info! 

You're seeing this error in the UI, right? could you post a screenshot of it? and if you have access to backend logs I would love to see a full stack trace.

I'm trying to reproduce this locally and on the demo site and having a tough time myself. Are you able to reproduce it on the demo site? https://demo.datahubproject.io/glossary just trying to see if this is specific to your setup/situation and not a bigger issue (obviously want to help resolve no matter what, though)

**Comment by chriscollins3456** [comment]
@smartnewsdingli just wanted to check in to see if this is still an issue for you or not

**Comment by jjoyce0510** [comment]
I think this is some sort of dangling pointer issue, which _should_ be resolved as of the latest release (v0.8.40). @smartnewsdingli Please let us know if this is the case or not. 

Thanks
John
