### ISSUE TITLE
glue statistics not showing up in stats tab

### ISSUE THREAD

**Issue by Seojiwoong** [datahub-project/datahub#5156]
**Describe the bug**
glue statistics not showing up in stats tab

**To Reproduce**
1. add statistics to my glue table through update-column-statistics-for-table ( https://docs.aws.amazon.com/cli/latest/reference/glue/update-column-statistics-for-table.html)
2. checked statistics through get-column-statistics-for-table (https://docs.aws.amazon.com/cli/latest/reference/glue/get-column-statistics-for-table.html)
3. Ingest glue table (add profile to config)
4. nothing showing up in stats tab

**Expected behavior**
Statistical data must be exposed

**Screenshots**
1. screenshot of stats tab
<img width="888" alt="스크린샷 2022-06-13 오후 7 14 03" src="https://user-images.githubusercontent.com/6044471/173475456-b5cc87a5-54b6-456c-9a25-5ed109a6028f.png">

2. screenshot of the get-column-statistics-for-table(aws cli) result
<img width="468" alt="스크린샷 2022-06-13 오후 7 22 14" src="https://user-images.githubusercontent.com/6044471/173475461-fed80c1f-b184-4d94-a44b-4d16925f3762.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: 0.8.36

**Additional context**
In datahub code, read statistics through get_table(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_table) and get_partitions(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_partition)
When I called the get_table api via boto3, there were no Parameters  field in the Table field, and get_partitions too

Why didn't use get_column_statistics_for_partition(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_column_statistics_for_partition) and get_column_statistics_for_table(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_column_statistics_for_table)?
Is what I checked wrong? let me know if there is a right way

**Comment by Seojiwoong** [comment]
I found that it should be used through update-table(https://docs.aws.amazon.com/cli/latest/reference/glue/update-table.html), not update-column-statistics-for-table ( https://docs.aws.amazon.com/cli/latest/reference/glue/update-column-statistics-for-table.html)

**Comment by keerthiis** [comment]
@Seojiwoong - Can you share details of what needs to be updated on the Glue table ? Are you on the Datahub Slack channel ?
