### ISSUE TITLE
"Generate new token" cannot be clicked

### ISSUE THREAD

**Issue by chengpeng2015** [datahub-project/datahub#5159]
**Describe the bug**
"Generate new token" cannot be clicked

**To Reproduce**
1. Add policy by document
https://datahubproject.io/docs/introducing-metadata-service-authentication/#personal-access-tokens
![image](https://user-images.githubusercontent.com/13881307/173551385-ac40e6c5-d4a7-46bc-a91c-991e7c7dc112.png)
![image](https://user-images.githubusercontent.com/13881307/173551486-a5f7428c-141d-485d-9f18-b502edefd8ab.png)

2. to 'Settings' > 'Access Tokens' > 'Generate Personal Access Token' to generate a token.
![image](https://user-images.githubusercontent.com/13881307/173551738-19a9c1d4-833f-4333-8ce0-f4bef3dccf2b.png)

**Expected behavior**
"Generate new token" Can click

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/13881307/173552442-58a7a272-576b-4012-94f5-b12b9160f986.png)

 - Browser 
![image](https://user-images.githubusercontent.com/13881307/173552562-e19f1293-e660-4b51-9b31-173bdc85aa64.png)

 - Version 
![image](https://user-images.githubusercontent.com/13881307/173552229-ed697109-43b5-423f-b2ec-e2e40391c198.png)

**Additional context**

**Comment by maggiehays** [comment]
Hi @pedro93! Can you take a look at this as part of your work to improve docs around policies/permissions?

**Comment by pedro93** [comment]
Hello @chengpeng2015 

Did you enable [Metadata Service Authentication​](https://datahubproject.io/#configuring-metadata-service-authentication)? 

Access tokens are only used when GMS (also known as the Metadata Service) has been configured with authenticated access only. Without authenticated access, anyone can access GMS making access token irrelevant.

**Comment by chengpeng2015** [comment]
Hello @pedro93 

Thank you for your reply!

 I'm a newbie of datahub , The system I deployed with datahub docker QuickStart has not been changed. How can I enable metadata service authentication?

In addition, I believe that the token can be configured even if metadata service authentication is not enabled, because it is only an administrative function. Maybe one day I will turn on metadata service authentication

**Comment by pedro93** [comment]
Hello @chengpeng2015 

Did the suggested approach work? Can I close this issue?

**Comment by pedro93** [comment]
Closing due to lack of answer. Assuming situation resolved.

**Comment by Mri16** [comment]
@chengpeng2015 Is your issue resolved related to Token based authentication is currently disabled. Contact your DataHub administrator to enable this feature.
