### ISSUE TITLE
Case Sensitive SQL Server databases fail ingestion

### ISSUE THREAD

**Issue by BALyons** [datahub-project/datahub#5181]
https://github.com/datahub-project/datahub/blob/b4bf1d4b1d22d8c808e992f62a1899227e303308/metadata-ingestion/src/datahub/ingestion/source/sql/mssql.py#L115

When attempting to use a SQL Server database that is case sensitive as a source, the ingestion fails due to the 'SYS.TABLES' object not existing.

**Comment by chriscollins3456** [comment]
PR has been merged!
