### ISSUE TITLE
Unable to see the ingestion data

### ISSUE THREAD

**Issue by MarkKobs** [datahub-project/datahub#5183]
i ingested mysql data successfully, but the front-page tells me that i have no metadata yet.
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/20516349/173997614-67147784-7df8-4bd1-8baf-5e3c3a95d720.png">

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/20516349/173997644-115e6019-a6a1-48cd-8d07-c7575de2c223.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/20516349/173997658-96c79132-218b-4210-8d1c-5b5694f7dd70.png">

**Comment by chriscollins3456** [comment]
Hey @MarkKobs! Do you see the data you would expect from ingestion in your database? wondering if this is an ingestion issue or a frontend issue.

Also if you aren't seeing data in your database it must have failed and I'm wondering why we would show a success. one more thing - if you run the ingestion again, are you able to see what is being ingested? you could look in your network tab if you're using UI-based ingestion (or the logs in GMS). just want to make sure we're not getting a success with zero data coming back. If that's the case there's probably something going on in your recipe

**Comment by jjoyce0510** [comment]
Hi @MarkKobs - We see the ticket has been inactive for 25 days. We are going to close the ticket. Please reopen or reach out on Slack with further questions.
