### ISSUE TITLE
java.lang.ClassNotFoundException: datahub.spark2.shaded.http.conn.DnsResolver

### ISSUE THREAD

**Issue by maggie-zhu** [datahub-project/datahub#5192]
I want to analyze some spark sql commands in spark 3. And I upgrade the spark dependency in build.gradle like following:
'sparkSql' : 'org.apache.spark:spark-sql_2.12:3.2.1',
'sparkHive' : 'org.apache.spark:spark-hive_2.12:3.2.1'

But when I integrate the jar file with my project, I got the error like:
![image](https://user-images.githubusercontent.com/38024655/174213771-cbac9c2a-c2d8-4855-b104-63920e308f31.png)

How could I fix this  bug?

**Comment by gp1105739** [comment]
I meet the same issue. The class is not in the jar file
