### ISSUE TITLE
Unable to ingest data from Databricks/Hive

### ISSUE THREAD

**Issue by sachinwadhwa** [datahub-project/datahub#5194]
**Describe the bug**
Unable to ingest data from Databricks using pyhive method specified at https://datahubproject.io/docs/generated/ingestion/sources/hive/

It works fine using python on desktop but UI and docker images both missing  databricks-dbapi[hive,sqlalchemy] and acryl-datahub[hive] libraries.

**To Reproduce**
as above

**Expected behavior**
Include the python libraries  databricks-dbapi[hive,sqlalchemy] to ingestion and acryl-datahub-actions docker containers.

**Comment by maggiehays** [comment]
Hi @anshbansal! Please take a look at this one - let's add in all known ingestion-related dependencies to managed ingestion so we can avoid these types of errors going forward.

**Comment by sachinwadhwa** [comment]
This issue is still not fixed. Its linked to incorrect fix.

We still get following error while ingesting hive data using UI method (0.8.39):

 "NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:databricks.pyhive\n"
