### ISSUE TITLE
[Question] Unable to find "acryl-datahub-actions" docker image source code

### ISSUE THREAD

**Issue by kilnamkim** [datahub-project/datahub#5202]
**Question**
I want to find [acryldata/acryl-datahub-actions](https://hub.docker.com/r/acryldata/acryl-datahub-actions)  source code.
Where is source code?

 - https://github.com/datahub-project/datahub/blob/master/docker/docker-compose.yml#L126

**Comment by shirshanka** [comment]
It is here: https://github.com/acryldata/datahub-actions
We'll update the docs to make sure this is clear.
