### ISSUE TITLE
BigQuery profiling ingests great-expectations temp views

### ISSUE THREAD

**Issue by maaaikoool** [datahub-project/datahub#5210]
**Describe the bug**
Running the bigquery ingestion with profiling enabled results in the ingestion of thousands of temp views used internally by great-expectations e.g. `ge-temp-{uuid}`

**Comment by aditya-radhakrishnan** [comment]
Hi @maaaikoool can you share what your recipe looks like, and which version of the CLI you're on?

cc @treff7es

**Comment by maaaikoool** [comment]
Seems like the problem is that the views are not deleted:
* I cleaned up everything (both from bigquery and datahub) 
* Modified the ingestion to add the  `bigquery_temp_table_schema` option to a temp dataset.
* After the ingestion ended successfully I found again lots of newly created `ge-temp-xxx` views in the temp dataset

**Comment by treff7es** [comment]
Hmm, I need to check what is happening as it should clean up the temp tables

**Comment by maaaikoool** [comment]
Are we missing the `bigquery.tables.delete` permission from the listed [here](https://datahubproject.io/docs/generated/ingestion/sources/bigquery/#create-a-datahub-profile-in-gcp)?

If I mount a service account with the permissions listed there and try to replicate the query we do [here](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py#L835) it fails:
```
bq --project_id foo query --use_legacy_sql=false 'drop view if exists `foo`.temp.test_david'
BigQuery error in query operation: Error processing job 'foo:bqjob_r722c146ddac2c343_00000181ab43fa6b_1': Access Denied: Table foo:temp.test_david: Permission
bigquery.tables.delete denied on table foo:temp.test_david (or it may not exist).
```

**Comment by maaaikoool** [comment]
Hey @treff7es did you have a chance to review if we should have `bigquery.tables.delete`? Many thanks

**Comment by treff7es** [comment]
I think you need to grant delete access on those schemas where bigquery source creates temporary tables.
If you specify a schema dedicated (`bigquery_temp_table_schema` property in profiling) to these temporary tables, then it is enough if you grant delete permission only to that schema.

**Comment by mohdsiddique** [comment]
Hi @maaaikoool 
Is this still an issue? if not, will close it after a few days of inactivity.

**Comment by maaaikoool** [comment]
Hi!

Sorry but I've been AFK for a while 😅 I've added the permission to the list in https://github.com/datahub-project/datahub/pull/5826
