### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by johnfelipe** [datahub-project/datahub#5215]
i want contribute 
once you extract english strings, pot method or json method, i will translate to es. fr and it
pls ping me when is ready

**Comment by maggiehays** [comment]
Hey @gabe-lyons & @chriscollins3456 - what are our options for addressing this incrementally?

**Comment by gabe-lyons** [comment]
Hey @johnfelipe that's great to hear! We will certainly be in touch.

**Comment by jjoyce0510** [comment]
Hi @gabe-lyons - let's turn this into a feature request since it requires net new work and close the issue here.

Thanks
John
