### ISSUE TITLE
create workflow for KNOWAGE

### ISSUE THREAD

**Issue by johnfelipe** [datahub-project/datahub#5218]
I will test superset and metabase, but other good for enhanced datahub is knowage support integration

**Comment by maggiehays** [comment]
Hi @johnfelipe! I've created a feature request on your behalf [here](https://feature-requests.datahubproject.io/p/knowage-integration) so we can gauge level of interest & impact from the community. Feel free to upvote & subscribe to updates as we move through the review process. I'll close out this issue for now.
