### ISSUE TITLE
Conflicting Dependencies with apache-airflow 2.3.2

### ISSUE THREAD

**Issue by iamakashladdha** [datahub-project/datahub#5226]
**Describe the bug**
Getting the dependency conflict when installing `acryl-datahub[datahub-rest,airflow,redshift]==0.8.38.3` to use with apache-airflow==2.3.2. Please release compatible release to resolve this error.

**To Reproduce**
1. Install acryl-datahub[datahub-rest,airflow,redshift]==0.8.38.3 package with Apache Airflow 2.3.2

Error:
```
ERROR: Cannot install acryl-datahub[airflow,datahub-rest,redshift]==0.8.38.3 and apache-airflow==2.3.2+astro.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```
**Expected behavior**
Conflict should not happen and we should be able to Leverage DataHub Functionality with Apache Airflow 2.3.2

**Screenshots**
![image](https://user-images.githubusercontent.com/98732616/175029011-8190b2b3-20d4-4ce3-86c2-f9644a6bfd07.png)

**Additional context**
Tried with several acryl-datahub versions as below, but still got the same issue.
- acryl-datahub[datahub-rest,airflow,redshift]==0.8.38.3
- acryl-datahub[datahub-rest,airflow,redshift]==0.8.38.2
- acryl-datahub[datahub-rest,airflow,redshift]==0.8.38
- acryl-datahub[datahub-rest,airflow,redshift]==0.8.36

**Comment by anshbansal** [comment]
@treff7es Giving this one to you as you are more aware of all airflow dependencies.

**Comment by iamakashladdha** [comment]
Still getting the dependency conflict when installing acryl-datahub[datahub-rest,airflow,redshift]==0.8.42 to use with apache-airflow==2.3.x So please don't mark it as stale.

Tried this with the latest version 0.8.42 released today 4th August. https://pypi.org/project/acryl-datahub/0.8.42/

Error: 
```
ERROR: Cannot install acryl-datahub[airflow,datahub-rest,redshift]==0.8.42 and apache-airflow==2.3.3+astro.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Snapshot:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/98732616/182811757-15e1bbee-18eb-4218-aa76-c129be289336.png">

Thanks!

**Comment by KulykDmytro** [comment]
seems like dup #4809

**Comment by rslanka** [comment]
Fixed by PR: https://github.com/datahub-project/datahub/issues/5593
