### ISSUE TITLE
MarkDatasetStatus Transformer completes without error, but Dataset is still visible in UI

### ISSUE THREAD

**Issue by RyanHolstien** [datahub-project/datahub#5242]
**Describe the bug**
(https://datahubspace.slack.com/archives/C029A3M079U/p1656002671603829)

**To Reproduce**
See Slack thread, create an ingestion recipe with the mark dataset status transformer and execute.

**Expected behavior**
Datasets should not be visible in UI after removal.

**Screenshots**
See thread

**Desktop (please complete the following information):**

**Additional context**

**Comment by anshbansal** [comment]
This should be fixed with server release https://github.com/datahub-project/datahub/releases/tag/v0.8.41
