### ISSUE TITLE
Add organizationName to corpUserInfo aspect + display in UI

### ISSUE THREAD

**Issue by jjoyce0510** [datahub-project/datahub#5245]
**Describe the bug**

Add organization name to corp user info. Display departmentName + organizationName in the UI.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by maggiehays** [comment]
@jjoyce0510 is this actually a bug or should it be a feature request?

**Comment by jjoyce0510** [comment]
This is really a small feature request yes. I will raise as such

**Comment by jjoyce0510** [comment]
https://feature-requests.datahubproject.io/p/add-organization-name-to-corpuser-surface-in-ui 

Closing this ticket, as it is not a bug.
