### ISSUE TITLE
Feature request: retrieve single aspect by its type

### ISSUE THREAD

**Issue by Falci** [datahub-project/datahub#5251]
Currently, the GraphQL schema has a method to retrieve all aspects as a list:
https://github.com/datahub-project/datahub/blob/fdf4e48495f083314f59c414bcc7c2601633a2b8/datahub-graphql-core/src/main/resources/entity.graphql#L983-L987

It would be super useful if we could retrieve a single aspect by its key/unique identifier (type?).
Some thing like:

```graphql
aspect(type: String!): RawAspect
```

This would allow us to query specific aspect and map/name them to well defined properties in the data model.

**Comment by maggiehays** [comment]
Hi @Falci! Thanks for opening the request; I've migrated it over to our Feature Request Portal so we can gauge interest/impact from the Community; please feel free to upvote & subscribe to the post for automated updates as we move through prioritization

https://feature-requests.datahubproject.io/p/retrieve-single-aspect-by-its-type
