### ISSUE TITLE
acryldata/datahub-actions v0.0.4 fails

### ISSUE THREAD

**Issue by sachinwadhwa** [datahub-project/datahub#5257]
**Describe the bug**
We deployed latest version v0.8.39 withdatahub-actions v0.0.4 using helm on Azure Container Services. but its pod keep restarting with "Problem with request: Get "http:///health": http: no Host in request URL. Sleeping 1s"

It worked fine with previously.

**To Reproduce**
As above

**Expected behavior**
Correct health check.

**Comment by sachinwadhwa** [comment]
I think I found the issue:

https://github.com/acryldata/datahub-actions/blob/main/docker/datahub-actions/Dockerfile have

CMD dockerize -wait http://$DATAHUB_GMS_HOST:$DATAHUB_GMS_PORT/health -timeout 240s /start_datahub_actions.sh

while the variable passed via helm are:
          env:
            - name: GMS_HOST
              value: datahub-datahub-gms
            - name: GMS_PORT
              value: "8080"

**Comment by anshbansal** [comment]
The helm chart was updated https://github.com/acryldata/datahub-helm/pull/135 Please update your helm chart version
