### ISSUE TITLE
lineage not shown in v0.8.39

### ISSUE THREAD

**Issue by sachinwadhwa** [datahub-project/datahub#5260]
**Describe the bug**
If you ingest lineage with preserve_upstream: false , upstream is not shown in new UI (with degree of dependencies), although you can still see in visualization.
This used to work fine with 0.8.38

**To Reproduce**
as above

**Expected behavior**
Lineage should listed as text

**Comment by jjoyce0510** [comment]
It may be that the upstream datasets are not created as entities in the Metadata Graph --> We are looking into it.

**Comment by jjoyce0510** [comment]
@sachinwadhwa can you confirm that the issue persists?

**Comment by sachinwadhwa** [comment]
> @sachinwadhwa can you confirm that the issue persists?

confirmed, its happening on v0.8.41

**Comment by jjoyce0510** [comment]
@sachinwadhwa thanks for the reply. If you reach out on Slack, we can find some time to jump into a call and get this sorted out!
