### ISSUE TITLE
"NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:databricks.pyhive"

### ISSUE THREAD

**Issue by sachinwadhwa** [datahub-project/datahub#5288]
**Describe the bug**
While ingesting data using UI for databricks/hive source, it fails with "NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:databricks.pyhive" error.

Works with local Python install

**To Reproduce**
as above

**Comment by jjoyce0510** [comment]
@anshbansal Have you done some work in this regard already?

**Comment by anshbansal** [comment]
@shirshanka did some work related to databricks if I remember correctly. But don't think it made it to managed ingestion.

**Comment by rslanka** [comment]
The support has now been added by the PR mentioned above. Closing the issue.
