### ISSUE TITLE
Error while doing Airflow Integration

### ISSUE THREAD

**Issue by Kuladeep1996** [datahub-project/datahub#5300]
**Describe the bug**
We are following this "[https://datahubproject.io/docs/lineage/airflow](https://datahubproject.io/docs/lineage/airflow)" for airflow integration with datahub but when running step3 command causing error

**Screenshots**
![image](https://user-images.githubusercontent.com/74226018/176667657-1615e58c-f40e-46d7-9d6c-b31ce75e6340.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 103.0.5060.66

**Comment by Kuladeep1996** [comment]
Got this error when modified core.lazy_load_plugins to False 
![image](https://user-images.githubusercontent.com/74226018/177108636-d22d8c47-2d5d-4567-91ed-7507f12aba0c.png)

**Comment by treff7es** [comment]
@Kuladeep1996 you made a typo in your config and you wrote flase instead of false

**Comment by Kuladeep1996** [comment]
My bad sry..
When running 
airflow connections add  --conn-type 'datahub_rest' 'datahub_rest_default' --conn-host 'http://localhost:8080'
getting this error
![image](https://user-images.githubusercontent.com/74226018/177156807-98d791ed-03c1-4135-9354-f557d991a05a.png)

**Comment by treff7es** [comment]
Does this cause any issues? I think this is a windows specific issue in Airflow and not in our integration.
Based on what I read this should not cause any issue.

**Comment by shirshanka** [comment]
@Kuladeep1996 : this seems like an issue with running airflow on windows. Not something specific to datahub. Please raise this with the airflow project. Closing this, please re-open if you think this is a datahub specific issue.
