### ISSUE TITLE
Please allow selfsigned ca-certs for S3 source

### ISSUE THREAD

**Issue by semmjon** [datahub-project/datahub#5307]
I get SSL / CA-CERT errors
```
'SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain '
```
When trying to connect a non-AWS S3, the boto3-client requires its own CA certificate.
It would be best if all source connections had a custom cert path opportunity (e.g. /etc/ssl/certs/ca-certificates.crt).

**Comment by semmjon** [comment]
Yes it is still an issue.
I used the following image (version).
[acryldata/datahub-actions:v0.0.4](https://hub.docker.com/layers/datahub-actions/acryldata/datahub-actions/v0.0.4/images/sha256-60cbf0081ef0f6db3854a3a8bbbd500480ea69b54863ac6ad819974303191584?context=explore)
I also believe it could be just a few lines of code. 
Only the "cafile" / "verify" parameter would have to be passed to the S3 client.

**Comment by mohdsiddique** [comment]
Hi @semmjon 
Could you please add detail for the issue you are facing, like the recipe, DataHub version, and which container is raising the above error?

**Comment by semmjon** [comment]
Hi,
it's been a while now, which is why i hadn't tried it again with the new version. Test case was the following:
- private S3 object storage (with selfsigned certificate) (in my case Ceph, but I think it doesn't matter which S3 storage)
- One of the most recent Helm charts on a K3s cluster
- The error appeared when scheduling the S3 ingestion
- Probably in the boto3 module in the acryldata/datahub-actions container (then v0.0.4 , but probably not fixed yet in newer)
- To fix the error, a cafile would have to be given when creating the S3 client.

**Comment by am2222** [comment]
@shirshanka I noticed you approved the PR. However this issue happens for all the ingestion sources when we use self-signed ssl certificates in internal networks. 
I think having a general param for all of the ingestions to set `verify` to false would solve this issue.
