### ISSUE TITLE
Datahub python package 0.8.40+ cannot be installed onto Airflow:2.2.5 image

### ISSUE THREAD

**Issue by KulykDmytro** [datahub-project/datahub#5324]
**Describe the bug**
Datahub python package 0.8.40+ cannot be installed onto Airflow:2.2.5 image

seems like have restrictions for Python version `<=3.9.9`
Is it possible to loose this dependency to use with original `Airflow` image which is built on 3.9.12?

**To Reproduce**
1. setup pyproject.toml with `acryl-datahub = "^0.8.32.2"`
2. run `poetry update acryl-datahub`

**Screenshots**
```
Package operations: 3 installs, 1 update, 0 removals

  • Installing bracex (2.3.post1)
  • Updating acryl-datahub (0.8.39 -> 0.8.40.2): Installing...
  • Installing parse (1.19.0): Failed

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
```

**Desktop (please complete the following information):**
 - MacOs: 12.3.1

**Comment by anshbansal** [comment]
Just checked that DataHub 0.8.41.1 can be installed on Python 3.9.10
```
(python3_9_10) aseembansal@Aseems-MacBook-Pro metadata-ingestion % python --version
Python 3.9.10
(python3_9_10) aseembansal@Aseems-MacBook-Pro metadata-ingestion % datahub --version
acryl-datahub, version 0.8.41.1
```

I am not familiar with poetry but the error is about missing setuptools. Have you checked that?

**Comment by KulykDmytro** [comment]
0.8.41.x is NOW compatible with airlow:2.2.5 and python:3.9.13
