### ISSUE TITLE
Unable to create new tags from the UI

### ISSUE THREAD

**Issue by putnam120** [datahub-project/datahub#5336]
**Describe the bug**
My users are unable to create new tags from the UI. When they click add tag they are able to go through the entire flow but when they select create they get the error `Failed to create & add tag.` All of these users have permissions to `Edit Tags` and `Edit Dataset Column Tags` on the following resources `[Tags, Datasets]`.

However, the `datahub` admin user is able to create tags. These tags are then able to be used by other users to assign to different assets. But the non-admin users are unable to create new tags.

**To Reproduce**
1. Log in as a non-admin user (any account but the one with username `datahub`) that has the `Edit Tags` and `Edit Dataset Column Tags` permissions for `Dataset` and `Tag` resources.

2. Select any dataset and select to add a tag.
3. Choose to add a new tag that doesn't belong to the current set of known tags.
4. Go through the tag creation flow and select create tag.
5. See error

**Expected behavior**
I expect that a new tag would be created and added to the dataset.

**Desktop (please complete the following information):**
 - OS: OSX 11.6.2
 - Browser chrome
 - Version 101.0.4951.64

**Comment by jjoyce0510** [comment]
We are actively looking into this- I know we had recently added a platform privilege called 'Create Tags' which is intended to be used for this exact purpose.

**Comment by jjoyce0510** [comment]
Fixed in this PR: https://github.com/datahub-project/datahub/pull/5359

Will be released shortly!
