### ISSUE TITLE
Postgres Ingestion profiling bug

### ISSUE THREAD

**Issue by Kuladeep1996** [datahub-project/datahub#5375]
**Describe the bug**
Before v0.8.40 if i keep profiling it used to work properly. But after updating to v0.8.40 i was getting ["Profiling exception 'partial_unexpected_list'"] error for profiling 

**To Reproduce**
source:
    type: "postgres"
    config:
        host_port: "localhost:5432"
        database: "employee"
        username: "********"
        password: "*********"
        include_tables: true
        include_views: true
        profiling:
            enabled: true
    
sink:
    type: "datahub-rest"
    config:
        server: "http://localhost:8080"

Use this recipe for postgres 

**Expected behavior**
Profiling should work  

**Screenshots**
![image](https://user-images.githubusercontent.com/74226018/178421626-48ed2061-2353-428e-af66-f2ecf96f1187.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by denisov-vlad** [comment]
Having the same issue on `v0.8.43` with  MySQL and Postgres ingestions.
