### ISSUE TITLE
Problem with analytics when using ES OSS

### ISSUE THREAD

**Issue by murzindima** [datahub-project/datahub#5376]
**Describe the bug**
I have deployed DataHub using managed ElasticSearch in AWS and for some reason Analytics is not working (http://localhost:9002/analytics). 

**To Reproduce**
1. Go to 'https://datahubproject.io/docs/quickstart/'
2. Use 'https://github.com/datahub-project/datahub/blob/master/docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml'
3. Change ES image to 'https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss:7.9.3' + USE_AWS_ELASTICSEARCH=true

**Expected behavior**

**Screenshots**
<img width="1169" alt="Screenshot 2022-07-12 at 10 12 17 AM" src="https://user-images.githubusercontent.com/18555945/178434305-33bded21-0ef3-49cf-a008-b215e8e51f74.png">

**Additional context**
ES: managed ES OSS in AWS
```
{
  "name" : "123qwe123qwe",
  "cluster_name" : "blahblahblah",
  "cluster_uuid" : "123we123qwe",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2022-02-10T09:41:23.620550Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
PostgreSQL:  PostgreSQL 14.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
DataHub: v0.8.40

**Logs:**
[tmpnqxgvxye.log](https://github.com/datahub-project/datahub/files/9090627/tmpnqxgvxye.log)

**Comment by murzindima** [comment]
Hello @tomas-kubin 

Many thanks! It works like a charm.

**Comment by tomas-kubin** [comment]
Thanks for the feedback @murzindima ! Now that I have the issue confirmed from two sources, I will try to make a proper fix.

**Comment by anshbansal** [comment]
@tomas-kubin If you do make a contribution that would be great. Please head to #contribute channel in slack in case you need any help

**Comment by aditya-radhakrishnan** [comment]
Closing this issue since it has been resolved. If you'd like to make a contribution to fix this, that'd be great. Thank you!
