### ISSUE TITLE
UI Allows to Delete Glossary Node

### ISSUE THREAD

**Issue by fprima** [datahub-project/datahub#5410]
**Describe the bug**
When looking at a Glossary Node and I click on the kebab menu, the Delete option is greyed out. If I click it, a tooltip tells me I can't delete it, but a modal appears to confirm if I want to delete it. If I click yes, the node is deleted and the children attached to the top level.

**To Reproduce**
1. Go to the main Glossary screen and select a node
2. Click on the kebab menu
3. Click on Delete
4. Click Yes on the confirmation modal
5. Node will be deleted and children appear on the top level

**Expected behavior**
Confirmation modal should not appear. No action should happen when clicking on the greyed out Delete

**Screenshots**
![Screen Shot 2022-07-15 at 11 25 53](https://user-images.githubusercontent.com/52747129/179256302-c82e74eb-c790-488d-9b9f-82d8282504c2.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser Chrome
 - Version 103.0.5060.114 (Official Build) (arm64)

**Comment by chriscollins3456** [comment]
Created a PR to fix! https://github.com/datahub-project/datahub/pull/5430

**Comment by fprima** [comment]
Thanks!
