### ISSUE TITLE
docker/dev.sh doesn't work due to missing debug tag in docker images

### ISSUE THREAD

**Issue by jinlintt** [datahub-project/datahub#5439]
**Describe the bug**
When I ran `docker/dev.sh` from commit (ac61bcd951c9ada015ec2d4c8c5b9b824da58789), I got the following error:
```
Error response from daemon: manifest for linkedin/datahub-kafka-setup:debug not found: manifest unknown: manifest unknown
```

Looking at the docker images in docker hub, I found that the `debug` tag didn't exist any more for the `linkedin/datahub-kafka-setup` image. This also applied to the `datahub-frontend-react` and `datahub-elasticsearch-setup` images, which are also referenced in the `docker-compose.dev.yml` file.

**To Reproduce**
1. Just run `docker/dev.sh` from the root of the repo.

**Expected behavior**
Not to see this error.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.4

**Comment by anshbansal** [comment]
Can you please ensure docker V2 is disabled? We have tested everything on docker v1

**Comment by anshbansal** [comment]
Confirmed on slack that this was the solution
