### ISSUE TITLE
docker-compose up --build failed on MacOS with M1 chip

### ISSUE THREAD

**Issue by jinlintt** [datahub-project/datahub#5441]
**Describe the bug**
When I tried to build everything using docker-compose locally, I got the following error.
I am on MacOS with M1 chip.

```
#0 209.7 Execution failed for task ':datahub-web-react:nodeSetup'.
#0 209.7 > Could not resolve all files for configuration ':datahub-web-react:detachedConfiguration1'.
#0 209.7    > Could not find org.nodejs:node:16.8.0.
#0 209.7      Searched in the following locations:
#0 209.7        - https://plugins.gradle.org/m2/org/nodejs/node/16.8.0/node-16.8.0.pom
#0 209.7        - file:/root/.m2/repository/org/nodejs/node/16.8.0/node-16.8.0.pom
#0 209.7        - https://repo.maven.apache.org/maven2/org/nodejs/node/16.8.0/node-16.8.0.pom
#0 209.7        - https://packages.confluent.io/maven/org/nodejs/node/16.8.0/node-16.8.0.pom
#0 209.7        - https://linkedin.jfrog.io/artifactory/open-source/org/nodejs/node/16.8.0/node-16.8.0.pom
#0 209.7        - https://nodejs.org/dist/v16.8.0/node-v16.8.0-linux-aarch64.tar.gz
#0 209.7      Required by:
#0 209.7          project :datahub-web-react
```

**To Reproduce**
1. run 
```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 DATAHUB_MAPPED_MYSQL_PORT=53306 docker-compose \
    -f docker-compose.yml \
    -f docker-compose.override.yml \
    -f docker-compose.m1.yml \
    --verbose pull
```

2. Run
```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 DATAHUB_MAPPED_MYSQL_PORT=53306 docker-compose \
    -f docker-compose.yml \
    -f docker-compose.override.yml \
    -f docker-compose.m1.yml \
    up --build
```
5. See error

**Expected behavior**
The build should go through without failure.

**Desktop (please complete the following information):**
 - OS: MacOS with M1 chip
 - Version: 12.4

**Comment by goldlant** [comment]
wirte preview

**Comment by pedro93** [comment]
Hello @jinlintt 

What version of `docker` are you using? 
I see you execute `docker-compose`, could you instead try with `docker compose`, note the space. The former is an old, deprecated version of docker-compose which has known issues with M1 Arm systems.

**Comment by jinlintt** [comment]
@pedro93 thank you! I will give it a try.
The doc used to ask us to use `docker-compose` instead of `docker compose`, which was why I ran that command.
You mentioned at the office hour earlier that now it is fully on docker compose v2, which is terrific.

**Comment by pedro93** [comment]
This is probably a case of out-dated docs. Can you send me a link to the doc in question?

**Comment by jinlintt** [comment]
Please see below.
https://datahubspace.slack.com/archives/CV2UVAPPG/p1658253771813039

https://datahubproject.io/docs/docker/development
