### ISSUE TITLE
[Question] How to send schema to DataHub via Python Emitter

### ISSUE THREAD

**Issue by orcahmlee** [datahub-project/datahub#5445]
Hi,
I was able to follow the [example code](https://datahubproject.io/docs/metadata-ingestion/as-a-library#example-usage) to send the metadata to GMS server. After following the example code, I could see the `customProperties={"governance": "ENABLED"})` shown on the `Properties` tab of the DataHub UI.

However, Does Python Emitter have more detailed API documentation? I would like to send `Schema` using the  Python Emitter.

**Comment by xiphl** [comment]
check metadata-ingestion/examples/library/dataset_schema.py in the repo
The folder has some other examples.

**Comment by orcahmlee** [comment]
> check metadata-ingestion/examples/library/dataset_schema.py in the repo The folder has some other examples.

Thanks for the quick reply @xiphl !
I could send the schema using `dataset_schema.py`. It would be very helpful if the official documentation contains these examples.

**Comment by orcahmlee** [comment]
After digging examples on `metadata-ingestion/examples/library/`, I successfully sent `Schema`, `Documentation`, and `Properties` to DataHub. 

However, I am not able to send `Stats` to DataHub. I've tried `DatasetFieldProfileClass` and `DatasetProfileClass` but I still could see the `Stats` tag enable on the DataHub UI. After I `.emit(event)`, it will return a tuple of two datetimes, but the DataHub UI seems not to be affected.

@xiphl could you provide some examples showing how to send `Stats` via Python Emitter?

**Comment by orcahmlee** [comment]
> I dont have sample code for stats. but you can take a look at loop_profiler() inside /metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

Thanks @xiphl 
I've taken a look at `loop_profiler()` for a couple of hours but still don't understand why I couldn't emit the `Stats`.

Here is my sample code:

```python
# Imports for urn construction utility methods
from datahub.emitter.mce_builder import make_data_platform_urn, make_dataset_urn
from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.emitter.rest_emitter import DatahubRestEmitter

# Imports for metadata model classes
from datahub.metadata.schema_classes import (
    ChangeTypeClass,
    DatasetFieldProfileClass,
    DatasetProfileClass,
)
from time import time


emitter = DatahubRestEmitter(gms_server="http://localhost:8080", extra_headers={})

dp = DatasetProfileClass(
    timestampMillis=int(time()),
    rowCount=400000,
    columnCount=200,
    fieldProfiles=[]
)

event = MetadataChangeProposalWrapper(
    entityType="dataset",
    changeType=ChangeTypeClass.UPSERT,
    entityUrn=make_dataset_urn("gcs", "tmp-file"),
    aspectName="datasetProfile",
    aspect=dp,
)

# Emit metadata! This is a blocking call
emitter.emit(event)
```

After I executed the above script, I could see a new Dataset on DataHub UI. However, the `Stats` tag was still disabled.

<img width="1074" alt="Screen Shot 2022-07-21 at 15 16 43" src="https://user-images.githubusercontent.com/26179752/180153275-86db6070-9028-49cc-9d5a-a2b411e59558.png">

**Comment by orcahmlee** [comment]
> I dont have sample code for stats. but you can take a look at loop_profiler() inside /metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py

Thanks @xiphl 
I've taken a look at `loop_profiler()` for a couple of hours but still don't understand why I couldn't emit the `Stats`.

Here is my sample code:

```python
# Imports for urn construction utility methods
from datahub.emitter.mce_builder import make_data_platform_urn, make_dataset_urn
from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.emitter.rest_emitter import DatahubRestEmitter

# Imports for metadata model classes
from datahub.metadata.schema_classes import (
    ChangeTypeClass,
    DatasetFieldProfileClass,
    DatasetProfileClass,
)
from time import time


emitter = DatahubRestEmitter(gms_server="http://localhost:8080", extra_headers={})

dp = DatasetProfileClass(
    timestampMillis=int(time()),
    rowCount=400000,
    columnCount=200,
    fieldProfiles=[]
)

event = MetadataChangeProposalWrapper(
    entityType="dataset",
    changeType=ChangeTypeClass.UPSERT,
    entityUrn=make_dataset_urn("gcs", "tmp-file"),
    aspectName="datasetProfile",
    aspect=dp,
)

# Emit metadata! This is a blocking call
emitter.emit(event)
```

After I executed the above script, I could see a new Dataset on DataHub UI. However, the `Stats` tag was still disabled.

<img width="1074" alt="Screen Shot 2022-07-21 at 15 16 43" src="https://user-images.githubusercontent.com/26179752/180153275-86db6070-9028-49cc-9d5a-a2b411e59558.png">

**Comment by orcahmlee** [comment]
I did it!!!

After I modified the `timestampMillis` from `int(time())` to `int(time() * 1000)`, I was able to see the `Stats` on the UI.
