### ISSUE TITLE
[Feature Request] Analytics configuration without rebuilding

### ISSUE THREAD

**Issue by Babbleshack** [datahub-project/datahub#5450]
Enabling analytics requires rebuilding datahub projects. 

For use hosting on K8s or other managed infra this might mean forking, building and hosting datahub docker images. 

The [docs](https://datahubproject.io/docs/datahub-web-react/src/app/analytics/#configuring-an-analytics-provider) mention a `no-code` solution:

> Currently, configuring an analytics provider requires that you fork DataHub & modify code. As described in 'Coming Soon', we intend to improve this process by implementing no-code configuration.

However I dont see an issue or RFC for it

- Is there any ETA on this feature? 
- How should we track the progress of this feature?

**Comment by anshbansal** [comment]
Please use https://feature-requests.datahubproject.io/ for feature requests. Please search if there is an existing feature requests.
