### ISSUE TITLE
Running Airflow locally with DataHub, init fail

### ISSUE THREAD

**Issue by zsdyx** [datahub-project/datahub#5461]
**Describe the bug**
initialize airflow fail

**To Reproduce**
https://datahubproject.io/docs/docker/airflow/local_airflow

**Expected behavior**
```
airflow-init_1       | Admin user airflow created
airflow-init_1       | 2.1.3
airflow_install_airflow-init_1 exited with code 0

```

**Comment by zsdyx** [comment]
Hi，Is there a solution

**Comment by anshbansal** [comment]
Can you please share details of your system where you are running? Have you made any changes in the docker compose files? Have you given sufficient memory to Docker as per prerequisites?

**Comment by mohdsiddique** [comment]
Hi @zsdyx 
Is this still an issue? if not, will close it after a few days of inactivity.
