### ISSUE TITLE
No way to get rid of the default datahub/datahub username + password combo

### ISSUE THREAD

**Issue by jinlintt** [datahub-project/datahub#5462]
**Describe the bug**
I followed the instruction below to configure a different password for the default `datahub` username when deploying to GKE in the cloud. Afterwards, the `datahub/<new password>` combo worked, but the old `datahub/datahub` combo also still worked. 
https://datahubproject.io/docs/authentication/guides/add-users#helm

**To Reproduce**
1. Follow the instruction below to store a custom `users.prop` file in the kubenetes secret store. Also create a custom `values.yaml` file according to the instruction.
https://datahubproject.io/docs/authentication/guides/add-users#helm
2. Follow the instruction below to deploy to Kubenetes. When deploying the `datahub` chart, also pass in the custom `values.yaml` file created in step 1.
https://datahubproject.io/docs/deploy/kubernetes/
3. Access the `datahub-datahub-frontend` using its public ip address + port 9002
4. You can login using both `datahub/datahub` and `datahub/<new password>` combos.

**Expected behavior**
Shouldn't be able to login using `datahub/datahub` any more.

**Additional context**
I tested this in GKE.

**Comment by xiphl** [comment]
I mounted user.props in /datahub-frontend/conf/user.props instead and the default password is overwritten.

**Comment by anshbansal** [comment]
@jinlintt Please try what @xiphl has said which will replace the user. That guide you are linking to was always for "Adding Users" not "Replacing Users".
