### ISSUE TITLE
Delete the table from the data source. Metadata also contains information about that table

### ISSUE THREAD

**Issue by liyuhui666** [datahub-project/datahub#5466]
When I delete a table in the metadata, the metadata of DataHub should delete that table after the ingestion is complete. But when I tested it, I found metadata of this table in datahub

**Comment by maggiehays** [comment]
Hi @liyuhui666! Please take a look at [Stateful Ingestion](https://datahubproject.io/docs/metadata-ingestion/docs/dev_guides/stateful/) - this should support removing deleted data from DataHub when it's deleted from source. I'll close out this issue for now, but please feel free to re-open if the issue persists!
