### ISSUE TITLE
Dataset schemaMetadata aspect UPSERT does not work in Python REST emitter API

### ISSUE THREAD

**Issue by jazzblue** [datahub-project/datahub#5486]
**Describe the bug**
Upserting Dataset schemaMetadata aspect using Python _MetadataChangeProposalWrapper/DatahubRestEmitter_ API throws schema error.

**To Reproduce**
1. Follow [DataHub Quickstart Guide](https://datahubproject.io/docs/quickstart) including **ingesting sample metadata**.
2. Run Python interpreter (I used with Python 3.8.9)
3. Run (copy/paste) the following calls one by one:
```python
import datahub.metadata.schema_classes as models
from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.emitter.rest_emitter import DatahubRestEmitter

aspect = {
    "schemaName":"FooEvent",
    "platform":"urn:li:dataPlatform:foo",
    "version":0,
    "hash":"",
    "platformSchema":{
        "com.linkedin.schema.KafkaSchema":{
                "documentSchema":"{\"type\":\"record\",\"name\":\"MetadataChangeEvent\",\"namespace\":\"com.linkedin.mxe\",\"doc\":\"Kafka event for proposing a metadata change for an entity.\",\"fields\":[{\"name\":\"auditHeader\",\"type\":{\"type\":\"record\",\"name\":\"KafkaAuditHeader\",\"namespace\":\"com.linkedin.avro2pegasus.events\",\"doc\":\"Header\"}}]}"
        }
    },
    "fields":[
        {
            "fieldPath":"foo",
            "description":"Bar",
            "nativeDataType":"string",
            "type":{"type": {"com.linkedin.schema.StringType":{}}}
        }
    ]
}
metadata_change_proposal = MetadataChangeProposalWrapper(
                entityType="dataset",
                changeType=models.ChangeTypeClass.UPSERT,
                entityUrn="urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)",
                aspectName="schemaMetadata",
                aspect=models.SchemaMetadataClass(**aspect),
)
emitter = DatahubRestEmitter(
                gms_server='http://localhost:8080',
)
emitter.emit_mcp(metadata_change_proposal)
```
You will get **"...is not an example of the schema..."** error.

**Comment by xiphl** [comment]
under "fields", it is expecting a list of schemaField (I forgot the full name) objects, not a list of dictionary. check the schemaMetaDataClass again in schema_classes.py.

**Comment by jazzblue** [comment]
> under "fields", it is expecting a list of schemaField (I forgot the full name) objects, not a list of dictionary. check the schemaMetaDataClass again in schema_classes.py.

Thanks for your prompt response. I simply followed [this example](https://datahubproject.io/docs/metadata-service/#create-a-dataset) and using Rest.li like it shows does work with no problem. It is the Python Rest Emitter that would not work for me.

**Comment by jazzblue** [comment]
> under "fields", it is expecting a list of schemaField (I forgot the full name) objects, not a list of dictionary. check the schemaMetaDataClass again in schema_classes.py.

@xiphl Thank you!  I did check the schema classes file and you are right, for Python it is all done through classes:
```python
type=models.SchemaFieldDataTypeClass(type=models.StringTypeClass())
```
That solved the problem>
I wish I could find more documentation on the Python Rest Emitter API usage.
