### ISSUE TITLE
No enum constant com.linkedin.datahub.graphql.generated.AssertionStdOperator.REGEX_MATCH

### ISSUE THREAD

**Issue by amzar96** [datahub-project/datahub#5513]
**Describe the bug**
Hi, I got this error after I added the below expectation using GreatExpectation

```json
...
{
      "expectation_context": {
        "description": null
      },
      "expectation_type": "expect_column_values_to_match_regex",
      "kwargs": {
        "column": "account_type",
        "regex": "^(CLIENT)$"
      },
      "meta": {}
}
...
```

my expectation is, only passed if the value is `CLIENT`
my command `great_expectations checkpoint run account_checkpoint` and there is no issue when I run this command, but only show error in DataHub view (as per screenshot)

**To Reproduce**
1. Create a new expectation `~\great_expectations\expectations\reproduce_expect.json` and link to `checkpoint`
2. Add new item (as above) in `expectations` list
3. Run this command `great_expectations checkpoint run {your checkpoint}`

**Expected behavior**
Can view the dataset with validation enabled 

**Screenshots**
1. Inspect value
![image](https://user-images.githubusercontent.com/19677928/181442009-db3257d8-4a55-4445-ac6b-81fe16825250.png)

2. DataHub view (blank)
![image](https://user-images.githubusercontent.com/19677928/181442108-74e49a09-f0a6-4b04-8ba0-e7d2b11f7368.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 0.8.38

**Comment by jjoyce0510** [comment]
We are working on this!

Thanks for the report
John
