### ISSUE TITLE
Showing files as datasets in Datahub

### ISSUE THREAD

**Issue by Shaikh-Zainab** [datahub-project/datahub#5525]
**Description**
This an issue of how file sources or datasets in general are rendered by DH. It looks like the containerization of sources is handled in DH UI, based on separators like '.', '/' etc. So if a file and folder structure was say FolderA contains files Sample1.txt and Sample2.txt, MDH would show it as FolderA>Sample1>txt and FolderA>Sample2>txt which translates to FolderA having two sub-folders SampleA and SampleB with txt as file names, with the extension coming as filename.
This causes an issue if I am trying to ingest and build lineage where a source maybe a file and it not being represented correctly in DH.
We are trying to build lineage and an upstream or downstream could be file residing on a server like Unix or Windows. Also per current design of datahub it seems we can have only one file in filesystem with a particular name. But in reality, we can have multiple files with same name residing in different paths within a filesystem.

**Comment by jjoyce0510** [comment]
@Shaikh-Zainab If you emit a custom browse path aspect from your ingestion source code, you should be able to control the hierarchy so that the UI does not mint this on your behalf. 

This doc should help you understand the browse paths aspect: https://datahubproject.io/docs/metadata-modeling/metadata-model/#browsepaths-aspect

**Comment by Shaikh-Zainab** [comment]
Hi @jjoyce0510,
I have tried creating custom browse using above example and solves the issue of '.' in file names, it have given rise to a new issue that it takes away the containerization of the path. e.g earlier it would show FolderA as container having FolderD as another container with Sample as a dataset. But now it just shows FolderA>FolderD>Sample.txt in browse paths but when I click on actual containers they are empty.

**Comment by Shaikh-Zainab** [comment]
Also in addition to above, there is bug in lineage UI which shows a file called sample.txt having name as only txt.
[code which shows lineage node](https://github.com/datahub-project/datahub/blob/b32a0723a116f1b9c7d334fd6783303a79dfe8d0/datahub-web-react/src/app/lineage/LineageEntityNode.tsx#L30)

**Comment by Shaikh-Zainab** [comment]
Missing child containers issue - Screenshots
![image](https://user-images.githubusercontent.com/110192305/183880429-30ee7c68-581e-466c-9b74-9ced2cb7c0c6.png)

![image](https://user-images.githubusercontent.com/110192305/183880560-97b08ee0-6fab-4e96-8fba-d814874faa69.png)

Also tried removing spaces in string from browsepaths. Still no child containers are being build
![image](https://user-images.githubusercontent.com/110192305/183883348-3eaacbaa-9a2a-465f-b517-84a39bd8aa22.png)
