### ISSUE TITLE
Datahub integration airflow

### ISSUE THREAD

**Issue by YangQian-99** [datahub-project/datahub#5543]
I installed it according to the latest plug-in provided by the official website. The example of the official website is to define inlets and outlets in DAG, but I can't achieve the effect when running DAG. Who knows about datahub_ airflow_ How to use plugin?
link：https://github.com/datahub-project/datahub/tree/master/metadata-ingestion-modules/airflow-plugin

**Comment by YangQian-99** [comment]
This problem was solved because I only restarted schedluer and webserver after installing the datahub dependency, but did not restart the celery worker.

**Comment by rslanka** [comment]
Closing since the issue got resolved.
