### ISSUE TITLE
Salesforce integration authentication method does not work in Enterprise Edition sandbox environment

### ISSUE THREAD

**Issue by guangyuchendice** [datahub-project/datahub#5556]
**Describe the bug**
I built the salesforce ingestion recipe according to the documentation provided (please see below recipe). I tested that against Salesforce Enterprise edition with both Direct access token as well as password method but failed.
For access token one, the token is invalid even it was only generated within a minute:
Response content: [{'message': 'Session expired or invalid', 'errorCode': 'INVALID_SESSION_ID'}]
For username/passoword:
ERROR    {datahub.ingestion.source.salesforce:231} - INVALID_LOGIN: Invalid username, password, security token; or user locked out.
But I am using the correct credential and tokens. Just not Salesforce enterprise edition sandbox

**To Reproduce**
1. datahub ingest -c ~/salesforce.dhub.yml where the yaml file is below code tex.text

**Expected behavior**
Authentication should not be failing

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser [Chrome]

**recipe**
[tex.txt](https://github.com/datahub-project/datahub/files/9252501/tex.txt)

**Comment by guangyuchendice** [comment]
I tried out the simple-salesforce library that the plugin relies on. It seems that if I missed domain='test' argument during the login I will have the same problem

**Comment by mayurinehate** [comment]
Closed by https://github.com/datahub-project/datahub/pull/6105
Set `is_sandbox: True` in recipe.
