### ISSUE TITLE
[Feature request] Add new entity of metric and dimension

### ISSUE THREAD

**Issue by predator4ann** [datahub-project/datahub#5565]
**Is your feature request related to a problem? Please describe.**
Yes. Actually we want to manage `metric` and `dimension` metadata of charts, and fine grained lineage from upstream `datasets`/`fields`.

**Describe the solution you'd like**
1. Add new entity of `metric` and `dimension`
2. Make them be properties of `chart`
3. Support fine grained lineage defined with upstream `datasets`/`fields`

**Describe alternatives you've considered**
n/a

**Additional context**
1. Just want to discuss that is this a good solution or maybe a better way to do. Thanks
2. I'd like to do this feature

**Comment by jjoyce0510** [comment]
We will be responding here shortly :)

**Comment by viniciusdsmello** [comment]
Hey @jjoyce0510, do you have any updates about this Feature Request? I was going to make the same request. At my company, we're evaluating some Metric Platforms, and it would be amazing If we could catalog metrics on Datahub and have features like lineage.
