### ISSUE TITLE
Airflow 2.3.3 compatibility

### ISSUE THREAD

**Issue by stijndehaes** [datahub-project/datahub#5593]
**Describe the bug**
The following packages:
```
acryl-datahub==0.8.42
acryl-datahub[datahub-rest]==0.8.42
acryl-datahub[datahub-kafka]==0.8.42
```
Can not be installed together with Airflow 2.3.3.
```
markupsafe>=1.1.1 (from apache-airflow==2.3.3->-r requirements-2.in (line 6))
MarkupSafe>=0.23 (from jinja2==2.11.3->apache-airflow==2.3.3->-r requirements-2.in (line 6))
markupsafe<=2.0.1,>=1.1.1 (from acryl-datahub[datahub-kafka,datahub-rest]==0.8.42->-r requirements-2.in (line 10))
MarkupSafe>=2.1.1 (from werkzeug==2.2.2->apache-airflow==2.3.3->-r requirements-2.in (line 6))
````

**To Reproduce**
1. create virtual env
2. pip install airflow==2.3.3
3. pip install acryl-datahub==0.8.42

**Expected behavior**
I expect to be able to combine the 2.

I noticed markupsafe was pinned to <= 2.0.1 because of issues with jinja:
https://github.com/datahub-project/datahub/pull/4188

And update to be compatible with Airflow:
https://github.com/datahub-project/datahub/pull/4388

However I do not have enough experience with this project to know if updating markupsafe is "safe"

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by KulykDmytro** [comment]
seems like dup #4809

**Comment by hsheth2** [comment]
Yup this is a dup - thanks for calling that out. We'll close this one and track it in the other issue.

We have been looking into the issue and will be back with more updates soon.
