### ISSUE TITLE
Username are case sensitive excepted them to be not

### ISSUE THREAD

**Issue by nj7** [datahub-project/datahub#5658]
Found out the that username propagating from External OIDC are case sensitive
For example:
There would be having multiple registered user with following mail ids:
nirmit.jain@exmple.com
Nirmit.jain@exmple.com
nirmit.jaIn@exmple.com
 and so on.
 
 There is a very simple fix to this 
 just need to add need to type cast to lower case  for the return value 

https://github.com/datahub-project/datahub/blob/5cce3acddcb46443c748bf2eb0b1e5e53994d936/datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java#L170

**Comment by xiphl** [comment]
erm. Isn't logins supposed to be exact matching?

**Comment by nj7** [comment]
I don't think think so, mails are always case and whitespace insensitive, basically these are same thing 
nirmit.jain@example.com
nirmit.           jain@example.com
nirmit.Jain@example.com
and many more combination

**Comment by xiphl** [comment]
Ok, it doesn't affect me either way, but if Identity Provider says there is a distinction between entity "Aa" and entity "aa", why would apps want to second guess and arbitrate that they're the same person.

**Comment by nj7** [comment]
hmm, i understand the concern here is it possible to add configuration around username 
- Transformation : to what ever casing we want and concatenation (if you think other may help)
- Regex Checker <tocheck oidc format in a particular way>
I think Regex is already present but just not exposed as configuration. 

does this make sense?

**Comment by jjoyce0510** [comment]
Great dialogue folks. Regex support is already there -> `AUTH_OIDC_USER_NAME_CLAIM_REGEX` environment variable but in general I agree that we should be careful about throwing away case sensitivity, especially when it comes to configurations which take _usernames_ instead of _emails_. 

@nj7 Is there a specific anomaly which is occurring because of this? Are you unable to join your users from batch connector with OIDC login because of this? Or something else? I want to get a sense for how it is impacting you and if it will impact others in the same way.

**Comment by nj7** [comment]
@jjoyce0510 facing this issue with Okta, as it uses email id for authentication and while creating user okta store exact string as email id 
for example 
it will store Nirmit.jain@example.com
where as it follows email centric use case for identifying user , 

[nirmit.jain@exmple.com](mailto:nirmit.jain@exmple.com)
[Nirmit.jain@exmple.com](mailto:Nirmit.jain@exmple.com)
[nirmit.jaIn@exmple.com](mailto:nirmit.jaIn@exmple.com)

all above email ids are allowed while logging inn for the user having username [Nirmit.jain@example.com]

I think this issue can occur for other oidc platform that uses email address for user verification.

I agree custom username would be very tricky to handle and think configuration around it would help, to enable user to manage this at there end.
