### ISSUE TITLE
Glossary Term Group - Policy Issues

### ISSUE THREAD

**Issue by xiphl** [datahub-project/datahub#5672]
Just raising a formal bug report for tracking the issue. Tested against the latest code in master branch.
I believe this bug has been there since term group was introduced as part of UI Glossary Edits.
The issue is that term group is not target-able as an entity in policies, hence requiring a lot of privileges to be granted. This brings about some issues:
1. If you disable the "view entity page" for all entities, term group entity page is not viewable, unless you grant a policy like this:
 
![image](https://user-images.githubusercontent.com/50935738/185372698-a9b592c5-9ec3-4a78-a8e1-a8573d6c04e4.png)  

2. If you do not grant user a universal edit policy, ie
![image](https://user-images.githubusercontent.com/50935738/185373083-bd702f98-4c50-43e8-95db-13b5260a69a5.png)  

The user is unable to update the description of the term group. But granting this policy gives the user alot of edit rights, effectively making him/her an admin.  
This is **not** ideal at all, particularly when the rest of the system has finer grained privileges for other entities. 

how to reproduce:
1. new instance, edit the "All Users - View Entity Page" policy and add all entities in the Resource Type filter, instead of a blank field. Then try visiting a term group. No permission page is encountered. Undo the changes to the policies. then step(2)
2. grant a user "glossary term" edit rights (all privileges) and the glossary platform privilege. The user is able to edit term description, but unable to edit the description of term group.

Lastly, I would like to request that glossary term/term group ownership be automatically assigned to the person who created, this would allow me to grant exclusive edit rights to "owner" of the asset. Right now I can't do that as there is no owner automatically assigned, hence a site admin must add the user as owner. (I want to implement policies that restrict ownership edit rights to owners only) It can be standardized as the same as tags, whoever who created tag is the owner of the tag.

**Comment by jjoyce0510** [comment]
Thanks for reporting @xiphl - We are looking to address this soon.

**Comment by xiphl** [comment]
Thanks Chris! Closing the issue

**Comment by xiphl** [comment]
Any thoughts about making the glossary creator the owner as well? This would help me alot with my policies as I give alot of privileges to owners, and I don't want the admin to have to do extra work to assign ownership.

**Comment by chriscollins3456** [comment]
@xiphl yup! this is on our roadmap and something I'm planning on tackling hopefully in the next week or two. Since this is net new functionality would you mind if we close this issue? we could open a feature request but this should be dealt with soon anyways.

**Comment by xiphl** [comment]
Sure!
