### ISSUE TITLE
Docker Quickstart - Pulling datahub-actions in error

### ISSUE THREAD

**Issue by matwalk** [datahub-project/datahub#5686]
Hi!
I have this error message when I launch quickstart command.
`datahub docker quickstart`
(I launched it yesterday without any problem)

It seems related to the image pull of datahub-actions:

`ERROR: for datahub-actions  failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/8e4a978b78ea7e210f5feb6cc5d864ca03ed1cc652bde6a0a6e0772fb1ab71b2/merged: too many levels of symbolic links
ERROR: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/8e4a978b78ea7e210f5feb6cc5d864ca03ed1cc652bde6a0a6e0772fb1ab71b2/merged: too many levels of symbolic links
Error while pulling images. Going to attempt to move on to docker-compose up assuming the images have been built locally`

![image](https://user-images.githubusercontent.com/46995425/185615985-58aa855f-9c1b-47af-b615-ea4f4aa4b54f.png)

Thank you for your help!

**Comment by matwalk** [comment]
If I try to change in the docker-compose quickstart file, the tag of datahub-actions image (acryldata/datahub-actions:v.0.0.5). It works, so maybe there's a problem with the new version of the image.

**Comment by anshbansal** [comment]
@matwalk 
- Can you please confirm if this is working for you now with latest CLI versions? 
- If not working even now, can you please share the environment details? Which OS? What version? 
- Can you provide output of these commands
```
python -c "import platform; print(platform.platform())"
python -c "import sys; print(sys.version); print(sys.executable); import datahub; print(datahub.__file__); print(datahub.__version__);"
```
- Can you provide the output of
```
docker ps -a
```
