### ISSUE TITLE
List of UI actions that do not capture user identity inside MySQL

### ISSUE THREAD

**Issue by xiphl** [datahub-project/datahub#5715]
Currently, if a user made an UI edit inside the Datahub UI, I can see a new aspect being persisted to MySQL. In the field `createdby`, I could see the urn of the user who made the change. 
However, there are some actions which bafflingly shows the default UNKNOWN_ACTOR identity. We are hoping to use MySQL as a source of truth to see the edits done inside Datahub. The list below is what we found that do not log the identity and uses UNKNOWN_ACTOR:

1. Create Glossary Node/Term via UI 
2. create domain in UI
3. add/edit/deactivate policies
4. edit dataset description (This is pretty critical for us as editing description is a common usecase, and we're trying to see how to patch it. Any advice is appreciated)
5. create new tag (though, the tag has an aspect `ownership` which shows the person who created it)

In addition,
All hard delete actions (glossary terms, nodes, domains, policies) will result in records being dropped and we do not know who did it.

**Comment by jjoyce0510** [comment]
@xiphl Thank you for reporting this! We are working internally to prioritize auditing these cases. 

Hard delete actions will result in records being dropped, yes. Is the desire to have this event logged in kafka?

**Comment by xiphl** [comment]
For hard deletes, I would prefer that the records be stored on another table inside the datahub schema, that way I only need to refer to MySQL to see what happens. Also, I could still copy records back to the main table if necessary. Does that make sense?

**Comment by xiphl** [comment]
Ie the deleted record table would have 2 more fields to capture the delete time and the user who deleted it. Retention of records can be decided by the DB admin, to prune by date or something

**Comment by xiphl** [comment]
hi @jjoyce0510 when we merged latest changes recently (previously running on early Jun 2022 code), we noticed that the behavior for "creating new tags" have changed. Now, new tags created in UI _do not have an owner automatically assigned_. Is this a deliberate change? (The changes came from one of the Batch Actions PR)
Because, I currently have policies that only allow tag owners to edit their own tags and add additional owners to the tag. Now, if I were to update my instance, I will end up having to manually assign owners to new tags.

**Comment by chriscollins3456** [comment]
hey @xiphl! we just addressed this issue where we weren't properly setting `createdby` on changes properly. I just confirmed that all of the actions you listed above are now setting `createdby` properly so that should be settled now (PR just got merged this morning: https://github.com/datahub-project/datahub/pull/5788)

We also addressed the situation where users creating tags were not longer being added as an owner, also merged in this morning: https://github.com/datahub-project/datahub/pull/5787

**Comment by xiphl** [comment]
Nice! I will check and verify later this week, thanks!

**Comment by xiphl** [comment]
tested and verified, thanks!
