### ISSUE TITLE
"View in Looker/Dbt" should be renamed "View in GitHub/GitLab/..." in the UI

### ISSUE THREAD

**Issue by remisalmon** [datahub-project/datahub#5723]
**Describe the bug**

The "View in Looker ->" URL in the UI when looking at Looker entities with a `github_info` configured should be instead "View in GitHub" (or GitLab or whatever service is configured), since that URL redirects to the github.com page of the entity definition.

The same goes for any source with `github_info` is configured (see https://datahubproject.io/docs/generated/ingestion/sources/looker for Looker configuration).

**To Reproduce**
1. Setup a lookml or dbt source and configure `github_info`
2. Open a lookml or dbt entity in the UI

**Expected behavior**

"View in {platform_name}" should be renamed to ""View in {git_platform_name}".
Ideally `github_info` should be renamed `git_info` in the source config and `git_platform_name` should be pulled from `git_info.base_url` in the source config (`.*github.*` as `GitHub`, `.*gitlab.*` as `GitLab`, etc.).

**Screenshots**

Both "View in ..." links in those screenshots open github.com:

![image](https://user-images.githubusercontent.com/26257211/186512566-94549d99-3a0d-406a-8bca-dc853ff5729c.png)

![image](https://user-images.githubusercontent.com/26257211/186512608-d150016a-38c4-492c-ade9-45f5444d25ed.png)

**Comment by aditya-radhakrishnan** [comment]
Thanks for reporting this issue, I will take a look and follow up with you on next steps!
