### ISSUE TITLE
Ingestion status not change when job finished

### ISSUE THREAD

**Issue by thiennguyen-waf** [datahub-project/datahub#5754]
**Describe the bug**
Ingestion status not update after job finished when ingestion on Oracle DB
**To Reproduce**
1. Go to 'manage ingestion'
2. Click on 'create new source'
3. Fill config to Oracle DB
4. Save and run ingestion and wait process

**Expected behavior**
After process ingestion done then update status of process succeeded or fail
![Screenshot from 2022-08-29 11-48-01](https://user-images.githubusercontent.com/110364833/187325805-cb01608f-d55a-4045-b5a0-5d1559efec6c.png)
![Screenshot from 2022-08-29 11-47-28](https://user-images.githubusercontent.com/110364833/187325808-b0af6bee-78f0-4b0e-9264-7a20c3c3e53e.png)

**Comment by hieunt-itfoss** [comment]
@thiennguyen-waf it would be helpful if you upload the screenshot of the ingestion job.

**Comment by jjoyce0510** [comment]
I believe this is a bug that was recently fixed.

Can you report which version of the `datahub-actions` container you are using?

**Comment by thiennguyen-waf** [comment]
i run docker for datahub version 0.8.44 , name : datahub_datahub-actions_1

**Comment by aditya-radhakrishnan** [comment]
This has been confirmed as fixed as of the latest release. If you're still seeing the issue on the latest version, please let us know! Closing out for now.

**Comment by thiennguyen-waf** [comment]
Thanks team. after update version this issue have been fix.
