### ISSUE TITLE
(Changed system behavior) Tag ownership not automatically assigned in UI anymore

### ISSUE THREAD

**Issue by xiphl** [datahub-project/datahub#5782]
**Describe the bug**
in the past when you create a tag via UI, the tag is owned by the user automatically. Sometime between June 2022 and now, the behavior has changed such that it no longer has ownership assigned.

**To Reproduce**
1. go to demo site, add new tag (that does not exist)
2. click on tag page for the new tag

**Expected behavior**
Tag owner should list user who created it.

**Comment by jjoyce0510** [comment]
Resolved by a recent PR: https://github.com/datahub-project/datahub/pull/5787
