### ISSUE TITLE
Trino queries wrong table for table properties when underlying connector isn't hive

### ISSUE THREAD

**Issue by hsheth2** [datahub-project/datahub#5790]
Our current code queries the `<table>$properties` to get info about the table. However, this special table is only available when the underlying connector is hive, as per docs https://trino.io/docs/current/connector/hive.html#special-tables. 

The correct behavior would be aligned with the default Trino get_table_comment behavior if it fails (https://github.com/trinodb/trino-python-client/blob/cffd2b232d9298321c34430f0ac829f6b6ebea8f/trino/sqlalchemy/dialect.py#L266)

We could either:
1. Determine the underlying connector type and use the appropriate query. Knowing the underlying connector type would be useful for Trino anyways, so it might be worthwhile doing. 
2. Attempt the $properties query first, and fall back to the built-in trino one if it fails.

Slack thread: https://datahubspace.slack.com/archives/CUMUWQU66/p1661965447018999?thread_ts=1661782187.583279&cid=CUMUWQU66

**Comment by hsheth2** [comment]
As per https://datahubspace.slack.com/archives/CUMUWQU66/p1662360515824649?thread_ts=1661782187.583279&cid=CUMUWQU66, it seems this issue happens with Trino 0.315.0 but not with Trino 0.314.0

**Comment by IceS2** [comment]
I feel being able to do both 1 and 2 would be amazing.
Have a specific behavior per underlying connector and fallback to the built-in if it fails.
