### ISSUE TITLE
airflow datahub integration. Authentication chain failed to resolve a valid authentication

### ISSUE THREAD

**Issue by wwwvikas123** [datahub-project/datahub#5852]
The problem with airflow datahub integration. Datahub set as linage backend for Airflow. DAG works, but it shows an error sometimes. Thanks in advance. 
METADATA_SERVICE_AUTH_ENABLED is true.  We use token to access GMS.
Airflow log
![image](https://user-images.githubusercontent.com/85458456/188879095-501057df-ded2-4c9d-a028-1f765f6eea43.png)
Datahub log
![image](https://user-images.githubusercontent.com/85458456/188879229-292a8611-64a1-4fcf-88a7-540cd16dd63d.png)

Connection in Airflow
![image](https://user-images.githubusercontent.com/85458456/188879317-493c8905-b431-4c61-a7db-470977b84f6e.png)

**Comment by zsdyx** [comment]
airflow configuration token (token==password)

**Comment by wwwvikas123** [comment]
> airflow configuration token (token==password)

Hi. we use token. it is just hidden in " Edit connection" window. Or you mean another token ? Could you, please, give details ?
I want to add, that connection works mostly, but sometimes it fails. Screenshot shows it.
![image](https://user-images.githubusercontent.com/85458456/189294783-ddb1b844-70e4-4ee3-902b-4e10ee7ec4a9.png)

**Comment by wwwvikas123** [comment]
> 

Tested it with v8.8.40.

**Comment by hsheth2** [comment]
@wwwvikas123 could you try upgrading to the latest acryl-datahub (v0.9.3.2) and DataHub version (v0.9.3) and let us know if this problem is still present?

I'm going to close it for now, and we can re-open if the problem persists.
