### ISSUE TITLE
Frontend failed to publish after modifying the code，i can't find the error prompt code in the project

### ISSUE THREAD

**Issue by iosMental** [datahub-project/datahub#5881]
hi,team,when i deploy front-end, it prompts ,but i could't found the file  [SchemaFieldBlameMapper] in datahub-graphql-core. it only exisit SchemaBlameMapper,SchemaVersionListMapper
Compiling with toolchain '/usr/lib/jvm/java-1.8-openjdk'.
Compiling with JDK Java compiler API.
[91m/datahub-src/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaFieldBlameMapper.java:45: error: cannot find symbol
    result.setLatestVersion(
          ^
  symbol:   method setLatestVersion(SemanticVersionStruct)
  location: variable result of type GetSchemaBlameResult
/datahub-src/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/timeline/mappers/SchemaFieldBlameMapper.java:118: error: cannot find symbol
    result.setSemanticVersionList(semanticVersionStructList);
          ^
  symbol:   method setSemanticVersionList(List<SemanticVersionStruct>)
  location: variable result of type GetSchemaBlameResult
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
![error](https://user-images.githubusercontent.com/10148880/189254859-0540419c-7feb-49a2-ba46-d53e9413d9f2.jpeg)

**Comment by iosMental** [comment]
I didn't report an error when I built it locally. Please help me

**Comment by aditya-radhakrishnan** [comment]
Hey @iosMental is this still an issue?

**Comment by laulpogan** [comment]
Hi @iosMental  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
