### ISSUE TITLE
dbt DataHub recipe selects incorrect schema from manifest

### ISSUE THREAD

**Issue by nggiles** [datahub-project/datahub#5955]
**Describe the bug**
The dbt DataHub recipe derives the schema from the schema field in the manifest.json produced by dbt. In some cases, the schema is overridden by a config block; however, the default schema is still passed to DataHub.

**To Reproduce**
1. Add a schema to the config of a model in dbt that is different from the default schema for the project. This can be done via the dbt_project.yml file.
2. Generate the manifest.json, catalog.json, and sources.json file by running `dbt docs generate` on your project.
3. Ingest the dbt nodes into Datahub using the dbt_recipe.yaml pointing to the dbt-generated json files

**Expected behavior**
DataHub should assign the schema name from the config block to the corresponding DataHub node.

**Screenshots**
- Sample config added in dbt_project. Note that the default schema for the project is `jaffle_shop.analytical`
![image](https://user-images.githubusercontent.com/74195677/190470941-b880c961-d952-4014-890d-28884fecf93b.png)

- Snippet from the resulting manifest.json. Note that the default schema appears in the schema field and the overridden schema (where the data actually ends up) is in the config block:
![image](https://user-images.githubusercontent.com/74195677/190472026-bd40efe7-ff5f-4963-86d5-88466da5cef1.png)

- Currently the schema in the config block is not used by the DataHub recipe

**Desktop (please complete the following information):**
- acryl-datahub==0.8.44 
- acryl-datahub[dbt]==0.8.44
- DataHub server version 0.8.44

**Comment by hsheth2** [comment]
@nggiles Given that #6207 was closed, is this issue also no longer relevant or should we keep it open?

**Comment by nggiles** [comment]
@hsheth2 Good to close. I'll do so now.
