### ISSUE TITLE
Roles are not visible

### ISSUE THREAD

**Issue by atul-chegg** [datahub-project/datahub#5966]
We are running datahub version v0.8.44 on EKS. But there are no roles visible on datahub frontend.

<img width="1722" alt="Screenshot 2022-09-16 at 5 51 40 PM" src="https://user-images.githubusercontent.com/35129543/190637763-5c8cb62a-d19a-4719-a3da-f8025aa046f0.png">

**Comment by atul-chegg** [comment]
Hi @jjoyce0510 / @aditya-radhakrishnan 
Yes this is still a problem. Please let me know if anything I can do to troubleshoot from my side.

**Comment by aditya-radhakrishnan** [comment]
Hey @atul-chegg I'm happy to jump on a call with you to debug this. Sorry for the late response - is this still an issue?

**Comment by cheyuriy** [comment]
The same mistake with fresh 0.14.1 @aditya-radhakrishnan
