### ISSUE TITLE
OIDC Callback handling throws error if token is too big

### ISSUE THREAD

**Issue by mattbonnell** [datahub-project/datahub#5971]
**Describe the bug**
I have two instances of DataHub, prod and staging, which are configured identically.
The OIDC callback was throwing an error only for the prod one, with
```
ERROR auth.sso.oidc.OidcCallbackLogic - Unable to renew the session. The session store may not support this feature
```
Nothing relevant in the debug logs.
The user would see an error page. However, if you manually returned to the DataHub home page, you would be signed in. So the OIDC flow was working, and it seemed this error was being thrown after-the fact.

In investigating this, it turned out that the OIDC client for the prod instance was configured to include more claims than the staging one. Once these extra claims were disabled, the errors went away. So it seems like the error occurs when the token is past a certain size.

**To Reproduce**
1. Create an OIDC client with some provider, configured to include only the minimal claims
2. Spin up a DataHub instance configured to use this OIDC client
3. Validate that the OIDC auth flow works.
4. Now return to your OIDC provider and add, say, 10 extra claims
5. Try logging in again
6. In my case, it fails here.

**Expected behavior**
It shouldn't fail if there are some extra claims

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.2.1
 - Browser: Chrome
 - Version: Version 105.0.5195.125 (Official Build) (arm64)

**Comment by xiphl** [comment]
https://github.com/datahub-project/datahub/pull/5114

**Comment by mattbonnell** [comment]
> #5114

Looks like a fix went in v0.8.43, but I’m still getting this in v0.8.44

**Comment by berndlunghamer** [comment]
Deployed v0.8.45, this issue is still present with azure activte directory OIDC.

Workaround: 
- do not request the profile scope as this will increast the session cookie, 
- reconfigure oidc to use a claim which in openid or email scopes, in this case I used the email claim

Environment set:
AUTH_OIDC_SCOPE=openid email 
AUTH_OIDC_USER_NAME_CLAIM=email

**Comment by xiphl** [comment]
@mattbonnell can I check if you have set PAC4J_SESSIONSTORE_PROVIDER as "PlayCacheSessionStore"? Is it still not working for you?
(from not a datahub dev)

**Comment by mattbonnell** [comment]
> @mattbonnell can I check if you have set PAC4J_SESSIONSTORE_PROVIDER as "PlayCacheSessionStore"? Is it still not working for you?
> (from not a datahub dev)

Sorry, missed this. I’ve worked around it in a similar way to @berndlunghamer

**Comment by jjoyce0510** [comment]
This should be addressed in this PR: https://github.com/datahub-project/datahub/pull/6260 which is released as of v0.9.1!

We have removed the profile from the session cookie so this should not happen...

**Comment by jjoyce0510** [comment]
Closing the ticket for now.

**Comment by ruedigerblock** [comment]
Moin !
I just updated from 10.2 to 12.1 and faced this issue.
@berndlunghamer 's solution was not sufficient but @mattbonnell 's woked like a charm ✅
