### ISSUE TITLE
Failure to delete containers (with delete references) using CLI command 'delete'

### ISSUE THREAD

**Issue by Stefs-2142** [datahub-project/datahub#5992]
Error rise when attempting delete metadata  using CLI command 'delete'
Same with all flags --soft, --hard, --force

```
Failed to execute operation
java.lang.UnsupportedOperationException: Only upsert operation is supported
```

**To Reproduce**
1. Setup Datahub CLI
2. Set env via `datahub init`
3. run `datahub delete --urn "urn:li:container:5f38c5bcfb279844c5471dd926da13e7"`

**Expected behavior**
Metadata deleted

**Desktop:**
 - OS: [e.g. Linux Mint 20.2 Uma 64-bit]

**Server:**
 - Datahub [0.8.43]

**Type of entity:**
 - Container
 
**Additional context**
[datahub-gms.log](https://github.com/datahub-project/datahub/files/9606011/datahub-gms.log)
In attach gms log with error trace

**Comment by etadelta222** [comment]
I've run into same error.

Datahub v0.8.38

**Comment by YuriyGavrilov** [comment]
also have the same problem with delete

**Comment by YuriyGavrilov** [comment]
@shirshanka any updates?

**Comment by lambertpan** [comment]
If I run datahub delete --env PROD --entity_type=dataset --hard, I get the following warning and it is unable to delete the entities. I tried this on latest v.0.10.0.
`WARNING  {datahub.cli.cli_utils:440} - Discrepancy in entities yielded 0 and num entities 589. This means all entities may not have been deleted.`

**Comment by hsheth2** [comment]
This should be fixed by some previous changes and https://github.com/datahub-project/datahub/pull/8709

**Comment by hsheth2** [comment]
So https://github.com/datahub-project/datahub/pull/8709 is merged, so I'm gonna call this one done!
