### ISSUE TITLE
mae-consumer unable to authorize to elastic

### ISSUE THREAD

**Issue by Wilderone** [datahub-project/datahub#6063]
**Describe the bug**
Got an error from mae-consumer while using kubernetes chart with linkedin/datahub-mae-consumer:v0.8.45 image
```
base64: unrecognized option: wrap
BusyBox v1.33.1 () multi-call binary.

Usage: base64 [-d] [-w COL] [FILE]

Base64 encode or decode FILE to standard output
	-d	Decode data
	-w COL	Wrap lines at COL (default 76, 0 disables)
```

**To Reproduce**
1. Deploy helm chart with inkedin/datahub-mae-consumer:v0.8.45 image
2. Add all necessary credentials
3. Watch logs

**Expected behavior**
Application is able to connect to elasticsearch

**Screenshots**
<img width="691" alt="image" src="https://user-images.githubusercontent.com/60431057/192563210-191108ff-bd25-443f-b8ad-5f63a7db4b42.png">

**Additional context**
Actually root of this problem is using alpine image, which repository do not supported properly, i suggest some previous version of base64 contains necessary keys.
So fast fix is replace `--wrap` with `-w` in start.sh script here 
https://github.com/datahub-project/datahub/blob/master/docker/datahub-mae-consumer/start.sh#L9

But better solution is to get rid of alpine image at all :)

**Comment by Wilderone** [comment]
--help of base64 in linkedin/datahub-mae-consumer:v0.8.45
<img width="460" alt="image" src="https://user-images.githubusercontent.com/60431057/192564429-b77f5025-3027-4649-9f4d-df8e21454d43.png">

**Comment by pedro93** [comment]
Hello @Wilderone

Thank you for submitting this very helpful diagnosis of the issue. There is a PR in progress to address this issue: https://github.com/datahub-project/datahub/pull/6061, could you take a look and see if it matches what you found?

**Comment by Wilderone** [comment]
Hi @pedro93 !
Yep, base64 from coreutils would fit fine, i checked it in fresh alpine image, --wrap flag present in this version
