### ISSUE TITLE
无法获取hive到hdfs的血缘

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [datahub-project/datahub#6085]
我写了一个从kafka获取数据然后落地到hive中，hive关联到hdfs的数据链路，但是使用datahub的血缘选项是灰色的，请问它是无法像apache atlas那样自动获取血缘关系么，只能是手动定义血缘关系？

**Comment by hsheth2** [comment]
Based on the google translate of your issue description, it seems like you should use file-based lineage to augment your ingestion run: https://datahubproject.io/docs/generated/ingestion/sources/file-based-lineage/.

I'm closing this issue for now, but feel free to reply or ask in slack if you have any follow-up questions.
