### ISSUE TITLE
Search / filter have Bug on version 0.8.45 

### ISSUE THREAD

**Issue by thiennguyen-waf** [datahub-project/datahub#6130]
**Describe the bug**
Condition filter was clear and not apply for next step of filter

**To Reproduce**
1. Go to 'search page'
2. Click chose some condition filter (ex: platform mysql )
3. Click on some result or search for go to next step ( ex: chose a schema )
4. On next screen the result show data error ( ex Oracle), and condition chose on before was clear ( then condition query not apply => wrong result query) 

**Expected behavior**
Condition filter at all step filter

**Screenshots**
![Screenshot from 2022-10-06 10-53-59](https://user-images.githubusercontent.com/110364833/194211482-37b9a395-9714-4fd5-83ab-036d78908d1f.png)

after click schema y4a_cdm then result contain table of Oracle

![Screenshot from 2022-10-06 10-55-48](https://user-images.githubusercontent.com/110364833/194211556-417ddb92-57de-4460-a7a1-91295fe829ab.png)

**Desktop 

 - Version: 0.8.45

**Comment by chriscollins3456** [comment]
@thiennguyen-waf I believe we pushed a fix for this to `head`. We are issuing a new release this week so I would suggest either pulling `head` and trying or waiting until we push a new release to solve this issue.

Let us know if you still see a problem afterwards
