### ISSUE TITLE
deploy a DataHub instance locally error

### ISSUE THREAD

**Issue by zcw5116** [datahub-project/datahub#6164]
1 python version: 3.9.5
2 datahub version
# datahub --version
acryl-datahub, version 0.8.45.2

3  run the following CLI command from my terminal, following errors printed on the screen:

# datahub docker quickstart
No Datahub Neo4j volume found, starting with elasticsearch as graph service.
To use neo4j as a graph backend, run 
`datahub docker quickstart --quickstart-compose-file ./docker/quickstart/docker-compose.quickstart.yml`
from the root of the datahub repo

Fetching docker-compose file https://raw.githubusercontent.com/datahub-project/datahub/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml from GitHub
Pulling docker images...
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var
                           and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  engine      Manage the docker engine
  image       Manage images
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

Error while pulling images. Going to attempt to move on to docker compose up assuming the images have been built locally

unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var
                           and default context set with "docker context use")

**Comment by zcw5116** [comment]
> Hello @zcw5116
> 
> You are most likely running an old version of `docker`. What is the output of `docker compose --version`? If you see an error it means you have to update your docker version. `compose` is meant to be a plugin do the `docker` cli tool.
> 
> This is a breaking change from docker where in the past you would run `docker-compose` (notice the `-`). DataHub has since migrated to the newer version and users need to update their `docker` installs. Sadly we can not automate this.

Your judgment is very correct. The Docker version is too old. I have updated the Docker. Everything is OK. Thank you very much.

**Comment by LuigiCerone** [comment]
Hello, 
I was following the [official quickstart instructions](https://datahubproject.io/docs/quickstart/) and I've this problem too. 

The instructions state that if running on linux, one should use the v1 for docker-compose. 

My configuration: 

OS:
```bash
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

Docker and docker-compose:
```bash
Docker version 20.10.20, build 9fdeb9c
docker-compose version 1.29.2, build 5becea4c
```


When I try to run `datahub docker quickstart` I get the same error written in this issue. Also, given the old (and [deprecated](https://github.com/docker/compose/blob/master/INSTALL.md)), `docker-compose` version I also get:

```bash
docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'
```

I've solved the problem by upgrading docker-compose to `Docker Compose version v2.12.0` and by following [official docker documentation](https://docs.docker.com/compose/install/linux/) where it says to install: `sudo apt-get install docker-compose-plugin`.

Is this approach correct? If so, should the docs be updated for linux?
Thanks! :)

**Comment by jiangbiao910** [comment]
> The Docker vers

Can you tell me which version for your Docker?

**Comment by laulpogan** [comment]
Docker compose has since been indicated as a prereq

**Comment by pedro93** [comment]
Hello folks,

Is anyone still having issues on deploying DataHub locally?
