### ISSUE TITLE
Validation error of type FieldUndefined:  Upgrade from v0.8.41 to v0.8.45

### ISSUE THREAD

**Issue by zsdyx** [datahub-project/datahub#6165]
**Describe the bug**
Upgrade from v0.8.41 to v0.8.45, and build an image through  “DOCKER_BUILDKIT=1 docker build --no-cache -t xavier-web -f ./docker/datahub-frontend/Dockerfile .”
Only the logo is modified, Exception occurred during deployment

**To Reproduce**
1、Download source code
2、Update logo icon and UI titile
3、DOCKER_BUILDKIT=1 docker build --no-cache -t xavier-web -f ./docker/datahub-frontend/Dockerfile .

**Expected behavior**
DOCKER_BUILDKIT=1 docker build --no-cache -t xavier-web -f ./docker/datahub-frontend/Dockerfile .”

**Screenshots**
<img width="1680" alt="截屏2022-10-11 上午8 09 59" src="https://user-images.githubusercontent.com/62527876/194970667-f0780212-3d1e-4f5b-bcf5-2fc9fb62d05c.png">

error info:
`UI error:
Validation error (FieldUndefined@[analyticsChart/rows/cells/linkParams/searchParams/filters/value]) : Field 'value' in type 'Filter' is undefined
Validation error (FieldUndefined@[listRecommendations/modules/content/params/searchParams/filters/value]) : Field 'value' in type 'Filter' is undefined (code undefined)

Fornt error:
00:53:21 [application-akka.actor.default-dispatcher-25] ERROR controllers.TrackingController - Failed to emit product analytics event. actor: urn:li:corpuser:datahub, event: {"title":"Conviva Schema Center","url":"http://xxxx/","path":"/","hash":"","search":"","width":656,"height":971,"referrer":"http://xxxx/","prevPathname":"/login","type":"PageViewEvent","actorUrn":"urn:li:corpuser:datahub","timestamp":1665276799567,"date":"Sun Oct 09 2022 08:53:19 GMT+0800 (中国标准时间)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","browserId":"96726d31-fc24-47fd-98ff-6fa14864c04e"}`

**Comment by laulpogan** [comment]
@zsdyx is this issue still ongoing in the most recent release?
