### ISSUE TITLE
Ingest S3 compressed json data without .json extension fails to generate schema

### ISSUE THREAD

**Issue by swraithel** [datahub-project/datahub#6181]
**Describe the bug**
Ingesting a compressed json file in s3 fails to extract the schema from the file is the extension is `.gz` instead of  `.json.gz`

**To Reproduce**
1) Config Script
```
source:
    type: s3
    config:
        path_specs:
        - include : "s3://MY_BUCKET/testdata/example_compressed_json.gz"
          default_extension: "json"
          sample_files : false
          enable_compression : true
        aws_config:
            aws_access_key_id: ${MY_KEY}
            aws_secret_access_key: ${MY_SECRET}
            aws_region: us-east-1
        profiling:
            enabled: false
```
2) File contents of example_compressed_json.gz:
```
{"field_1": "value_1","field_2":"value_2"}
{"field_1": "value_1","field_2":"value_2"}
{"field_1": "value_1","field_2":"value_2"}
{"field_1": "value_1","field_2":"value_2"}
{"field_1": "value_1","field_2":"value_2"}
{"field_1": "value_1","field_2":"value_2"}
{"field_1": "value_1","field_2":"value_2"}
```
3) `["could not infer schema for file s3://MY_BUCKET/testdata/example_compressed_json.gz: module 'ujson' has no attribute 'JSONDecodeError'"]`

**Expected behavior**
Using the `default_extension: JSON` should allow for json fields to be extracted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version 0.8.45

**Additional context**
Using the file locally i can reproduce bug with the following script:
```
import gzip
from smart_open import open as smart_open
from datahub.ingestion.source.schema_inference import json

file_path = 'example_compressed_json.gz'
test = json.JsonInferrer()


# gzip forced (returns fields)
file = gzip.open(file_path,'rb')
test.infer_schema(file) == []

# smart open (returns fields)
file = smart_open(file_path,mode = 'rb')
test.infer_schema(file) == []

# standard open (returns no fields)
file = open(file_path, mode = 'rb')
test.infer_schema(file) == []
```

**Comment by hsheth2** [comment]
Could you paste the output of `pip freeze` for my reference?

I've seen the error message `module 'ujson' has no attribute 'JSONDecodeError'` before with outdated versions of ujson - maybe running `pip install --upgrade ujson` would fix it?

**Comment by swraithel** [comment]
Looks like I just needed to upgrade `usjon`.

I was on 5.1.0 and upgrading to 5.5.0 fixed the ingestion issue. Thanks for the help!
