### ISSUE TITLE
In the AssertionStdAggregation enumeration the UNIQUE_PROPORTION value is misspelled as UNIQUE_PROPOTION

### ISSUE THREAD

**Issue by IanHopkinson** [datahub-project/datahub#6227]
**Describe the bug**
In the AssertionStdAggregation enumeration the UNIQUE_PROPORTION value is misspelled as UNIQUE_PROPOTION

**To Reproduce**
Look here:
https://github.com/datahub-project/datahub/blob/85268d68450330cf47ce3cd8bd157a9cec65cfea/metadata-models/src/main/pegasus/com/linkedin/assertion/AssertionStdAggregation.pdl#L45

UNIQUE_PROPOTION appears in six places around the code:
https://github.com/datahub-project/datahub/search?q=UNIQUE_PROPOTION

**Expected behavior**
I expect UNIQUE_PROPOTION to be spelt UNIQUE_PROPORTION

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
I discovered this whilst reading the code to understand how to fill the validation tab. I have not exercised this issue in live code. I appreciate this is a really trivial bug :-)

**Comment by aditya-radhakrishnan** [comment]
Thanks for pointing this one out! Unfortunately, I don't think there's an easy way to deal with this as if we migrated it now, it would break existing instances of DataHub where users have this attribute filled out in their MySQL DB.

Given this, I'm going to close this one out, but appreciate you calling it out.
