### ISSUE TITLE
Datahub v0.9.0 introduces a new feature Posts, but the GraphQL does not have deletePost

### ISSUE THREAD

**Issue by viniciusdsmello** [datahub-project/datahub#6231]
The new release [v0.9.0](https://github.com/datahub-project/datahub/releases/tag/v0.9.0) introduces a new Posts feature that allows Pinning posts to the Home page with links or announcements, but there isn't a way to delete posts added to UI.

GraphQL only has two methods to interact with posts: listPosts and createPost [1]. Due to this, posts created have to be deleted directly from the Database.

References:
1. https://github.com/datahub-project/datahub/blob/master/datahub-graphql-core/src/main/resources/entity.graphql

**Comment by PatrickfBraz** [comment]
Besides, the documentation links of the Mutations are broken: 
https://github.com/datahub-project/datahub/blob/master/docs/posts.md

**Comment by laulpogan** [comment]
While the docs links are broken in git, they work on web https://datahubproject.io/docs/posts/

**Comment by aditya-radhakrishnan** [comment]
Hey @PatrickfBraz I opened this PR to add the deletePost endpoint, thanks for calling this out https://github.com/datahub-project/datahub/pull/6813

**Comment by aditya-radhakrishnan** [comment]
Closing this out since this has been merged, thank you again for reporting this!
