### ISSUE TITLE
[FR][S3|JSON] Support "max_rows" for JSONL (multiline) files.

### ISSUE THREAD

**Issue by livelace** [datahub-project/datahub#6235]
**version**: 0.9.0

According to [docs](https://datahubproject.io/docs/generated/ingestion/sources/s3/) CSV/TSV files do support "max_rows" option.

At this moment ingesting framework loads the full body of [JSONL](https://jsonlines.org/) files, this is not efficient and time consuming.

**Comment by hieunt-itfoss** [comment]
@livelace I'm gonna take a look at it. Still consider the impact to standard JSON and JSONL.

**Comment by laulpogan** [comment]
Hi @livelace this seems to be a feature request. We currently reserve git issues for bugs. If you’d like to submit this as a feature request, please use our portal here: https://feature-requests.datahubproject.io/
