### ISSUE TITLE
Add PlatformInstance to SageMaker Source

### ISSUE THREAD

**Issue by kirillmakhonin** [datahub-project/datahub#6265]
Hello,
This is a feature request to add support of platformInstance in SageMaker importer
This is highly relevant for companies who have more then one AWS Account in same env (e.g. PROD) where they are hosting SageMaker models

MetaModel already contains platform instance information but SageMaker recipe does not support this

Ref. https://datahubproject.io/docs/generated/ingestion/sources/sagemaker
Ref. https://datahubproject.io/docs/platform-instances/

**Comment by laulpogan** [comment]
Hi @kirillmakhonin  this seems to be a feature request. We currently reserve git issues for bugs. If you’d like to submit this as a feature request, please use our portal here: [https://feature-requests.datahubproject.io/](https://feature-requests.datahubproject.io/)
