### ISSUE TITLE
QuickStart Guide doesn't work

### ISSUE THREAD

**Issue by anon-account-123** [datahub-project/datahub#6274]
**Describe the bug**
```python3 -m pip install -U datahub acryl-datahub```
```
Collecting datahub
  Using cached datahub-0.8.90dev.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting acryl-datahub
  Using cached acryl_datahub-0.9.0.3-py3-none-any.whl (1.1 MB)
Collecting pastescript>=1.0
  Using cached PasteScript-3.2.1-py2.py3-none-any.whl (73 kB)
Collecting cheetah>=2.0
  Using cached Cheetah-2.4.4.tar.gz (190 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-naamg059/cheetah_fadb6abb11cd463ab55fc5787054feee/setup.py", line 10, in <module>
          import SetupTools
        File "/tmp/pip-install-naamg059/cheetah_fadb6abb11cd463ab55fc5787054feee/SetupTools.py", line 50
          except DistutilsPlatformError, x:
                                       ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**
1. Spin up an EC2 instance with Ubuntu 18.0.4 installed
2. Install python3.8
3. Set python3 to alias python3.8 in ~/.bash_profile
4. Install docker, jq, docker-compose
5. Run `python3 -m pip install --upgrade pip wheel setuptools`

**Expected behavior**
Supposed to install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser NA
 - Version18.0.4

**Additional context**
The error mentions Cheetah-2.4.4 which requires python2.7. However this is not mentioned as a dependency in Datahub's install instructions. Python2.7 was installed on the machine and the default `python` was set to alias `python2.7`, and setuptools was installed for it as well, but I still run into this error.

**Comment by xiphl** [comment]
Why are you installing package "datahub"? It is causing the bug. The project only uses acryl-datahub, and datahub is not maintained by it.

**Comment by anon-account-123** [comment]
Thanks, I must have mixed up the install instructions in the back and forth. It looks like it's installed, but I'm getting the following error when I try to run `python3 -m datahub docker quickstart`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datahub/__main__.py", line 1, in <module>
    from datahub.entrypoints import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datahub/entrypoints.py", line 13, in <module>
    from datahub.cli.delete_cli import delete
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datahub/cli/delete_cli.py", line 123, in <module>
    type=click.DateTime(),
AttributeError: module 'click' has no attribute 'DateTime'
```

**Comment by xiphl** [comment]
https://datahubspace.slack.com/archives/C029A3M079U/p1666719988650269?thread_ts=1666719988.650269&cid=C029A3M079U someone posted something similar.
I'll recommend going on datahub slack to troubleshoot.
