### ISSUE TITLE
datahub inpute clickhouse 21.4.4.30 metadata, query sql include 'comment' column

### ISSUE THREAD

**Issue by 1149608162** [datahub-project/datahub#6275]
datahub inpute clickhouse 21.4.4.30 metadata, query sql include 'comment' column

1、edit clickhouse dhub yaml file
2、execute metadata absorb
3、metadata absorb fail
4、err log
clickhouse_sqlalchemy.exceptions.DatabaseException: Orig exception: Code: 47, e.displayText() = DB::Exception: Missing columns: 'comment' while processing query: 'SELECT database, name AS table_name, comment, formatRow('JSONEachRow', engine, partition_key, sorting_key, primary_key, sampling_key, storage_policy, metadata_modification_time, total_rows, total_bytes, data_paths, metadata_path) AS properties FROM system.tables WHERE name NOT LIKE '.inner%'', required columns: 'comment' 'primary_key' 'engine' 'data_paths' 'name' 'metadata_modification_time' 'metadata_path' 'partition_key' 'sampling_key' 'storage_policy' 'total_bytes' 'sorting_key' 'database' 'total_rows', maybe you meant: ['name'] (version 21.4.4.30 (official build))

**Comment by 1149608162** [comment]
edit 'site-packages/datahub/ingestion/source/sql/clickhouse.py'  file 166 line, empty string as comment, avoid the question

**Comment by laulpogan** [comment]
Hi @1149608162 are you still experiencing this issue? Or is it a feature request? I'm not very clear from your comments

**Comment by victorsheng** [comment]
Implement table comments. Closes [#23225](https://github.com/ClickHouse/ClickHouse/issues/23225). [#23548](https://github.com/ClickHouse/ClickHouse/pull/23548) ([flynn](https://github.com/ucasFL)).
[ClickHouse release 21.6, 2021-06-05](https://clickhouse.com/docs/en/whats-new/changelog/2021/#clickhouse-release-216-2021-06-05)

According to the clickhouse release records,system.table has comment fields in 21.6, 2021-06-05.
Less than that version of clickhouse instance, datahub clickhouse ingestion will fail.

**Comment by victorsheng** [comment]
I met the same problems .clickhouse  version: 20.9.2.20 
DESCRIBE TABLE system.tables

┌─name───────────────────────┬─type─────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ database                   │ String           │              │                    │         │                  │                │
│ name                       │ String           │              │                    │         │                  │                │
│ uuid                       │ UUID             │              │                    │         │                  │                │
│ engine                     │ String           │              │                    │         │                  │                │
│ is_temporary               │ UInt8            │              │                    │         │                  │                │
│ data_paths                 │ Array(String)    │              │                    │         │                  │                │
│ metadata_path              │ String           │              │                    │         │                  │                │
│ metadata_modification_time │ DateTime         │              │                    │         │                  │                │
│ dependencies_database      │ Array(String)    │              │                    │         │                  │                │
│ dependencies_table         │ Array(String)    │              │                    │         │                  │                │
│ create_table_query         │ String           │              │                    │         │                  │                │
│ engine_full                │ String           │              │                    │         │                  │                │
│ partition_key              │ String           │              │                    │         │                  │                │
│ sorting_key                │ String           │              │                    │         │                  │                │
│ primary_key                │ String           │              │                    │         │                  │                │
│ sampling_key               │ String           │              │                    │         │                  │                │
│ storage_policy             │ String           │              │                    │         │                  │                │
│ total_rows                 │ Nullable(UInt64) │              │                    │         │                  │                │
│ total_bytes                │ Nullable(UInt64) │              │                    │         │                  │                │
│ lifetime_rows              │ Nullable(UInt64) │              │                    │         │                  │                │
│ lifetime_bytes             │ Nullable(UInt64) │              │                    │         │                  │                │
└────────────────────────────┴──────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
