### ISSUE TITLE
Strange property transformer behavior

### ISSUE THREAD

**Issue by jamesrobsn** [datahub-project/datahub#6277]
**Describe the bug**
When a property transformer is added in a recipe with ~3 or more other transformers, the properties do not get applied to the dataset.

- If I try to add all 5 other transformers at one time, it DOES NOT WORK
- If I add it by itself, it WORKS
- If I add it first, by itself, then add the other 4 transformers after that and process again, it WORKS
- If I add all 5 transformers to start, then remove them one-by-one, with just two other transformers remaining, it WORKS

**To Reproduce**
1. Create an S3 ingestion pipeline
2. Add the following transformers (see attachment for example): simple_add_dataset_properties, simple_add_dataset_tags, simple_add_dataset_terms, simple_add_dataset_domain, simple_add_dataset_ownership
3. Check a dataset ingested from S3 to see if the transformers were applied properly

**Expected behavior**
I would expect the transformers to all be applied, regardless of how many are added to the recipe

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 16.0
 - DataHub Version: 0.9.0

**Additional context**
[s3_recipe_example.txt](https://github.com/datahub-project/datahub/files/9862220/s3_recipe_example.txt)

**Comment by hsheth2** [comment]
When you say works/doesn't work, that just means that the properties aren't added? In all cases, the ingestion run completes without printing any errors?

**Comment by jamesrobsn** [comment]
Sorry for the lack of clarity. The ingestion pipeline executes successfully in each scenario. The 'works' or 'does not work' refers to whether the properties are successfully applied to the datasets or not.

**Comment by hsheth2** [comment]
We've recently made some fixes to the properties transformer - could you test with acryl-datahub v0.9.2.2 and let me know if it works?

**Comment by laulpogan** [comment]
Hi @jamesrobsn, were you able to test? Otherwise I'll go ahead and close this issue.

**Comment by jamesrobsn** [comment]
Hello, I had a chance to test on 0.9.3.2 and it looks like the issue is resolved. Thank you for you patience!
