### ISSUE TITLE
Airflow-Datahub image version

### ISSUE THREAD

**Issue by ZipBomb** [datahub-project/datahub#6299]
Hi! Would it be possible to update the Airflow-Datahub image available in [Dockerhub](https://hub.docker.com/layers/acryldata/airflow-datahub/latest/images/sha256-9f9086adf9e6c528ddf53db538da3dce83dce84edd4fdb304bc6816ccc842810?context=explore) so it uses one of the latest 0.9.x versions of the python package?

Thanks in advance.

**Comment by ZipBomb** [comment]
For those of you interested in this, just use the following Dockerfile:

```
FROM apache/airflow:2.2.5-python3.8

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade acryl-datahub==0.9.0.4
RUN python3 -m pip install --upgrade acryl-datahub[snowflake]==0.9.0.4
```

The docker-compose.yaml file from the [docs](https://datahubproject.io/docs/docker/airflow/local_airflow/#step-1-set-up-your-airflow-area) will keep working with these image while you'll still get the latest ingestion version.

**Comment by laulpogan** [comment]
Hi @ZipBomb, is this problem still active in the most recent release?
