### ISSUE TITLE
Env ignored when ingesting metadata from a unity catalog

### ISSUE THREAD

**Issue by ms32035** [datahub-project/datahub#6326]
**Describe the bug**
When ingesting the metadata from the new unity-catalog source, env is always set to PROD as it is not passed to the underlying urn generation methods. Otherwise, thanks for the great work on databricks ingestion

**To Reproduce**
1. ingest any databricks metadata via the cli

**Expected behavior**
Correct env value

**Comment by laulpogan** [comment]
Hi, it seems that you resolved this in the PR, I'm going to close it for now. Thanks!
