### ISSUE TITLE
Soft deleted entity ML Model still appears in the UI

### ISSUE THREAD

**Issue by jazzblue** [datahub-project/datahub#6328]
**Describe the bug**
After soft deleting mlModel entity still appears on UI despite what the docs say [here](https://datahubproject.io/docs/metadata-service/#soft-deleting-an-entity).

**To Reproduce**
1. Follow [these](https://datahubproject.io/docs/quickstart/) instructions to spin up Datahub locally (`quickstart`) and install Python dependencies.
2. Run the following Python code to create ml modelGroup, mlModel and then soft delete that mlModel:
```python
import datahub.metadata.schema_classes as models
import datahub.emitter.mce_builder as builder
from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.emitter.rest_emitter import DatahubRestEmitter


rest_emitter = DatahubRestEmitter(gms_server="http://localhost:8080")

model_group_urn = builder.make_ml_model_group_urn(
    platform="myplatform", group_name="mymodelgroup", env="PROD"
)


model_urn = builder.make_ml_model_urn(
    platform="myplatform", model_name="mymodel", env="PROD"
)

# Create model group
metadata_change_proposal = MetadataChangeProposalWrapper(
    entityType="mlModelGroup",
    changeType=models.ChangeTypeClass.UPSERT,
    entityUrn=model_group_urn,
    aspectName="mlModelGroupProperties",
    aspect=models.MLModelGroupPropertiesClass(
        description="My model Group",
    ),
)
rest_emitter.emit_mcp(metadata_change_proposal)

# Create model
metadata_change_proposal = MetadataChangeProposalWrapper(
    entityType="mlModel",
    changeType=models.ChangeTypeClass.UPSERT,
    entityUrn=model_urn,
    aspectName="mlModelProperties",
    aspect=models.MLModelPropertiesClass(
        description="My model", groups=[model_group_urn]
    ),
)
rest_emitter.emit_mcp(metadata_change_proposal)

# Delete model
metadata_change_proposal = MetadataChangeProposalWrapper(
    entityType="mlModel",
    changeType=models.ChangeTypeClass.UPSERT,
    entityUrn=model_urn,
    aspectName="status",
    aspect=models.StatusClass(removed=True),
)
rest_emitter.emit_mcp(metadata_change_proposal)
```
3. Navigate to the UI: http://localhost:9002/
4. Drill down: ML Groups -> mymodelgroup
5. You will see that the ML model we soft deleted above is still shown in the UI.

**Expected behavior**
The above soft deleted  ML model should not be shown in the UI.

**Screenshots**
![Screen Shot 2022-11-01 at 11 51 51 AM](https://user-images.githubusercontent.com/7321986/199277426-d4784b4e-d434-445c-a24c-768daea379f3.png)

**Comment by aditya-radhakrishnan** [comment]
Hey @jazzblue sorry for the delayed response here. Were you able to verify that the entity was indeed soft deleted in the database?

**Comment by aditya-radhakrishnan** [comment]
Ah it looks like we don't support the `status` aspect on MLModels, thanks for the catch. Let me talk to my colleagues and get back to you on what next steps are!

**Comment by aditya-radhakrishnan** [comment]
Hey @jazzblue so I realized that our docs are misleading. Soft deletion only means that an entity won't show up in Search or Browse, but its entity page will still be viewable. I created this PR to make that clear https://github.com/datahub-project/datahub/pull/7117

That said, supporting soft deletion for ML models is a different matter, and I will get back to you soon on this!

**Comment by aditya-radhakrishnan** [comment]
It actually looks like we do support soft deletion for ML models via the legacy snapshot aspects, as shown here https://github.com/datahub-project/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/metadata/aspect/MLModelAspect.pdl

Given this, I'm going to close this one out!

**Comment by jazzblue** [comment]
> Hey @jazzblue so I realized that our docs are misleading. Soft deletion only means that an entity won't show up in Search or Browse, but its entity page will still be viewable. I created this PR to make that clear #7117
> 
> That said, supporting soft deletion for ML models is a different matter, and I will get back to you soon on this!

I would disagree, soft deleted is deleted and should not show up in the UI. The meaning of soft is that it can be restored, but while it is in soft deleted state it is deleted as far as any user whether API or UI. This should be fixed. I will reopen this issue.
