### ISSUE TITLE
SageMaker processing job details does not have "ProcessingInputs" key

### ISSUE THREAD

**Issue by kevinnowland** [datahub-project/datahub#6360]
**Describe the bug**

In this line: https://github.com/datahub-project/datahub/blob/a9ad13817290331ac107f00b73c7916107d63376/metadata-ingestion/src/datahub/ingestion/source/aws/sagemaker_processors/jobs.py#L770.

I have a job that when calling the DescribeProcessingJob endpoint under the SageMaker API that does not have this key in the response.

This line should maybe be something like `job.get("ProcessingInputs", [])`

**To Reproduce**
1. Calling the DescribeProcessingJob API with any processing job that has no inputs and verify that this behavior is possible.

**Expected behavior**

I expect the ingestion to not fail if there is no such field in the response.

**Screenshots**

<img width="1715" alt="Screen Shot 2022-11-03 at 2 38 32 PM" src="https://user-images.githubusercontent.com/6806753/199806939-105d6a88-a94e-4efe-8630-7f08a7cff3e7.png">

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome
 - Version 0.9.1

**Additional context**

**Comment by hsheth2** [comment]
@kevinnowland thanks for the bug report - this will be fixed by https://github.com/datahub-project/datahub/pull/6697
