### ISSUE TITLE
Impossible to create an aspect DataJobInfo using the REST API

### ISSUE THREAD

**Issue by nmolinier** [datahub-project/datahub#6361]
**Describe the bug**
It seems that the type information cannot be set which blocks the creation of the object

**To Reproduce**
I get either a 500: "org.springframework.web.client.HttpClientErrorException$UnprocessableEntity: 422 Failed to validate record with class com.linkedin.datajob.DataJobInfo: ERROR :: /type :: union type is not backed by a DataMap or null.

```
[
    {
        "aspect": {
            "__type": "DataJobInfo",
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": "OTHERS"
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]
```

or a 400 Bad request

```
[
    {
        "aspect": {
            "__type": "DataJobInfo",
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": {"string": "test"}
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]

[
    {
        "aspect": {
            "__type": "DataJobInfo",
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": {"AzkabanJobType": "COMMAND"}
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]
```

This was tested on datahub demo environment this day.

**Expected behavior**
I would like to create a DataJobInfo in order to set custom properties.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Version [/openapi/v3/api-docs -- v0.8.40]

**Additional context**
Seems similar to anomaly: https://github.com/datahub-project/datahub/issues/4289

**Comment by yagatipavani** [comment]
I suspect that issue is due to the aspect that you were setting, use **DataJobProperties** instead as **DataJobInfo** deprecated.

[
    {
        "aspect": {
            **"__type": "DataJobProperties"**,
            "name": "ingest",
			"description": "ingest data from src-ext_SFTP_test-jmc-02 into s3://ce00/test-perf-nifi",
			"type": {"string": "test"}
        },
        "entityType": "dataJob",
        "entityUrn": "urn:li:dataJob:(urn:li:dataFlow:(urn:li:dataPlatform:nifi-zds1,test-jmc-02--to--myBucket,PROD),ingest)"
    }
]

Please go through this class for reference [com.linkedin.datahub.graphql.generated.DataJobInfo](https://github.com/linkedin/datahub/blob/77a27359f2fdddacb537b5a79fa46bea24bd2e0a/datahub-graphql-core/src/main/resources/entity.graphql#L3861)

**Comment by nmolinier** [comment]
Tanks for your reply.

Type: DataJobProperties didn't work. "EditableDataJobProperties" does, but I couldn't pass any "customProperties" attributes (or name). It should if I look at the java class you gave me...

Still, I managed to leave a comment. 
Lineage vizualisation is not too nice, as I can't see the job title, and i really need custom attributes on this object.

Thanks for the tips though.

I didn't start using graphQL API (only openAPI). I'l try that next, but still, it would have been simpler for me to keep using openAPI.

**Comment by nmolinier** [comment]
I didn't get anychance with graphiQL interface.

Only the comment can be updated.

**Comment by laulpogan** [comment]
Hi @nmolinier  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs. If you’d like to submit this as a feature request, please use our portal here: [https://feature-requests.datahubproject.io/](https://feature-requests.datahubproject.io/)

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.

**Comment by nmolinier** [comment]
Hi @laulpogan ,
I don't understand how this can be seen as something else but a bug or a regression. As of today, neither openApi nor graphQlApi accessible through the solution allow the capability to set custom properties on datajob anymore.

Could you please reopen and try to reproduce the bug. Do I need to provide additional inputs ?

**Comment by Jorricks** [comment]
As a note for whomever comes across this;
I use the restl api
```
import json

import requests

data = {
    "proposal" : {
        "entityType": "dataJob",
        "entityUrn" : "urn:li:dataJob:(urn:li:dataFlow:(spark,airflow-sandbox.delta_fake_partitioned_data_daily_and_hourly,airflow-sandbox),airflow-sandbox.delta_fake_partitioned_data_daily_and_hourly)",
        "changeType" : "UPSERT",
        "aspectName" : "dataJobInfo",
        "aspect" : {
            "value" : json.dumps(
                {
                    # '__type': 'DataJobInfo',
                    'created': {'time': 1747896479883},
                    'customProperties': {
                        'processingEngine': 'spark',
                        'processingEngineVersion': '3.5.1',
                        'spark.app.name': 'delta_fake_partitioned_data_daily_and_hourly_deltafakedailypartition__deltafakehourlypartition_2025-05-20T22:00:00+00:00',
                        'spark.master': 'yarn'
                    },
                    'externalUrl': 'https://my-domain-airflow.com/dags/delta_fake_partitioned_data_daily_and_hourly/grid?task_id=deltafakedailypartition__deltafakehourlypartition',
                    'flowUrn': 'urn:li:dataFlow:(spark,airflow-sandbox.delta_fake_partitioned_data_daily_and_hourly,airflow-sandbox)',
                    'name': 'airflow-sandbox.delta_fake_partitioned_data_daily_and_hourly',
                    'type': {
                        "com.linkedin.datajob.azkaban.AzkabanJobType": "COMMAND"
                    }
                }
            ),
            "contentType": "application/json"
        }
    }
}

result = requests.post(
    "https://my_domain.com/aspects?action=ingestProposal",
    json=data,
    timeout=5,
)
print(result.text)
```
