### ISSUE TITLE
The downstream cannot see the upstream when the platform is nifi

### ISSUE THREAD

**Issue by Vincenthy1205** [datahub-project/datahub#6406]
**Describe the bug**
The downstream cannot see the upstream when the platform is nifi.

**To Reproduce**
1. Set up a group at nifi.
2. Create four processors in the group.
3. Write the configuration file for the datahub to ingest metadata and run it.
4. Enter Datahub and select nifi platform. Click upstream to see the downstream, but click downstream to not see the upstream

**Expected behavior**
Click downstream to see the upstream relationship.

**Screenshots**
![image](https://user-images.githubusercontent.com/49978079/201250051-5db3fa84-ff01-4e85-97eb-529f7a3db8d2.png)
![image](https://user-images.githubusercontent.com/49978079/201250204-713b1925-1f4a-4b68-ae9d-e03cd2040d93.png)
![image](https://user-images.githubusercontent.com/49978079/201250256-69e6e93a-277d-434c-9b0d-6f3063b5b0a0.png)

**Desktop (please complete the following information):**
 - OS: Winodws10
 - Browser: chrome
 - Version: 107.0.5304.106

**Service**
- DataHub version: 0.8.45
- Python version: 3.8.10
- Nifi version: 1.17.0

**Comment by aditya-radhakrishnan** [comment]
Hi @Vincenthy1205 are you sure that lineage aspects were ingested?

**Comment by aditya-radhakrishnan** [comment]
Hey @Vincenthy1205 I'm going to close this one out since we haven't heard back, but please feel free to reopen if this is still an issue!
