### ISSUE TITLE
Not possible to ingest MLmodels via OpenApi

### ISSUE THREAD

**Issue by patriciaramosf** [datahub-project/datahub#6414]
**Describe the bug**
There is a bug related to MLModel schema. The structure is ok, I also managed to ingest other entities as glossaryterms following this "structure or instructions" that appear in the swagger of datahub.
The error is always related to the name of the aspect "MLModelProperties". I send the correct name but  it is detected as if it was written with the first m in lowercase.

**ERROR :** "Request processing failed; nested exception is java.lang.RuntimeException: Unknown aspect mLModelProperties for entity MLModel"

**REQUEST BODY:**
 `[
  {
    "entityType": "MLModel",
    "entityUrn": "urn:li:mlModel:(urn:li:dataPlatform:science,sciencePatri,PROD)",
    "entityKeyAspect": {
      "__type": "MLModelKey",
      "platform":"urn:li:dataPlatform:science",
     "name":"sciencePatri",
     "origin":"PROD"
    },
    "aspect": {
      "__type": "MLModelProperties",
      "customProperties": {
        "additionalProp1": "value1",
        "additionalProp2": "value2",
        "additionalProp3": "value3"
      },
      "externalUrl": "url",
      "description":"description",
      "tags":["urn:li:tag:hola"]
    }
  }
]`

**To Reproduce**
1. Go to 'https://demo.datahubproject.io/openapi/swagger-ui/index.html#
2. Create the tags you are going to associate to your MLModel (tags are a required field)
3. Create the platform entity where you are going to have the MLModel, or choose the urn of a platform that already exists
4. Copy the structure attached above in to the POST /entities/v1 query
5.  Check the error in the console

**Expected behavior**
The response should be 200 sucess and the mlModel should be created.

**Screenshots**
<img width="1407" alt="Captura de pantalla 2022-11-10 a las 10 16 49" src="https://user-images.githubusercontent.com/60430499/201348512-cd6977ff-711f-4156-8990-f697af2a6b9e.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by patriciaramosf** [comment]
This issue is still a bug. Tested in last version 10.0.0

**Comment by Ido-Levi** [comment]
Also managed to reproduce in 0.10.0, but weirdly enough I managed to create an empty `MlModel` entity without any aspects or ownership

**Comment by Ido-Levi** [comment]
This is the body I used
```
[
  {
    "entityType": "MlModel",
    "entityUrn": "urn:li:mlModel:(urn:li:dataPlatform:testplatform,testtest,DEV)",
    "aspect": {
        "__type": "Ownership"
    }
  }
]
```
But I couldn't add any aspects to it or features, just an empty shell

**Comment by patriciaramosf** [comment]
Thanks!! But yes, still aspects are necessary.
