### ISSUE TITLE
Tableau ingestion avoid Tableau project hierarchy and "subfolders".

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6422]
**Describe the bug**
Tableau has the ability to create subfolders. At the moment, Datahub incorrectly unloads subprojects
This makes navigation difficult and it can lead to a conflict of identical names. 

**To Reproduce**
1. Go to 'Tableau and create Project inside existing project.'
2. Click on 'ingestion RUN'
3. Try to 'navigate results in Datahub'
4. Seek error. That there is no navigation option instead of wild search by name 

**Expected behavior**
Proper work with Tableau Subprojects hierarchy

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
we have a lot of projects inside other projects in the Tableau. At this moment it seems impossible to navigate tableau subprojects in datahub. Today, only projects of the first level are well synchronized in datahub.

**Comment by hsheth2** [comment]
@YuriyGavrilov this should be resolved by https://github.com/datahub-project/datahub/pull/7864
