### ISSUE TITLE
Incorrect directory in the datahub-web-react guide

### ISSUE THREAD

**Issue by shcd-garjo3** [datahub-project/datahub#6428]
**Describe the bug**
The datahub-web-react guide indicates the following: 
If you want to make changes to the UI see them live without having to rebuild the **datahub-frontend-react** docker image, you can run the following in this directory:

I believe the directory should be **datahub-web-react**.

**Screenshots**
![image](https://user-images.githubusercontent.com/108762174/201736363-8508c83d-2b92-4a17-bbbd-1a738dd28a4a.png)

**Comment by aditya-radhakrishnan** [comment]
Thanks for catching this! I'll make a PR to fix this.

**Comment by aditya-radhakrishnan** [comment]
I have https://github.com/datahub-project/datahub/pull/6701 to fix this one!

**Comment by aditya-radhakrishnan** [comment]
Actually I don't think this is an error. Check out the container here https://hub.docker.com/r/linkedin/datahub-frontend-react

Closing!
