### ISSUE TITLE
Policies not working with domains

### ISSUE THREAD

**Issue by jakeskatez** [datahub-project/datahub#6430]
**Describe the bug**
When trying to create a policy to allow users of GroupA to access a domain, those users are met with "unauthorized access" while trying access the domain resource page, but are still able to see the metadata for datasets under that domain.

**To Reproduce**
1. Turn off all pre-baked policies
2. Create a policy under DomainA giving "View Entity" perms to userA
3. Try accessing DomainA's resource page using userA 

**Expected behavior**
UserA is able to access the domain resource page and access datasets within the domain.

**Screenshots**
Screenshot of the policy 
![image](https://user-images.githubusercontent.com/54611384/201748556-3eb9aca1-6e88-4627-8576-97376a7861e1.png)

Screenshot of the domain resource page as userA
![image (1)](https://user-images.githubusercontent.com/54611384/201748881-adaaf568-19e0-4023-abb9-ce55bdf992e0.png)

Screenshot of a data asset under DomainA as userA
![image (2)](https://user-images.githubusercontent.com/54611384/201748997-c4674a4d-e2d4-424d-b56f-0958f3bb5ebf.png)

Screenshot of 
**Desktop (please complete the following information):**

**Additional context**
While the domain page is restricted for userA, they are still able to view the data assets under DomainA

**Comment by aditya-radhakrishnan** [comment]
Hey @jakeskatez thanks for reporting this issue, I was able to reproduce.

Please take a look at the fix here! https://github.com/datahub-project/datahub/pull/6812

**Comment by aditya-radhakrishnan** [comment]
This PR has been merged, so going to close this one out. Thanks again for reporting this bug!
