### ISSUE TITLE
Mysql table metedata cann't sink into gms through datahub-rest

### ISSUE THREAD

**Issue by qiusheng0755** [datahub-project/datahub#6442]
**Describe the issue**
With v0.8.24，docker-compose running, install datahub-rest and mysql plugin， recipe.yml like this: 
source:
  type: "mysql"
  config:
    username: datahub
    password: datahub
    host_port: "localhost:3306"
sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"

when execute datahub ingest -c recipe.yml command,  many errors  occur on datahub-gms console like this: 
08:33:02.588 [qtp544724190-37] INFO  c.l.m.filter.RestliLoggingFilter:56 - POST /aspects?action=ingestProposal - ingestProposal - 500 - 3ms
08:33:02.589 [qtp544724190-37] ERROR c.l.m.filter.RestliLoggingFilter:38 - java.lang.RuntimeException: Unknown aspect container for entity dataset
08:33:02.594 [qtp544724190-38] INFO  c.l.m.filter.RestliLoggingFilter:56 - POST /entities?action=ingest - ingest - 422 - 0ms
08:33:02.594 [qtp544724190-38] ERROR c.l.m.filter.RestliLoggingFilter:38 - com.linkedin.metadata.entity.ValidationException: Failed to validate record with class com.linkedin.entity.Entity: ERROR :: /value/com.linkedin.metadata.snapshot.DatasetSnapshot/aspects/1/com.linkedin.dataset.DatasetProperties/name :: unrecognized field found but not allowed

Please tell me why and how to fix it, thanks!

**Comment by qiusheng0755** [comment]
append context:  docker-compose file is copied from docker-compose-without-neo4j.quickstart.yml

**Comment by qiusheng0755** [comment]
DataHub CLI version: 0.9.2.1
Python version: 3.8.15 (default, Nov 14 2022, 18:32:39)

**Comment by xiphl** [comment]
i don't know when the class for DatasetProperties changed across versions, but it seems like GMS was validating the inputs and rejected the data because it was of a different definition. should use the same acryl-datahub version as the datahub you're running to be safe.

**Comment by qiusheng0755** [comment]
The issue is fixed by upgrade CLI to v0.8.24，thanks very much!
