### ISSUE TITLE
Quickstart does not work with Docker Compose V2

### ISSUE THREAD

**Issue by cbeauch** [datahub-project/datahub#6449]
This is happening on Centos 8 Stream after following the official Docker installation guide. 

```
[2022-11-15 23:52:23,821] ERROR    {datahub.entrypoints:189} - Command failed with [Errno 2] No such file or directory: 'docker-compose': 'docker-compose'. Run with --debug to get full trace
```

`docker-compose` is now `docker compose` in V2

**Comment by hsheth2** [comment]
We've also switched to using `docker compose` v2 

What version of `acryl-datahub` are you using? You can check with `datahub --version`

**Comment by cbeauch** [comment]
I will check tomorrow for you. 

However, 2 days ago all I did was follow this guide: https://datahubproject.io/docs/quickstart/ so I assume I should be up to date.
