### ISSUE TITLE
How to assign hive kerberos parameters in recipe-hive.yml

### ISSUE THREAD

**Issue by qiusheng0755** [datahub-project/datahub#6470]
**Describe the bug**
Now hive-server provided kerberos mode to access,  there have 2 files such as krb5.conf and xxxxx.keytab，the Datahub-CLI version is v0.8.45,  recipe-hive.yml is like this:
source:
  type: "hive"
  config:
    host_port: "localhost:10000"
    options:
      connect_args:
        auth: KERBEROS
        kerberos_service_name: hive

sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"

when execute datahub --debug ingest -c recipe-hive.yml command, many errors occured on datahub-cli console like this:
TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server hive/xxxxx@YYYY.TDB1 not found in Kerberos database)'
[2022-11-17 13:37:45,649] DEBUG    {datahub.entrypoints:198} - DataHub CLI version: 0.8.45 at /usr/local/lib/python3.8/site-packages/datahub/__init__.py
[2022-11-17 13:37:45,650] DEBUG    {datahub.entrypoints:201} - Python version: 3.8.15 (default, Nov 14 2022, 18:32:39)

My question is how to configure the krb5.conf and xxxxx.keytab manually for hive kerberos mode in recipe-hive.yml? thanks!

**Comment by qiusheng0755** [comment]
this issue is fixed by add machine to hdfs cluster

**Comment by javaht** [comment]
> this issue is fixed by add machine to hdfs cluster

想具体问您一下 如果datahub在其他机器部署，要访问配置了kerberos的hive的数据，具体应该怎么做？
虽然看到文档写如下配置就可以：
options:
    #  connect_args:
    #    auth: KERBEROS
    #    kerberos_service_name: hive
但是我配置了依然报错，如果不按照您说的把datahub的服务器添加到集群，那我应该怎么做？ 谢谢你

**Comment by Olave** [comment]
I encountered the same problem, what you mean "add machine to hdfs cluster"？
