### ISSUE TITLE
Couldn't properly create domain name from ingestion. The new domain is created with the characters urn:li:domain in the name

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6473]
**Describe the bug**

Could not properly create domain name from ingestion when domain creates first time. Currently we can avoid this but when we create domain before ingestion Run.

**To Reproduce**
1. Go to ingestion and create new one with Domain name settings.
2. Click on ingestion run
3. Go to the main screen 
4. See error that the domain created with "urn:li:domain" characters.

**Expected behavior**
New domains should be created from ingestion at the first time properly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44679014/202397230-afd20708-0a0e-4b20-b48e-7f79d9944e7d.png)
![image](https://user-images.githubusercontent.com/44679014/202397443-88338bd8-1e9e-4538-8c07-12cd93fc14b5.png)

**Desktop (please complete the following information):**

**Additional context**
There is no such bug when we create manually Domain before ingestion run.

**Comment by treff7es** [comment]
@YuriyGavrilov Domains first has to be created on the UI and then you should reference the newly created Domain's urn.
Check out our docs about this here ->  https://datahubproject.io/docs/domains/

**Comment by YuriyGavrilov** [comment]
@treff7es Thanks a lot. So it is not a bug.
