### ISSUE TITLE
No assets ingested from lookml source

### ISSUE THREAD

**Issue by larry-lai-awx** [datahub-project/datahub#6487]
**Describe the bug**
When Looker model.lkml file does not have any explore definition and only includes explore from other explore.lkml, the lookml ingestion does not ingest anything into DataHub even if the ingestion is successfully run. 

**To Reproduce**
1. Create a explore.lkml file to define your explore in Looker
2. Create a model.lkml file to include the explore.lkml file in Looker
3. Create a Lookml ingestion in DataHub
4. You can see that the ingestion is successfully run, but no assets have been ingested into DataHub

**Expected behavior**
Looker views and explores can be ingested into DataHub even when they are only included in model file. 

**Screenshots**
<img width="719" alt="Screen Shot 2022-11-18 at 15 05 28" src="https://user-images.githubusercontent.com/68638066/202641952-7434f7da-5629-4b81-83df-65568adb8b0f.png">
<img width="779" alt="Screen Shot 2022-11-18 at 15 06 35" src="https://user-images.githubusercontent.com/68638066/202642033-516ed6bd-9b06-4207-b33f-e6266fe9f595.png">

**Desktop (please complete the following information):**
 - OS: IOS12.6
 - Browser chrome
 - Version 0.9.2

**Additional context**

**Comment by laulpogan** [comment]
Hi @larry-lai-awx, have you added the looker source module as well as noted in the documentation? You can't get a complete integration without both modules https://datahubproject.io/docs/generated/ingestion/sources/looker/#module-lookml

**Comment by larry-lai-awx** [comment]
Hi @laulpogan, I have added looker source modules as well.
