### ISSUE TITLE
Failed to Login-Unexpected Error http://localhost:9002/ (Windows 10 Pro)

### ISSUE THREAD

**Issue by karesz3** [datahub-project/datahub#6489]
**Describe the bug**
Followed instructions to setup Datahub on Windows 10 Pro:
https://datahubproject.io/docs/quickstart/

**To Reproduce**
1. After services are up and running>>>attempting to login with datahub/datahub (username/pwd) from http://localhost:9002/
2. After 10-15 seconds>>>Login failed with unexpected error message appears (MS Edge and Chrome)

**Expected behavior**
Login with default credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/92691523/202714207-ebdac3da-1841-4fa6-96ca-aea4be376735.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Edge and Chrome
 - Version: Chrome: Version 107.0.5304.107 (Official Build) (64-bit)

**Additional context**

**Comment by karesz3** [comment]
I'm also getting this message: 2022/11/18 14:53:16 Problem with request: Get "http://datahub-gms:8080/health": dial tcp 172.19.0.8:8080: connect: connection refused. Sleeping 1s

**Comment by pedro93** [comment]
Hello @karesz3 

Can you share the Quickstart version and command that was executed as well as the output of `docker ps -a`?

**Comment by pedro93** [comment]
Mhmm, what CPU architecture is your computer?

The compose file you shared is meant to be used for M1 MacBooks. It will not work for x86 CPUs.

Could you try to deploy DataHub using: `datahub docker quickstart --version v0.9.2`?

**Comment by pedro93** [comment]
Docker does not seem to be running on your machine.

**Comment by karesz3** [comment]
S C:\datahub> docker ps -a
CONTAINER ID   IMAGE                                       COMMAND                   CREATED             STATUS                         PORTS                                        NAMES
456d6bf31e37   linkedin/datahub-kafka-setup:head           "/bin/sh -c ./kafka-…"    About an hour ago   Exited (1) About an hour ago                                                kafka-setup
3df4ac240804   confluentinc/cp-schema-registry:5.4.0       "/etc/confluent/dock…"    About an hour ago   Exited (1) About an hour ago                                                schema-registry     
099dc9e5c0b5   linkedin/datahub-frontend-react:head        "/bin/sh -c ./start.…"    About an hour ago   Up About an hour (healthy)     0.0.0.0:9002->9002/tcp                       datahub-frontend-react
a86a6661cc84   acryldata/datahub-actions:head              "/bin/sh -c 'dockeri…"    About an hour ago   Exited (1) 46 minutes ago                                                   datahub-datahub-actions-1
03fcedf2dd4f   confluentinc/cp-kafka:5.4.0                 "/etc/confluent/dock…"    About an hour ago   Up About an hour               0.0.0.0:9092->9092/tcp                       broker
62eb78ec5376   linkedin/datahub-gms:head                   "/bin/sh -c /datahub…"    About an hour ago   Exited (1) About an hour ago                                                datahub-gms
7e6a01d266ce   acryldata/datahub-mysql-setup:head          "/bin/sh -c 'dockeri…"    About an hour ago   Exited (1) About an hour ago                                                mysql-setup
f8dc49d943d3   linkedin/datahub-elasticsearch-setup:head   "/bin/sh -c 'if [ \"$…"   About an hour ago   Exited (0) About an hour ago                                                elasticsearch-setup 
159714fe17b1   confluentinc/cp-zookeeper:5.4.0             "/etc/confluent/dock…"    About an hour ago   Up About an hour               2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp   zookeeper
ac9ed744ae15   elasticsearch:7.9.3                         "/tini -- /usr/local…"    About an hour ago   Up About an hour (healthy)     0.0.0.0:9200->9200/tcp, 9300/tcp             elasticsearch       
d4dba47e0204   mysql:5.7                                   "docker-entrypoint.s…"    About an hour ago   Exited (1) About an hour ago                                                mysql
3fab52fa0add   docker/getting-started                      "/docker-entrypoint.…"    20 hours ago        Exited (0) 3 hours ago                                                      keen_antonelli      
PS C:\datahub>

**Comment by karesz3** [comment]
I'm probably doing something dumb, but I assume it's running:
PS C:\datahub> docker run -dp 80:80 docker/getting-started
3e7d3f20abce2aa70a1d55fa0265a645eb7b0f08c998df0bb40d635175ca81bc
PS C:\datahub> datahub docker quickstart --version v0.9.2 
Unable to run quickstart:
- Docker doesn't seem to be running. Did you start it?
PS C:\datahub>

**Comment by karesz3** [comment]
Quick update, I think I was able to bypass the error by this command: ywin32_postinstall.py. I'm running QuickStart now
