### ISSUE TITLE
Some fields cannot be further parsed in avro schema

### ISSUE THREAD

**Issue by xxniuren** [datahub-project/datahub#6497]
**Describe the bug**
I ingested avro schema into datahub, and found some nest fields cannot be expanded further.

**To Reproduce**
1. Ingest avro schema as follows
```json
{
  "type": "record",
  "name": "Payment",
  "namespace": "some.event.namespace",
  "fields": [
    {
        "name":"networks",
        "type":[
            "null",
            {
                "type":"record",
                "name":"Networks",
                "namespace":"some.event.namespace.report",
                "fields":[
                    {
                        "name":"cro",
                        "type":[
                            "null",
                            {
                                "type":"record",
                                "name":"Network",
                                "fields":[
                                    {
                                        "name":"role",
                                        "type":[
                                            "null",
                                            "string"
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "name":"distributors",
                        "type":[
                            "null",
                            {
                                "type":"array",
                                "items":"Network"
                            }
                        ]
                    },
                    {
                        "name":"entire_chain",
                        "type":[
                            "null",
                            {
                                "type":"array",
                                "items":"Network"
                            }
                        ]
                    }
                ]
            }
        ]
    }
  ]
}
```
2. The output schema information is as follows:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/18276112/202948934-8d46730f-5243-49d1-8498-7a0ac709f98b.png">
Column '**entire_chain**' can be parsed further.

**Expected behavior**
Expect output schema information is as follows:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/18276112/202949341-de1df836-a7a1-40c0-87b0-4214d9728980.png">

**Comment by xxniuren** [comment]
I don't think it is as expect.
**actual**: Field 'entire_chain' can not be expand further.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/18276112/202969737-e00d490f-9b22-47cc-9f6f-ca078a410ce0.png">
**expect**: Field 'entire_chain' can be expand further.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/18276112/202970134-bc95e657-8679-49d6-aa91-4c7240bb17b1.png">

**Comment by laulpogan** [comment]
@hsheth2 is this outside of expected behavior?

**Comment by xxniuren** [comment]
@laulpogan, Thanks for your reply.  
1. This behavior may be not expected, developer might expect a defined object to be expanded only once. The example I showed above that the sub object of cro / distributor / end_reseller / entire_chain were Network, developer may be expected that Network could only be expanded only in cro. Is there any problems with my understanding?   
2.  From the user point of view, I want **each field** can be **expanded step by step** until it reaches the base type. 
FYI @hsheth2

**Comment by hsheth2** [comment]
@xxniuren you're right that this is a known bug.

syu on the DataHub Slack is actually already working on a fix for this

**Comment by hsheth2** [comment]
@xxniuren are you still working on this?
