### ISSUE TITLE
How to pull images fast？

### ISSUE THREAD

**Issue by jiangbiao910** [datahub-project/datahub#6499]
Hello，May I ask some questions：
```
[root@datahub docker]# cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://kunjp3fw.mirror.aliyuncs.com"]
}
```

![image](https://user-images.githubusercontent.com/23710717/202975599-75e53725-6ad5-4848-8b57-3c1c11154fe3.png)
I want to know how to pull images faster？

**Comment by laulpogan** [comment]
Hi @jiangbiao910, is this actually a bug, or do you want advice? If you just need advice, please check out the community slack here: https://datahubspace.slack.com/ssb/redirect

If you do believe you're experiencing a bug, please respond and let me know so we can get it sized!
