### ISSUE TITLE
UI not reporting successful ingestions

### ISSUE THREAD

**Issue by jbolesjc** [datahub-project/datahub#6523]
**Describe the bug**
We have deployed datahub on an EKS cluster. Using CLI based ingestion we have connected 8 databases.  In our datahub-values.yaml file we have set schedules for each to ingest every 6 hours. Based on the UI ingestion page most run without a problem every 6 hours. Yet, seemingly at random, the UI suggest an ingestion for a postgres database will not run. We have 4 postgres connections. We can check the logs for that "failed" ingestion pod and see that it has run successfully. These logs are present.

`[2022-11-22 12:00:20,618] INFO     {datahub.ingestion.run.pipeline:450} - Successfully committed changes for DatahubIngestionCheckpointingProvider.
[2022-11-22 12:00:20,717] INFO     {datahub.cli.ingest_cli:135} - Finished metadata ingestion` 

We see no relevant error logs in the datahub-gms or the datahub-frontend pods. Logs indicate that the ingestion pods ran and completed successfully. We believe that the output from that ingestion pod must be being handled incorrectly by another datahub pod resulting in the UI not reporting a successful ingestion.

**Expected behavior**
We expect the UI to report all ingestions if the ingestion pods are successful.

**Comment by laulpogan** [comment]
Hi @jbolesjc this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at https://slack.datahubproject.io and we can troubleshoot there. For now, I'm going to close this issue.
