### ISSUE TITLE
Assertions not correct mark next to table name.

### ISSUE THREAD

**Issue by sachinwadhwa** [datahub-project/datahub#6534]
**Describe the bug**
Please see attached image: all assertions are passed but still shows a X mark next to table name.

Previous soft-deleted assertions are still evaluated.

**Expected behavior**
Green tick mark if all assertions are passed.

**Workaround**
Hard delete assertions.

**Screenshots**
Added

**Additional context**
v0.9.2

**Comment by laulpogan** [comment]
Hi @sachinwadhwa, it seems that your screenshots didn't come across- could you try adding them again?

**Comment by aditya-radhakrishnan** [comment]
Hi @sachinwadhwa I'm going to close this one out due to inactivity. Please feel free to reopen if this is still an issue and you have screenshots!
