### ISSUE TITLE
Disable login for default user datahub on portal

### ISSUE THREAD

**Issue by vsikka91** [datahub-project/datahub#6567]
Is it possible to disable the login for datahub user? 
Right now we are handling infrastructure using terraform. Since datahub user is superuser and its password is known to all, we want to change the password without making changes in the code.

**Comment by pdraguiar** [comment]
I think its not possible to disable login for a specific user, but if you want to change the default password for datahub user, check this docs: https://datahubproject.io/docs/authentication/guides/add-users/#changing-the-default-datahub-user
