### ISSUE TITLE
AWS Glue Job lineage not working properly

### ISSUE THREAD

**Issue by Shib12** [datahub-project/datahub#6581]
Hi Team,

I need some details of how to capture AWS Glue Job lineage. I have gone through your documentation link for Glue.
Recently I have created one Glue Job where I tried a simple use case via Glue Job Visualization, I have created a glue job where my source in s3 bucket sample .csv file then I have done a transformation next push the data to target S3 bucker in .json format.
Below is the screen shot of my Glue job:
![image](https://user-images.githubusercontent.com/104564510/204787132-f47e1686-8586-412b-9f07-20673eb88272.png)

From Glue I was able to run the Job successfully and it created a file into my target s3 bucket. So the Job satisfied its requirement.
Next I was tried to run glue ingestion recipe in Datahub UI ( I am using Datahub v0.8.44) below is my recipe details:

//////////////////////////////////////////////////

    **sink:
        type: datahub-rest
        config:
            server: 'http://x.x.x.x:8080'
    source:
        type: glue
        config:
            aws_region: ap-northeast-1
            aws_access_key_id: '${AWS_ACCESS_KEY_ID}'
            aws_secret_access_key: '${AWS_SECRET_KEY}'
            emit_s3_lineage: true
            glue_s3_lineage_direction: upstream
    pipeline_name: 'urn:li:dataHubIngestionSource:438f67f9-576e-47c0-8ca9-d2da66913cf8'**

/////////////////////////////////////////////////

My ingestion run successful. It was able to ingest AWS Glue Catalog database & tables , also I got the Glue Job in Glue pipeline, I was able to view the glue job pipeline property details. **But the problem is there is 0 task which is the missing point**.
![image](https://user-images.githubusercontent.com/104564510/204789679-0fe7ef7e-a747-4e50-8fd5-9956a24104c6.png)

NB: I have expected IAM permission in AWS as per the documentation, also enable "Generate classic Script" option from Script tab.

**I need to understand, what additional steps I need to incorporate so that I will get the tasks and end to end lineage.**
Currently in demo site there is no glue pipeline. Is it possible to load some glue pipeline so that we get some understanding.

Looking for a quick help. 
Thanks a lot in advance.

Regards,
Shib

**Comment by laulpogan** [comment]
Hi @Shib12 We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io/) and we can troubleshoot there. For now, I'm going to close this issue.
