### ISSUE TITLE
Idea: Allow search results to show multiple matches

### ISSUE THREAD

**Issue by timcosta** [datahub-project/datahub#6643]
Hi all! While digging into the platform and all of the great features available, I had a question about the search results page. Currently when you put in a term like `x`, the results show something like `Matches column x_a`, but there could be a lot of columns in that one table that match that term. It's potentially a bit misleading for users who are looking for something slightly more specific than what they typed in, because the phrasing/view implies that there's a single match in that table without telling the user there are more and they should either be more specific or look at the table to see what else exists.

Looking at the code, I believe [this is the logic](https://github.com/datahub-project/datahub/blob/155a68386a15f8ab7c7145b8d98a4e7958ec71aa/datahub-web-react/src/app/entity/shared/utils.ts#L110) for that component/field selection.

Is there any appetite to making this component able to render `n` matches in a single table like `Matches columns x_a, x_b, and x_c`, or display something like `Matches column x_a and n others`? I'm not sure if there was a specific rationale behind limiting matches to a single field per table before, so I figured I would ask!

**Comment by aditya-radhakrishnan** [comment]
Hey @timcosta that's a great idea! Would you mind actually posting it to our Feature Requests page [here](https://feature-requests.datahubproject.io/) so we can track it better?

I'm going to close out the "Issue" here since this isn't really an issue but would really appreciate if you could post it there :)
