### ISSUE TITLE
Vertica missing images

### ISSUE THREAD

**Issue by martinontcode** [datahub-project/datahub#6646]
**Describe the bug**
Vertica isn't shown as a platform on the main page, even if datasets exist.

**Possible cause**
As explained on [metadata-ingestion/adding-source](https://datahubproject.io/docs/metadata-ingestion/adding-source/#9-add-logo-for-the-platform), both the logo ([src/images](https://github.com/datahub-project/datahub/tree/master/datahub-web-react/src/images)) and related platform code ([data_platforms.json](https://github.com/datahub-project/datahub/blob/master/metadata-service/war/src/main/resources/boot/data_platforms.json)) is missing.

**Desktop (please complete the following information):**
 - Version [v0.9.3]

**Comment by laulpogan** [comment]
Hi @martinontcode, were the assets there in a previous release, or have they always been missing?

**Comment by hsheth2** [comment]
@vishalkSimplify could you resolve this as part of https://github.com/datahub-project/datahub/pull/7010?

@martinontcode in the interim, you can use `datahub put platform` to add the platform info and logo manually.

**Comment by vishalkSimplify** [comment]
> @vishalkSimplify could you resolve this as part of #7010?
> 
> @martinontcode in the interim, you can use `datahub put platform` to add the platform info and logo manually.

Sure, will look into it .
