### ISSUE TITLE
linkedin/datahub-frontend-react:debug not found when executing docker/dev.sh

### ISSUE THREAD

**Issue by yangjiandan** [datahub-project/datahub#6648]
**Describe the bug**
executing docker/dev.sh fails, error message is:
WARNING: Some service image(s) must be built from source by running:
    docker compose build datahub-frontend-react datahub-gms mysql-setup elasticsearch-setup kafka-setup
Error response from daemon: manifest for linkedin/datahub-frontend-react:debug not found: manifest unknown: manifest unknown

**To Reproduce**
1. git clone master branch
2. cd datahub 
3. ./gradlew build -x test
4. docker/dev.sh
5. See error: Error response from daemon: manifest for linkedin/datahub-frontend-react:debug not found: manifest unknown: manifest unknown

**Expected behavior**
doing this was well yesteday, but it fails today,

**Desktop (please complete the following information):**
 - OS: mac

**Comment by yangjiandan** [comment]
linkedin/datahub-frontend-react:debug  does not exist now in hub.docker.com

**Comment by laulpogan** [comment]
Hi @yangjiandan that's an internal dev image that we build locally and don't host- the DEBUG tag is build locally only

**Comment by yangjiandan** [comment]
@laulpogan Thanks for your quickly reply very
much. Could you tell me how to build Debug tag

**Comment by yangjiandan** [comment]
I can not find related code or script about build debug images, @laulpogan @mhw @cburroughs @koconder please give me a hint, thanks.

**Comment by laulpogan** [comment]
Hi @yangjiandan  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs. 

If you're still having trouble, please join us at [slack.datahubproject.io](https://slack.datahubproject.io/) and we can troubleshoot there. For now, I'm going to close this issue.
