### ISSUE TITLE
Overpermissioned default policies automatically recreated

### ISSUE THREAD

**Issue by timcosta** [datahub-project/datahub#6679]
**Describe the bug**
When the default policies in https://github.com/datahub-project/datahub/blob/1282cf76382ccc6505eace16e2e2f277818b3fdf/metadata-service/war/src/main/resources/boot/policies.json#L91 are deleted in the UI, the next container restart silently recreates them. This is a security risk because it results in All Users being granted a wide set of permissions by the system when the operator has previously revoked the permissions.

**To Reproduce**
1. Deploy DataHub
2. Delete default policies like `All Users - All Platform Privileges (EXCEPT MANAGE POLICIES)`
3. Restart DataHub containers
4. `All Users - All Platform Privileges (EXCEPT MANAGE POLICIES)` has been recreated and is actively granting platform permissions to users

**Expected behavior**
When one of the default policies is deleted, it should NOT be recreated under any circumstance. 

**Additional context**
It would be acceptable in my mind to re-init them as deactivated, but definitely less ideal because they are still present in the UI. It would likely be better for these policies to be added as part of the database setup jobs in an initial migration rather than asserted on during boot.

Possibly related to this removed check from several months ago: https://github.com/datahub-project/datahub/commit/980c0550de7b93f1f02f357a19c690b869536351#diff-a5d2c58123d177132515791e546684b40dcb65fbca8968c43b8f94d7959bae5cL116

**Comment by timcosta** [comment]
This issue is not stale, it remains a security risk.

**Comment by aditya-radhakrishnan** [comment]
Hey @timcosta it shouldn't be a security risk if you deactivate the policy. I understand that it's a bit frustrating that it remains in the UI, but this is a bit technically challenging to solve.

Is there any reason why this is not an acceptable solution to you?

**Comment by timcosta** [comment]
We would like to wholly remove these policies because they grant a very large number of permissions by default, and while deactivating them is nice it still leaves them present and with a one-click restore option that grants wide open access. Full removal is far more desirable.
