### ISSUE TITLE
Lineage resolver not excluding soft-deleted entities:

### ISSUE THREAD

**Issue by aezomz** [datahub-project/datahub#6688]
**Describe the bug**
Lineage result is different between the two Graph Resolver. One does no exclude soft deletion.

**To Reproduce**
Ingest some dataset with lineage and soft delete 1 or a few of them.
The discrepancy will show on the UI

**Expected behavior**
The two resolvers should exclude soft deleted entities

**Screenshots**
![image](https://user-images.githubusercontent.com/45879156/206344309-0528669c-a2fe-417e-84f6-7883483c6982.png)
![image](https://user-images.githubusercontent.com/45879156/206344319-8d9dd0d8-621f-4e51-8336-a0d7205a474c.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

Hi, I found out that lineage result number return is wrong between this two resolver.
Mainly its because one uses `searchAcrossEntities` to check if its soft-deleted  from `LineageSearchService.java`
      `LineageSearchResult resultForBatch = buildLineageSearchResult(
          _searchService.searchAcrossEntities(entitiesToQuery, input, finalFilter, sortCriterion, queryFrom, querySize,
              SKIP_CACHE), urnToRelationship)`
The top UI showing 9. But 2 of them are soft deleted.
This one is using resolver from `EntityLineageResultResolver.java`
The bottom UI show the correct value.  Which is 7
Resolver from `SearchAcrossLineageResolver.java`

Can you advice how to take it from here?

https://datahubspace.slack.com/archives/C029A3M079U/p1670409819840909

**Comment by jjoyce0510** [comment]
Thanks for reporting. We are taking a look and trying to evaluate the priority on this one.

**Comment by aezomz** [comment]
@jjoyce0510 any update for this? saw that u was doing clean up in one of the PR.

**Comment by david-leifker** [comment]
This https://github.com/datahub-project/datahub/pull/11453 should address the issue
