### ISSUE TITLE
Oracle source documentation bug

### ISSUE THREAD

**Issue by dvenza** [datahub-project/datahub#6710]
**Describe the bug**
The Oracle documentation page at:
https://datahubproject.io/docs/generated/ingestion/sources/oracle
does not list the grants needed for the database user.

Searching in the pull requests we found out that access to the DBA_* tables is needed.

This is an obstacle in our organization, as access to those tables is restricted.

The Snowflake page can be used as an example:
https://datahubproject.io/docs/generated/ingestion/sources/snowflake#prerequisites

**Additional context**
See also: https://github.com/datahub-project/datahub/issues/5905#issuecomment-1246638659, #6530

**Comment by dvenza** [comment]
Still there, bad bot,

**Comment by darnaut** [comment]
Fixed by #10712
