### ISSUE TITLE
Column level lineage between Looker and BigQuery missing

### ISSUE THREAD

**Issue by larry-lai-awx** [datahub-project/datahub#6732]
**Describe the bug**
I use the lookml source to extract the column lineage between BigQuery tables and Looker views. I found out that when the dimension name in Looker differs from the field in BigQuery, it cannot be linked.
here is the column lineage screenshot and dimension definition

**To Reproduce**
1. define a new Looker view that dimension name differs from the table field name
2. Create a LookML ingestion
3. check column lineage 

**Expected behavior**
the column-level lineage between the BigQuery table and Looker views should be working correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/68638066/207020394-1a4bd523-5cc6-4da0-b22f-751da9be5697.png)
![image](https://user-images.githubusercontent.com/68638066/207020421-0ba4aff7-3a71-485b-924f-cf790447f61a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Browser Chrome
 - Version 0.9.3

**Comment by hsheth2** [comment]
Hey @larry-lai-awx, I had a quick question on this one. If you turn off the "compress lineage" toggle in the bottom right of the lineage view, does the column-level lineage show up correctly?

I'm trying to figure out if this is a LookML ingestion issue or a frontend viz problem.

**Comment by jjoyce0510** [comment]
Larry - Please let us know if you are able to sync on this one :)

**Comment by larry-lai-awx** [comment]
sorry for the late replay, I was sick for the last 2 weeks. If I turn off the compress lineage toggle in the bottom right of the lineage view, the column-level lineage does not show up correctly. I think it should be a LookML ingestion issue. @hsheth2

**Comment by jjoyce0510** [comment]
Hi @larry-lai-awx ! Are you in Slack? We'd love to catch up on a call to understand what is happening here. Please reach out directly to me or @hsheth2.

Cheers
John

**Comment by jjoyce0510** [comment]
Syncing over Slack now.
