### ISSUE TITLE
Lineage sample code for column lineage ,thanks !

### ISSUE THREAD

**Issue by ChanghrSuper** [datahub-project/datahub#6755]
https://datahubproject.io/docs/lineage/sample_code
I want to configure column lineage, but cannot find sample code.
It would be better if there were examples in java.
![image](https://user-images.githubusercontent.com/41114643/207533759-cd1bceb8-3adc-4c01-9ba8-c46aa7e1a29a.png)

**Comment by jjoyce0510** [comment]
Thanks for the report. We understand that this is not ideal. We are trying to prioritize this on our side so that everyone can easily start producing column level lineage.

**Comment by hsheth2** [comment]
@ChanghrSuper we actually have some sample code here https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/examples/library/lineage_emitter_dataset_finegrained.py, but that doc just doesn't list it

Leaving this issue open so we remember to update the docs
