### ISSUE TITLE
Setting k8s user credentials / default admin password using helm

### ISSUE THREAD

**Issue by tomaecoward** [datahub-project/datahub#6771]
**Describe the bug**
linkedin/datahub-frontend-react:v0.9.3

Guidance from https://datahubproject.io/docs/authentication/guides/add-users/
Setting below values:

datahub-frontend:
  ...
  extraVolumes:
    - name: datahub-users
      secret:
        defaultMode: 0444
        secretName:  datahub-users-secret
  extraVolumeMounts:
    - name: datahub-users
      mountPath: /etc/datahub/plugins/frontend/auth/user.props
      subPath: user.props

Does not set default password from secret 

Kubernetes version 1.24

**Expected behavior**
User credentials, including default user, should be able to be set from generic secret

**Comment by chrisharris-inawisdom** [comment]
@szalai1 Same issue for me

**Comment by tomaecoward** [comment]
Apologies. 
This is working now as expected. 
The issue was with the subPath not matching the secret name

This is however when creating the file in **mountPath: /datahub-frontend/conf/user.props**
Not tried under the location that is suggested from https://datahubproject.io/docs/authentication/guides/add-users/

If this is wrong can this be updated otherwise if all good then this can be closed
