### ISSUE TITLE
cannot use helm to install datahub-mae-consumer

### ISSUE THREAD

**Issue by jkl0898** [datahub-project/datahub#6802]
**Describe the bug**
cannot use helm to install datahub-mae-consumer

helm repo: 
https://github.com/acryldata/datahub-helm/tree/master/charts/datahub/subcharts/datahub-mae-consumer

branch:
master

exec cmd:
helm install datahub-mae-consumer datahub-mae-consumer

error output:
# helm install datahub-mae-consumer datahub-mae-consumer
Error: INSTALLATION FAILED: template: datahub-mae-consumer/templates/deployment.yaml:93:32: executing "datahub-mae-consumer/templates/deployment.yaml" at <.Values.global.datahub.gms.port>: nil pointer evaluating interface {}.port

**To Reproduce**
helm repo: 
https://github.com/acryldata/datahub-helm/tree/master/charts/datahub/subcharts/datahub-mae-consumer

branch:
master

exec cmd:
helm install datahub-mae-consumer datahub-mae-consumer

error output:
# helm install datahub-mae-consumer datahub-mae-consumer
Error: INSTALLATION FAILED: template: datahub-mae-consumer/templates/deployment.yaml:93:32: executing "datahub-mae-consumer/templates/deployment.yaml" at <.Values.global.datahub.gms.port>: nil pointer evaluating interface {}.port

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [-]
 - Version [-]

**Additional context**

**Comment by jjoyce0510** [comment]
Thanks for reporting. We are looking at this one and will get back shortly!

**Comment by pedro93** [comment]
Hello @jkl0898,

DataHub's sub charts require the `global` section of DataHub's values.yaml to be deployed standalone. 
Please make sure you have this section in your values.yaml: https://github.com/acryldata/datahub-helm/blob/1c48990081a14009296cfbffb487f6c52d0418ea/charts/datahub/values.yaml#L131

**Comment by jkl0898** [comment]
> Hello @jkl0898,
> 
> DataHub's sub charts require the `global` section of DataHub's values.yaml to be deployed standalone. Please make sure you have this section in your values.yaml: https://github.com/acryldata/datahub-helm/blob/1c48990081a14009296cfbffb487f6c52d0418ea/charts/datahub/values.yaml#L131

Thanks for your replied!

I executed the cmd at:
datahub-helm/charts/datahub/subcharts

the cmd is: 
helm install datahub-mae-consumer datahub-mae-consumer

and I want to install datahub-mae-consumer standalone. 

how can I do?

**Comment by RyanHolstien** [comment]
The Charts are intended to be installed from the top level, not at the subchart level. When executing from the subchart level you will be missing values like Pedro mentioned. To enable standalone consumers you need to install at the top level of helm with `global. datahub_standalone_consumers_enabled` set to true in your values.yaml.

**Comment by pedro93** [comment]
Following up on what Ryan said:

Install standalone consumers from:`datahub-helm/charts` with a values.yaml where everything but `datahub-mce-consumer` is enabled + `global` area

**Comment by jkl0898** [comment]
@RyanHolstien @pedro93 
Hello, Thanks for your replied!

I had made tried:
1. changed global.datahub_standalone_consumers_enabled to true in file datahub-helm/charts/datahub/values.yaml.
 `global:
  datahub_standalone_consumers_enabled: true`

2.  installed from the top level which the cmd is:
 helm install datahub-mae-consumer subcharts/datahub-mae-consumer

but still got the error output:
Error: INSTALLATION FAILED: template: datahub-mae-consumer/templates/deployment.yaml:93:32: executing "datahub-mae-consumer/templates/deployment.yaml" at <.Values.global.datahub.gms.port>: nil pointer evaluating interface {}.port

What did I do wrong?

**Comment by jkl0898** [comment]
@RyanHolstien @pedro93 
Hello, Thanks for your replied. I followed your advice:
1. changed datahub_standalone_consumers_enabled to true in file datahub-helm/charts/datahub/values.yaml.
`global:
  graph_service_impl: neo4j
  datahub_analytics_enabled: true
  datahub_standalone_consumers_enabled: true`

2. installed datahub-mae-consumer from the top level.

now it works with the cmd:
`helm install -f datahub/values.yaml datahub-mae-consumer datahub/subcharts/datahub-mae-consumer/
NAME: datahub-mae-consumer
LAST DEPLOYED: Wed Dec 21 10:11:32 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=datahub-mae-consumer,app.kubernetes.io/instance=datahub-mae-consumer" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80`

**Comment by jkl0898** [comment]
@pedro93 @RyanHolstien 

Hello, Thanks for your replied. I followed your advice:

1.changed datahub_standalone_consumers_enabled to true in file datahub-helm/charts/datahub/values.yaml.

`global:     
 datahub_standalone_consumers_enabled: true`

2.installed datahub-mae-consumer from the top level.

it works with the cmd:
`helm install -f datahub/values.yaml datahub-mae-consumer datahub/subcharts/datahub-mae-consumer/
`

hope it will useful for others who met the same problem too.
