### ISSUE TITLE
Getting Issue while ingesting more field from hive to datahub 

### ISSUE THREAD

**Issue by kirantodekar** [datahub-project/datahub#6828]
**Describe the bug**
Bug is with the ingestion failure for hive source . The field structure is has more field so it's  failing 

**Expected behavior**
we should get the metadata even we have more field in table structure 

**Screenshots**
![image](https://user-images.githubusercontent.com/60921331/208936002-64c9348a-0c3b-480e-9e4e-a3bf218729c7.png)

**Desktop (please complete the following information):**
OS linux - datahub 0.45 version 

**Additional context**
yam**l file 

source:
  type: hive
  config:
    host_port: https://XXXXXX-xxxx.cloud.databricks.com:443
    username: token
    password: XXXXXXX
    scheme: 'databricks+pyhive'

    options:
      connect_args:
        http_path: 'sql/xxxxxxxx/o/4714961015346809/0519-084045-babel838'

sink:

 type: "datahub-rest"
 config:
    server:  "https://datahub-gms.xxxxxx.com:8080"**

**Comment by kirantodekar** [comment]
**Error 
more fields"],
              'lakehouse_views.pie_matched_clicks': ["Ingestion error: The struct field string format is: 'field_name:field_type', but got: ... 10 more fields"],
              'lakehouse_views.pie_matched_installs': ["Ingestion error: The struct field string format is: 'field_name:field_type', but got: ... 10 more fields"],
              'lakehouse_views.pie_unmatched': ["Ingestion error: The struct field string format is: 'field_name:field_type', but got: ... 10 more fields"],
              'sampled': '10 sampled of at most 16 entries.'},**

**Comment by jjoyce0510** [comment]
Is there any way you can provide the schema for one of the tables where the errors are reported? For example `'lakehouse_views.pie_matched_clicks`. It's difficult for us to reproduce without this!

**Comment by jjoyce0510** [comment]
How many fields do you have in this schema?

**Comment by kirantodekar** [comment]
I have more than 10  field that is 40 fields are there

**Comment by kirantodekar** [comment]
@jjoyce0510
