### ISSUE TITLE
Tags created via GraphQL do not render correctly in Datahub frontend

### ISSUE THREAD

**Issue by andrunah** [datahub-project/datahub#6831]
**Describe the bug**
Looks like Tags are being displayed incorrectly in UI when created using GraphAPI.

**To Reproduce**
Below actions reproduced on https://demo.datahubproject.io/

1. Create a `tag` using Graph API with custom `id` and `name`:

```
mutation createTags {
  createTag(
    input: {
      id: "DQ_ignore", 
      name: "Data Quality: Ignore", 
      description: "Do not send data quality notifications for data quality incidents"
    }
  )
}
```
2. Go to UI and try assigning this `tag` to any entity it will show correct `name` in the dropdown:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/17752048/208980870-db8158f0-9732-4435-aea1-287b402e362c.png">

3. Once `tag` is assigned it will be shown using `id` instead of `name`:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/17752048/208981035-7cebee71-10cd-4f35-ae16-d10b897be9d7.png">

4. When making Graph API query there seems to be odd situation, there are properties section with proper values, yet there are deprecated name and description also (which might be used in the UI):

```
{
  tag(urn: "urn:li:tag:DQ_ignore"){
      urn
    name
    description
    properties {
      name
      description
      colorHex
    }
  }
}
```
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/17752048/208981348-b647b436-2932-4448-8bc9-f4b0468a5d59.png">

**Expected behavior**
I believe `tags` should be displayed with proper `name` instead of `id` in the UI.

**Additional context**
version used v0.9.3

**Comment by jjoyce0510** [comment]
Yes this is indeed a bug. We are looking to address this ASAP. Thank you for reporting! Will post the PR here.
