### ISSUE TITLE
Tableau ingestion load published datasource twice as Embedded and as Published

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6842]
**Describe the bug**
There is an option on tableau server to create dashboards based on published datasource. but current ingestion load data twice as published datacource and as Embeded. So we will have two different entities in datahub. There will be two different needs to decribe documentation. 

**To Reproduce**
1. Go to Tableau web server. 
2. Click on Create new workbook based on published datasource. 
3. ingest this workbook. 
4. see two different datasource Embedded datasource and Published datasource which are not linked between together. 

**Expected behavior**
Tableau workbook created based on published datasource should have link to published datasource and shouldn't have any embedded datasource due to its created on existing datasource. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44679014/209152955-c543c348-47f5-4752-b6f8-3b4d97797719.png)

**Desktop (please complete the following information):**

**Additional context**
There is also two "projects" will be created in datahub if published datasource published in different tableau project but not the same as we ingest

**Comment by YuriyGavrilov** [comment]
May be on the place of embedded datasource should be linked workbook.

**Comment by jjoyce0510** [comment]
Thank you for reporting this! Our team is investigating.

**Comment by YuriyGavrilov** [comment]
any update @jjoyce0510 @Mohd-gslab ?
