### ISSUE TITLE
Bump pyspark dependency to >=3.1.3

### ISSUE THREAD

**Issue by keerthiis** [datahub-project/datahub#6852]
Currently used version of pyspark==3.0.3
[datahub/metadata-ingestion/setup.py](https://github.com/datahub-project/datahub/blob/b5e1ed739c72b1559ead4747a42a805dac65ef78/metadata-ingestion/setup.py#L142-L145)

Lines 142 to 145 in [b5e1ed7](https://github.com/datahub-project/datahub/commit/b5e1ed739c72b1559ead4747a42a805dac65ef78)

 data_lake_profiling = { 
     "pydeequ==1.0.1", 
     "pyspark==3.0.3", 
 } 

contains a security vulnerability https://github.com/advisories/GHSA-9rr6-jpg7-9jg6 that is fixed in pyspark>=3.1.3
Expected behavior
No security vulnerability

Opened this as the original one is closed without resolution - https://github.com/datahub-project/datahub/issues/4978

**Comment by hsheth2** [comment]
pyspark is currently pinned because deequ requires spark 3.0.x

They've since added support for Spark 3.1.x and above (up to spark 3.3). However, they still haven't released and hence we're blocked on https://github.com/awslabs/python-deequ/issues/106.

**Comment by swestrum-rii** [comment]
@hsheth2 They just closed that ticket, and pushed a 1.1.0 release - is there any chance we can revisit this?

**Comment by hsheth2** [comment]
@swestrum-rii yup, we're looking at this.
