### ISSUE TITLE
mssql ingestion failures - Tables error: (pytds.tds_base.OperationalError)

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6884]
**Describe the bug**

there is a lot of error mesages like: 

failures': {'GROUPS7\\a.v.nazarov': ["Tables error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist

don't undeerstand why it happend.

full one message: 

[earlier logs truncated...]
 'failures': {'GROUPS7\\a.v.nazarov': ["Tables error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist. Make sure that the name is entered correctly.\n[SQL: use [GROUPS7\\a.v]]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Views error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist. Make sure that the name is entered correctly.\n[SQL: use [GROUPS7\\a.v]]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Tables error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist. Make sure that the name is entered correctly.\n[SQL: use [GROUPS7\\a.v]]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Views error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist. Make sure that the name is entered correctly.\n[SQL: use [GROUPS7\\a.v]]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Tables error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist. Make sure that the name is entered correctly.\n[SQL: use [GROUPS7\\a.v]]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Views error: (pytds.tds_base.OperationalError) Database 'GROUPS7\\a.v' does not exist. Make sure that the name is entered correctly.\n[SQL: use [GROUPS7\\a.v]]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"]},
 'soft_deleted_stale_entities': [],
 'tables_scanned': '3203',
 'views_scanned': '284',
 'entities_profiled': '0',
 'filtered': [],
 'start_time': '2022-12-29 10:37:33.177611 (7 minutes and 30.83 seconds ago).',
 'running_time': '7 minutes and 30.83 seconds'}
Sink (datahub-rest) report:
{'total_records_written': '13606',
 'records_written_per_second': '30',
 'warnings': [],
 'failures': [],
 'start_time': '2022-12-29 10:37:32.140918 (7 minutes and 31.87 seconds ago).',
 'current_time': '2022-12-29 10:45:04.006918 (now).',
 'total_duration_in_seconds': '451.87',
 'gms_version': 'v0.9.5',
 'pending_requests': '982'}

⏳ Pipeline running with at least 6 failures so far; produced 14589 events in 7 minutes and 30.83 seconds.

Cli report:
{'cli_version': '0.9.5',
 'cli_entry_location': '/tmp/datahub/ingest/venv-mssql-0.9.5/lib/python3.9/site-packages/datahub/__init__.py',
 'py_version': '3.9.9 (main, Dec 21 2021, 10:03:34) \n[GCC 10.2.1 20210110]',
 'py_exec_path': '/tmp/datahub/ingest/venv-mssql-0.9.5/bin/python3',
 'os_details': 'Linux-4.18.0-305.62.1.el8_4.x86_64-x86_64-with-glibc2.31',
 'mem_info': '172.81 MB'}
Source (mssql) report:
{'events_produced': '14989',
 'events_produced_per_sec': '32',
 'event_ids': ['CMDM.dbo.ffp_upgrade_status',
               'CMDM.dbo.to_del_blabla',
               'container-urn:li:container:1d315b276af93d2f2fef119e1a2ed4d2-to-urn:li:dataset:(urn:li:dataPlatform:mssql,IBM_CM.CMDM.dbo.to_del_qweqweqwe,PROD)',
               'SANDBOX.dbo.a3',
               'container-subtypes-db_datareader-urn:li:container:24c152cc83e28189b6a121d16fc9af6c',
               'urn:li:dataset:(urn:li:dataPlatform:mssql,IBM_CM.WORK.dbo.cc180,PROD)-dataPlatformInstance',
               'WORK.dbo.Cell_code_06062017125251',
               'urn:li:dataset:(urn:li:dataPlatform:mssql,IBM_CM.WORK.dbo.dbo_todel_OVB,PROD)-dataPlatformInstance',
               'WORK.dbo.EXP_EMAIL_20221129182239_34-subtypes',
               'urn:li:dataset:(urn:li:dataPlatform:mssql,IBM_CM.WORK.dbo.EXP_EMAIL_20221201153647_23,PROD)-dataPlatformInstance',
               '... sampled of 14989 total elements'],
 'warnings': {'CMDM.dbo.V_ABANDONED_CART_APPS': ['unable to map type UNIQUEIDENTIFIER() to metadata schema'],
              'SANDBOX.dbo.ABANDONED_CART': ['unable to map type UNIQUEIDENTIFIER() to metadata schema']},

**To Reproduce**
1. Go to ingestion and run ms sql ingestion 
2. Click on 'logs'
3. Scroll down to 'error message'

**Expected behavior**
pytds.tds_base.OperationalError works with correct name 'GROUPS7\\a.v.nazarov' without failures

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
the ingestion yaml:
transformers:
    -
        type: simple_add_dataset_ownership
        config:
            owner_urns:
                - 'urn:li:corpuser:d.perchun'
            ownership_type: PRODUCER
    -
        type: simple_add_dataset_tags
        config:
            tag_urns:
                - 'urn:li:tag:product.ibm_cm'
                - 'urn:li:tag:product.CCPL'
    -
        type: simple_add_dataset_domain
        config:
            domains:
                - 'urn:li:domain:Client'
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms-datahub-gms:8080'
        token: '${ingestions_by_yua}'
source:
    type: mssql
    config:
        platform_instance: IBM_CM
        include_tables: true
        database: null
        password: '${ibm_cm_prod}'
        host_port: 'msdb24t24.group.s7:1433'
        include_views: true
        env: PROD
        username: datahub_ibm_cm
pipeline_name: 'urn:li:dataHubIngestionSource:212ee572-5f06-4a31-813f-901c4bf4ef62'

**Comment by jjoyce0510** [comment]
Hi @YuriyGavrilov - Are you able to set the "database" config to be equal to "GROUPS7\a.v.nazarov" (or whatever this database is _actually_ named? 

This will help us understand what's happening.

**Comment by jjoyce0510** [comment]
Actually - can you delete what the name of the database is?

**Comment by YuriyGavrilov** [comment]
[exec-urn_li_dataHubExecutionRequest_b37f78ed-7511-4571-8645-1621b15f00a5.log](https://github.com/datahub-project/datahub/files/10383125/exec-urn_li_dataHubExecutionRequest_b37f78ed-7511-4571-8645-1621b15f00a5.log)

**Comment by YuriyGavrilov** [comment]
there are a lot of errors like:

  '"Tables error: (pytds.tds_base.OperationalError) Database \'GROUPS7\\\\a.v\' does not exist. Make sure that the name is entered '
           'correctly.\\n[SQL: use [GROUPS7\\\\a.v]]\\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Views error: '
           "(pytds.tds_base.OperationalError) Database 'GROUPS7\\\\a.v' does not exist. Make sure that the name is entered correctly.\\n[SQL: use "
           '[GROUPS7\\\\a.v]]\\n(Background on this error at: https://sqlalche.me/e/14/e3q8)", "Tables error: (pytds.tds_base.OperationalError) '
           "Database 'GROUPS7\\\\a.v' does not exist. Make sure that the name is entered correctly.\\n[SQL: use [GROUPS7\\\\a.v]]\\n(Background on "
           'this error at: https://sqlalche.me/e/14/e3q8)", "Views error: (pytds.tds_base.OperationalError) Database \'GROUPS7\\\\a.v\' does not '
           'exist. Make sure that the name is entered correctly.\\n[SQL: use [GROUPS7\\\\a.v]]\\n(Background on this error at: '

**Comment by YuriyGavrilov** [comment]
@jjoyce0510 Solved this issue by setting up concrete database CMDM with filter by schemas dbo. so that means issue was on database side.
