### ISSUE TITLE
ldap ingestion - Failed to validate record with class com.linkedin.entity.Entity

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6885]
**Describe the bug**

                      "b'0\\\\x84\\\\x00\\\\x00\\\\x00\\\\x05\\\\x02\\\\x01\\\\x00\\\\x04\\\\x00')], 'info': '00002040: SvcErr: DSID-031403F9, "
                      'problem 5010 (UNAVAIL_EXTENSION), data 0\\\\n\'}"], "sampled": "10 sampled of at most 66 entries."}, "failures": {}, '
                      '"soft_deleted_stale_entities": [], "dropped_dns": [], "start_time": "2022-12-29 11:10:10.558029 (4.74 seconds ago).", '
                      '"running_time": "4.74 seconds"}}, "sink": {"type": "datahub-rest", "report": {"total_records_written": "169", '
                      '"records_written_per_second": "33", "warnings": [], "failures": [{"error": "Unable to emit metadata to DataHub GMS", "info": '
                      '{"exceptionClass": "com.linkedin.restli.server.RestLiServiceException", "stackTrace": '
                      '"com.linkedin.restli.server.RestLiServiceException [HTTP Status:500]: javax.persistence.PersistenceException: Error when '
                      'batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where '
                      'urn=? and aspect=? and version=?\\n\\tat com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:42)\\n\\tat '
                      'com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:50)", "message": "javax.persistence.PersistenceException: '
                      'Error when batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, '
                      'systemmetadata=? where urn=? and aspect=? and v", "status": 500, "id": "urn:li:corpuser:i.shipenkov"}}, {"error": "Unable to '
                      'emit metadata to DataHub GMS", "info": {"exceptionClass": "com.linkedin.restli.server.RestLiServiceException", "stackTrace": '
                      '"com.linkedin.restli.server.RestLiServiceException [HTTP Status:500]: javax.persistence.PersistenceException: Error when '
                      'batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where '
                      'urn=? and aspect=? and version=?\\n\\tat com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:42)\\n\\tat '
                      'com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:50)", "message": "javax.persistence.PersistenceException: '
                      'Error when batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, '
                      'systemmetadata=? where urn=? and aspect=? and v", "status": 500, "id": "urn:li:corpuser:p.vikharev"}}, {"error": "Unable to '
                      'emit metadata to DataHub GMS", "info": {"exceptionClass": "com.linkedin.restli.server.RestLiServiceException", "stackTrace": '
                      '"com.linkedin.restli.server.RestLiServiceException [HTTP Status:422]: '
                      'com.linkedin.metadata.entity.validation.ValidationException: Failed to validate record with class com.linkedin.entity.Entity: '
                      'ERROR :: /value/com.linkedin.metadata.snapshot.CorpUserSnapshot/aspects/1/com.linkedin.identity.GroupMembership/groups/5 :: '
                      '\\"Provided urn urn:li:corpGroup:sccm-Amadeus Altea INV (RIT HD\\\\\\" is invalid\\n\\n\\tat '
                      'com.linkedin.metadata.resources.entity.EntityResource.ingest(EntityResource.java:213)", "message": '
                      '"com.linkedin.metadata.entity.validation.ValidationException: Failed to validate record with class '
                      'com.linkedin.entity.Entity: ERROR :: /value/com.linkedin.metadata.snapshot.CorpUserSnapshot/aspects/1/", "status": 422, "id": '
                      '"urn:li:corpuser:d.zharikov"}}], "start_time": "2022-12-29 11:10:10.206563 (5.09 seconds ago).", "current_time": "2022-12-29 '
                      '11:10:15.298454 (now).", "total_duration_in_seconds": "5.09", "gms_version": "v0.9.5", "pending_requests": "0"}}}'}
Execution finished with errors.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
the ingestion YAML:

sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms-datahub-gms:8080'
        token: '${ingestions_by_yua}'
source:
    type: ldap
    config:
        ldap_password: '${active_directory}'
        filter: '(&(memberOf=CN=datahub.viewer,OU=Datahub,OU=Groups,DC=group,DC=s7)(objectClass=person))'
        ldap_user: 'CN=datahub_active_directory,OU=Users,OU=ЗАО «Группа компаний С 7»,OU=Company,DC=group,DC=s7'
        ldap_server: 'ldaps://dcgroup24i01.group.s7:636'
        base_dn: 'OU=Company,DC=group,DC=s7'
        drop_missing_first_last_name: true
pipeline_name: 'urn:li:dataHubIngestionSource:956cdd23-d93d-4962-b286-bcb72c5f60d7'

**Comment by bda618** [comment]
@YuriyGavrilov, I see an error "Unable to 'emit metadata to DataHub GMS" with status": 500 and your GMS URL "http://datahub-gms-datahub-gms:8080/" looks kind of suspicious. Also, I see no reason to have pipeline_name at the source because I see no "stateful_ingestion section" at your YAML (this should not cause any issue, just something I have noticed). You need to have datahub up and running at local to proceed with ldap ingestion and GMS URL usually (by default) will be: http://localhost:8080.

**Comment by YuriyGavrilov** [comment]
@bda618 Thanks. will try to run locally.

**Comment by bda618** [comment]
->Provided urn urn:li:corpGroup:sccm-Amadeus Altea INV (RIT HD\\\\\\" is invalid\\n\\n\\tat

Once I thought the above  group names caused the issue, but when I tried to emulate the scenario with such group name at my local environment it worked with no issues.

**Comment by YuriyGavrilov** [comment]
I will provide a full log soon

**Comment by YuriyGavrilov** [comment]
this is additional log 

----
\'CN=Карамушко Денис Маркович,OU=Users,OU=ЗАО «Группа компаний С 7»,OU=Company,DC=group,DC=s7\': ["manager LDAP search '
           "failed: {'msgtype': 101, 'msgid': 79, 'result': 12, 'desc': 'Critical extension is unavailable', 'ctrls': [('1.2.840.113556.1.4.319', 0, "
           "b'0\\\\x84\\\\x00\\\\x00\\\\x00\\\\x05\\\\x02\\\\x01\\\\x00\\\\x04\\\\x00')], 'info': '00002040: SvcErr: DSID-031403F9, problem 5010 "
           '(UNAVAIL_EXTENSION), data 0\\\\n\'}"],\n'
----

**Comment by bda618** [comment]
This error is normal (I have the same and it is a warning) and related to your LDAP server settings. In short, it will not impact a datahub LDAP ingestion. You can double check this by running the ldap ingestion process all way up to the end and check last message saying if ingestion was a success.
