### ISSUE TITLE
kafka connect ingestion does not support newer versions of debezium connectors

### ISSUE THREAD

**Issue by jaegwonseo** [datahub-project/datahub#6927]
**Describe the bug**
kafka connect ingestion does not support newer versions of debezium connectors.

**env**
helm version : 0.2.118

**Screenshots**
newer version debezium(2.1) - source connect task none
![스크린샷 2023-01-03 오후 4 42 33](https://user-images.githubusercontent.com/90180644/210316607-08438e92-0e08-4904-a44c-55676630daad.png)

old version of debezuim(1.9)
![스크린샷 2023-01-03 오후 4 42 43](https://user-images.githubusercontent.com/90180644/210316623-f8cbade7-a770-4cef-8491-d321223c7dc0.png)

**Additional context**
according to [source](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/kafka_connect.py#L709) topic_naming_pattern is using server_name.
But newer version of debezium is using **topic.prefix** 

https://debezium.io/documentation/reference/1.9/connectors/mysql.html#mysql-property-database-server-name
https://debezium.io/documentation/reference/2.1/connectors/mysql.html#mysql-property-topic-prefix

**Comment by jjoyce0510** [comment]
Thank you for reporting this! We are looking into it at present. 

Cheers 
John

**Comment by jaegwonseo** [comment]
@jjoyce0510 @mayurinehate 
i make a pr plz check this
