### ISSUE TITLE
Physical deletion will not be synchronized

### ISSUE THREAD

**Issue by qzl965678745** [datahub-project/datahub#6928]
When I want to delete metadata physically, I can delete it successfully, but the space has not been released. How can I solve the problem?

The deletion method is http

POST:/entities?action=delete
{
    "urn":"urn:li:dataset:(urn:li:dataPlatform:mysql,skywalking.alarm_record_tag,PROD)"
}

**Comment by jjoyce0510** [comment]
Hi there! What do you mean that the space will not be released? Can you elaborate?
