### ISSUE TITLE
The deletion operation will not be synchronized, only the addition and modification operations will be synchronizedA short description of the bug

### ISSUE THREAD

**Issue by qzl965678745** [datahub-project/datahub#6929]
After the source database deletes the database table, pull the source database again synchronously. It is found that the deleted database table still exists in the datahub. If it is ensured that the database table of the source data is deleted and then synchronized again, it will not exist in the datahub

**Comment by jjoyce0510** [comment]
Hi there! Thanks for reporting. We are looking into this. My guess is that this is on a source where stateful ingestion is enabled?

**Comment by hsheth2** [comment]
I believe this will be fixed by https://github.com/datahub-project/datahub/pull/6877. Deletion synchronization requires stateful ingestion to be enabled.
