### ISSUE TITLE
Spark lineage: Delete Task changed name/URN and appeared in lineage, didn't appear in spark platform UI

### ISSUE THREAD

**Issue by laulpogan** [datahub-project/datahub#6935]
See slack thread here:
https://datahubspace.slack.com/archives/CUMUWQU66/p1672494615000419

found out that I should have used Spark shell instead of Spark%20shell, which I copied from the UI link.
More importantly, the deletion for Spark lineage only works with the hard way, not the soft way. This should be an issue. (edited) 
white_check_mark
eyes
thanks_bear

Also, the deleted task changed its name to the urn and still appeared on the lineage (píc 1), although it wasn't seen in the Spark platform UI. So this is another bug.
image.png
 
![image](https://user-images.githubusercontent.com/101486603/210410570-b5147df7-fa1f-46b3-86ce-34de0e7ba18d.png)

**Comment by xuan1905** [comment]
I'm reopening the issue since the feature is important.
