### ISSUE TITLE
dataset from oracle ingest doesn't match to kafka-connect lineage

### ISSUE THREAD

**Issue by jaegwonseo** [datahub-project/datahub#6977]
**Describe the bug**
dataset from oracle ingest doesn't connect to kafka connect lineage

```
Oracle DB info
 - database : ORCL
 - schema : MRT
 - table : TB_AIR_RV100
 ```

urn from kafka connect 
urn:li:dataset:(urn:li:dataPlatform:oracle,ORCL.MRT.TB_AIR_RV100,PROD)
**database + schema + table**

urn from oracle
urn:li:dataset:(urn:li:dataPlatform:oracle,mrt.tb_air_rv100,PROD)
**(lowercase)schema + table**

two datasets are treated as another resource
 
**Expected behavior**
urn from ingest(kafka connect, oracle) must be same 

**Screenshots**
real table name : RV120

oracle source ingestion result - convert to lowercase
![스크린샷 2023-01-09 오후 1 31 43](https://user-images.githubusercontent.com/90180644/211242386-8a59c669-b517-4974-8fc6-6a2e74ffbf13.png)

kafka connect ingestion result - using uppercase

![스크린샷 2023-01-09 오후 1 31 18](https://user-images.githubusercontent.com/90180644/211242427-02f05080-1c4d-4a12-b8eb-8069f0e44216.png)

**so the same resource RV120, rv120 table is treated as another resource.**

**Comment by mayurinehate** [comment]
Can you please mention which source connector type is used here to push oracle data to kafka.

**Comment by jaegwonseo** [comment]
@mayurinehate 
i'm using [oracle debezium connector](https://debezium.io/documentation/reference/1.9/connectors/oracle.html) v1.9

**Comment by jaegwonseo** [comment]
urn name format issue is from oracle ingestion should be 
```
schema + table -> database + schema + table
```
is it right?


urn from postgres is also database + schema + table
**urn:li:dataset:(urn:li:dataPlatform:postgres,d492ini1gimd3l.public.abusing_ip_whitelists,PROD)**
![스크린샷 2023-01-12 오전 12 03 05](https://user-images.githubusercontent.com/90180644/211840377-48d06461-8f83-431b-b8b7-1651cedfa3a5.png)

**Comment by mayurinehate** [comment]
Okay, for Postgres, inside each database are multiple schemas, which contain tables. For mysql, its just schemas(also called database) and tables. So the formation of urns can not be compared to each other directly. 

On an initial thought, I believed that urn from oracle source is correct and the urn in kafka connect source needs an update to remove the database prefix. However I am not familiar with oracle database architecture so not sure. Could you share some insight ?

In any case, I do believe that setting `platform_instance: ORCL` in oracle ingestion recipe will fix the urn mismatch problem if we ignore the case. The problem with urns being in different case still remains.

**Comment by jaegwonseo** [comment]
@mayurinehate 
I think it's better to separate the issue into two
1. oracle urn format
2. kafka connect casing 

I uploaded [pr](https://github.com/datahub-project/datahub/pull/7016) about oracle urn format by referring to the [postgresql source](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/sql/postgres.py#L104).
