### ISSUE TITLE
mysql cann't get properties

### ISSUE THREAD

**Issue by tower111** [datahub-project/datahub#6990]
**Describe the bug**
When i use mysql dataset it cann’t get properties 
This problem from file `datahub/ingestion/source/sql/sql_common.py`  , function     `get_table_properties`
```
table_info: dict = inspector.get_table_comment(table, schema)
```
This function can get clickhouse  dataset properties
![image](https://user-images.githubusercontent.com/31761342/211477595-0471a024-229a-4a16-aba9-6475d8243c1a.png)

but cann't get mysql dataset
![image](https://user-images.githubusercontent.com/31761342/211477733-3d2ebe0d-8503-4f21-bd45-042d5bd79937.png)

Can it be resolve?

**Comment by hsheth2** [comment]
Hi @tower111 - this is a deficiency in the MySQL dialect that we're using under the hood. 

Is there a SQL query that can be used to fetch those properties? If so, we can add support for these properties to our source.
