### ISSUE TITLE
Custom sinks

### ISSUE THREAD

**Issue by tonxxd** [datahub-project/datahub#7018]
Hi and thanks for this great project.
I was wondering if it is possible to create custom sinks, using the existing ones as templates (e.g. the file sink).
Is there documentation how to achieve it? Does it work in the same way as plugins development?

**Comment by chriscollins3456** [comment]
hey @tonxxd ! That's a great question, and I believe there isn't currently a way to easily create a custom sink other than forking and building a new one in our ingestion framework, and there's no explicit docs on how that should be done right now.

Do you mind me asking what your custom sink would look like and why you want it?

Also, questions like this are perfect for discussing in our Slack community and we'd love to have you join us there :) here's the link to our Slack workspace: http://slack.datahubproject.io/

**Comment by hsheth2** [comment]
Actually it is possible to use a custom sink type without forking - the `type: ` field can accept a string, which you can put in `import.path.to.my.sink:MySinkClass` and we'll load your class directly.

I still would be curious to understand your use case for a custom sink though :)

**Comment by tonxxd** [comment]
Thanks for the answers! 

>  the type:  field can accept a string, which you can put in import.path.to.my.sink:MySinkClass and we'll load your class directly.

Yes I was actually thinking this could be an option, could you elaborate a bit further by giving me an example of field value and where to place the sink code? 

I don't have a defined use case yet but i think the datahub ingestion framework is very valuable and better architected than other alternatives like the openmetadata's one since it's almost standalone and not depending on the whole platform. I imagine contributing to the creation of connectors that are standardised and could be used within the datahub platform or not but still adding value to the project indirectly. And this would be achieved by custom sinks.

**Comment by hsheth2** [comment]
@tonxxd we have an example for sources here, and the process is the same for sinks: https://datahubproject.io/docs/how/add-custom-ingestion-source/

I'd be super curious to hear about your use cases for a custom sink! I believe a number of people have had success by simply using the file sink, which writes metadata in a JSON format.

**Comment by attekei** [comment]
@hsheth2 FYI that I'm interested in building custom sink as well. Our organisation is not (yet) ready to self-host or purchase full-blast DataHub, but want to built a simplistic data catalog using DataHub's data model and ingestion capabilities.

File sink is better than nothing, but a bit like DataHub Lite uses DuckDB, I could use Snowflake data warehouse as the sink. Then our simple data catalog application (built with Python) could read metadata from Snowflake and use the DataHub schema classes for easy consumption of that metadata.

I will try out creating a sink for Snowflake. I can share the learnings / outcomes afterwards if you are interested.
