### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by resulraveendran** [datahub-project/datahub#7032]
Hi,

    How to change the mysql port for running quicksart.sh .which all files i need to change that. 

Note: iam running the tag version 9.5

**Comment by chriscollins3456** [comment]
hey @resulraveendran - you can customize your quickstart deployment by specifying a docker-compose file to use when issuing the quickstart command (check out the docs here: https://datahubproject.io/docs/quickstart/#customization)

In the docker-compose file you can always change the port from 3306 to any port you want as long as it doesn't conflict with something else in use. Just change all of the instances of `3306` in the docker-compose file the docs tell you to use with whatever port you'd like!

Also i'll use this as an opportunity to suggest directing future questions like this towards our slack community as it's a great place to ask questions and have discussions around all thing datahub! http://slack.datahubproject.io/

Let me know if this resolves your problem and then I'll close this issue

**Comment by chriscollins3456** [comment]
@resulraveendran - going to close this issue for now, but feel free to ask more questions in our slack community or re-open this issue if you're still having problems.
