### ISSUE TITLE
schedule run failure issue but manual run ok (failed to write record with work unit - HTTP Status:500) - ingestion tried to run twice at once.

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#7053]
**Describe the bug**
every day I observe the same error when normal ingestion completes with errors but after manual startup everything turns green.
There is no same time run alredy but ingestion try to run twice and goes to falues on both due to unable to write twice at a time.  

**To Reproduce**
1. Go to ingestion at the morning
2. Click on ingestion logs
3. Scroll down to 'error'

           '⏳ Pipeline running with at least 1 failures so far; produced 40 events in 19.18 seconds.\n'
           '[2023-01-16 22:00:58,266] ERROR    {datahub.ingestion.run.pipeline:62} -  failed to write record with workunit '
           'container-urn:li:container:78b34191380acf4a4b739734d71b8348-to-urn:li:dataset:(urn:li:dataPlatform:s3,datalake%28EDL%29.edp-edl-prod/data/parsed/lms/transaction,PROD) '
           "with ('Unable to emit metadata to DataHub GMS', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'stackTrace': "
           "'com.linkedin.restli.server.RestLiServiceException [HTTP Status:500]: javax.persistence.PersistenceException: Error when batch flush on "
           'sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where urn=? and aspect=? and '
           'version=?\\n\\tat com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:42)\\n\\tat '
           "com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:50)', 'message': 'javax.persistence.PersistenceException: Error when "
           'batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where urn=? and '
           "aspect=? and v', 'status': 500, 'id': "
           "'urn:li:dataset:(urn:li:dataPlatform:s3,datalake%28EDL%29.edp-edl-prod/data/parsed/lms/transaction,PROD)'}) and info {'exceptionClass': "
           "'com.linkedin.restli.server.RestLiServiceException', 'stackTrace': 'com.linkedin.restli.server.RestLiServiceException [HTTP Status:500]: "
           'javax.persistence.PersistenceException: Error when batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, '
           'createdBy=?, createdFor=?, systemmetadata=? where urn=? and aspect=? and version=?\\n\\tat '
           'com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:42)\\n\\tat '
           "com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:50)', 'message': 'javax.persistence.PersistenceException: Error when "
           'batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where urn=? and '
           "aspect=? and v', 'status': 500, 'id': "
           "'urn:li:dataset:(urn:li:dataPlatform:s3,datalake%28EDL%29.edp-edl-prod/data/parsed/lms/transaction,PROD)'}\n"

![image](https://user-images.githubusercontent.com/44679014/212843280-2fef3b45-815d-4ee6-94fc-5be49427f130.png)

**Expected behavior**
Scheduled run - runs as manual run with success results once at a time.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
I observe it on each shcedule run on each ingestion. at the moment, the error is observed in 19 ingestions.

Maybe there is a some bug fix solution? does anyone know?

**Comment by hsheth2** [comment]
The "status 500" indicates that our GMS backend is getting overwhelmed by all of the requests. I'd recommend staggering your ingestion runs a bit so that they don't overlap. 

You can also try setting the rest sink's `retry_max_times` config option to add retries

**Comment by YuriyGavrilov** [comment]
thanks @hsheth2 I will try retry_max_times soon

**Comment by YuriyGavrilov** [comment]
@hsheth2 I doubt that the problem is overloading and starting at the same time.
i tryed to run all the ingestion manual at once and during some time it is all green.
![parallel_run1](https://user-images.githubusercontent.com/44679014/213379702-5261dc2a-f52d-42c6-91ae-f9c33496fd6f.PNG)
![parallel_run2](https://user-images.githubusercontent.com/44679014/213379709-68e972e6-1f07-45ea-a079-3211ca67822a.PNG)
![parallel_run3](https://user-images.githubusercontent.com/44679014/213379711-550bc9f7-68ba-437a-b08a-8f9070a27efb.PNG)

last two runs takes takes a bit more time but iam sure it will be green. 
I think problem only is in schedule run and in an attempt to write the same object at the same time.

**Comment by YuriyGavrilov** [comment]
two last logs...

[exec-urn_log_success_manual_run.log](https://github.com/datahub-project/datahub/files/10463711/exec-urn_log_success_manual_run.log)
[exec-urn_log_with_error.log](https://github.com/datahub-project/datahub/files/10463712/exec-urn_log_with_error.log)

**Comment by YuriyGavrilov** [comment]
@hsheth2 any ideas?

**Comment by hsheth2** [comment]
The 500 error indicates that our backend system is getting overwhelmed by the volume of metadata your ingestion source is producing. Having multiple ingestions running at the same time is likely the reason for it. If this is truly blocking you, you can try using the kafka sink instead of the rest sink for better scalability.

I'm going to close this issue for now, but feel free to ask additional questions here or on slack.

**Comment by szalai1** [comment]
@YuriyGavrilov  reported that he is using a single GMS instance with no standalone consumers and seeing double schedules.

**Comment by YuriyGavrilov** [comment]
link for slack https://datahubspace.slack.com/archives/C029A3M079U/p1675153278034129

**Comment by YuriyGavrilov** [comment]
fresh case 
![image](https://user-images.githubusercontent.com/44679014/217172420-d0d0321a-a087-4ce1-b234-9845feb718a1.png)

**Comment by YuriyGavrilov** [comment]
There was recomendation to turn off MCE and  MAE https://app.slack.com/client/TUMKD5EGJ/C029A3M079U/thread/C029A3M079U-1675153278.034129
"
we have
`- name: MCE_CONSUMER_ENABLED
         value: 'true'
       - name: MAE_CONSUMER_ENABLED
         value: 'true'`

 if you have MCE and MAE running separatly, disable them on gms."

After disabling schedul starts to work properly
