### ISSUE TITLE
Misplaced and missing content in Tableau ingestion 

### ISSUE THREAD

**Issue by basiltechwrite** [datahub-project/datahub#7054]
**Version**
DataHub CLI version: 0.8.43.5
Python version: 3.10.7 (main, Sep 13 2022, 14:31:33) [GCC 10.2.1 20210110]

**Issue** 
Some specific Tableau entities are misplaces or missing after ingestion. Some cases can be explained by lack of nested projects support, which already has a [feature request](https://feature-requests.datahubproject.io/p/tableau-nested-projects-support). Some cases are not explained by this, but those entities have same names, which might be the reason. More about this case below. 

I have three examples 

1) In Tableau, there is a parent folder called "Market assesment". Inside this folder there's a workbook named exactly the same "Market assesment", which has chart named "Pokermaster" and a datasource. In Datahub, only folder, chart and datasource were created, but no workbook. It seems like folder and workbook sharing same name created a conflict. 

2) In Tableau, there's parent folder "Eco" with many sub-folders. One of this sub-folders is named "Pokermaster". In Datahub, there were no such subfolder OR its contents, while other sub-folders were successfully imported. It seems like this folder and a chart from Market assesment named exactly the same created a conflict.
Also, folder "Eco" itself weren't present in Datahub either.

3) In Tableau there's a parent folder named "Bot" with many workbooks inside. One of them is called "bot_tournament_results", and this workbook has a dashboard named the exactly the same. Both workbook and its dashboard were missing from DataHub 

Lack of nested project support certainly doesn't help it, but it seems like it's not the reason for this behavior. For some reason, having the same name across different types of entities (folder, workbook, dashboard, chart) creates conflicts. Something will remain, and other stuff won't be ingested. 

Configuration for Tableau ingestion was like this:
        projects:
            - JackPoker
            - Eco
            - HR
            - Bot
            - 'Market assessment'
            - Hint
            - General
            - GGNetwork
            - 'Style guide'
            - Drafts

**What we tried to fix the issue**
We changed projects to include everything without exception ("project: []")
It made a lot of stuff to appear, but something to disappear too. 
For example, both workbook and its dashboard bot_recommended_tournament from third example appeared, despite still sharing the same name 
But both folder and workbook named Market assesment from first example disappeared     

Something weird is going on and we can't figure out what.

**Expected behavior** 
A 100% reproduction of what Tableau structure has. I know you don't support nested project hierarchy yet, but missing content is irritating

**Comment by YuriyGavrilov** [comment]
@basiltechwrite There is also https://github.com/datahub-project/datahub/issues/6422 and https://github.com/datahub-project/datahub/issues/6421 
same cases regarding tableau ingestion.

**Comment by YuriyGavrilov** [comment]
there is also feture request as https://feature-requests.datahubproject.io/p/tableau-stateful-ingestion

**Comment by basiltechwrite** [comment]
> @basiltechwrite There is also #6422 and #6421 same cases regarding tableau ingestion.

Thank you for mentioning them, although I believe they're not exactly the same cases. While I also experience a chaos in folders, it doesn't explain why some content is missing, seemingly based on having the same name as other entity 

> there is also feture request as https://feature-requests.datahubproject.io/p/tableau-stateful-ingestion

I tried to ask why they haven't updated status of this feature request yet, because to my knowledge, most recent version should have stateful ingestion for Tableau

**Comment by YuriyGavrilov** [comment]
This is actual

**Comment by hsheth2** [comment]
@basiltechwrite We now support nested hierarchies with Tableau properly. I'm closing this issue for now, but let me know if you run into any issues.

**Comment by YuriyGavrilov** [comment]
Great 👍
