### ISSUE TITLE
Signing out when Keycloak is the OIDC provider lets you click back button to get back to DataHub

### ISSUE THREAD

**Issue by aditya-radhakrishnan** [datahub-project/datahub#7071]
When signing out on DataHub, if the OIDC provider is Keycloak, users are able to use the back arrow of the browser to go back to the DataHub homepage and can still access it. This does not happen for native users.

**Comment by jjoyce0510** [comment]
Keycloak must provide `end_session_endpoint` in their OIDC configs

**Comment by iilrgmv** [comment]
Hi! Is there any end_session_endpoint  env variable that I can provide to datahub to make logout work properly?

Thanks!
