### ISSUE TITLE
Signing into Azure AD removes all roles from ingestion

### ISSUE THREAD

**Issue by andrewp-nextphase** [datahub-project/datahub#7090]
After ingesting users and roles for Azure AD using an ingestion recipe, using sso to log into datahub will delete the roles that have been mapped to the user. Could be a problem with other sso methods as well but I've only tried with Azure AD
Tested on v0.9.6

**Comment by namnt2307** [comment]
- name: AUTH_JAAS_ENABLED
      value: "false"
    - name: AUTH_NATIVE_ENABLED
      value: "false"
you should enable auth_native, login as datahub user first and then grant admin role to your user
i've met this issue when use v0.9.6.1 with keycloak oidc.
In my case, the user is duplicated so i have to use datahub user to grant Admin role to 2 user with the same display name
