### ISSUE TITLE
Tutorial Issue: DAG import issue, when I followed documentation: Running Airflow locally with DataHub

### ISSUE THREAD

**Issue by Sergogga** [datahub-project/datahub#7100]
**Describe the bug**
DAG import issue, when I followed documentation: [Running Airflow locally with DataHub.](https://datahubproject.io/docs/docker/airflow/local_airflow)
Error message:
`Broken DAG: [/opt/airflow/dags/lineage_backend_demo.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage_backend_demo.py", line 12, in <module>
    from datahub_provider.entities import Dataset, Urn
ImportError: cannot import name 'Urn' from 'datahub_provider.entities' (/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/entities.py)`

**To Reproduce**
1. Download docker compose file and DAG using the instruction - [step 1] (https://datahubproject.io/docs/docker/airflow/local_airflow)
2. run: `docker-compose up airflow-init`
![Screenshot 2023-01-22 at 23 18 30](https://user-images.githubusercontent.com/23636633/213945779-0a6318d1-bd54-48db-acf8-f11a3a7303a3.png)
4. run `docker-compose up`
5. open airflow web UI: http://localhost:58080/home
6. get an issue ![Screenshot 2023-01-22 at 23 32 07](https://user-images.githubusercontent.com/23636633/213945203-8472b71b-5195-4163-8f28-769230e1f910.png)

**Expected behavior**
I expected to get a working container with working sample DAG followed the article in documentation.

**Comment by hsheth2** [comment]
@Sergogga thanks for the report - we're looking into it.

**Comment by yoojin-finda** [comment]
Same 🖐🏻

**Comment by Sergogga** [comment]
@hsheth2 
Hello, maybe you need some extra information from my side?

**Comment by hsheth2** [comment]
I believe this is just that the docker image that the tutorial uses hasn't been updated in a while.

cc @treff7es
