### ISSUE TITLE
Azure OIDC using `email` field in `AUTH_OIDC_SCOPE` causing SSO failure

### ISSUE THREAD

**Issue by adamhowardprice** [datahub-project/datahub#7107]
Initially, I couldn't log into my DataHub instance with OIDC because my `email` field was empty in Azure AD.

It turns out that this field is empty for all employees at my company. This is because, for whatever reason, Rippling doesn't support filling out this field for employees, only the "work email" field.

My Azure admin filled in the field for me and then login worked as expected.

<img width="1446" alt="Screenshot 2023-01-23 at 12 11 53 PM" src="https://user-images.githubusercontent.com/602596/214105282-c3dc333d-ac5a-465e-9aea-93ab81bd822c.png">

Instead of `email`, I believe the right field to use may be "User Principal Name" (`upn`)?

In the DataHub helm chart, the env var for `AUTH_OIDC_SCOPE` cannot be customized. It is hardcoded in the template to `openid profile email`. https://github.com/acryldata/datahub-helm/blob/1c48990081a14009296cfbffb487f6c52d0418ea/charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml#L181-L182

I was considering opening a separate issue there to allow customization, but I assumed they would tell me to open an issue here instead, since I'm not sure what DataHub really requires for authentication.

**To Reproduce**
1. Create an Azure account without the email field populated in Azure AD
2. Try to log into a DataHub instance with SSO
3. See this page:
<img width="1141" alt="image (15)" src="https://user-images.githubusercontent.com/602596/214107119-fc574d10-c592-41cf-b9e3-3c7a17644d3a.png">

**Expected behavior**
Log-in should work as expected.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc
 - Version: 0.86.0

**Additional context**
DataHub version 0.95.0

**Comment by laulpogan** [comment]
@adamhowardprice, 0.9.5 has a known bug - could you try an update to the most recent edition?

**Comment by adamhowardprice** [comment]
A user without an email in his Azure AD reported the same issue with 0.9.6.1

**Comment by adamhowardprice** [comment]
@laulpogan ^

**Comment by szalai1** [comment]
Fix for this:
 https://github.com/acryldata/datahub-helm/pull/249/files

**Comment by adamhowardprice** [comment]
TYSM!

**Comment by aditya-radhakrishnan** [comment]
Since this is fixed, going to close this one! Thanks for reporting the bug

**Comment by adamhowardprice** [comment]
@aditya-radhakrishnan can we wait til I test it?

**Comment by aditya-radhakrishnan** [comment]
Sure, please report back when you get the chance!

**Comment by adamhowardprice** [comment]
This came up in `datahub-upgrade-job`:

```
    client.id = producer-1
    compression.type = none
    connections.max.idle.ms = 540000
    delivery.timeout.ms = 15000
    enable.idempotence = false
    interceptor.classes = []
    key.serializer = class org.apache.kafka.common.serialization.StringSerializer
    linger.ms = 0
    max.block.ms = 60000
    max.in.flight.requests.per.connection = 5
    max.request.size = 1048576
    metadata.max.age.ms = 300000
    metadata.max.idle.ms = 300000
    metric.reporters = []
    metrics.num.samples = 2
    metrics.recording.level = INFO
    metrics.sample.window.ms = 30000
    partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
    receive.buffer.bytes = 32768
    reconnect.backoff.max.ms = 1000
    reconnect.backoff.ms = 50
    request.timeout.ms = 3000
    retries = 3
    retry.backoff.ms = 500
    sasl.client.callback.handler.class = null
    sasl.jaas.config = null
    sasl.kerberos.kinit.cmd = /usr/bin/kinit
    sasl.kerberos.min.time.before.relogin = 60000
    sasl.kerberos.service.name = null
    sasl.kerberos.ticket.renew.jitter = 0.05
    sasl.kerberos.ticket.renew.window.factor = 0.8
    sasl.login.callback.handler.class = null
    sasl.login.class = null
    sasl.login.refresh.buffer.seconds = 300
    sasl.login.refresh.min.period.seconds = 60
    sasl.login.refresh.window.factor = 0.8
    sasl.login.refresh.window.jitter = 0.05
    sasl.mechanism = GSSAPI
    security.protocol = PLAINTEXT
    security.providers = null
    send.buffer.bytes = 131072
    ssl.cipher.suites = null
    ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
    ssl.endpoint.identification.algorithm = https
    ssl.key.password = null
    ssl.keymanager.algorithm = SunX509
    ssl.keystore.location = null
    ssl.keystore.password = null
    ssl.keystore.type = JKS
    ssl.protocol = TLS
    ssl.provider = null
    ssl.secure.random.implementation = null
    ssl.trustmanager.algorithm = PKIX
    ssl.truststore.location = null
    ssl.truststore.password = null
    ssl.truststore.type = JKS
    transaction.timeout.ms = 60000
    transactional.id = null
    value.serializer = class io.confluent.kafka.serializers.KafkaAvroSerializer

2023-01-24 21:21:48.790  INFO 1 --- [           main] i.c.k.s.KafkaAvroSerializerConfig        : KafkaAvroSerializerConfig values: 
    bearer.auth.token = [hidden]
    proxy.port = -1
    schema.reflection = false
    auto.register.schemas = true
    max.schemas.per.subject = 1000
    basic.auth.credentials.source = URL
    value.subject.name.strategy = class io.confluent.kafka.serializers.subject.TopicNameStrategy
    schema.registry.url = [http://datahub-prerequisites-cp-schema-registry:8081]
    basic.auth.user.info = [hidden]
    proxy.host = 
    use.latest.version = false
    schema.registry.basic.auth.user.info = [hidden]
    bearer.auth.credentials.source = STATIC_TOKEN
    key.subject.name.strategy = class io.confluent.kafka.serializers.subject.TopicNameStrategy

2023-01-24 21:21:49.204  WARN 1 --- [           main] o.a.k.clients.producer.ProducerConfig    : The configuration 'schema.registry.security.protocol' was supplied but isn't a known config.
2023-01-24 21:21:49.292  INFO 1 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 5.5.1-ccs
2023-01-24 21:21:49.292  INFO 1 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: cb1873c1fdf5f5f9
2023-01-24 21:21:49.293  INFO 1 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1674595309204
2023-01-24 21:21:49.397  INFO 1 --- [           main] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
ERROR LoggingFailureAnalysisReporter 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field kafkaHealthChecker in com.linkedin.gms.factory.kafka.DataHubKafkaEventProducerFactory required a bean of type 'com.linkedin.metadata.dao.producer.KafkaHealthChecker' that could not be found.

The injection point has the following annotations:
    - @javax.inject.Inject()
    - @javax.inject.Named(value="noCodeUpgrade")


Action:

Consider defining a bean of type 'com.linkedin.metadata.dao.producer.KafkaHealthChecker' in your configuration.

Stream closed EOF for datahub-dev/datahub-datahub-upgrade-job-lxbt7 (datahub-upgrade-job)
```

**Comment by adamhowardprice** [comment]
I tested it out but for some reason I can't get the `0.2.139` version of the Helm chart to correctly pull in the transitive dependency of `datahub-frontend` version `0.2.132`.

**Comment by adamhowardprice** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/602596/214448910-3a304f2a-947b-40b4-9ec2-c30b08174303.png">

**Comment by adamhowardprice** [comment]
I think this line is wrong: https://github.com/acryldata/datahub-helm/blob/gh-pages/index.yaml#L15

**Comment by adamhowardprice** [comment]
I deployed version `0.2.142` which is the the latest Helm chart and customized `AUTH_OIDC_SCOPE` to `openid profile` and I still got a user without an email in their Azure AD failing to log in:
![Screenshot 2023-01-25 at 2 45 04 PM](https://user-images.githubusercontent.com/602596/214709112-bbe45650-4052-4e29-890a-05ffb56d8450.png)
