### ISSUE TITLE
datahub-protobuf doesn't parse message comment correctly

### ISSUE THREAD

**Issue by tinolyu** [datahub-project/datahub#7114]
**Describe the bug**
datahub-protobuf doesn't parse message comment correctly

**To Reproduce**
1. Using datahub-protobuf 0.9.6
2. Modify `metadata-integration/java/datahub-protobuf/src/test/resources/protobuf/messageB.proto`, add message `OuterMessage` above message `MessageB` and compile proto.
```
// Description for OuterMessage
message OuterMessage {
  MessageB messageB = 1;
}
```
3. Add the function `getTestProtobufGraph` in `metadata-integration/java/datahub-protobuf/src/test/java/datahub/protobuf/TestFixtures.java` and modify `metadata-integration/java/datahub-protobuf/src/test/java/datahub/protobuf/visitors/dataset/DescriptionVisitorTest.java` to find the root message
```
public static ProtobufGraph getTestProtobufGraph(String protoPackage, String filename, String m) throws IOException {
    return new ProtobufGraph(getTestProtobufFileSet(protoPackage, filename), m);
}
```
```
ProtobufGraph graph = getTestProtobufGraph("protobuf", "messageB", "protobuf.MessageB");
```
4. Run the test 

**Expected behavior**
I hope to get the description of `MessageB`
```
/**
 * This contains nested types.
 *
 * Owned by TeamB
 */
```
But it read the description of `OuterMessage`.

**Comment by tinolyu** [comment]
It seems [this PR](https://github.com/datahub-project/datahub/pull/6959/files#diff-4872a7f92847b5516231ee186146402b6b7a38f81353db57f1f486411f5a1e73R27) removed the message check `messageProto() == fileProto().getMessageType(loc.getPath(1))` in `datahub.protobuf.model.ProtobufElement`, and it now could not parse the message comment correctly if there are multiple messages in a proto file.

**Comment by tinolyu** [comment]
My solution is to add an overwritten `messageLocations()` for `datahub.protobuf.model.ProtobufField` and add `messageProto() == fileProto().getMessageType(loc.getPath(1)) in datahub.protobuf.model.ProtobufElement` back to `datahub.protobuf.model.ProtobufElement.messageLocations()`.
```
    public Stream<DescriptorProtos.SourceCodeInfo.Location> messageLocations() {
        List<DescriptorProtos.SourceCodeInfo.Location> fileLocations = fileProto().getSourceCodeInfo().getLocationList();
        return fileLocations.stream()
                .filter(loc -> loc.getPathCount() > 1
                        && loc.getPath(0) == FileDescriptorProto.MESSAGE_TYPE_FIELD_NUMBER
                );
    }
```

**Comment by david-leifker** [comment]
I believe this was fixed [here](https://github.com/datahub-project/datahub/commit/65c275979b4f12fe98572fdce674df12219d6d0b) ?

**Comment by tinolyu** [comment]
Is it in the v0.9.6.1?

> I believe this was fixed [here](https://github.com/datahub-project/datahub/commit/65c275979b4f12fe98572fdce674df12219d6d0b) ?

**Comment by tinolyu** [comment]
`Could not find io.acryl:datahub-protobuf:0.9.6.1`
It seems this dep couldn't be found.

**Comment by tinolyu** [comment]
> I believe this was fixed [here](https://github.com/datahub-project/datahub/commit/65c275979b4f12fe98572fdce674df12219d6d0b) ?

It still couldn't work.

**Comment by david-leifker** [comment]
0.9.6.1 doesn't contain the fix, would be included in the next release. Will add test to verify.
