### ISSUE TITLE
Original path gets lost in OIDC flow

### ISSUE THREAD

**Issue by mattbonnell** [datahub-project/datahub#7115]
**Describe the bug**
If a non-logged user clicks a link to some path within DataHub, they'll get redirected to OIDC login. After completing login, this original path is lost, and they get dumped back at the homepage.

**To Reproduce**
1. Copy a link to some entity in your DH
2. Open it in incognito
3. Sign in
4. You'll be redirected to the homepage

**Expected behavior**
The original path should be remembered and the user should be redirected there after logging in.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jjoyce0510** [comment]
This was recently fixed by this PR: https://github.com/datahub-project/datahub/pull/7011.

Should appear in new releases.

**Comment by aditya-radhakrishnan** [comment]
@mattbonnell we will confirm that this is fixed with the next release and then close it out if it is! Thanks for reporting this issue.
