### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by thewizkid87** [datahub-project/datahub#7133]
**Describe the bug**
Broken link in documentation for metadata ingestion

**To Reproduce**
1. Go to https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/README.md
2. Click on example links - eg. https://github.com/datahub-project/datahub/blob/master/docs/generated/ingestion/sources/bigquery.md
![image](https://user-images.githubusercontent.com/39795021/214530613-991d945a-144f-4c20-bd0a-b08766bb6bc4.png)
3. Leads to 404

I tried also different branches

**Expected behavior**
Reach requested doc.

**Context**
I am looking to create a custom ingestion for datahub, i want to see an example of one written and working. For example BigQuery.
Any other links that can help will be much appriciated.

**Comment by chriscollins3456** [comment]
@thewizkid87 - thanks so much for calling this out! I just created a PR to fix those links: https://github.com/datahub-project/datahub/pull/7183

Once that gets merged and we confirm the links are looking good I'll close this PR

**Comment by thewizkid87** [comment]
@chriscollins3456 
Thank you :-) Will look in the commit

**Comment by chriscollins3456** [comment]
closing!
