### ISSUE TITLE
User Roles not being properly assigned.

### ISSUE THREAD

**Issue by jjoyce0510** [datahub-project/datahub#7138]
**Describe the bug**

When you assign a role to an existing user from Groups page, and then refresh the page, it's non-deterministic but in some cases it appears that the role was not applied. 

Relevant thread: https://datahubspace.slack.com/archives/C029A3M079U/p1671717473032899

**Comment by kkrishnan** [comment]
hi Team,
this issue is consistently occurring on a self-hosted platform. The version of Datahub is 0.10.5. Please assist
