### ISSUE TITLE
Support Domains for DBT ingestion

### ISSUE THREAD

**Issue by Vimpy** [datahub-project/datahub#7143]
Currently for DBT manifest ingestion we are not able to attach our metadata to domains. 

.....

**Comment by chriscollins3456** [comment]
hey @Vimpy! This is true - would you mind opening a feature request [here](https://feature-requests.datahubproject.io/) instead?

In the meantime before the team can prioritize this, I would suggest a few other options to add domains to ingested data:
- Using a transformer: https://datahubproject.io/docs/metadata-ingestion/docs/transformer/dataset_transformer#simple-add-dataset-domains
- Using the CSV enricher: https://datahubproject.io/docs/generated/ingestion/sources/csv/#module-csv-enricher
- Bulk applying domains through the UI (demo'd in our July townhall last year: https://www.youtube.com/watch?v=Zrkf3Mzcvc4)

**Comment by Vimpy** [comment]
@chriscollins3456 Thanks for the help. I posted my issue in the roadmap
