### ISSUE TITLE
Can't logout with OIDC from v0.9.1

### ISSUE THREAD

**Issue by sunli1223** [datahub-project/datahub#7144]
I used Keycloak as  the OIDC provider,  when datahub add the function "Login with SSO button on the login page." from v0.9.1,logOut just only logout itself, it didn't redirect to keycloak to logout keycloak session anymore from v0.9.1. 
So, when you click logout, then click the button "sign in with sso", you don't need enterpassword in keyclock, you will directly log in to datahub successfully.

https://user-images.githubusercontent.com/3821439/214895833-6c87e368-a0d4-4021-8b09-e32296028a8b.mp4

**Comment by jjoyce0510** [comment]
Yes this is a known issue.

This is because we use the end_session_endpoint in the OIDC protocol to log folks out. In this case, it seems that Keycloak _does not support_ that endpoint. Therefore we are unable to clear the user's session when they log out.

There is another option (token revocation endpoint) but it is not prioritized for implementation at this time. 

What material impact is this having on your users?

Cheers
John

**Comment by sunli1223** [comment]
> Yes this is a known issue.
> 
> This is because we use the end_session_endpoint in the OIDC protocol to log folks out. In this case, it seems that Keycloak _does not support_ that endpoint. Therefore we are unable to clear the user's session when they log out.
> 
> There is another option (token revocation endpoint) but it is not prioritized for implementation at this time.
> 
> What material impact is this having on your users?
> 
> Cheers John

The Keycloak have the end_session_endpoint, the version of datahub before v9.0.1, the logout for SSO works normallly, when click logOut, datahub will redirect to Keycloak to log out the Keycloak session.
![image](https://user-images.githubusercontent.com/3821439/214978848-32570035-524d-4226-918f-96eaab1ddc40.png)

**Comment by caiopavanelli** [comment]
Is this related? https://github.com/datahub-project/datahub/issues/7221

**Comment by KonstantinVishnivetskii** [comment]
Same issue

**Comment by KonstantinVishnivetskii** [comment]
Issue is relevant to current release 0.10.4

**Comment by bandla-himateja** [comment]
I am facing the same issue  @jjoyce0510. Is there any plans to fix this in the coming releases?

**Comment by iilrgmv** [comment]
Hello! I'm also facing the same issue in version v1.2.0
