### ISSUE TITLE
Ingestion run on Snowflake fails with json.decoder.JSONDecodeError:

### ISSUE THREAD

**Issue by fg-pt** [datahub-project/datahub#7156]
the ingestion run on Snowflake using GOVERNANCE_VIEWER_ROLE as per this [documentation](https://docs.snowflake.com/en/sql-reference/snowflake-db-roles.html) fails.

here's the full traceback, not sure what is happening:

```
~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': 'f17b891d-3c89-4d57-b659-7ee445d1af3c',
 'infos': ['2023-01-27 16:39:39.553327 [exec_id=f17b891d-3c89-4d57-b659-7ee445d1af3c] INFO: Starting execution for task with name=RUN_INGEST',
           '2023-01-27 16:39:39.570981 [exec_id=f17b891d-3c89-4d57-b659-7ee445d1af3c] INFO: Caught exception EXECUTING '
           'task_id=f17b891d-3c89-4d57-b659-7ee445d1af3c, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 70, in execute\n'
           '    recipe: dict = SubProcessTaskUtil._resolve_recipe(validated_args.recipe, ctx, self.ctx)\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_task_common.py", line 107, in _resolve_recipe\n'
           '    json_recipe = json.loads(resolved_recipe)\n'
           '  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads\n'
           '    return _default_decoder.decode(s)\n'
           '  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode\n'
           '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n'
           '  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode\n'
           '    obj, end = self.scan_once(s, idx)\n'
           "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 204 (char 203)\n"]}
Execution finished with errors.
```

**Comment by mayurinehate** [comment]
From the error message, the issue does not seem to be with snowflake ingestion process but, rather on recipe resolution side. It appears that you are using managed ingestion.

Can you please share the recipe you are using ? It need not be complete but primarily including all the config keys you are using. You can replace config values with masked representation.

It would also be great if you can mention DataHub version and whether you are using Managed Secrets in UI.

**Comment by fg-pt** [comment]
lol that worked. It's funny because I thought I had tried that already, I guess I hadn't. 

So ye if I type in the password without using the secret it works, and my password is not ASCII only. For now that's ok because I can at least use it, i'll keep an eye out for the fix, thanks!

**Comment by mayurinehate** [comment]
Wow ! Thanks for checking @fg-pt.

Would you mind sharing the non ASCII characters that were part of your password ? It would greatly reduce time to reproduce this issue and fix it.

**Comment by fg-pt** [comment]
sure, here they are: 
_
£
"
$
