### ISSUE TITLE
Does DataHub plan support Table and Column level lineage for Apache Hive

### ISSUE THREAD

**Issue by bigdata-spec** [datahub-project/datahub#7167]
@treff7es Hi, Apache Hive is common data warehouse，But I find in the datahub **Hive  Lineage  is grey**，Does DataHub plan support Table and Column level lineage for Apache Hive in next version？Thank you very much.

**Comment by chriscollins3456** [comment]
hi @bigdata-spec! right now we have no plans on supporting automatic lineage extraction from Hive. You can always emit your own custom lineage either with a [Python emitter](https://datahubproject.io/docs/lineage/lineage-feature-guide/#using-dataset-to-dataset-lineage) or through [file-based lineage ingestion](https://datahubproject.io/docs/generated/ingestion/sources/file-based-lineage)! However it's a more manual process either way.

I would also suggest opening up a feature request for this so we can keep track of it and prioritize it appropriately: https://feature-requests.datahubproject.io/

**Comment by chriscollins3456** [comment]
closing for now
