### ISSUE TITLE
Tableau ingestion fails when applying string methods to NoneType variables

### ISSUE THREAD

**Issue by khgould** [datahub-project/datahub#7182]
**Describe the bug**
Tableau ingestion fails when an asset's view metadata (identified as csql) has the "query" key but the value is None. The clean_query method fails because it tries to apply a string method on a NoneType object. 

**To Reproduce**
1. Run tableau ingestion on a project that has a view without defined sql. 
2. See error: 
> File` "/usr/local/lib/python3.9/site-packages/datahub/ingestion/source/tableau.py", line 896, in emit_custom_sql_datasources
    viewLogic=clean_query(csql.get("query", "")),
  File "/usr/local/lib/python3.9/site-packages/datahub/ingestion/source/tableau_common.py", line 623, in clean_query
    query = query.replace("<<", "<").replace(">>", ">").replace("\n\n", "\n")
AttributeError: 'NoneType' object has no attribute 'replace'

**Expected behavior**
I believe the intent is to have the query be an empty string when its NoneType

**Screenshots**
![Uploading image.png…]()

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - Version: latest

**Additional context**

**Comment by hsheth2** [comment]
@khgould thanks for the report. This should be fixed by https://github.com/datahub-project/datahub/pull/7186.
