### ISSUE TITLE
Tableau Datasets display UUID in auto-complete instead of name

### ISSUE THREAD

**Issue by chriscollins3456** [datahub-project/datahub#7193]
**Describe the bug**
When searching for a Tableau dataset, you only see the random UUID in the auto-complete box instead of the name of the entity. This is because we get the name of a dataset from the datasetKey and the URN, and we mint UUIDs as the name for Tableau datasets.

**To Reproduce**
1. Go to an env that contains Tableau datasets
2. Search for one of them
3. Find a UUID in the search box:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/28656603/215800394-a6d87a97-568b-4f47-bc91-0df31f670362.png">

**Expected behavior**
We display the name of the dataset properly.

**Additional context**
This could be fixed by ingestion minting names and not UUIDs in the urn. Or we could display names from properties and not from dataset keys in the auto-complete results (although we would lose some context here as the names from the keys include other info like database and schema). Or we could specifically render names from properties instead of the key only for tableau entities here.

**Comment by bossenti** [comment]
As fare as I observed this is fixed in DataHub `0.10.0`
