### ISSUE TITLE
database names with uppercase, ingest will report pymysql.err.OperationalError: (1049, "Unknown database 'xxx'")

### ISSUE THREAD

**Issue by kpretty** [datahub-project/datahub#7208]
**Describe the bug**
if the name of the database to be ingested is a Test, the ingestion task will report：pymysql.err.OperationalError: (1049, "Unknown database 'atest'")

**To Reproduce**
1. create a database that includes uppercase, e.g. aTest
2. execute ingest
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/77819741/216022029-fa14f0da-da1a-4d03-b0bc-0464853369f1.png">

**Desktop (please complete the following information):**
 - OS: mac os
 - Version 0.9.2.4

**Additional context**
I've seen in the get_db_name method in sql_common.py convert to lowercase when getting the database name, I don't quite understand why it's doing that. The database name is case-sensitive. I commented out the lowercase conversion logic in the project to meet my needs. I don’t know what the logic of this step is? What is the effect of deleting
<img width="600" alt="image" src="https://user-images.githubusercontent.com/77819741/216023183-b2449546-99f4-45fe-b5e4-0011710f520a.png">

**Comment by kpretty** [comment]
更正一下bug截图，postman中的截图是对其的二次封装，下面的就是使用datahub ingest run -c recipe.yml
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/77819741/216029534-32559bba-9a63-4e5f-8256-e0f7568e903b.png">

**Comment by kpretty** [comment]
link pr #7209

**Comment by mayurinehate** [comment]
Hi @kpretty 

Can you help with DataHub CLI version on which you encountered the mentioned issue ?

For MySQL, `get_db_name` from sql_common is not used however `get_db_name` from [TwoTierSQLAlchemySource](https://github.com/datahub-project/datahub/blob/f9bd20d908349ab5a4a73473ac189fe5d867e188/metadata-ingestion/src/datahub/ingestion/source/sql/two_tier_sql_source.py#L123) is used in latest versions and it already has this fix.

**Comment by kpretty** [comment]
@mayurinehate 
thx, upgrading to the latest version has resolved the issue
