### ISSUE TITLE
[DataHub CLI] Problems deleting time-series aspects

### ISSUE THREAD

**Issue by PatrickfBraz** [datahub-project/datahub#7212]
**Describe the bug**

I implemented integration with a Data Quality tool that extracts the metadata from APIs and ingests Assertion metadata into DataHub. After a period of tests, I discovered that the integration creates a BUG in the DataHub UI. The problem is that Assertion soft-deleting does not guarantee that the assertion metadata stops to appears on the UI. So, stateful ingestion for Assertion is not working correctly. 

I thought deleting Assertions would guarantee that the search service only searches for time-series aspects if the Assertion has the Status aspect with the value remove=false, which is not true.

Besides, another problem appeared when I tried to delete the assertionRunEvent.  Running the command below returns a message that all my datasets entities should be hard deleted (because time-series aspects could only be hard deleted). 

```shell
datahub delete -p <platform> -a assertionRunEvent --hard
```

Still, I tried to delete the aspects and got the error message below.

> This will permanently delete X entities. Are you sure? [y/N]: y
Failed to execute operation                                                                                                                                                                   
  0% (0 of 65) |                                                                                                                                         | Elapsed Time: 0:00:00 ETA:  --:--:--
java.lang.UnsupportedOperationException: Not supported for non-timeseries aspect '{}'.

**To Reproduce**
1. Ingest Assertion metadata and some assertionRunEvent 
2. Soft delete the Assertion and check the validation tab on the UI.
3. Try to hard delete the assertionRunEvent aspect ingested.

**Expected behavior**

After soft or hard deleting the Assertion, no metadata appears on the UI, and the validation tab appears to be blocked to the user.

**Screenshots**

I hard deleted the Assertions:
![image](https://user-images.githubusercontent.com/25487679/216067263-79848c5e-231d-4fb4-a866-7aa7ae013528.png)

But the validation tab is stills available:
![image](https://user-images.githubusercontent.com/25487679/216067474-a11d738e-53f1-462f-8dea-c157eb07dea0.png)

Entering the validation tab, the screen appears all white:

![image](https://user-images.githubusercontent.com/25487679/216067791-471c8bd1-6168-4b30-a862-b06b7ea7d8da.png)

The graphql returns the assertions info:

![image](https://user-images.githubusercontent.com/25487679/216068328-c3b441bd-eba2-44dd-9615-ecc5dcfcb912.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - DataHub version: 0.9.6.1
 - Deployment: Helm - Google Kubernetes Engine
 - Kubernetes version: v 1.21
 - Elasticsearch version: 7.17.3 - [Chart](https://artifacthub.io/packages/helm/elastic/elasticsearch/7.17.3)

**Comment by YuriyGavrilov** [comment]
There is also https://github.com/datahub-project/datahub/issues/6733 regarding delete CLI.

**Comment by mayurinehate** [comment]
For 1 - the cli command needs to be updated to set entity_type as assertion.

`datahub delete -p <platform> -a assertionRunEvent --hard --entity-type assertion`
