### ISSUE TITLE
Typo in the docker-compose-without-neo4j.quickstart.yml file

### ISSUE THREAD

**Issue by amartinson193** [datahub-project/datahub#7255]
**Describe the bug**
There is a typo in the quickstart file. I had to nuke my docker instance of datahub and noticed it when I re-downloaded. I'm not sure if this is what caused my issue, but still wanted to correct it. The other thing I changed was adding version v0.9.6.1 to my `datahub docker quickstart` command.

**To Reproduce**
1. Run `datahub docker quickstart`

**Expected behavior**
I expected the quickstart to pull all of the docker images without an error.

**Desktop (please complete the following information):**
 - OS: MacOs Monterey 12.5.1
 - Browser Chrome
 - Version 12.5.1

**Comment by amartinson193** [comment]
```
      - curl -sS --fail 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=0s' 
|| exit 1 
```
This is the line with the typo, I think the || exit needs to be on the same line as curl

**Comment by vldt-aem** [comment]
This issue was fixed in this commit: https://github.com/datahub-project/datahub/commits/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml
