### ISSUE TITLE
The GX urn does not match with datahub bigquery urn

### ISSUE THREAD

**Issue by raigaurav2387** [datahub-project/datahub#7300]
**Describe the bug**
The urn generated by great expectations for bigquery does not match it from bigquery urn on datahub. Due to which GX quality checks doesnt reflect on datahub for urns which are not in lowercase.

**To Reproduce**
1. Ingest bigquery metadata to datahub with convert_urns_to_lowercase: True.
2. Once it reflects on data hub, write quality checks using GX and post them with acryl-datahub[great-expectations] to gms endpoint.

**Expected behavior**
Both urns from GX and datahub should match 
Datahub:  urn:li:dataset:(urn:li:dataPlatform:bigquery,project_name.fbt.fbt_diff,PROD)
GX:           urn:li:dataset:(urn:li:dataPlatform:bigquery,project_name.fbt.fbt_diff,PROD)

**Screenshots**
urn generated
Datahub:  urn:li:dataset:(urn:li:dataPlatform:bigquery,project_name.fbt.fbt_diff,PROD)
GX:           urn:li:dataset:(urn:li:dataPlatform:bigquery,project_name.FBT.fbt_diff,PROD)

**Desktop (please complete the following information):**

**Additional context**

**Comment by mayurinehate** [comment]
We could get around this by supporting a similar flag `convert_urns_to_lowercase` in GX integration. WDYT ?
