### ISSUE TITLE
Why is acryl-datahub Python package uninstalled in datahub-ingestion Docker image?

### ISSUE THREAD

**Issue by askarbozcan** [datahub-project/datahub#7350]
**Describe the bug**
Layer 27 of datahub-ingestion image: [link](https://hub.docker.com/layers/acryldata/datahub-ingestion/a4065fe/images/sha256-46f524728789068c5d134d3245694ead9fd20c09ab7663cdd8386d299483b322?context=explore)

requirements.txt is installed, and then acryl-datahub package is removed, forcing me to redownload it for my own custom image, as I am using datahub-ingestion image for programmatic metadata ingestion.

**To Reproduce**
1. Pull datahub-ingestion image
2. acryl-datahub Python package is uninstalled

**Comment by hsheth2** [comment]
@askarbozcan it is reinstalled in layer 31. We do this to speed up our docker build times.
