### ISSUE TITLE
typing-extensions import error  with 0.10.0.1

### ISSUE THREAD

**Issue by ADraginda** [datahub-project/datahub#7370]
**Describe the bug**

**To Reproduce**

* python 3.7.15 on mac and ubuntu (fails in both)
* acryl-datahub  0.10.0.1 
*  typing-extensions 3.10.0.2

```python
import datahub.emitter.mce_builder as builder
```

results in 
```
ImportError: cannot import name 'Self' from 'typing_extensions' 
```

The docs suggest that my typing-extensions should be good enough (see [here](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/setup.py#L21)), and indeed - we're on airflow 2.0.2 right now

**Comment by cburroughs** [comment]
Note that `Self` only is available in in typing-extensions >= 4.0.0 https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#added-in-version-400
