### ISSUE TITLE
Inconsistent URN casing in DBT ingestion

### ISSUE THREAD

**Issue by alex-magno** [datahub-project/datahub#7377]
**Describe the bug**
DBT ingestion deals with three main URNs during ingestion: the model name, the table name in source platform (bigquery, snowflake, etc.) and the column name. During ingestion, the **table identifier** is getting lowercased and the others are not.

- **model_name** preserves what is being used at the manifest: https://github.com/datahub-project/datahub/blob/1df806d1773b845759939e9574847b5d3ee84de8/metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py#L138-L148
- **table identifier (db_fqn)** is being lowercased: https://github.com/datahub-project/datahub/blob/aa388f04c2dc1cac945d5219ce8a8437e9f90cb4/metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py#L400
- **column URN** preserves what is being used at the catalog: https://github.com/datahub-project/datahub/blob/1df806d1773b845759939e9574847b5d3ee84de8/metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_core.py#L113

I'm using DBT with Snowflake and this is causing two bug scenarios:

1. When I do snowflake ingestion with `convert_urns_to_lowercase=False`:
Then I get a mismatch between the table identifier urn coming from snowflake (not being lowercased) with the table identifier from DBT (db_fqn), that is actually being lowercased. So nodes are not matching.

2. When I do snowflake ingestion with `convert_urns_to_lowercase=True`:
Now table identifiers are matching (both URNs are lowercased), but then the column identifiers mismatch. Because the snowflake ingestion will convert the column URNs to lowercase, while DBT preserves column casing. And the result is a schema view with duplicated columns (lower and uppercase).

**To Reproduce**
1. Ingest DBT using `snowflake` as the target_platform
2. Ingest snowflake metadata with `convert_urns_to_lowercase=False`. Observe the first bug described.
3. Ingest snowflake metadata with `convert_urns_to_lowercase=True`. Observe the second bug described.

**Expected behavior**
Columns and tables identifiers should match between DBT and source platform. Ideally, casing in DBT should be consistent - either lowercasing everything or preserving case in every identifier.

As I suggestion, **I can submit a PR to introduce a `convert_urns_to_lowercase` flag** to the DBT recipe as well, so users can decide if they want to lowercase or not every identifier. At least to make the behavior consistent.

**Screenshots**
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/87935605/220076934-f70d0824-4270-4dbc-bb1e-6606d8cfcc6f.png">
Column names being duplicated when using `convert_urns_to_lowercase=True` in Snowflake ingestion.

**Comment by remisalmon** [comment]
I am having the same issue starting with v0.10.0 where dbt and Snowflake columns are showing twice in upper and lower cases (with `convert_urns_to_lowercase=true` in Snowflake config), this looks like a regression that was introduced by https://github.com/datahub-project/datahub/pull/7063? Not having this issue with v0.9.5.
