### ISSUE TITLE
Incomplete intake data

### ISSUE THREAD

**Issue by qzl965678745** [datahub-project/datahub#7422]
Datahub version 0.9.5
Ingestion source：mysql

The questions are as follows：
1.The first intake of data source is full intake, which is no problem
2.Then add a new table in the database. When you ingest it again, you find that the new table is not displayed
![image](https://user-images.githubusercontent.com/38179264/221101779-33cef509-abb4-4655-94ea-4446002c0ded.png)
3.The new table in the previous step will be displayed only after the third intake
This bug is bound to recur. We have tested mysql, es, clickhouse, sqlserver, and oracle

**Comment by hsheth2** [comment]
@qzl965678745 are you finding that it reliably doesn't show up on the second run and reliably does show up on the third run?

**Comment by 2442603467** [comment]
> @qzl965678745 are you finding that it reliably doesn't show up on the second run and reliably does show up on the third run?

yes, its 100% happened in 0.9.5,  but it doesnot happen in 0.10.0. 
but in 0.10.0 ingestion, database and schema only  can fetch increment data (dont  contain deleted data),i wanna to get the full data with database and schema ,how can i do it?
