### ISSUE TITLE
PyAthena extra with version prior to 2.11.0 fails to install via latest Poetry (1.4.0)

### ISSUE THREAD

**Issue by jrouly** [datahub-project/datahub#7491]
**Describe the bug**

Installing the `acryl-datahub` package with the `athena` extras brings in `pyathena@2.4.1`. However, Poetry 1.4.0 is unable to install this version of `pyathena`, _likely_ due to https://github.com/pypa/installer/issues/97 but directly caused by https://github.com/python-poetry/poetry/issues/7572.

**To Reproduce**

1. Add `acyrl-datahub` with the `athena` extras at the latest version `v0.10.0` to `pyproject.toml`.
2. Attempt to `poetry install` with a fresh virtual environment.
3. Notice the following error:

```
  KeyError

  "There is no item named 'PyAthena-2.4.1.dist-info/WHEEL' in the archive"

  at /usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py:1438 in getinfo
      1434│     def getinfo(self, name):
      1435│         """Return the instance of ZipInfo given 'name'."""
      1436│         info = self.NameToInfo.get(name)
      1437│         if info is None:
    → 1438│             raise KeyError(
      1439│                 'There is no item named %r in the archive' % name)
      1440│
      1441│         return info
      1442│
```

**Expected behavior**

Successful installation.

**Comment by hsheth2** [comment]
As per https://github.com/python-poetry/poetry/issues/7572#issuecomment-1474400923, this should be resolved?

Either way, I'm not sure we can really do anything about this one - we're at the mercy of poetry / python installer.
