### ISSUE TITLE
v0.10.0 doesn't create 'auth-secrets' secret when metadata_service_authentication is enabled in the helm chart

### ISSUE THREAD

**Issue by nachiket-juneja** [datahub-project/datahub#7508]
**Describe the bug**
We've been trying to install the latest 0.10.0 version of DataHub and we feel there is a bug. We currently have enabled the metadata_service_authentication flag in the value.yaml in the helm installation. We are now moving to 0.10.0 using chart version 0.2.154.
When metadata_service_authentication value is true, the system-update job fails with the CreateConfigError since the 'datahub-auth-secrets' secret doesn't get created. On the other hand, if we put metadata_service_authentication as false, the system update job passes and the secret is also created successfully.
Maybe an issue with the helm templates which creates the secret. Unsure about the root cause, but I think this could be a potential problem.
Please let me know if this is the desired behavior or we are missing something.

**To Reproduce**
1. Enable metadata_service_authentication to true in the 'global' section in the values.yaml for the datahub helm chart
2. Set the datahub version to 0.10.0
3. Run the helm install command. The system-update-job throws an ContainerConfigError since the datahub-auth-secrets secret is not created.

**Expected behavior**
Datahub should have installed successfully without any errors

**Comment by matthijsvanderloos** [comment]
I created an issue for this in the DataHub Helm repo as well: https://github.com/acryldata/datahub-helm/issues/265

**Comment by nachiket-juneja** [comment]
Any updates on this?

**Comment by jinlintt** [comment]
Any updates on this? We are seeing exactly same issue.

**Comment by MadisLemsalu** [comment]
Same issue here
