### ISSUE TITLE
Quick-Start: three containers just quit

### ISSUE THREAD

**Issue by jarrelldunson** [datahub-project/datahub#7545]
Trying to run quick start 

I am running quick start... three contains just start and quit:
- Container datahub-upgrade
- Container elasticsearch-setup
- Container kafka-setup

Context
-----------------------------------------------------
I. First issue:   The docker-compose.yaml was empty (solved)
-----------------------------------------------------
A. Problem:  	I tried to run quickstart and the docker-compose.yaml was empty... 

`%> datahub docker quickstart `
- Found there was no info in the .datahub/quickstart directory. The docker-compose.yaml was empty... 

B. Solution:	Per Slack, I download this file: 
https://github.com/datahub-project/datahub/blob/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml 
... to the C:\Users\<username>\.datahub\quickstart\ directory 
... and ran this: 

`%> datahub docker quickstart --quickstart-compose-file C:\Users\<username>\.datahub\quickstart\docker-compose-without-neo4j.quickstart.yml`

----------------------------------------------
II. Second Issue: MySQL error (solved)
----------------------------------------------

A. Problem 		MySQL port already taken 

```
%> datahub docker quickstart --quickstart-compose-file C:\Users\<username>\.datahub\quickstart\docker-compose-without-neo4j.quickstart.yml

Container mysql                Starting                                                                         1.1s
Error response from daemon: driver failed programming external connectivity on endpoint mysql (88ae54d557be1fa51d6615476d653244c8dba7a8cbdd53d8f941cf479820651a): Bind for 0.0.0.0:3306 failed: port is already allocated
...........
```

B.  Solution:  	Move to port 3307 

I ran this... and saw the port was being allocated already:

```
PS C:\Users\jdunson> Get-NetTCPConnection | where Localport -eq 3306  | select Localport,OwningProcess

Localport OwningProcess
--------- -------------
     3306         18956
     3306         11160

```
I edited docker-compose-without-neo4j.quickstart.yml (changing 3306 to 3307)

----------------------------------------------
III. Third Issue: Three containers just start and quit
----------------------------------------------

A. Problem 	Three containers will not stay running: 
- Container datahub-upgrade       
- Container elasticsearch-setup
- Container kafka-setup

```
%> datahub docker quickstart --quickstart-compose-file C:\Users\<username>\.datahub\quickstart\docker-compose-without-neo4j.quickstart.yml

[+] Running 12/12
 - Container mysql                      Running                                                                    0.0s
 - Container zookeeper                  Running                                                                    0.0s
 - Container datahub-upgrade            Started                                                                    1.0s
 - Container mysql-setup                Running                                                                    0.0s
 - Container broker                     Running                                                                    0.0s
 - Container elasticsearch              Running                                                                    0.0s
 - Container datahub-gms                Running                                                                    0.0s
 - Container schema-registry            Running                                                                    0.0s
 - Container kafka-setup                Started                                                                    1.1s
 - Container datahub-datahub-actions-1  Running                                                                    0.0s
 - Container elasticsearch-setup        Started                                                                    1.0s
 - Container datahub-frontend-react     Running                                                                    0.0s

```
This kept running, with multiple attempts... then I got this error: 

If you think something went wrong, please file an issue at https://github.com/datahub-project/datahub/issues
or send a message in our Slack https://slack.datahubproject.io/
Be sure to attach the logs from C:\Users\jdunson\AppData\Local\Temp\tmpydc8kqmn.log

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version Version 110.0.5481.180 (Official Build) (64-bit)

**Additional context**
 - I have docker on an external SSD Drive 
 - Attached in the log file
[tmpydc8kqmn.log](https://github.com/datahub-project/datahub/files/10946180/tmpydc8kqmn.log)
![dockercontainers](https://user-images.githubusercontent.com/10639390/224430440-9446f9dc-6402-4c23-8a28-a6622ebfde08.png)

**Comment by hsheth2** [comment]
The *-setup jobs and the datahub-upgrade job are supposed to exit with status 0. The quickstart CLI should handle that piece and alert if there's issues.

You can use the --mysql-port option of quickstart to change the port.
