### ISSUE TITLE
Add Support for ElasticSearch version 7.17.6

### ISSUE THREAD

**Issue by acherla** [datahub-project/datahub#7549]
**Describe the bug**
Datahub currently only supports elasticsearch up till 7.17.3, upgrading past this minor release version results in a number of issues leveraging datahub potentially due to several API changes.  Linked to https://github.com/datahub-project/datahub/issues/7500

**To Reproduce**
1. Install docker container for elasticsearch version 7.17.6
2. Run automated elasticSetup job
3. Run the upgrade job
4. Restart GMS
5. Log into frontend using datahub:datahub
6. Click on settings, no admin privilege's.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by justmike1** [comment]
I use elasticsearch 7.17.9 without any issues, can you try to update to it?
