### ISSUE TITLE
Ability to specify platform instance on BigQuery

### ISSUE THREAD

**Issue by Idane** [datahub-project/datahub#7596]
We use platform instance in order to pair the metadata with a specific ingestion source in a way that is visible from the API. When configuring platform instance on BigQuery, we receive the following error: "BigQuery project ids are globally unique. You do not need to specify a platform instance."

Is there any workaround to this issue?

**Comment by hsheth2** [comment]
We probably aren't going to add platform_instance for BigQuery

If you want to tag each dataset with it's ingestion run, you could use a dataset tag transformer as described here https://datahubproject.io/docs/metadata-ingestion/docs/transformer/dataset_transformer#simple-add-dataset-globaltags
