### ISSUE TITLE
"datahub docker quickstart --backup" is not working

### ISSUE THREAD

**Issue by resulraveendran** [datahub-project/datahub#7604]
Hi,

     When i try to get backup of my datahub using this "datahub docker quickstart --backup" command i got Error: No such container: mysql 
       I changed mysql container name to datahub-mysql  in dockercompose file (docker-compose-without-neo4j.quickstart.yml) to identify easly.But now i cant do backup for mysql.
           Is there any way to change that mysql to  datahub-mysql in this "datahub docker quickstart --backup"

**Comment by hsheth2** [comment]
The backup command requires that you run datahub using `datahub docker quickstart`. It does not support changing the names of the containers.
