### ISSUE TITLE
PowerBI validation error for admin_apis_only config parameter

### ISSUE THREAD

**Issue by jkaelin** [datahub-project/datahub#7625]
**Describe the bug**
Specifying a value in the config for `admin_apis_only` triggers a validation failure.

**To Reproduce**
1. Configure PowerBI ingestion, setting a value for `admin_apis_only` [both `true` & `false` cause the issue]
2. Execute the ingestion
3. Receive validation error: 
```
Failed to configure the source (powerbi): 1 validation error for PowerBiDashboardSourceConfig
admin_apis_only
  extra fields not permitted (type=value_error.extra)
```

**Expected behavior**
`admin_apis_only` should be supported based on the documentation:
https://datahubproject.io/docs/generated/ingestion/sources/powerbi#config-details

**Other details**
Similar issues are found here:
https://github.com/datahub-project/datahub/search?q=extra+fields+not+permitted&type=issues

**Environment**
Using latest docker quickstart.

**Comment by hsheth2** [comment]
That flag was added somewhat recently, so you may need to set your cli version through the UI as described here https://datahubproject.io/docs/ui-ingestion/#advanced-running-with-a-specific-cli-version

**Comment by Murthy582** [comment]
In case if anyone run into similar issue,  setting up CLI version to 0.10.0.7 under advanced section solved it.
