### ISSUE TITLE
No support of .gzip instead of .gz   (same format but gzip doesn't supported on s3 ingestion) 

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#7672]
There is an option to use gz files on s3 ingestion. https://datahubproject.io/docs/generated/ingestion/sources/s3/#:~:text=path_specs.enable_compression
path_specs.enable_compression
but there is no support of same format but fullly writen like gzip. 

**To Reproduce**

**Expected behavior**
support the same format .gzip and .gz

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hsheth2** [comment]
We'd welcome a contribution around this :)

Likely would be an extra mapping here https://github.com/datahub-project/datahub/blob/18dd7298ad1d4f5c5d8e0414a68b8f5b3f6bd509/metadata-ingestion/src/datahub/ingestion/source/s3/source.py#L398-L403

**Comment by YuriyGavrilov** [comment]
Thanks gys!

**Comment by YuriyGavrilov** [comment]
Try to make a pull request with gzip extension https://github.com/datahub-project/datahub/pull/8960
