### ISSUE TITLE
profiling flags are not taking effect.

### ISSUE THREAD

**Issue by mingz-work** [datahub-project/datahub#7703]
**Describe the bug**
After setting profiling such as include_field_distinct_count: false, datahub still run `SELECT count(distinct` for each column.

**To Reproduce**
1. in recipe set SELECT count(distinct
2. Try ingest the recipe

**Expected behavior**
Distinct count should not be performed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1

**Additional context**

**Comment by xiangqiao123** [comment]
The version used is v0.10.1，i have the same problem.
