### ISSUE TITLE
setup question with acryl-datahub

### ISSUE THREAD

**Issue by chenchuan2882** [datahub-project/datahub#7726]
when i install acryl-datahub，everything is going well, but a except error happens when i test "datahub version".

`datahub version`

> DataHub CLI version: 0.10.0.6
> Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:37:49) [MSC v.1916 64 bit (AMD64)]
> Exception ignored in: <generator object configure_logging at 0x0000018A4B3AEF48>
> Traceback (most recent call last):
>   File "D:\APPS\anaconda3\lib\site-packages\datahub\utilities\logging_manager.py", line 191, in configure_logging
>   File "D:\APPS\anaconda3\lib\contextlib.py", line 486, in __exit__
> AttributeError: 'NoneType' object has no attribute 'exc_info'

**Comment by hsheth2** [comment]
@chenchuan2882 thanks for the update. I'll close this issue for now.
