### ISSUE TITLE
Business Glossary Config Error

### ISSUE THREAD

**Issue by tieungao88** [datahub-project/datahub#7731]
**Describe the bug**
I input config:
`source:
    type: datahub-business-glossary
    config:
        file: 'https://githubusercontent.com/imquocanh/DataHub/main/test_business_glossary-300323-v3.yml'
        enable_auto_id: false
`
But when I run, I reviced error:
`pydantic.error_wrappers.ValidationError: 1 validation error for BusinessGlossarySourceConfig
file
  file or directory at path "https:/githubusercontent.com/imquocanh/DataHub/main/test_business_glossary-300323-v3.yml" does not exist (type=value_error.path.not_exists; path=https:/githubusercontent.com/imquocanh/DataHub/main/test_business_glossary-300323-v3.yml)
`
File url had change form: https://githubusercontent.com/imquocanh/DataHub/main/test_business_glossary-300323-v3.yml to "https:/githubusercontent.com/imquocanh/DataHub/main/test_business_glossary-300323-v3.yml'"

Please, help me.

THanks

**Comment by xiphl** [comment]
This is likely the result of the acryl datahub library not receiving the recent changes that was merged 2 days ago - in the old code, paths is defined as pydantic.filepath type so it transforms any url by removing a slash.

**Comment by tieungao88** [comment]
Hi,
What do I do for resolve problem ?

Thanks.

**Comment by xiphl** [comment]
looking at pyi, the library isnt updated yet. you probably need to clone the repo and `pip install -e .` instead.
just to confirm@asikowitz, the python library is only updated at next release right

**Comment by tieungao88** [comment]
Thank.

**Comment by asikowitz** [comment]
Yup, our last pypi release was on Mar 27, while the ability to use urls as files was only added Mar 29. We should have a new release out within a week. Sorry for the inconvenience!

**Comment by hsheth2** [comment]
We have a new release (v0.10.1.1) out with those changes.
