### ISSUE TITLE
Snowflake top users have uppercase in their urn because of the email

### ISSUE THREAD

**Issue by matwalk** [datahub-project/datahub#7768]
When using Snowflake ingestion, top users are added to the dataset but don't match with OIDC created users.
It seems to be related to the email from SNOWFLAKE.ACCOUNT_USAGE.USERS which strangely includes uppercase.
In our table USERS, some values look like : "Firstname.Name@mycompany.com"

**Expected behavior**
When using Snowflake ingestion, top users should have urn without lowercase when using convert_urns_to_lowercase: true.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version v0.10.0

**Comment by mayurinehate** [comment]
Hey @matwalk , do you mean

**Expected behavior**
When using Snowflake ingestion, top users should have urn **with** lowercase when using convert_urns_to_lowercase: true.

**Comment by matwalk** [comment]
Hi @mayurinehate,
Yes that's I wanted to say. Not enough coffee yesterday ;-)

**Comment by hsheth2** [comment]
The PR is merged, so closing this too.
