### ISSUE TITLE
MS SQL Server profiling - performance concerns

### ISSUE THREAD

**Issue by jpomfret** [datahub-project/datahub#7822]
**Describe the bug**
When profiling MS SQL Server the queries generated are inefficient and cause a lot of IO, especially on larger tables.

**To Reproduce**
Run SQL profiling against a SQL Server database.

Capturing the queries that run you can see for each column to generate the min, max, avg and stdev a cte is used for each which causes a table scan.
![image](https://user-images.githubusercontent.com/981370/232014350-0c5bb9b8-9f25-4e0c-8131-be20a6a94251.png)

Here is the query plan - this only shows a small section of it as there are many columns, and 4 scans per column.
![image](https://user-images.githubusercontent.com/981370/232014805-301a8735-b2d0-4abd-9cdb-fb92a576e01e.png)

**Expected behavior**
If we could rewrite the query to just access the table once and aggregate the data - for example, to get the 4 stats for 2 columns would look like this:
![image](https://user-images.githubusercontent.com/981370/232015102-541f6872-e2cb-49b7-9b90-5dd3d5833bb5.png)

This changes the plan to this:
![image](https://user-images.githubusercontent.com/981370/232015273-f27bb745-8238-472c-8b46-6d34729520da.png)

If we compare the IO for running the two queries for this same table we can see the duration is reduced from 37 seconds to 15 and the IO on the table is massively reduced, 4348 scans --> 146 scans.

![image](https://user-images.githubusercontent.com/981370/232023438-504cea87-7df4-4449-b21d-a636f811d2ba.png)

**Comment by sachinwadhwa** [comment]
just to add - above performance issue is using version v0.10.1

**Comment by jpomfret** [comment]
Hi @hsheth2,

I wondered if you could help me with some guidance on this issue.

We noticed some performance concerns with how the data profiling happens for SQL Server databases and wondered whether some optimisations could be added for this DBMS. We have had a poke around in the code to try and help with a PR but we are struggling to figure out what actually generates the query in the issue above.

We have found the following code within the [ge_data_profiler.py](https://github.com/hsheth2/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py) file that seems to loop through columns and measures to profile the data - for example, to get the min values of the column we found this:

https://github.com/datahub-project/datahub/blob/94e7e51175660afbfb7b5cf198a3263f30d56f62/metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py#L364-L369

We then found references to great expectations and sqlalchemy, but are unsure what the fix might be, or where exactly it falls in this architecture.

We found a couple of old PRs that you worked on this profiling and so wondered if you could help shed some light.
- https://github.com/datahub-project/datahub/pull/3572
- https://github.com/datahub-project/datahub/pull/3730

We have the expertise on how to more efficiently get this data from SQL Server, however we are lacking the python and project knowledge to be useful - we could also set up a call if it would be easier for us to explain.

Thanks!

**Comment by jpomfret** [comment]
@sachinwadhwa - could you confirm if we have upgraded since and which version we are now on?

I can confirm we are still seeing these queries running on the SQL side.

@hsheth2 - any ideas who could help us with this?

**Comment by hsheth2** [comment]
@jpomfret this is a fairly deep problem - I'm not sure we have any easy mechanism for converting these from multiple subqueries into a single one. We've generally seen that most SQL warehouses are able to optimize these queries, so it's interesting that MSSQL cannot. 

For context, those are generated by our dynamic query combiner code: https://github.com/datahub-project/datahub/blob/ceaeb42a2b8abaecb49e575d076e8c94c587b472/metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py#L136.

My eventual goal is that we switch our profiling code to a newer interface that Great Expectations provides (batch v3), which should give us a bit more control over this stuff. However, I don't have a concrete timeline for that.
