### ISSUE TITLE
OpenAPI specification is missing info property

### ISSUE THREAD

**Issue by jan-wacker** [datahub-project/datahub#7844]
**Describe the bug**
The generated Swagger OpenAPI specification is missing the required info attribute.

**To Reproduce**
1. Go to datahub
2. Append `/openapi/v3/api-docs` to URL

**Expected behavior**
OpenAPI specification requires the info property. see [here](https://spec.openapis.org/oas/v3.1.0#openapi-object)

The info property is described [here](https://spec.openapis.org/oas/v3.1.0#info-object)

**Additional context**
If the info property is not available in the json file. The specifcation cannot be imported to Azure API Management

**Comment by vishesh10** [comment]
Hi @jan-wacker,
Can you please guide what needs to be added in the "title" and "version" tags of the info property. Additionally, can you also please provide the values of any tags of the info property which are required to be added.

Thanks

**Comment by jan-wacker** [comment]
As described in the OpenAPI Requirements [here](https://spec.openapis.org/oas/v3.1.0#fixed-fields-0) the following tags are required:

- title: *string* The title of the API.
- version: *string* The version of the OpenAPI document (which is distinct from the [OpenAPI Specification version](https://spec.openapis.org/oas/v3.1.0#oasVersion) or the API implementation version).

```
"title": "DataHub OpenAPI",
"version": "1.0.1"
```

Version tag needs to be generated.

**Comment by vishesh10** [comment]
Hi @jan-wacker,
I have created a PR for this issue.
Thanks
