### ISSUE TITLE
dbt no longer show model definitions on table or incremental materializations

### ISSUE THREAD

**Issue by remisalmon** [datahub-project/datahub#7868]
**Describe the bug**

After updating to DataHub v0.10.2 dbt model definitions (SQL code) are no longer visible in the UI on models materialized as table or incremental.

**To Reproduce**
1. Setup DataHub v0.10.2
2. Ingest dbt source with view and table materializations
3. Browse a model materialized as table in the UI
4. The "View Definition" tab is not shown

This is a regression vs DataHub v0.9 where "View Definition" was shown for all dbt materializations.

**Expected behavior**

The "View Definition" tab should be shown for all dbt materializations, and maybe renamed to "Model Definition".

**Screenshots**

Model materialized as view:
![image](https://user-images.githubusercontent.com/26257211/233431013-58cf1647-8b6b-4092-9f2b-27d8ad214aee.png)
![image](https://user-images.githubusercontent.com/26257211/233431073-2bfdb5b4-9fe1-49d0-b15b-852d20620b63.png)

Model materialized as table:
![image](https://user-images.githubusercontent.com/26257211/233431192-4d25a550-0d70-43b3-baaf-09711be6a7e9.png)
![image](https://user-images.githubusercontent.com/26257211/233431286-ce6f42f5-5b51-4e6e-a966-1c9af03c585c.png)
(clicking on the "See View Definition" on the link above does nothing)

**Desktop (please complete the following information):**
 - OS: MacOS 13
 - Browser: Firefox 112

**Comment by hsheth2** [comment]
@remisalmon thanks for the report - this should be fixed by https://github.com/datahub-project/datahub/pull/7872
