### ISSUE TITLE
Certs are not assigned to rest-emitter

### ISSUE THREAD

**Issue by jGuzmanSan** [datahub-project/datahub#7923]
**Describe the bug**
I'm trying to emit metadata to DATAHUB using a tuple of certs: (cert, key) for connecting with gms, using the python-sdk (custom crawler) and a python-emiter, but the latest version raise next exception

```
Traceback (most recent call last):
  File "/Users/jguzman/.pyenv/versions/3.10.10/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/jguzman/.pyenv/versions/3.10.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/jguzman/.pyenv/versions/3.10.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jguzman/.pyenv/versions/3.10.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
```

Checking the code, looks like the issue is coming on how the tuple is assigned: https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/emitter/rest_emitter.py#L91 

Updating the line to: 
```
self._session.cert = ca_certificate_path
```
it seems to work fine. Please, could you double check it? 

**To Reproduce**
Try to emit metadata from any source to a gms server that requires https tuple (cert and key). 

**Expected behavior**
The emitter is able to connect to gms via https.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: none (bash)
 - Version of datahub v0.10.2

**Additional context**

**Comment by hsheth2** [comment]
@jGuzmanSan thanks for reporting. I've implemented your suggested change here https://github.com/datahub-project/datahub/pull/7978.
