### ISSUE TITLE
DBT not linking models with BigQuery objects

### ISSUE THREAD

**Issue by sebaap** [datahub-project/datahub#7943]
**Describe the bug**
Most of the DBT models are not matched to BigQuery objects. In some cases they appear as upstream objects and i think for sources it appears as downstream. There are around ~10 models out of the ~200 that does get matched correctly but I couldn't find a pattern on the ones that work.

**To Reproduce**
I just ran the BigQuery ingestion and then the DBT one. BigQuery was executed through an ingestion set up in the web UI using CLI version 0.10.2.1 and DBT was executed running the CLI manually using the CLI version 0.10.2.2

**Expected behavior**
All models properly matched to their corresponding object in BigQuery.

**Screenshots**
Objects aligned vertically are supposed to be merged. This shows a merged one at the end of the lineage
![image](https://user-images.githubusercontent.com/5461092/235702308-a03fc0b0-730f-4e12-9fa6-176c5977e9c9.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterrey Version 12.3
 - Browser: Chrome Version 112.0.5615.49 (Official Build) (arm64)
 - Datahub Version: 0.10.2

**Additional context**
There are no errors or relevant warnings in the dbt ingestion logs.
This is my config file for the dbt ingestion:
```yaml
source:
  type: "dbt"
  config:
    manifest_path: ./dbt/target/manifest.json
    catalog_path: ./dbt/target/catalog.json

    target_platform: "bigquery"
```
Might be relevant that we have a multi-project setup in BigQuery, and can't confirm 100% because I didn't find a way to search for the matched models, but eyeballing through the models seems like all of the matched ones are from only one of the projects, although there are still unmatched models in the same project so doesn't seem to be the root cause.

**Comment by navarrojoaquin** [comment]
Is there any update regarding this issue?

We are currently encountering the same bug in version 0.10.3.

**Comment by hsheth2** [comment]
Could you try setting `convert_urns_to_lowercase` on your BigQuery ingestion?

Not sure if this is possible for you, but one other thing to try is to hard delete everything in dbt and re-ingest. I know there was one bug where the "siblings" relationship didn't kick in for dbt sources that's since been fixed.

**Comment by navarrojoaquin** [comment]
Thank you for your help. However it appears that the `convert_urns_to_lowercase` setting did not have any noticeable impact in our case.
