### ISSUE TITLE
Impact analysis/lineage csv not populating

### ISSUE THREAD

**Issue by SaraGleghornTR** [datahub-project/datahub#7944]
**Describe the bug**
When I attempt to download the lineage as a csv from the Lineage tab on an asset, the produced csv only has headers, now data.
This appears to have something to do with the `Degree of Dependencies` filter - if I remove this _(provided I toggle another filter first, otherwise I lose the option to filter anything)_ then the generated CSV includes records.

**To Reproduce**
1. Go to any asset that has lineage (I tried Looker and Snowflake assets)
2. Click on "Lineage"|
3. Set the filters to anything so long as `Degree of Dependencies` has at least one option checked and there's at least one result.
4. Click on the three buttons in the top right of the lineage frame (under "refresh", right of the lineage "search entities" search bar)
5. Click on download
6. Check the downloaded file. I'm expecting it to be 136 bytes and contain only the csv headers, but no actual data (despite you having at least one result in step 3)
7. Check one of the other filters (e.g. platform), and uncheck all options within `Degree of Dependencies`. Make sure the combination of filters you've selected has at least 1 result.
8. Click on the three buttons in the top right
9. Click on download
10. Check the downloaded file; I'm expecting this to contain the results that DataHub is showing in the UI

**Expected behavior**
I expect the downloaded csv to show me the same objects as shown in the UI when any `Degree of Dependencies` option is checked.
(Bear in mind that Degrees of dependencies are toggled on _by default_.)

**Screenshots**
With any Degree of Dependency toggled:
![image](https://user-images.githubusercontent.com/95487733/235744872-57d47b25-5f9a-4a18-b81d-5b6c74c6973a.png)

Without any Degree of Dependency toggled:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/95487733/235745518-66654334-b820-42bc-a340-ac650b00f013.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Chrome Version 112.0.5615.137
 - DataHub version

**Additional context**
I'm running `datahub docker quickstart`
DataHub CLI version: 0.10.2.2
Python version: 3.10.11
Missing records found in both default quickstart and quickstart using Postgres. Workaround when deselecting degree of dependencies discovered when using Postgres (but not tried on MySQL)

**Comment by eparreno** [comment]
I'm having the exact same issue.
