### ISSUE TITLE
Ingestion: setting max_threads > 1 in rest sink broke DataPlatformInstance ingestion

### ISSUE THREAD

**Issue by jinlintt** [datahub-project/datahub#7986]
One of the recent performance improvement to ingestion increased the default `max_threads` for the REST sink from `1` to `15`.
https://github.com/datahub-project/datahub/commit/589d354a5798d2dd3b46f68451c8f8e36561a459

Before this change, the CLI sends the ingestion requests sequentially, now it can send multiple requests in parallel and therefore boost the ingestion performance.

However, after we upgraded to CLI `0.10.2`, we have noticed that the `platform_instance` in many of our newly ingested datasets are missing. Below is our investigation:

When the CLI processes a dataset from the source, it will typically emit the following requests to GMS:
1. Ingest container aspect
2. Ingest DataPlatformaInstance aspect
3. Ingest subtypes aspect
4. Ingest dataset snapshot to create the dataset entity

The ingestion code for an aspect works as follows:
1. Ingest the aspect
2. Based on the entity type’s entity spec, determine what other aspects need to exist
3. Check if these required aspects exist for the entity, if not, ingest them.

Because the `DataPlatformInstance` (DPI) aspect is required for the `dataset` entity type, more than one ingestion requests for the same dataset might try to ingest the DPI aspect if they all detect the DPI aspect doesn't exist. This creates a race condition.

However, the code for creating the default DPI aspect (see snippet below) is incorrect because it doesn’t set the `instance` field of the DPI aspect because there is no reliable way to extract the instance value from a `dataset` entity’s urn.

```
  public static Optional<DataPlatformInstance> buildDataPlatformInstance(String entityType, RecordTemplate keyAspect) {
    try {
      return Optional.ofNullable(getDefaultDataPlatform(entityType, keyAspect))
          .map(platform -> new DataPlatformInstance().setPlatform(platform));
    } catch (URISyntaxException e) {
      log.error("Failed to generate data platform instance for entity {}, keyAspect {}", entityType, keyAspect);
      return Optional.empty();
    }
  }
```

Only the “Ingest DataPlatformaInstance aspect” will include the correct instance field. As a result, if any of the requests other than “Ingest DataPlatformaInstance aspect” wins the race, we will have an incorrect instance field.

As a workaround, set `max_threads` to `1` if you configure the `platform_instance` field in your ingestion recipe. A longer term fix might be one of the following:
1. Update the `DataPlatformInstanceUtils.buildDataPlatformInstance` method to correctly set the `instance` field.
2. Don't include DPI aspect as a required aspect for the `dataset` entity type, which will result in the DPI aspect being only ingested by the “Ingest DataPlatformaInstance aspect” request.

**Comment by hsheth2** [comment]
To tie this back - initial slack conversation here https://datahubspace.slack.com/archives/CUMUWQU66/p1683570110122239?thread_ts=1683165441.411299&cid=CUMUWQU66.
