### ISSUE TITLE
Datahub EntityChangeEvent_v1 not parsing glossary_terms or tags.

### ISSUE THREAD

**Issue by matthew-coudert-cko** [datahub-project/datahub#8007]
**Describe the bug**
 EntityChangeEvent_v1 not emitting GLOSSARY_TERM changes or TAGS
**To Reproduce**
1. Create a hello world action.yaml file.
name: "pipeline-name"
source:
  # source configs
filter: 
  event_type: "EntityChangeEvent_v1"
action:
  type: "hello_world"
2. Run the action
3. Change any tags or glossary_terms (remove/add)
4. Nothing is printed.

**Expected behavior**
The expected behaviour is that this emits payloads as expected.

This also broke all of our actions that were listening to EntityChangeEvent_v1.

**Screenshots**

**Additional context**
This happened on all versions above v10.1

MetadataChangeLogEvent_v1 still work as expected, only EntityChangeEvent_v1 are broken

**Comment by haeniya** [comment]
We also don't see any EntityChangeEvent_v1 events printed in the hello world action. @matthew-coudert-cko were you able to solve this?
