### ISSUE TITLE
Not able to quickstart datahub via docker

### ISSUE THREAD

**Issue by Attauheed-Sulaiman** [datahub-project/datahub#8044]
I am trying to run datahub in my Vm via docker, it was running fine few weeks ago but now when I try to start it again it gives me an error for the datahub-gms container. 
   
**Screenshots**

![Capture](https://github.com/datahub-project/datahub/assets/133659426/8e89ec68-4ac4-4181-8acc-f508e29b650d)

 Error Log file 

[datahub-gms.txt](https://github.com/datahub-project/datahub/files/11478716/datahub-gms.txt)

**Comment by sudoshi** [comment]
Same
