### ISSUE TITLE
S3 Data Lake ingestor skips directories with similar prefix

### ISSUE THREAD

**Issue by alplatonov** [datahub-project/datahub#8077]
**Describe the bug**
S3 Data Lake ingestor skips directories with similar prefix.
For example:
s3://datascience-production/data/a/accounts
s3://datascience-production/data/a/accounts_new
s3://datascience-production/data/a/accounts_2

probably directory s3://datascience-production/data/a/accounts will be omited.

**To Reproduce**
1. Create a directory structure like in the example
2. Ingest metadata from s3
3. Look at datahub UI and compare directories in s3 and datahub ui

**Expected behavior**
All directories listed in s3 also can be viewed in datahub ui

**Screenshots**

**Desktop (please complete the following information):**
Does not matter

**Additional context**
Under the hood, there is a call to the function list_objects_v2
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/list_objects_v2.html

from docs:

> CommonPrefixes contains all (if there are any) keys between Prefix and the next occurrence of the string specified by a delimiter.
> 
> For example, if the prefix is notes/ and the delimiter is a slash ( /) as in notes/summer/july, the common prefix is notes/summer/. All of the keys that roll up into a common prefix count as a single return when calculating the number of returns.

in case 
s3://datascience-production/data/a/accounts
s3://datascience-production/data/a/accounts_new
s3://datascience-production/data/a/accounts_2

call to list_objects_v2 must be with `prefix=data/a/accounts/` but now called with `prefix = data/a/accounts`

**Comment by treff7es** [comment]
thanks for the fix!
