### ISSUE TITLE
ERROR: for kafka-setup  Container "fbcf58a5db42" is unhealthy.

### ISSUE THREAD

**Issue by DayDreamM** [datahub-project/datahub#8123]
i run the command “source /root/datahub/docker/quickstart.sh ” on ubuntu 
prompt: 
Quickstarting DataHub: version head
No Datahub Neo4j volume found, starting with elasticsearch as graph service
elasticsearch is up-to-date
zookeeper is up-to-date
mysql is up-to-date
Starting elasticsearch-setup ... done
Starting broker              ... done
Starting mysql-setup         ... done
Starting schema-registry     ... done

ERROR: for kafka-setup  Container "fbcf58a5db42" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by remisalmon** [comment]
Same as https://github.com/datahub-project/datahub/issues/8133?

**Comment by hsheth2** [comment]
Yup this is a dup of https://github.com/datahub-project/datahub/issues/8133
