### ISSUE TITLE
Ingesting Datasets with region outside US does not generate metadata

### ISSUE THREAD

**Issue by smisachsen** [datahub-project/datahub#8127]
**Describe the bug**
When dealing with BigQuery datasets located in regions outside of "region-us," the metadata generation process during ingestion is not functioning properly.

**To Reproduce**
1. Create a BigQuery dataset in a non-US region, such as "EU," and assign a description to it.
2. Perform ingestion of the Google Cloud Platform (GCP) Project containing the dataset into Datahub.
4. Observe that the dataset metadata is missing in Datahub.

**Expected behavior**
Datahub should successfully ingest the metadata of BigQuery datasets located in regions outside of the United States ("US").

**Additional context**
The root cause of this issue can be attributed to [this specific line](https://github.com/datahub-project/datahub/blob/798ce3d6c82768b69e597f7f1a51ed992eacc4f3/metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_schema.py#L145), which defaults to using "region-us". Please refer to the [BigQuery documentation](https://cloud.google.com/bigquery/docs/information-schema-datasets-schemata#scope_and_syntax) for more details on the expected scope and syntax.

**Comment by hsheth2** [comment]
Slack discussion: https://datahubspace.slack.com/archives/CUMUWQU66/p1685535611884369?thread_ts=1684936507.117099&cid=CUMUWQU66

Current workaround: you can pass in the default location to the BigQuery source by adding this to your source config:

```
    extra_client_options: 
      location: "EU"
```
