### ISSUE TITLE
When downstream exists still in lineage .csv file is not populating the downstream records

### ISSUE THREAD

**Issue by vidhibadrakiya** [datahub-project/datahub#8134]
**Describe the bug**
With 1st degree dependencies enabled :
I am having lineage dataset to dataset and when I am trying to get lineage impact analysis via downloading the .csv file it only shows headers, don't have any records even if there is downstream dependency exists. 

Without Filtering :
When I remove the tick for 1st degree dependencies which is by default and download the .csv file then it shows the records.

**To Reproduce**

1. Go to asset that has lineage (I am having in Postgresql between dataset to dataset)
2. Go to  "Lineage" tab where Degree of Dependencies is by default selected for 1st. Don't apply any other filters like platform, domain etc.
3. Select the three dots in the top right of the lineage tab
4. Choose download option 
5. In the .csv file I am expecting one row for downstream dataset but got only headers in .csv file and no such data.
6. After that uncheck all options within Degree of Dependencies. Don't apply any other filters.
7. Again follow the steps 4 and 5.
8. In the downloaded file It will show the all records.

**Expected behavior**
It should give the records in .csv file for downstream dependencies when respective degree of dependencies are selected.

**Screenshots**
When degree of dependencies is selected
![MicrosoftTeams-image (1)](https://github.com/datahub-project/datahub/assets/54183689/31ad8f52-6ea1-499c-b96a-619af6f28d9a)

When degree of dependencies is not selected
![MicrosoftTeams-image (2)](https://github.com/datahub-project/datahub/assets/54183689/ba9fb7cb-684b-4224-bd37-fba8b0618a03)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**
Seems like issue is with filtering. 
I am using datahub version : v0.10.1
Datahub is deployed using helm charts and using Postgres as backend instead of MySQL.
Even when try to do same task downloading .csv file with python request to that API I am not getting result .

**Comment by egemenberk** [comment]
Hi, we are also experiencing the same issue. I think this is a duplicate for the https://github.com/datahub-project/datahub/issues/7944?
