### ISSUE TITLE
Database name not pulled from URL when ingesting Oracle database using Service Name

### ISSUE THREAD

**Issue by Shaikh-Zainab** [datahub-project/datahub#8148]
**Describe the bug**
We are trying to ingest oracle databases by providing a service name in the recipe. As per code in `sql_common.py` the database name is extracted from the SQLAlchemy url and then passed on to subsequent functions during ingestion. Because the url does not have a database attribute in the URL when using Service Name for connection to Oracle, the database container has the empty strings for `name` and `database` keys in the `containerProperties` aspect.

Ingestion Use Case: 

Our requirement is to ingest a database which has multiple instances of the primary instance and can be connected through a service name.

**To Reproduce**
1. Provide service_name in ingestion recipe

**Expected behavior**

Either pull database name from URL when service name is provided or add functionality in to provide database alias when running ingestion for Oracle using service name.

**Example**
Database: mydb
Database Instances: mydb1, mydb2, mdb3
Service Name: mydbservice

**Comment by xiphl** [comment]
it is also relevant for me..
