### ISSUE TITLE
version 10.3 - ERROR    {datahub.entrypoints:199} - Command failed: Query sheetsConnection error (Tableau ingestioin)

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#8204]
The error appears like:

ERROR    {datahub.entrypoints:199} - Command failed: Query sheetsConnection error: [{\'message\': "Validation '
           'error of type FieldUndefined: Field \'documentViewId\' in type \'Sheet\' is undefined @ \'sheetsConnection/nodes/documentViewId\'", '
           '\'locations\': [{\'line\': 10, \'column\': 5, \'sourceName\': None}], \'description\': "Field \'documentViewId\' in type \'Sheet\' is '
           'undefined", \'validationErrorType\': \'FieldUndefined\', \'queryPath\': [\'sheetsConnection\', \'nodes\', \'documentViewId\'], '
           "'errorType': 'ValidationError', 'path': None, 'extensions': None}]\n"
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-tableau-0.10.3.1/lib/python3.9/site-packages/datahub/entrypoints.py", line 186, in main\n'

The ingestion works perfectly but did't ingest charts and sheet from Tableau.

**To Reproduce**

**Expected behavior**

Ingest tableau sheets and charts properly.

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/44679014/d91e4f9c-e7a4-42f1-a0ae-877fcdad6aea)

**Desktop (please complete the following information):**

**Additional context**
[exec-urn li dataHubExecutionRequest 216697c4-3330-462b-9c64-f738d3bb3721.log](https://github.com/datahub-project/datahub/files/11705820/exec-urn.li.dataHubExecutionRequest.216697c4-3330-462b-9c64-f738d3bb3721.log)

**Comment by mayurinehate** [comment]
This is fixed for ingestion cli version 0.10.4.2 and above ([Fix PR](https://github.com/datahub-project/datahub/pull/8225)).
