### ISSUE TITLE
M1 chip Mac, how to build and run datahub from source code? The document does not provide a successful build.

### ISSUE THREAD

**Issue by axiang-huge** [datahub-project/datahub#8236]
**Describe the bug**
M1 chip Mac, how to build and run datahub from source code? The document does not provide a successful build.
**Desktop (please complete the following information):**
 - OS: MacOS13
 - 
**Additional context**
Java11、docker-desktop4.19.0

**Comment by asikowitz** [comment]
Can you retry after installing java8 (as well as java 11):
```
brew tap homebrew/cask-versions
brew install --cask zulu8
```
Also, what python version are you using?

**Comment by deluxebear** [comment]
Change “languageVersion = JavaLanguageVersion.of(8)” in the “build.gradle” files to “languageVersion = JavaLanguageVersion.of(11)”
