### ISSUE TITLE
For Glue table its partition column's description is not visible in datahub 

### ISSUE THREAD

**Issue by svsarang** [datahub-project/datahub#8259]
**Describe the bug**
For Glue as the source when datahub consumes its metadata such as table_name, description, column_name, column_type, and column_description, its partition column type and name are available but only the description is not visible in datahub 

**To Reproduce**
1. Configure glue as a source for datahub.
2. Ensure you have one glue table with a partition column 
3. Run ingestion and observe metadata in datahub you will find for the partition column its description will be missing

**Expected behavior**
It should also show a description of the partition column.

**Screenshots**
Here we have base_month_start_date as our partition column.

<img width="635" alt="Screenshot 2023-06-19 at 5 09 14 PM" src="https://github.com/datahub-project/datahub/assets/121279656/eca05706-3886-485f-8660-5c26d2867ffa">

In the code, we observed that we are not consuming partition column comments.

<img width="489" alt="Screenshot 2023-06-19 at 10 50 11 AM" src="https://github.com/datahub-project/datahub/assets/121279656/a569f24b-fd28-4085-bfc9-fd877c63f639">

**Comment by treff7es** [comment]
Thanks, @svsarang. Do you want to create a pr with the fix?
