### ISSUE TITLE
protobuf error occurs on certain versions and above.

### ISSUE THREAD

**Issue by wngus606** [datahub-project/datahub#8337]
**Describe the bug**

If I run a `jar` file with `v0.10.3` or later, an error occurs.
```Bash
Exception in thread "main" java.lang.NoSuchMethodError: 'datahub.shaded.jackson.core.JsonFactory datahub.shaded.jackson.core.JsonFactory.setStreamReadConstraints(datahub.shaded.jackson.core.StreamReadConstraints)'
```

However, I run it with the `v0.10.2` version of the `jar` and it works fine.

**To Reproduce**
https://datahubspace.slack.com/archives/C02TYRDKCBD/p1687940673159259?thread_ts=1687940391.960039&cid=C02TYRDKCBD

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: v0.10.3 or later

**Comment by wngus606** [comment]
the smae thing happens in v0.10.5

**Comment by dmnparent** [comment]
Same issue with the version [0.11.0-1] and [0.11.0-2]. Using the Java package io.acryl:datahub-protobuf in a standalone project using Gradle (8.1.1).

**Comment by wngus606** [comment]
Is this issue still unresolved?

**Comment by hsheth2** [comment]
Thanks for the detailed error report - we're looking into this issue!

**Comment by dyhn78** [comment]
I updated jacksonVersion as `2.16.0-rc1` and seems problem solved

https://github.com/datahub-project/datahub/blob/1b737243b266843136918ec92f6d20573b999272/build.gradle#L12

**Comment by phil-schreiber** [comment]
@RyanHolstien I'm running into the same issue. Could you give an example of how to add this dep? Apparently this somehow needs to get added as a shadoJar? As someone not coming from the java world I'm struggling to get this running.

**Comment by dyhn78** [comment]
@hsheth2 @david-leifker any progress on this issue? I want to upgrade datahub-protobuf to the latest version but staying blocked by this

**Comment by wngus606** [comment]
Is this issue in progress? @hsheth2 @david-leifker

**Comment by wngus606** [comment]
I found the place where this problem occurred.
It seems that the error occurs when you call the `setStreamReadConstraints` function in the constructor part of the 
- `EventFormatter`
https://github.com/datahub-project/datahub/blob/b0060cec27d09e69ce3913b6d5b8a7ea8dffde76/metadata-integration/java/datahub-client/src/main/java/datahub/event/EventFormatter.java#L35
- `FileEmitter.java`
https://github.com/datahub-project/datahub/blob/b0060cec27d09e69ce3913b6d5b8a7ea8dffde76/metadata-integration/java/datahub-client/src/main/java/datahub/client/file/FileEmitter.java#L56
- `RestEmitter.java`
https://github.com/datahub-project/datahub/blob/b0060cec27d09e69ce3913b6d5b8a7ea8dffde76/metadata-integration/java/datahub-client/src/main/java/datahub/client/rest/RestEmitter.java#L88

Is it possible to fix it? @hsheth2 @david-leifker

**Comment by BNikola** [comment]
I've just encountered this issue with the `v0.12.1` version of `datahub-protobuf`.
Version `v0.10.2` seems to work fine.
