### ISSUE TITLE
Move to PyIceberg

### ISSUE THREAD

**Issue by Fokko** [datahub-project/datahub#8338]
**Describe the bug**

The current release of Datahub uses the legacy iceberg library. It is better to move to PyIceberg.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Fokko** [comment]
Being worked on in https://github.com/datahub-project/datahub/pull/8357

**Comment by hsheth2** [comment]
Closing this as https://github.com/datahub-project/datahub/pull/8357 was merged.
