### ISSUE TITLE
Type hinting on Source.create doesn't respect inheritance 

### ISSUE THREAD

**Issue by LucasRoesler** [datahub-project/datahub#8358]
When creating a new ingestion [Source](https://github.com/datahub-project/datahub/blob/10e5ecf6d2ec00ebe0caef1f144884a0e92a9093/metadata-ingestion/src/datahub/ingestion/api/source.py#L174), we will directly or indirectly inherit the Source base object from `datahub.ingestion.api.source`

One of the required methods is the `classmethod` for `create`. This is essentially a factory method for the new ingestion Source. This method is _must_ be implemented by the new sub-class. One why of creating this subclass is to use the [`config_class` dectorator from `datahub.ingestion.api.decorators`](https://github.com/datahub-project/datahub/blob/10e5ecf6d2ec00ebe0caef1f144884a0e92a9093/metadata-ingestion/src/datahub/ingestion/api/decorators.py#L9)  This will add a default implementation for any class that does not already implement `create`. 

Unfortunately, the type hinting for these functions doesn't seem to work well enough for `pyright`, this is the analysis tool used by VSCode's default `pylance` extension. This means that we get errors complaining that known methods do not exist, like this in our tests
![image](https://github.com/datahub-project/datahub/assets/891889/3e5807d5-3f91-465e-b517-ad9a66e1f59d)

It seems that pylance detects the type hints from the base `create` method 
```python
    @classmethod
    def create(cls, config_dict: dict, ctx: PipelineContext) -> 'Source':
```

The type hinting on the decorator are correct, but the monkey patching is not detected by pyright. 

**To Reproduce**
1. Implement a new ingestion Source that inherits from the SQLAlchemy source
2. Write a test that requires the `get_db_connection()` method
3. This should produce a linting error in VSCode and `pyright`
For example

```py
source = CoolSource.create(config, ctx)
conn = source.get_db_connection()
```

**Expected behavior**
the type hinting on the base `Source.create` should use a generic so that linters can correctly detect and the following code will no longer cause a linting error

```py
source = CoolSource.create(config, ctx)
conn = source.get_db_connection()
```

**Additional context**
I have tested this locally and it seems to work as expected

```python 
T = TypeVar('T', bound='Source')

@dataclass
class Source(Closeable, metaclass=ABCMeta):
    ctx: PipelineContext

    @classmethod
    def create(cls: Type[T], config_dict: dict, ctx: PipelineContext) -> T:
```

**Comment by hsheth2** [comment]
@LucasRoesler the typing fix you've proposed should work - could you open a PR for it?

**Comment by LucasRoesler** [comment]
@hsheth2 I created a PR
