### ISSUE TITLE
PowerBI ingestion doesn't work with Python 3.11 (but does work with Python 3.10)

### ISSUE THREAD

**Issue by fargoun** [datahub-project/datahub#8383]
**Describe the bug**
Trying to run PowerBI ingestion (via the CLI) using Python 3.11 results in: 
```
Failed to find a registered source for type powerbi: mutable default <class 'datahub.metadata.schema_classes.NullTypeClass'> for field datahubDataType is not allowed: use default_factory
```

Trying the same with Python 3.10 works.

See full context in DataHub Slack: https://datahubspace.slack.com/archives/C034DC21HJN/p1687512554525499?thread_ts=1687276688.508919&cid=C034DC21HJN

**To Reproduce**
1. Install Python 3.11
2. Try to run a PowerBI ingestion via CLI

**Expected behavior**
It should work on Python 3.11 as well

**Comment by treff7es** [comment]
Python 3.11 is not supported yet; please use 3.10 until it will be supported.

**Comment by fargoun** [comment]
@treff7es - any ETA to when Python 3.11 is going to be supported?

**Comment by hsheth2** [comment]
No concrete timeline yet, but we're working on it here: https://github.com/datahub-project/datahub/pull/6485
