### ISSUE TITLE
Additional levels of assets are adding.

### ISSUE THREAD

**Issue by sleeperdeep** [datahub-project/datahub#8387]
**Describe the bug**
In case of ingestion metadata from mssql which tables have complex naming and contains dots '.', additional levels of assets are appearing in UI.

**To Reproduce**
1. Create mssql objects. Use complex naming approach and dot symbol ('.') as separator inside each name. For example: 'db.db_name.schema.schema_name.some.info.table_name'.
2. Follow DataHub Quickstart Guide and deploy system locally.
3. Ingest data via cli: 'datahub ingest'. 
4. Open datahub ui. Open SQL Server in 'Explore your data/Datasets' or 'Platforms' section.
5. Look at navigation bar with additional nested levels. Each level is obtained by splitting object name with dot as separator.

**Expected behavior**
Assets levels should be displayed without additional levels. Level should be obtained based only on databse_name, schema_name, table_name (without splitting complex names with dot as separator).

**Screenshots**
mssql objects:
![изображение](https://github.com/datahub-project/datahub/assets/86791232/13fed2eb-e9a0-41bc-a0f5-74f38b63ec12)

datahub ui:
![изображение](https://github.com/datahub-project/datahub/assets/86791232/b336fb40-315c-43ae-9eae-db1c702e65fd)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (22H2)
 - Browser Firefox (115)
 - Docker version 24.0.2
 - Datahub version 0.10.4

**Comment by sleeperdeep** [comment]
Still waiting for solution.

**Comment by sleeperdeep** [comment]
Can anyone help with this issue?

**Comment by medinarribas** [comment]
We are also facing this issue. What we have noticed is that if we ingest the recipe twice, the problem is fixed. 

First ingestion:

![image](https://github.com/datahub-project/datahub/assets/13286635/aef3df6e-9801-4ce3-89be-a4aeb9f34c9f)

Second ingestion:

![image](https://github.com/datahub-project/datahub/assets/13286635/47f34385-a415-4b11-b357-1044c49a39a3)

Does anybody know something about this behaviour?

**Comment by sleeperdeep** [comment]
This issue is actual right now.

**Comment by sleeperdeep** [comment]
+
