### ISSUE TITLE
Hive Ingestion broken over HTTP

### ISSUE THREAD

**Issue by travis-cook-sfdc** [datahub-project/datahub#8405]
**Describe the bug**

Hive ingestion won't work if using `hive+http` or `hive+https` unless you explicitly downgrade Thrift to `0.13.0`.

Issues aren't supported in `pyhive` so I couldn't raise it there: https://github.com/acryldata/PyHive

The fix should be to disallow the buggy versions in `setup.py`: https://github.com/acryldata/PyHive/blob/master/setup.py#L62

Here's the related pyhive issue (but that project is pretty dead, so maybe it could get fixed here?)
https://github.com/dropbox/PyHive/issues/417

**To Reproduce**
1. Create a hive.dhub.yml file like this:
```yaml
source:
    type: hive
    host_port: localhost:10000
    scheme: hive+http
```
2. Run datahub ingest run -c hive.dhub.yml 
3. See Error: 
```
File "/usr/local/lib/python3.10/site-packages/TCLIService/TCLIService.py", line 186, in OpenSession
    self.send_OpenSession(req)
File "/usr/local/lib/python3.10/site-packages/TCLIService/TCLIService.py", line 195, in send_OpenSession
    self._oprot.trans.flush()
File "/usr/local/lib/python3.10/site-packages/pyhive/hive.py", line 81, in flush
    super(TCookieHttpClient, self).flush()
File "/usr/local/lib/python3.10/site-packages/thrift/transport/THttpClient.py", line 191, in flush
    self.__http.putheader('Cookie', self.headers['Set-Cookie'])
File "/usr/local/lib/python3.10/http/client.py", line 1244, in putheader
    raise CannotSendHeader()
```

**Expected behavior**
HIve ingestion should work

**Workaround**
You can get around this behavior by explicitly downgrading thirft to 0.13.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: N/A
 - Version: 0.10.5.1

**Additional context**
This was raised a few months ago: https://datahubspace.slack.com/archives/C029A3M079U/p1669024089697259?thread_ts=1668698117.723649&cid=C029A3M079U

**Comment by hsheth2** [comment]
@travis-cook-sfdc thanks for the report. I have a PR up that will pin the thrift version.
