### ISSUE TITLE
[Feature Request] config spark-lineage timezone

### ISSUE THREAD

**Issue by lordk911** [datahub-project/datahub#8413]
the detail please reference to: 

https://github.com/datahub-project/datahub/issues/7890

https://github.com/datahub-project/datahub/blob/e32d5520393c441f0aecbe8bba3688dcd1ac0092/metadata-integration/java/spark-lineage/src/main/java/datahub/spark/model/LineageEvent.java#L19

I found that LineageEvent.timeStr method will always use GMT to format timestamp, So may be we can make the timezone configurable.

**Comment by treff7es** [comment]
Why do you prefer to change the timezone? We always try to be consistent and push timestamps in UTC to DataHub.

**Comment by lordk911** [comment]
please take a look about https://github.com/datahub-project/datahub/issues/7890

The start and end time of the Spark application that I saw on the web UI is 8 hours earlier than the actual time, which has caused some trouble in using metadata.

**Comment by lordk911** [comment]
Or simply to use SimpleDateFormat to format the timestamp , it will use the default local timezone. Will this cause any other problem?
