### ISSUE TITLE
what is query_word_delimited?

### ISSUE THREAD

**Issue by gitHONGYANG** [datahub-project/datahub#8429]
gms version: v0.10.4
error：{"error":{"root_cause":[{"type":"query_shard_exception","reason":"[simple_query_string] analyzer [query_word_delimited] not found","index_uuid":"5MG1U7ZSTxWPPqdW5VMH2g","index":"datahubpolicyindex_v2"}]

how to define this analyzer????

**Comment by shixiutao** [comment]
I have encountered the same problem. May I know how it was resolved in the end
