### ISSUE TITLE
got build error when execuite ./gradlew :metadata-service:war:build --stacktrace

### ISSUE THREAD

**Issue by superchenwei** [datahub-project/datahub#8440]
Hi:
   I'm tring build GMS war with window11 system,got below error,could you please help fix it,thanks!

_* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':metadata-models:generateAvroSchema'.
.........
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        ... 9 more___

**Comment by kingkong2019** [comment]
I face the same problem,is there update solution?
