### ISSUE TITLE
ownership transforms do not work with new ownership types

### ISSUE THREAD

**Issue by bossenti** [datahub-project/datahub#8441]
**Describe the bug**
DataHub `0.10.4` introduces new ownership types which are modeled completely different compared to ownership types in earlier releases. The new structure breaks the existing transformers for addind ownership information to data sets.

For more details see https://datahubspace.slack.com/archives/CUMUWQU66/p1689595529057289

cc @mohdsiddique

**Comment by sgomezvillamor** [comment]
Adding a comment just to keep this issue opened 🙂
