### ISSUE TITLE
[Feature Request] support hive select * Column lineage

### ISSUE THREAD

**Issue by didiaode18** [datahub-project/datahub#8443]
**Describe the bug**
I need sqllineage to parse hive syntax to send to datahub for build Column lineage. Most of them can be parsed, but I found that the hive select * syntax cannot be parsed Column lineage.

The sql is as follows:

insert overwrite table dwd.dwd_product_prod_product_business_info_s_day partition (dt)
select a.*
from (
         select if(product_id = '2021-258', '2021-285', product_id)                 as product_id
              , if(max(if(field_name = 'projectId', field_value, '')) = '2021-258', '2021-285',
                   max(if(field_name = 'projectId', field_value, '')))              as sub_project_id
              , max(if(field_name = 'citicCode', field_value, ''))                  as citic_code
              , max(if(field_name = 'distributorId', field_value, ''))              as distributor_id
              , max(if(field_name = 'selectProInfo', field_value, ''))              as select_pro_info
              , max(if(field_name = 'proName', field_value, ''))                    as product_name
              , max(if(field_name = 'proShortname', field_value, ''))               as product_shortname
              , max(if(field_name = 'proPeriod', field_value, ''))                  as pro_period
              , max(if(field_name = 'prouctPeriodOld', field_value, ''))            as prouct_period_old
              , max(if(field_name = 'proType', field_value, ''))                    as pro_type
              , max(if(field_name = 'proTermType', field_value, ''))                as pro_term_type
              , max(if(field_name = 'proTerm', field_value, ''))                    as pro_term
              , max(if(field_name = 'exproTerm', field_value, ''))                  as expro_term
              , max(if(field_name = 'proRisk', field_value, ''))                    as pro_term_unit
              , max(if(field_name = 'proTermUnit', field_value, ''))                as pro_risk
              , max(if(field_name = 'proBgnDt', field_value, ''))                   as pro_bgn_dt
              , max(if(field_name = 'proPendDt', field_value, ''))                  as pro_pend_dt
              , max(if(field_name = 'proEndDt', field_value, ''))                   as pro_end_dt
              , max(if(field_name = 'openYn', field_value, ''))                     as open_yn
              , max(if(field_name = 'closurePeriod', field_value, ''))              as closure_period
              , max(if(field_name = 'unit', field_value, ''))                       as unit
              , max(if(field_name = 'operateMode', field_value, ''))                as operate_mode
              , max(if(field_name = 'dividendMode', field_value, ''))               as dividend_mode
              , max(if(field_name = 'whethersubPro', field_value, ''))              as whether_subpro
              , max(if(field_name = 'whethersissue', field_value, ''))              as whether_sissue
              , max(if(field_name = 'isPublish', field_value, ''))                  as is_publish
              , max(if(field_name = 'businessOrientation', field_value, ''))        as business_orientation
              , max(if(field_name = 'minTotalScale', field_value, ''))              as min_total_scale
              , max(if(field_name = 'maxTotalScale', field_value, ''))              as max_total_scale
              , max(if(field_name = 'minSubAmount', field_value, ''))               as min_sub_amount
              , max(if(field_name = 'maxiSingleAmount', field_value, ''))           as max_isingle_amount
              , max(if(field_name = 'increBase', field_value, ''))                  as incre_base
              , max(if(field_name = 'increBaseScale', field_value, ''))             as incre_base_scale
              , max(if(field_name = 'minPurchaseAmount', field_value, ''))          as min_purchase_amount
              , max(if(field_name = 'maxPurchaseAmount', field_value, ''))          as max_purchase_amount
              , max(if(field_name = 'perMinRedeem', field_value, ''))               as per_min_redeem
              , max(if(field_name = 'singleMaxAmount', field_value, ''))            as single_max_amount
              , max(if(field_name = 'subScribeCloseTime', field_value, ''))         as subscribe_close_day
              , max(if(field_name = 'subScribeCloseDay', field_value, ''))          as subscribe_close_time
              , max(if(field_name = 'purchaseTime', field_value, ''))               as purchase_day
              , max(if(field_name = 'purchaseDay', field_value, ''))                as purchase_time
              , max(if(field_name = 'redeemCloseDay', field_value, ''))             as redeem_close_day
              , max(if(field_name = 'redeemCloseTime', field_value, ''))            as redeem_close_time
              , max(if(field_name = 'perMinHolding', field_value, ''))              as per_min_holding
              , max(if(field_name = 'perMinMoney', field_value, ''))                as per_min_money
              , max(if(field_name = 'minHolding', field_value, ''))                 as min_hold_amount
              , max(if(field_name = 'minHoldAmount', field_value, ''))              as min_holding
              , max(if(field_name = 'realScaleFund', field_value, ''))              as real_scale_fund
              , max(if(field_name = 'minScaleFund', field_value, ''))               as min_scale_fund
              , max(if(field_name = 'maxScaleFund', field_value, ''))               as max_scale_fund
              , max(if(field_name = 'interestRate', field_value, ''))               as interest_rate
              , max(if(field_name = 'approvalCost', field_value, ''))               as approval_cost
              , max(if(field_name = 'minNum', field_value, ''))                     as min_num
              , max(if(field_name = 'distributeArithmetic', field_value, ''))       as distribute_arithmetic
              , max(if(field_name = 'subsidyRiskReserve', field_value, ''))         as subsidy_risk_reserve
              , max(if(field_name = 'valuationDateReserve', field_value, ''))       as valuation_date_reserve
              , max(if(field_name = 'lowerAlgorithm', field_value, ''))             as lower_algorithm
              , max(if(field_name = 'subRate', field_value, ''))                    as sub_rate
              , max(if(field_name = 'sharePresAcc', field_value, ''))               as share_pres_acc
              , max(if(field_name = 'shareManPro', field_value, ''))                as share_man_pro
              , max(if(field_name = 'amountSavAcc', field_value, ''))               as amount_sav_acc
              , max(if(field_name = 'amountManPro', field_value, ''))               as amount_man_pro
              , max(if(field_name = 'costSavAcc', field_value, ''))                 as cost_sav_acc
              , max(if(field_name = 'costManPro', field_value, ''))                 as cost_man_pro
              , max(if(field_name = 'interestManPro', field_value, ''))             as accuracy_int_pre
              , max(if(field_name = 'accuracyIntPre', field_value, ''))             as interest_man_pro
              , max(if(field_name = 'revenuePreAcc', field_value, ''))              as revenue_pre_acc
              , max(if(field_name = 'treIncMan', field_value, ''))                  as tre_inc_man
              , max(if(field_name = 'savingPreRein', field_value, ''))              as saving_pre_rein
              , max(if(field_name = 'dividReinTrea', field_value, ''))              as divid_rein_trea
              , max(if(field_name = 'effecDate', field_value, ''))                  as effec_date
              , max(if(field_name = 'effecRules', field_value, ''))                 as effec_rules
              , max(if(field_name = 'durationRules', field_value, ''))              as duration_rules
              , max(if(field_name = 'establishRules', field_value, ''))             as establish_rules
              , max(if(field_name = 'payDayLiq', field_value, ''))                  as pay_day_liq
              , max(if(field_name = 'payLiquidationYN', field_value, ''))           as pay_liquidation_yn
              , max(if(field_name = 'payDayraise', field_value, ''))                as pay_day_raise
              , max(if(field_name = 'payInterestYN', field_value, ''))              as pay_interest_yn
              , max(if(field_name = 'strDate', field_value, ''))                    as str_date
              , max(if(field_name = 'endDate', field_value, ''))                    as end_date
              , max(if(field_name = 'netValue', field_value, ''))                   as net_value
              , max(if(field_name = 'netValueTime', field_value, ''))               as net_value_time
              , max(if(field_name = 'auditLogId', field_value, ''))                 as audit_log_id
              , max(if(field_name = 'businessId', field_value, ''))                 as business_id
              , max(if(field_name = 'category', field_value, ''))                   as category
              , max(if(field_name = 'clearStatus', field_value, ''))                as clear_status
              , max(if(field_name = 'directoryId', field_value, ''))                as directory_id
              , max(if(field_name = 'directoryName', field_value, ''))              as directory_name
              , max(if(field_name = 'isAutomatic', field_value, ''))                as is_auto_matic
              , max(if(field_name = 'isFound', field_value, ''))                    as is_found
              , max(if(field_name = 'isMain', field_value, ''))                     as is_main
              , max(if(field_name = 'isRiskReserve', field_value, ''))              as is_risk_reserve
              , max(if(field_name = 'productFoundedAnnouncement', field_value, '')) as product_founded_announcement
              , max(if(field_name = 'establishmentScale', field_value, ''))         as establishment_scale
              , max(if(field_name = 'proStatus', field_value, ''))                  as pro_status
              , max(if(field_name = 'strongAlgorithm', field_value, ''))            as strong_algorithm
              , max(if(field_name = 'originalKey', field_value, ''))                as original_key
              , max(if(field_name = 'parentOriginalKey', field_value, ''))          as parent_original_key
              , max(if(field_name = 'annualDays', field_value, ''))                 as annual_days
              , max(if(field_name = 'HugeRedePro', field_value, ''))                as huge_rede_pro
              , max(
                 case
                     when field_name = 'ClearingType' then field_value
                     when field_name = 'clearingType' then field_value
                     else '' end)                                                   as clearing_type
              , max(if(field_name = 'isHugeRedemption', field_value, ''))           as is_huge_redemption
              , max(if(field_name = 'optDate', field_value, ''))                    as opt_date
              , max(if(field_name = 'postponeYn', field_value, ''))                 as postponeyn
              , max(if(field_name = 'proActDt', field_value, ''))                   as pro_act_dt
              , max(if(field_name = 'redemptionStartDate', field_value, ''))        as redemption_start_date
              , max(if(field_name = 'redemptionStartTime', field_value, ''))        as redemption_start_time
              , max(if(field_name = 'subscriptionStartDate', field_value, ''))      as subscription_start_date
              , max(if(field_name = 'subscriptionStartTime', field_value, ''))      as subscription_start_time
              , max(if(field_name = 'VoucherCode', field_value, ''))                as voucher_code
              , max(if(field_name = 'VoucherName', field_value, ''))                as voucher_name
              , max(data_time)                                                      as data_time
              , from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss')              as collect_time
              , max(dt)                                                             as dt
         from ods.ods_tip_clickhouse_product_business_info_all_s_day
         group by product_id
     ) a
         inner join dim.dim_product_prod_base_info_s_day b
                    on a.product_id = b.product_id and b.dt = date_sub('${hiveconf:ETL_DATE}', 1)
where a.dt = date_sub('${hiveconf:ETL_DATE}', 1)
  and a.is_main = '1';

**Additional context**

**Comment by hsheth2** [comment]
@didiaode18 have you tried using the new SQL lineage parser? It should be able to handle these queries

We demo'd it at the DataHub town hall last month: https://www.youtube.com/watch?v=1QVcUmRQK5E

**Comment by didiaode18** [comment]
> @didiaode18 have you tried using the new SQL lineage parser? It should be able to handle these queries
> 
> We demo'd it at the DataHub town hall last month: https://www.youtube.com/watch?v=1QVcUmRQK5E

Hi, your answer seems to solve my problem. And in which version do you plan to officially enable the sql analysis function, our version is now v0.10.4, which does not support this function.

**Comment by hsheth2** [comment]
It's available in cli version 0.10.5.2rc5 (which is broadly compatible with server version 0.10.4), but we haven't released the main datahub 0.10.5 yet.

**Comment by didiaode18** [comment]
> It's available in cli version 0.10.5.2rc5 (which is broadly compatible with server version 0.10.4), but we haven't released the main datahub 0.10.5 yet.

Thanks for your answer, two questions as a python beginner. First, what is the principle of our replacement *? Second, can we abstract SQL analysis into methods instead of plug-ins for developers?

**Comment by didiaode18** [comment]
From the logic of the code, I can get the underlying metadata like the Atlas component, so as to get a special sql that parses * better than sqllineage. don't know if i understand

**Comment by didiaode18** [comment]
![image](https://github.com/datahub-project/datahub/assets/22792154/0da60515-aa2a-4494-bd43-7a44c107a503)
Hello, what is the function of the local parameters marked in red

**Comment by hsheth2** [comment]
Your questions made me realize that my documentation on this feature is lacking, so adding docs here: https://github.com/datahub-project/datahub/pull/8482.

Going to close this issue for now, but let me know if anything in there is unclear.
