### ISSUE TITLE
Non-string enums in JSON schemas cause ingestion to fail

### ISSUE THREAD

**Issue by benjamin-awd** [datahub-project/datahub#8480]
**Describe the bug**
Non-string enums in JSON schemas cause ingestion to fail

I have raised a PR to address this: https://github.com/datahub-project/datahub/pull/8479

**To Reproduce**
1. Create a dummy schema
```json
{
    "$id": "foo",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
      "bar": {
        "description": "Mixed enum",
        "enum": [
          "baz",
          0,
          1,
          null
        ]
    }
  }
}
```
2. Attempt to ingest via CLI
3. Errors are raised:
- `['Failed to process due to sequence item 2: expected str instance, int found']`
- `['Failed to process due to sequence item 4: expected str instance, NoneType found']`

**Expected behavior**
JSON schema should be successfully ingested

**Comment by hsheth2** [comment]
Closing as https://github.com/datahub-project/datahub/pull/8479 was merged
