### ISSUE TITLE
Issue loading `DeltaTable` due to 

### ISSUE THREAD

**Issue by tafaust** [datahub-project/datahub#8488]
**Describe the bug**

I stored a DeltaTable using the deltalake pypi library (https://pypi.org/project/deltalake/); tested version 0.9.0 and 0.10.0; and while attempting to ingest the DeltaTable from my storage with S3 interface (lakeFS), I end up with the following error message:
```
    delta_table = read_delta_table(path, self.storage_options, self.source_config)
  File "/tmp/datahub/ingest/venv-delta-lake-0.10.4/lib/python3.10/site-packages/datahub/ingestion/source/delta_lake/delta_lake_utils.py", line 44, in read_delta_table
    raise e
  File "/tmp/datahub/ingest/venv-delta-lake-0.10.4/lib/python3.10/site-packages/datahub/ingestion/source/delta_lake/delta_lake_utils.py", line 31, in read_delta_table
    return DeltaTable(
  File "/tmp/datahub/ingest/venv-delta-lake-0.10.4/lib/python3.10/site-packages/deltalake/table.py", line 238, in __init__
    self._table = RawDeltaTable(
_internal.DeltaError: Delta protocol violation: Failed to serialize operation: expected value at line 1 column 1
```

The error seems to come from here:
https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py#L19-L42

but I am able to load the table locally on my machine with:
```
from deltalake import DeltaTable
s3_aws_config = {
    "AWS_ACCESS_KEY_ID": lakefs_user,
    "AWS_SECRET_ACCESS_KEY": lakefs_pass,
    "AWS_ENDPOINT_URL": lakefs_endpoint,
    "AWS_REGION": "<redacted>",
    "AWS_S3_ALLOW_UNSAFE_RENAME": "True"
}
dt = DeltaTable('s3://<redacted>/delta/test', storage_options=s3_aws_config)
print(dt.protocol())  # ProtocolVersions(min_reader_version=1, min_writer_version=1)
```

**To Reproduce**
1. Go to the ingestion UI
2. Add the following config
```
source:
    type: delta-lake
    config:
        env: PROD
        platform_instance: lakeFS-delta-test
        base_path: 's3://<redacted>/delta/test'
        version_history_lookback: -1
        require_files: false
        s3:
            aws_config:
                aws_access_key_id: <redacted>
                aws_secret_access_key: <redacted>
                aws_region: <redacted>
                aws_endpoint_url: 'https://lakefs.<redacted>/'
sink:
    type: datahub-rest
    config:
        server: 'http://<redacted>:8085'
```
3. Run with this config

**Expected behavior**
I expect datahub to successfully ingest the delta lake source.

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser Firefox
 - Version 115.0.2

**Additional context**
datahub is deployed using the docker-compose template on an Ubuntu machine. Ingestion of S3 parquet tables and files (with lakeFS) works.

**Comment by tahesse** [comment]
Addition: I just connected to the datahub-actions container with an exec shell and ran the python command. From the prompt I tested

```
from deltalake import DeltaTable
s3_aws_config = {
    "AWS_ACCESS_KEY_ID": lakefs_user,
    "AWS_SECRET_ACCESS_KEY": lakefs_pass,
    "AWS_ENDPOINT_URL": lakefs_endpoint,
    "AWS_REGION": "<redacted>",
    "AWS_S3_ALLOW_UNSAFE_RENAME": "True"
}
dt = DeltaTable('s3://<redacted>/delta/test', storage_options=s3_aws_config)
```

which worked fine on my machine. I ended up with the same error here outlined above.
