### ISSUE TITLE
Unable to emit metadata to DataHub GMS: javax.persistence.PersistenceException: Error when batch flush on sql: (Tableau Ingestion)

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#8505]
**Describe the bug**

Just delete everything about tableau from Datahub to recreate it from the begining and with good hierarchy.
But reciving this error: "Unable to emit metadata to DataHub GMS:..."  a lot of such error in the full log

 "urn:li:container:5f2f548d74c3625e1bbed1aede0bdea5-subTypes with ('Unable to emit metadata to DataHub GMS: "
           'javax.persistence.PersistenceException: Error when batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, '
           "createdBy=?, createdFor=?, systemmetadata=? where urn=? and aspect=? and version=?', {'exceptionClass': "
           "'com.linkedin.restli.server.RestLiServiceException', 'message': 'javax.persistence.PersistenceException: Error when batch flush on sql: "
           'update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where urn=? and aspect=? and '
           "version=?', 'status': 500, 'id': 'urn:li:container:5f2f548d74c3625e1bbed1aede0bdea5'}) and info {'exceptionClass': "
           "'com.linkedin.restli.server.RestLiServiceException', 'message': 'javax.persistence.PersistenceException: Error when batch flush on sql: "
           'update metadata_aspect_v2 set metadata=?, createdOn=?, createdBy=?, createdFor=?, systemmetadata=? where urn=? and aspect=? and '
           "version=?', 'status': 500, 'id': 'urn:li:container:5f2f548d74c3625e1bbed1aede0bdea5'}\n"
           '[12:01:25] Call finished\n'
           '[12:01:25] Request complete\n'
           '[12:01:26] Async request returned: received <Response [200]>\n'
           'Response status: <Response [200]>\n'
           'Server response from https://tableau-dev.group.s7/api/metadata/graphql\n'
           'Querying Metadata API\n'
           '[2023-07-25 12:01:26,810] INFO     {TSC:61} - Querying Metadata API\n'
           'request method post, url: https://tableau-dev.group.s7/api/metadata/graphql\n'
           '[12:01:26] Begin blocking request to https://tableau-dev.group.s7/api/metadata/graphql\n'
           '[2023-07-25 12:01:26,846] ERROR    {datahub.ingestion.run.pipeline:68} -  failed to write record with workunit '
           "urn:li:container:cc0ec4fbc61c818728241c24f0a61382-dataPlatformInstance with ('Unable to emit metadata to DataHub GMS: "
           'javax.persistence.PersistenceException: Error when batch flush on sql: update metadata_aspect_v2 set metadata=?, createdOn=?, '
           "createdBy=?, createdFor=?, systemmetadata=? where urn=? and aspect=? and version=?', {'exceptionClass': "

Full log here 
[exec-urn li dataHubExecutionRequest ff5e10f4-81b3-49d1-8ff5-6528531bae0c.log](https://github.com/datahub-project/datahub/files/12161519/exec-urn.li.dataHubExecutionRequest.ff5e10f4-81b3-49d1-8ff5-6528531bae0c.log)

some of the workbook created but without fields, tags ... don't know why 
![image](https://github.com/datahub-project/datahub/assets/44679014/745b8eb1-f4fc-4664-82a8-cf7c3966a8af)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
ingestion yaml:

`transformers:
    -
        type: simple_add_dataset_tags
        config:
            tag_urns:
                - 'urn:li:tag:product.BI'
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms-datahub-gms:8080'
        token: '${ingestions_by_yua}'
source:
    type: tableau
    config:
        ingest_owner: true
        platform_instance: TABLEAUDEV
        connect_uri: 'https://tableau-dev.group.s7'
        password: '${tableau_dev}'
        ingest_tables_external: true
        env: dev
        ingest_tags: true
        username: datahub_tableau_dev
        page_size: 1
        stateful_ingestion:
            enabled: true
            remove_stale_metadata: true
`

**Comment by YuriyGavrilov** [comment]
there is an assumption that an error occurs in this request, because datahub receives an empty source owner field: 
https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/tableau_common.py#L42

I will add new log here soon...

IMPORTANT: We are still can't ingest Tableau Platform properliy. Hope we will.

**Comment by YuriyGavrilov** [comment]
This is full log: 
[exec-urn li dataHubExecutionRequest afa32629-62a0-454e-ae42-60c2d4c06203.log](https://github.com/datahub-project/datahub/files/12191172/exec-urn.li.dataHubExecutionRequest.afa32629-62a0-454e-ae42-60c2d4c06203.log)


This is log when we try to ingest one tableau project with "ingest owner = false":
[exec-urn li dataHubExecutionRequest b8c139a6-81d2-4c89-81cb-48df0abe7b52.log](https://github.com/datahub-project/datahub/files/12191174/exec-urn.li.dataHubExecutionRequest.b8c139a6-81d2-4c89-81cb-48df0abe7b52.log)

**Comment by Masterchen09** [comment]
Are you using a PostgreSQL database? I think then it is related to this issue: #8257

According to the full log a serialization error is occurring (search for "ERROR: could not serialize access due to concurrent update").

With version 0.10.5 a fix for this issue is available: #8278

**Comment by YuriyGavrilov** [comment]
@Masterchen09 thanks for your feedback 🙏 will try to make a test on next week. Will come back with the results.
