### ISSUE TITLE
Table information of the same database name in different data sources gets overwritten.

### ISSUE THREAD

**Issue by WhiteZz1** [datahub-project/datahub#8582]
My datahub version is v.0.10.4. I created two MySQL-type databases with different URLs through the UI interface: 112 and 113. Both of them contain a "test" database, and under the "test" database, there's a "test_user" table. However, the "test_user" table in each database has a different number of fields and different field information. Now, when I execute the "run" command separately on these two data sources, after execution, I check the corresponding datasets. The result is that the output from the first execution is overwritten by the output from the second execution. Although there's version distinction, it's not possible to determine the source data source of each version.

Is this design intentional?

**Comment by WhiteZz1** [comment]
I might not have explained it clearly. created two distinct data sources, both containing databases with the same name, and tables with the same name but different structures. When you execute the "run" command on these two data sources and examine the resulting datasets, you're unable to differentiate between the results originating from Data Source 1 and Data Source 2.

**Comment by hsheth2** [comment]
@WhiteZz1 you can use the platform instance to distinguish between the two: https://datahubproject.io/docs/platform-instances/
