### ISSUE TITLE
how to support Chinese search

### ISSUE THREAD

**Issue by 1taoze** [datahub-project/datahub#8613]
Hello, how to configure Datahub to support Chinese search? I saw someone mention installing a Chinese tokenizer plugin for Elasticsearch. I tried installing the plugin, but it didn’t work. Are there any additional steps that need to be taken?

**Comment by ghf0128** [comment]
It looks like you need to uncomment the following section of the GMS docker.env file and restart the GMS service for it to take effect.
**ELASTICSEARCH_MAIN_TOKENIZER=smartcn_tokenizer**

**Comment by 1taoze** [comment]
[> It looks like you need to uncomment the following section of the GMS docker.env file and restart the GMS service for it to take effect. **ELASTICSEARCH_MAIN_TOKENIZER=smartcn_tokenizer**](https://github.com/datahub-project/datahub/issues/8613#issuecomment-1674543672)
@ghf0128

1、Installing the Smart plugin in Elasticsearch
2、Added environment variables(ELASTICSEARCH_MAIN_TOKENIZER=smartcn_tokenizer ) in GMS

![image](https://github.com/datahub-project/datahub/assets/36031461/ab5550b5-8678-42f9-aabd-c8489873905f)

In a table, where the field is described as “证券代码” , when I search using “代码”  the search result is empty.
Do I need to do any other configurations?

**Comment by ghf0128** [comment]
@1taoze No more configuration in my env.  I'm using version v10.5. You might need to search for "证劵代码" for that field as the data that stored in ES is the full name of that field.   
![ES](https://github.com/datahub-project/datahub/assets/63630830/10dddf92-08ed-4d42-be9f-cad235f2b30f)

![example](https://github.com/datahub-project/datahub/assets/63630830/5d5615c7-c1a3-4281-a170-20f8e540b40f)

**Comment by goodstudy12** [comment]
你好 你解决中文搜索的问题了吗
