### ISSUE TITLE
RuntimeError: Query workbooksConnection error: [{\'message\': "Cannot return null for non-nullable type: \'TableauUser\' within parent

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#8614]
**Describe the bug**
There is a strange error with Tableau ingestion on some Tableau projects (We have more than ~200 projects and identify that this appearse with at least 3 of them. 

The error look like:
`           '    ) = self.get_connection_object_page(\n'
           '  File "/tmp/datahub/ingest/venv-tableau-0.10.5.5/lib/python3.9/site-packages/datahub/ingestion/source/tableau.py", line 736, in '
           'get_connection_object_page\n'
           '    raise RuntimeError(f"Query {connection_type} error: {errors}")\n'
           'RuntimeError: Query workbooksConnection error: [{\'message\': "Cannot return null for non-nullable type: \'TableauUser\' within parent '
           '\'Workbook\' (/workbooksConnection/nodes[0]/owner)", \'path\': [\'workbooksConnection\', \'nodes\', 0, \'owner\'], \'locations\': None, '
           "'errorType': 'DataFetchingException', 'extensions': None}]\n",
           "2023-08-11 12:52:23.137420 [exec_id=8580a335-3d27-4260-936b-9e7f959cbf04] INFO: Failed to execute 'datahub ingest'",
           '2023-08-11 12:52:23.137876 [exec_id=8580a335-3d27-4260-936b-9e7f959cbf04] INFO: Caught exception EXECUTING '
           'task_id=8580a335-3d27-4260-936b-9e7f959cbf04, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete\n'
           '    return future.result()\n'`

Full log here:
[exec-urn li dataHubExecutionRequest 8580a335-3d27-4260-936b-9e7f959cbf04.log](https://github.com/datahub-project/datahub/files/12321690/exec-urn.li.dataHubExecutionRequest.8580a335-3d27-4260-936b-9e7f959cbf04.log)

The Recipies this:

`transformers:
    -
        type: simple_add_dataset_tags
        config:
            tag_urns:
                - 'urn:li:tag:product.BI_Data_Quality'
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms-datahub-gms:8080'
        token: '${ingestions_by_yua}'
source:
    type: tableau
    config:
        ingest_owner: false
        platform_instance: TABLEAUDEV
        connect_uri: 'https://tableau-dev.group.s7'
        password: '${tableau_dev}'
        ingest_tables_external: true
        ingest_tags: true
        username: datahub_tableau_dev
        page_size: 5
        stateful_ingestion:
            enabled: true
            remove_stale_metadata: true
        project_pattern:
            allow:
                - 'Data Quality'
pipeline_name: my_tableau_pipeline_1_data_quality
datahub_api:
    server: 'http://datahub-gms-datahub-gms:8080'
`

**To Reproduce**

**Expected behavior**

**Screenshots**
The error:
![image](https://github.com/datahub-project/datahub/assets/44679014/86fa4c76-6d17-424b-a5a6-40edecaf040e)

The workbook of this project but we didn't see anything inside due to it not finished corectly:
![image](https://github.com/datahub-project/datahub/assets/44679014/45a16ecd-dcc2-4749-b86e-1f0b6cac01fe)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. chromium, Mozilla]
 - Version [e.g. 0.10.5.5]

**Additional context**
The is also was disappointed due to How to ingest only one project with name "Data Quality" be course we have two projects with such name. Currently Datahub ingest both of them.  

Two projects with same name:
![image](https://github.com/datahub-project/datahub/assets/44679014/78a857a1-2cb7-4283-a654-469b9ca906ca)

**Comment by YuriyGavrilov** [comment]
It is actual

**Comment by asikowitz** [comment]
This appears to be an error with Tableau's GraphQL API. As per https://help.tableau.com/current/api/metadata_api/en-us/reference/workbook.doc.html, it expects a workbook's owner to be non-null, but it seems like that's not the case for at least one of your workbooks. Could you try assigning an owner to all your workbooks and retry ingestion? As for limiting your projects ingested, you can specify a deny project pattern to deny the undesired project. Something like:
```
project_pattern:
  allow:
     - "Data Quality"
  deny:
    - "Staff Data Warehouse/.+/Data Quality"
```
