### ISSUE TITLE
ERROR    {datahub.entrypoints:199} - Command failed: Response is not a http response?\n (Tabeleau)

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#8664]
**Describe the bug**

There is an error sometime with Tableau ingestion. 

![image](https://github.com/datahub-project/datahub/assets/44679014/7d434eab-126a-4055-931b-f5e1989c840c)

After seccond run it could be done successfully. 

Full log here:
[exec-urn li dataHubExecutionRequest 51fbd472-0b9e-486b-baad-38e7fe1a6df1.log](https://github.com/datahub-project/datahub/files/12376701/exec-urn.li.dataHubExecutionRequest.51fbd472-0b9e-486b-baad-38e7fe1a6df1.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 0.10.5.5]

**Additional context**

**Comment by djrmarques** [comment]
Hello! Currently dealing with the same issue (Although we are on version v0.11.0). Did you manage to figure our what the problem was?

**Comment by YuriyGavrilov** [comment]
@djrmarques Actually still have this problem sometimes. I follow  to a monkey strategy to turn off each project and and it again one by one. The watch on difference manually. There is no other logs. For today I can’t upload all tableau server, each time it shows different issues 😩 currently I focus only on 10 projects but I have more than 100.

**Comment by djrmarques** [comment]
Yeah it's the same for us as well. I tried to enable the advanced logs on the UI, but the ingestion fails right away when I do that 😩 . I am trying to investigate this I will post back if I find something

**Comment by djrmarques** [comment]
So it seems that, for us, scaling up our Elastic Search Cluster solved the issue. The ingestion seems to be working. We will end up splitting the tableau ingestion into the various Tableau Top Level projects. You can create/manage ingestion recipes via Graphql, so most likely what we will end up doing is writing some code using the Tableau API that fetches all the Top Level projects, and then use the Datahub Graphql API to create an ingestion recipe for each project.

**Comment by YuriyGavrilov** [comment]
> So it seems that, for us, scaling up our Elastic Search Cluster solved the issue. The ingestion seems to be working. We will end up splitting the tableau ingestion into the various Tableau Top Level projects. You can create/manage ingestion recipes via Graphql, so most likely what we will end up doing is writing some code using the Tableau API that fetches all the Top Level projects, and then use the Datahub Graphql API to create an ingestion recipe for each project.
> 
> EDIT: Weirdly enough, the Tableau ingestion succeeds when it runs at 3AM (when scheduled), but fails when I triggered it manually just now. Maybe it has to do with the fact that very few people are using Tableau at 3am?

I set up Tableau ingestion at 18:00 pm, for me it is a best way to upload it. also each sunday i go to church to upload Tableau to Datahub properly on the next week. it helps sometime. 

It is not good idea to separate tableau on different ingestion due to it anyway recursively search all the projects on tableau and create datasets only on filtered one. so it will make additional load on tableau server and also datahub.

**Comment by YuriyGavrilov** [comment]
just to update... still have this error "Response is not a http response?" with tableau ingestion.

**Comment by richenc** [comment]
I am also seeing this same issue after upgrading from v0.10.3 to v0.12.0

**Comment by YuriyGavrilov** [comment]
Some additional context: when I remove all projects to ingest everything from tableau I receive this bug: https://github.com/datahub-project/datahub/issues/9398

**Comment by YuriyGavrilov** [comment]
still actual

**Comment by YuriyGavrilov** [comment]
It is actual

**Comment by YuriyGavrilov** [comment]
This is actual. Still can't ingest  fully our Tableau server
