### ISSUE TITLE
do we have a plan for i18n?

### ISSUE THREAD

**Issue by PertQin** [datahub-project/datahub#8690]
Hello，I am a developer from China, and I am doing research recently. Datahub is our satisfactory selection. do we have a plan for i18n?

**Comment by ghf0128** [comment]
Hi Pert, I have a playable repo [[myRep](https://github.com/ghf0128/datahub.git)] which already contains "i18Next" and some Chinese localizations for learning and playing purpose. Feel free to play around it.  :)
