### ISSUE TITLE
Apache Spark 3.4.x lineage compatibility

### ISSUE THREAD

**Issue by Fabryprog** [datahub-project/datahub#8702]
**Describe the bug**

I am testing spark-lineage using spark 3.4.x version but, according to docs, it didn't work correctly.
I think that I am able to found the bug:

_ERROR_

`java.lang.NoSuchMethodError: 'org.json4s.JsonAST$JValue org.apache.spark.util.JsonProtocol.sparkEventToJson(org.apache.spark.scheduler.SparkListenerEvent)'`

_APACHE SPARK 3.2.x_ 
![image](https://github.com/datahub-project/datahub/assets/8210189/2a9301e3-ff9c-4dc9-8242-e37e060e640c)
LINK: https://spark.apache.org/docs/3.2.1/api/java/index.html?org/apache/spark/util/JsonProtocol.html

_APACHE SPARK 3.4.x_ 

Note: In this version, the method name is "sparkEventToJsonString"

![image](https://github.com/datahub-project/datahub/assets/8210189/cc94dc6a-6f0a-4b74-a365-4486c945b47d)
LINK: https://spark.apache.org/docs/3.4.1/api/java/index.html?org/apache/spark/util/JsonProtocol.html

**To Reproduce**

use lineage features with spark-3.4.x

**Comment by Fabryprog** [comment]
In my side, temporally, I solved the issue editing the spark-lineage source with the **very dirty** follow code:

```
private String grepSqlStartJsonSparkCompatible(SparkListenerEvent sqlStart) {
    String result = null;
    if (result == null) {
        try {
            Class<?> c = Class.forName(JsonProtocol.class.getName());
            //spark lt 3.4.x
            Method method_3_2_x = c.getDeclaredMethod("sparkEventToJson", org.apache.spark.scheduler.SparkListenerEvent.class);

            //spark ge 3.4.x
            Method method_3_4_x = c.getDeclaredMethod("sparkEventToJsonString", org.apache.spark.scheduler.SparkListenerEvent.class);

            if (method_3_2_x != null) {
                result = JsonMethods$.MODULE$.compact((JsonAST.JValue) method_3_2_x.invoke(null, sqlStart));
            } else {
                result = JsonMethods$.MODULE$.compact((JsonAST.JValue) method_3_4_x.invoke(null, sqlStart));
            }
        } catch (Exception e) {
        }
    }

    return result;
}
```

**Comment by helloimowen** [comment]
Also seeing this issue on Spark 3.3.2. I don't have the option of downgrading Spark, or building our own JAR file.

**Comment by helloimowen** [comment]
Commenting to remove the "stale" label. This issue is still relevant, and blocks spark version upgrades for people using the lineage JAR.

**Comment by MaicoTimmerman** [comment]
The spark version that is compiled against is still 2.4.8. If I were to create an MR for this, what version would we want to bump it to? How does 3.4.1 sound?

**Comment by helloimowen** [comment]
@MaicoTimmerman In this particular case that sounds good. Any version with the new naming of `sparkEventToJsonString` is appropriate, and change should be backwards compatible.

**Comment by gp1105739** [comment]
any update on it?
