### ISSUE TITLE
Some Doc image link is not valid

### ISSUE THREAD

**Issue by EunSeop** [datahub-project/datahub#8802]
Seems doc url link changed like below

- old : https://raw.githubusercontent.com/datahub-project/datahub/master/docs/imgs/
- new : https://raw.githubusercontent.com/datahub-project/static-assets/main/imgs/

But some links still shows old version url, so doc image is not showing.
https://datahubproject.io/docs/domains/
https://datahubproject.io/docs/tags/

![image](https://github.com/datahub-project/datahub/assets/6908807/6ca471e1-f2cc-4963-955f-fd269a1b4c23)

![image](https://github.com/datahub-project/datahub/assets/6908807/d16c0f3e-2a9b-4bca-ac13-9e075cdef953)

**Comment by hsheth2** [comment]
cc @yoonhyejin - I believe most of these issues are resolved now

**Comment by yoonhyejin** [comment]
Thanks for reporting on this @EunSeop , we pushed the fix here: https://github.com/datahub-project/datahub/pull/8771 & added markdown-link-check to spot the future broken links.

**Comment by yoonhyejin** [comment]
Will close this issue - Again, thanks so much for raising this! 👍
