### ISSUE TITLE
Compatibility of acryl-datahub package with Pydantic v2

### ISSUE THREAD

**Issue by lopezco** [datahub-project/datahub#8829]
**Describe the bug**
It is more a request than a bug...

`acryl-datahub` package is not compatible with Pydantic v2

```
The conflict is caused by:
    pydantic 2.3.0 depends on typing-extensions>=4.6.1
    acryl-datahub 0.11.0 depends on typing-extensions<4.6.0 and >=3.10.0.2; python_version >= "3.8"
```

**Comment by HHQuraishi** [comment]
Can you please suggest some beginner friendly issues.

**Comment by ihvol-freenome** [comment]
We also have this conflict due to the Pydantic version. is there a plan or expected date for Pydantic 2 support?

**Comment by hsheth2** [comment]
We definitely want to tackle this, but it's going to take a bit - pydantic v2 made a number of major changes, and we use pydantic quite extensively throughout our codebase.

**Comment by KulykDmytro** [comment]
interested also
