### ISSUE TITLE
Failed to ingest IBM Db2 metadata using SQLAlchemy source

### ISSUE THREAD

**Issue by deepak-garg** [datahub-project/datahub#8835]
**Describe the Bug**
While trying to ingest metadata for IBM Db2 using SQLAlchemy Source and dialect ibm-db-sa, following error occurred
`Traceback (most recent call last):
  File "/data/vdc/conda/condapub/svc_am_cicd/envs/dh-actions/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 373, in run
    for record_envelope in self.transform(record_envelopes):
  File "/data/vdc/conda/condapub/svc_am_cicd/envs/dh-actions/lib/python3.10/site-packages/datahub/ingestion/extractor/mce_extractor.py", line 77, in get_records
    raise ValueError(
ValueError: source produced an invalid metadata work unit: MetadataChangeEventClass(`

Source has produced invalid metadata workunit. It results in Datasets without SchemaMetadata.

Cli Version: 0.10.2
Datahub Version: v0.10.2
SqlAlchemy Version: 1.4.41

**To Reproduce**
Recipe Used
`source:
 type: sqlalchemy
 config:
   connect_uri: "ibm_db_sa://user:password@host.name.com:50000/database "
   platform: "db2"
   include_tables: true
   include_views: false
sink:
 type: "datahub-rest"
 config:
   server: ${DATAHUB_GMS_HOST}
   token: ${DATAHUB_GMS_TOKEN}`

**Expected behavior**
Complete Ingestion of DB2 Metadata 

**Screenshot**
As we can see no schemetadata has been pushed
<img width="1429" alt="Screenshot 2023-09-06 at 7 55 41 PM" src="https://github.com/datahub-project/datahub/assets/5126634/14aac9e0-81a1-4ee1-8929-2d55bfb8dd5b">

Attaching Logs:
exec-urn_li_dataHubExecutionRequest_sqlalchemy-2023_09_01-14_44_01.log

**Reason for the behaviour**
DataSetProperties Class field "description" has invalid data 
`DatasetPropertiesClass({'customProperties': {}, 'externalUrl': None, 'name': 'vvaf_drf_im_loc', 'qualifiedName': None, 'description': (None,),`

**I have fixed the issue and will raise PR**

**Comment by HHQuraishi** [comment]
Can you please suggest some beginner friendly issues.

**Comment by deepak-garg** [comment]
@HHQuraishi  Source produced invalid metadata workunit during ingestion
