### ISSUE TITLE
Tableau ingestion: Seeing "too many 500 error response" to GMS even though service is up and reachable

### ISSUE THREAD

**Issue by jinfluenza** [datahub-project/datahub#8887]
**Describe the bug**
We ingest large data from Tableau Cloud and have seen 20000 NODE_LIMIT. From my understanding, NODE_LIMIT can't be adjusted in Tableau Cloud version, so we lowered down the `page_size` in the recipe. This in return extend the ingestion duration by third causing it to go on for 3~4 hrs. Changing this made ingestion work for a while, however recently we hav been seeing seeing this weird behavior of below message.

```
 "HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /aspects?action=ingestProposal (Caused by ResponseError('too many 500 error responses'))"
```

This message shows up towards 2~3 hr mark and fails the ingestion. Also, not sure this is related, but I have been seeing GMS using loads of memory (almost 10gig+) even though there are no logs indicating any activities. And the memory usage compounds as if the application is experiencing memory leak. I've set the JAVA_OPTS to use 5g to 8g max, but to no avail. GMS itself is working fine and reachable.

**To Reproduce**
For the ingestion error:
1. Create a Tableau ingestion source with large data sets (we have about 80000+ total_records_written)
2. Set the recipe with `page_size` = 2
3. Wait for the data to be ingested and you should see this weird 500 errors cropping up

**Expected behavior**
  
Ingestion is successful with no failure error

**Screenshots**
<img width="747" alt="image" src="https://github.com/datahub-project/datahub/assets/113461575/340acbb4-6799-4ff3-927f-47205c106552">

**Desktop (please complete the following information):**
N/A as it is deployed to Cloud

**Additional context**

**Comment by hsheth2** [comment]
@jinfluenza are there any logs from GMS related to those 500 errors?

At first glance, this looks similar to the issue described here https://datahubspace.slack.com/archives/CUMUWQU66/p1696351247011519. We're still working on triaging and understanding root cause.

**Comment by jinfluenza** [comment]
No. From what I remember we wouldn't see the error on GMS. Yes I think the slack thread you share is similar to what I am seeing.

**Comment by zarb-trafilea** [comment]
I've got similar behavior in mi implementation using the 0.11 version
