### ISSUE TITLE
"DATAHUB_TELEMETRY_ENABLED" does not work when running a data ingestion

### ISSUE THREAD

**Issue by HolgerWang1999** [datahub-project/datahub#8893]
**Describe the bug**
The config named "DATAHUB_TELEMETRY_ENABLED" is setted false, but it still send telemetry when I am running a data ingestion from hive

**Screenshots**
part of the docker-compose.yml
![image](https://github.com/datahub-project/datahub/assets/128286646/759389a8-1773-437f-9e77-b311fbcda27f)

the debug log of send telemetry and the version of client
![image](https://github.com/datahub-project/datahub/assets/128286646/b633c36d-4404-4af6-86aa-b36f17e9b857)

**Comment by hsheth2** [comment]
Can you set the `DATAHUB_TELEMETRY_ENABLED` env var in the container/machine that is running the ingestion?

**Comment by HolgerWang1999** [comment]
Sorry... I don't know the way you mentioned to set env var in the container. I have set the env var in the docker-compose.yml, so I think that it will work in the container?🤣

**Comment by HolgerWang1999** [comment]
> Can you set the `DATAHUB_TELEMETRY_ENABLED` env var in the container/machine that is running the ingestion?

Sorry... I don't know the way you mentioned to set env var in the container. I have set the env var in the docker-compose.yml, so I think that it will work in the container?🤣

**Comment by hsheth2** [comment]
@HolgerWang1999 I've added some additional docs on how to fully disable telemetry. It looks like you're running the datahub cli locally, so you should use the `datahub telemetry disable` command in addition to the env variables.
