### ISSUE TITLE
Issues with Azure OIDC

### ISSUE THREAD

**Issue by deepak-khetwal-e** [datahub-project/datahub#8965]
I have installed Datahub application in a private AWS EKS cluster using [this helm chart](https://github.com/acryldata/datahub-helm). Now I am trying to set SSO integration via Azure AD in the same Datahub application by following [this link](https://datahubproject.io/docs/authentication/guides/sso/configure-oidc-react-azure).

I followed all the steps as it is. But when I tried to login via SSO, then it redirects to that Azure AD SSO url and after login I am thrown back to the login screen with error. Below is the error in datahub frontend pod.

ERROR controllers.SsoCallbackController - Caught exception while attempting to handle SSO callback!

Here is the OIDC config I used:

  oidcAuthentication:
      enabled: true
      provider: "azure"
      clientId: "client-id"
      clientSecretRef:
        secretRef: secret-name
        secretKey: secret-key
      scope: "openid profile email"
      azureTenantId: "azure-tenant-id"
    extraEnvs:
      - name: AUTH_VERBOSE_LOGGING
        value: "true"

Any Idea where I am doing wrong ?

**Comment by shristi-khandelwal** [comment]
I am also getting same issue, it would be amazing if anyone can provide any solution to this

**Comment by gschuurman** [comment]
@deepak-khetwal-e to get some more information check the logs of the datahub-frontend pods. these give some pretty acurate logging, In my case it seems that there is no email address send with the token, thus it's not possible to create a user.
