### ISSUE TITLE
ERROR: All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)

### ISSUE THREAD

**Issue by arthur-borcato** [datahub-project/datahub#8974]
**Describe the bug**
I'm trying to ingest the dbt data to a DataHub instance and I'm getting the following error for all the attempts:

`[2023-10-09 15:41:46,093] ERROR    {datahub.ingestion.run.pipeline:68} -  failed to write record with workunit upstreamLineage-for-urn:li:dataset:(urn:li:dataPlatform:snowflake,db_prod.structured_model_data_quality.dq_stripe_charges,PROD) with ("Unable to emit metadata to DataHub GMS: All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)", {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': "All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)", 'status': 400}) and info {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': "All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)", 'status': 400}`

The error above is happening to all entries, so nothing is loaded. In the end we can see that all the attempts are failing:
 **Pipeline finished with at least 983 failures; produced 983 events in 15.79 seconds.**

My recipe file:
**source:
  type: "dbt"
  config:
    manifest_path: "/target/manifest.json"
    catalog_path: "/target/catalog.json"
    sources_path: "/target/sources.json"
    test_results_path: "/target/run_results.json"
    target_platform: "snowflake"**

**To Reproduce**
The issue happens when I try to ingest the data to DataHub:
`datahub ingest -c dbt_recipe.dhub.yaml`

**Expected behavior**
Data loaded into DataHub

**Desktop:**
 - OS: happening on MacOS and Ubuntu

**Comment by ethan-cartwright** [comment]
Hi @arthur-borcato , can you share the GMS endpoint you are hitting? Are you using `http` instead of `https`?

**Comment by arthur-borcato** [comment]
Hi @ethan-cartwright. Thanks for asking. I figured out the root cause. It was happening due to the redirection on the nginx, changing the request from _post_ to _get_. DevOps team changed the redirection code to replicate the exact same request and now it's working fine, so I will close this issue.
