### ISSUE TITLE
There is an error with cli: Error: No such option: --name in datahub ingest deploy

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#8980]
**Describe the bug**

There is an error with cli: Error: No such option: --name in datahub ingest deploy

command `datahub ingest deploy --name "test" --schedule "5 * * * *" --time-zone "Europe/London" -c recipe.yaml`

**To Reproduce**

**Expected behavior**
Update datahub doc about cli or fix an issue with cli. 

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/44679014/923d0922-d9a8-4cc8-b960-43597d5d4f12)
![image](https://github.com/datahub-project/datahub/assets/44679014/50755249-660f-479c-9f12-cc6c799ff864)

**Desktop (please complete the following information):**

**Additional context**

**Comment by YuriyGavrilov** [comment]
@pedro93 `yu.gavrilov@S7-13-038829:~$ datahub --version
acryl-datahub, version 0.10.5.1
`

**Comment by pedro93** [comment]
Please use 0.1.1.0

**Comment by YuriyGavrilov** [comment]
@pedro93 Thanks for helping. actually it seams to be working. but got other error twith reciepies. will try to solve it ..
