### ISSUE TITLE
Column level lineage not working for Snowflake

### ISSUE THREAD

**Issue by ealtuna** [datahub-project/datahub#9013]
**Describe the bug**
I am ingesting a Snowflake account, with all the default configuration options. According to the documentation the column level lineage should be enable by default.

In the user interface I can see the lineage for tables. However, when I select column level lineage, it shows an empty results screen after selecting any of the columns.

**To Reproduce**
1. Ingest an Snowflake account.
2. Navigate to a table that is related with other views.
3. In the Schema tab go to the 3 dots at the right and select "See column lineage"

**Expected behavior**
I should see some information about the column lineage.

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/11414127/9f93180a-073d-4f77-94f8-7a95f0e5cc51)

**Desktop:**
 - OS: MacOS
 - Browser chrome

**Additional context**
I am running DataHub locally from Docker using `python3 -m datahub docker quickstart`

**Comment by hsheth2** [comment]
@ealtuna are you seeing table-level lineage on these tables?

**Comment by NoVeTe36** [comment]
> @ealtuna are you seeing table-level lineage on these tables?
Hi @hsheth2 i have also configured dbt with datathub. dbt run ok and does update in sql server. Datahub can also ingest dbt but can only see table-level lineage (as image below). But to my understand, if Datahub enables column-level, i should see it somewhere right?? Please fix me if i'm wrong 

![image](https://github.com/user-attachments/assets/76e8907f-de1f-42a2-bb97-f48f2cc30f1e)

**Comment by hsheth2** [comment]
@NoVeTe36 it's likely a case sensitivity issue - you must run the sql server ingestion with `convert_urns_to_lowercase` enabled, and then rerun dbt ingestion. See https://github.com/datahub-project/datahub/pull/11920

If issues persist, please open a new github issue with additional details

**Comment by NoVeTe36** [comment]
> @NoVeTe36 it's likely a case sensitivity issue - you must run the sql server ingestion with `convert_urns_to_lowercase` enabled, and then rerun dbt ingestion. See #11920
> 
> If issues persist, please open a new github issue with additional details

This does fix my issue. Thank you very much!
