### ISSUE TITLE
Not all ldap users synced properly 

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#9028]
**Describe the bug**
There is a strange bug when i synced ldap. 122 users synced properly but there are much more which is not.

The problem like this:

```
    "                           '... sampled of 122 total elements']},\n"
           " 'aspects': {'corpuser': {'corpUserInfo': 122, 'groupMembership': 122, 'status': 122}},\n"
           ' \'warnings\': {\'CN=XXXXXXXX Елена Владимировна,OU=Users,OU=ООО «С 7 ИНЖИНИРИНГ»,OU=Company,DC=group,DC=s7\': ["manager LDAP search '
           "failed: {'msgtype': 101, 'msgid': 24, 'result': 12, 'desc': 'Critical extension is unavailable', 'ctrls': [('1.2.840.113556.1.4.319', 0, "
           "b'0\\\\x84\\\\x00\\\\x00\\\\x00\\\\x05\\\\x02\\\\x01\\\\x00\\\\x04\\\\x00')], 'info': '00002040: SvcErr: DSID-031403F9, problem 5010 "
           '(UNAVAIL_EXTENSION), data 0\\\\n\'}"],\n'
```

**To Reproduce**

**Expected behavior**
Sync all the users without huge logs with warnings. 

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/44679014/ed723a13-eedc-4c6f-9133-bb4d4e6ca6b5)

**Desktop (please complete the following information):**
 - Version [e.g. 0.11.0]

**Additional context**
Overal ldap sync status is green but not all users can see datasets details. 

like this screen
![image](https://github.com/datahub-project/datahub/assets/44679014/18003712-1b76-4a60-a89b-2a2ce284ac42)

**Comment by hsheth2** [comment]
@YuriyGavrilov do you know what critical extension it is missing? I'm not sure this is enough information for us to debug this

**Comment by YuriyGavrilov** [comment]
@hsheth2 There was additional info from our support team that not all fields were filled in ad for such users. So after i fill additional info the problem gone with two users. anyway I am still receive this message in thee ldap logs: `0\\\\x84\\\\x00\\\\x00\\\\x00\\\\x05\\\\x02\\\\x01\\\\x00\\\\x04\\\\x00'`
