### ISSUE TITLE
Athena Table->View & View->View Lineage Not Implemented?

### ISSUE THREAD

**Issue by walter9388** [datahub-project/datahub#9165]
**Context and Expected Behavior**

I'm doing a preliminary investigation into Datahub for use throughout the company I work for, and I have had fun trying it out so far.

However, one of the main things that we would want to use Datahub for is lineage between all the Athena Tables/Views we have in the business, as this is where most of our analysis is done.

Looking through the [Athena source documentation](https://datahubproject.io/docs/generated/ingestion/sources/athena), I assumed this would be easy as there is the flags `include_view_lineage`/`include_view_column_lineage` for when `include_views=True`.

After spending a while trying to get the Athena source to work as I expected it to, I dug into the code and found that there is a `NotImplementedError` getting triggered each time I run the ingestion:
https://github.com/datahub-project/datahub/blob/f42cb95b928c071b8309cf7c3e9a0fe8b41d3a90/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L954-L963

`view_definition` is needed for `self._view_definition_cache`:
https://github.com/datahub-project/datahub/blob/f42cb95b928c071b8309cf7c3e9a0fe8b41d3a90/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L966-L967

`self._view_definition_cache` is need for the lineage function:
https://github.com/datahub-project/datahub/blob/f42cb95b928c071b8309cf7c3e9a0fe8b41d3a90/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L552-L576

**A Couple Questions?**
The `NotImpementedError` implies this behaviour is intentional and view based lineage is not possible yet. Before I invest any further time into Datahub, can I ask
1. Is the table->view & view->view lineage working for other SQL based databases? or is it just Athena which is not implemented, and an Athena adaptor needs to be written?
2. If it is just Athena which is the issue, is there a timeline/roadmap/version for when this expected behaviour is going to implemented?
3. If 2 is true, is there any clear roadmap documentation of what needs to be implemented and where? if you point it out to me I will happily spend a bit of time writing a PR to fix this explicit behaviour.

**Documentation Bug**
Regardless of the questions above, I think there maybe should have been a note in the documentation saying that this feature is not implemented yet as it would have saved me a lot of time trying to get it to work. Maybe there is a way to flag specific source features which aren't ready yet at each version in the documentation?

**Comment by bossenti** [comment]
@walter9388 Yes, you are right, lineage is currently not supported for Athena
This PR should enable the lineage for Athena 🙂
https://github.com/datahub-project/datahub/pull/9354
