### ISSUE TITLE
Search autocomplete causing site outages

### ISSUE THREAD

**Issue by timcosta** [datahub-project/datahub#9176]
**Describe the bug**
The search bar does not debounce autocomplete requests, so every character typed results in an outgoing call to graphql and the backing search cluster.

This causes load on the search cluster to go from 5-10 tps to over a hundred when more than one person is typing at once, which takes it down temporarily and results in a near total site outage until it recovers.

**To Reproduce**
1. Go to the search page like https://datahub.mycompany.com/search
2. Open network console
3. Start typing characters
4. See tens or hundreds of graphql requests being made, one for every character you type

Not sure if it's relevant, but our users all have a default view selected.

**Expected behavior**
Autocomplete should be debounced and only fire after a user hasnt entered a character for a few hundred milliseconds.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/datahub-project/datahub/assets/3916501/4f0f2d3b-0bd0-43a2-985f-07c2d6ad879e">

**Desktop (please complete the following information):**
 - OS: macos
 - Chrome
 - Version 118.0.5993.117

**Additional context**
This is an issue that causes total outages for us multiple times per day.

**Comment by chriscollins3456** [comment]
hey @timcosta here's a PR to address this issue! https://github.com/datahub-project/datahub/pull/9205

**Comment by timcosta** [comment]
Nice, thanks for fixing this @chriscollins3456!!
