### ISSUE TITLE
Inconsistent datasets name case in UI

### ISSUE THREAD

**Issue by remisalmon** [datahub-project/datahub#9276]
**Describe the bug**

The DataHub UI shows a (random?) mix of uppercase and lowercase dataset names for the same database/schema.

See the attached screenshot where Snowflake has only 1 SNOWPIPE.PUBLIC database/schema but DataHub shows 2 of those. The tables in this schema are split between those two.

**To Reproduce**
1. Ingest a Snowflake source (tested with `convert_urns_to_lowercase: true`)
2. Snowflake dataset are split between uppercase and lowercase in the UI

**Expected behavior**

The DataHub UI should not split datasets between uppercase and lowercase in the UI if their Snowflake identifiers are not explicitely uppercase or lowercase.

Snowflake query:
```
select table_schema, count(*)
from snowpipe.information_schema.tables
where table_schema in ('PUBLIC', 'public')
group by table_schema;
```
returns
```
TABLE_SCHEMA	COUNT(*)
PUBLIC	21
```
(21 = 13+8 in the screenshot...)

**Screenshots**

![image](https://github.com/datahub-project/datahub/assets/26257211/fe1625f7-abc8-4686-b3f8-5fe1b6fe0a63)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: DataHub v0.12.0

**Comment by remisalmon** [comment]
Seeing the same issue with Postgres sources, even more confusing where instance, database and schema are all lowercase but show in separate folders:
![image](https://github.com/datahub-project/datahub/assets/26257211/47f97d62-8a23-4b3e-9029-f9ff09368a87)

**Comment by hsheth2** [comment]
@remisalmon I have a hypothesis for this, related to https://github.com/datahub-project/datahub/pull/9227

If you re-run the snowflake/postgres ingestion, does this problem appear to go away?

**Comment by remisalmon** [comment]
> @remisalmon I have a hypothesis for this, related to #9227
> 
> If you re-run the snowflake/postgres ingestion, does this problem appear to go away?

Hi @hsheth2 thanks for taking a look! Yes this does go away when I re-run the ingestion (even with stateful ingestion enabled):
![image](https://github.com/datahub-project/datahub/assets/26257211/4a3fece6-9a3a-4c88-81e7-5eaccea11dca)

This is with:
```
> cat .env
DATAHUB_VERSION="v0.11.0"
> datahub version
DataHub CLI version: 0.11.0.5
Python version: 3.11.6 (main, Oct  2 2023, 22:00:51) [Clang 14.0.3 (clang-1403.0.22.14.1)]
```

**Comment by glasalvia** [comment]
Hi! We have the same issue!

DataHub CLI version: 0.12.0.3
Python version: 3.9.16 (main, Sep  8 2023, 00:00:00)

But when we re run the ingestión the issue is not solved, any suggestion?  Thanks!

**Comment by JoakimNil** [comment]
We are also seeing the same issue on Snowflake, which doesn't disappear when rerunning the ingestion.

Datahub version: 0.12.1.3

**Comment by hsheth2** [comment]
@JoakimNil that's surprising! Can we get some more details about your setup - are you using quickstart or a helm deployment? Have you tweaked any settings e.g. GMS replicas, async ingest, standalone mae/mce consumers?

**Comment by JoakimNil** [comment]
@hsheth2 We're using quickstart, with all default settings. The only thing that's changed is adding the Snowflake source, with this config:

```yaml
source:
    type: snowflake
    config:
        account_id: [REMOVED]
        warehouse: COMPUTE_WH
        username: datahub
        password: '${SNOWFLAKE_DATAHUB_PASSWORD}'
        incremental_lineage: true
        profiling:
            enabled: false
        stateful_ingestion:
            enabled: true
```

I will send you the resulting JSON in a DM in slack.

**Comment by YuriyGavrilov** [comment]
@hsheth2 hi, is this fix duplication issues with tableau, Postgres and etc. platforms?
