### ISSUE TITLE
Tags created by Python Emitter are not shown in the UI

### ISSUE THREAD

**Issue by ewaldmikolaj** [datahub-project/datahub#9296]
**Describe the bug**
The description for this story can be copied from [this issue](https://github.com/datahub-project/datahub/issues/6333) as it is about the same problem. I was working with Python Emitter and created few tags and assigned them to new Dataset. These tags appear in the UI under dataset name, but they are not available in the "Explore All" when I want to list all tags. 

**To Reproduce**
1. Run the following python code:
```
from datahub.ingestion.graph.client import DatahubClientConfig, DataHubGraph
from datahub.emitter.mce_builder import (
    make_dataset_urn,
    make_tag_urn,
)

from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.metadata.schema_classes import GlobalTagsClass, TagAssociationClass

graph = DataHubGraph(DatahubClientConfig(server=<server>, token=<token>))
new_tag = TagAssociationClass(make_tag_urn("TestTag"))
aspect = GlobalTagsClass(tags=[new_tag])

event= MetadataChangeProposalWrapper(entityUrn=<dataset_urn>, aspect=aspect)
graph.emit(event)
```

**Expected behavior**
Tags created by emitter should be visible in Data Hub UI.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Additional context**
I didn't attach any screenshots, as the same screenshots from the linked issue can be used to understand this problem.

**Comment by mayurinehate** [comment]
Hi @ewaldmikolaj the code you shared only assigns the tag to dataset however it does not create the tag in DataHub. You'll need to emit an aspect for tag urn, in order to create the tag.
```
from datahub.metadata.schema_classes import TagKeyClass

tag_urn = make_tag_urn("TestTag")
aspect = TagKeyClass(name=tag_urn.get_entity_id()[0]),

event= MetadataChangeProposalWrapper(entityUrn=tag_urn, aspect=aspect)
graph.emit(event)
```

Please confirm if this solves the issue you are facing. You can close the issue if it does.

**Comment by chriscollins3456** [comment]
@ewaldmikolaj can you confirm if mayuri's solution worked for you or not?
