### ISSUE TITLE
MSSQL ingestion fails due to missing pyodbc on Kubernetes with Helm charts

### ISSUE THREAD

**Issue by mvandeborne61** [datahub-project/datahub#9298]
**Describe the bug**
I run datahub on Kubernetes, deployed with Helm charts. The pod that performs the ingestions is the `acryl-datahub-actions` that relies on the image `acryldata/datahub-actions`. The image misses not only the `pyodbc` package, but also the Microsoft ODBC Driver for SQL Server.

I built a new image on top of the `acryldata/datahub-actions`, to install the missing dependencies, using this Dockerfile:
```
FROM acryldata/datahub-actions:head

USER 0
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
RUN pip install pyodbc
RUN pip install 'acryl-datahub[mssql]'
USER datahub
```
but, at runtime of the image, I still get an error "no module name pyodbc", because when the ingestion starts, it creates a python venv **at runtime** and pip installs its dependencies, except pyodbc, in here: `/tmp/datahub/ingest/venv-mssql-94b47a253025c09f/lib/python3.10/site-packages/` . This is an unpredictable path that does not exist when the image is built since the venv isn't yet created at build time.

I have 3 questions:
1. how to make pyodbc installed in the venv?
2. I cannot fathom having to rebuild a Docker image is the only way to add plugins or missing dependencies. There needs to exist a way to bring missing dependencies thanks to environments variables (that will pip install whatever is in the list), or a sidecar, or a volume, or init container, or something, right?
3. I see people tend to use the `datahub-ingestion` image, whereas in my helm release, it's the `datahub-actions` pod that runs the ingestions. Am I using the right image? If not, then the Kubernetes deployment doc should be adapted. I see there is a `datahub-ingestion-cron` sub-chart I could use but it's a cronjob, so it won't run ingestion on demand, I assume.

**Expected behavior**
An mssql source could be ingested with all the necessary dependencies pre-installed.

**Comment by vrychkov-repay** [comment]
@mvandeborne61, ingestions are executed by `/usr/local/bin/ingestion_common.sh` in virtual environments, which do not use system packages. To make your custom image work, you need to replace the script and add `python3 -m venv --system-site-packages $venv_dir`.

**Comment by vrychkov-repay** [comment]
@mvandeborne61, if you go system-site-packages way, mind that the official datahub helm chart may reference an outdated actions image, which may contain older/newer datahub packages. This is the case of the latest 0.3.11/0.3.12: helm charts install datahub v0.12.0 but actions image with datahub v0.10.4.2. It is fine if ingestion is executed in isolated vens. With system-site-packages, it makes sense to keep the datahub packages in the custom actions image in sync with deployment-wise datahub version. You can find the right image at https://github.com/acryldata/datahub-actions or make yourself. For example, 0.3.11/0.3.12 helm charts can be parameterized by the latest actions tag v0.0.14, which has datahub v0.12.0.

**Comment by mvandeborne61** [comment]
@vrychkov-repay , thank you for your response. 2 quick questions:
1. I couldn't find the script `ingestion-common.sh` anywhere in github. If I need to modify it, could you tell me where it is?
2. I find it strange to modify a Docker image and create a custom one to support something as common as SQL Server. wouldn't it make more sense to just add pyodbc and the Microsoft ODBC Driver for SQL Server in the list of dependencies installed in the official images?

**Comment by vrychkov-repay** [comment]
@mvandeborne61,
1. As far as I can see, the sctipt is generated at docker build time. You can take the file from the base image of your custom image. Don't forget to sync your copy after any upgrade (from my experience, the file hasn't been change for a while).
2. I guess, it is due to the choice of free/proprietary drivers.

**Comment by hsheth2** [comment]
You can use the `mssql-odbc` source type to get it to install the pyodbc package by default.

Additionally, the UI ingestion now supports setting custom dependencies and env variables as needed 
<img width="785" alt="image" src="https://github.com/datahub-project/datahub/assets/12566801/dceb8656-8d3e-474d-bbfc-4ff5bf1da618">

**Comment by vrychkov-repay** [comment]
@Anton-Trixter, as I mentioned above, I created a custom image with extra python packages and replaced `/usr/local/bin/ingestion_common.sh`. This is the code for an older version of datahub:
```bash
#!/bin/bash
 
 function create_venv {
     task_id=$1
     datahub_version="$2"
     plugin="$3"
     tmp_dir="$4"
     # we always install datahub-rest and datahub-kafka in addition to the plugin
     all_plugins="datahub-rest,datahub-kafka,${plugin}"
 
     extra_deps=()
     if [ "$plugin" = "hive" ]; then
         # Add dependency
         extra_deps+=("databricks-dbapi")
     fi
 
     venv_dir="$tmp_dir/venv-$plugin-${datahub_version}"
 
     echo 'Obtaining venv creation lock...'
     (
         flock --exclusive 200
         echo 'Acquired venv creation lock'
         SECONDS=0
 
         # Create tmp file to store requirements using provided recipe id.
         req_file="$tmp_dir/requirements-${task_id}.txt"
         touch "$req_file"
         if [ "$datahub_version" == "latest" ]; then
             echo "Latest version will be installed"
             echo "acryl-datahub[${all_plugins}]" > "$req_file"
         else
             echo "acryl-datahub[${all_plugins}]==$datahub_version" > "$req_file"
         fi
         # Install extra deps
         if [ ${#extra_deps[@]} -ne 0 ]; then
             for extra_dep in ${extra_deps[@]}; do
                 echo "$extra_dep" >> "$req_file"
             done
         fi
         if [ ! -d "$venv_dir" ]; then
             echo "venv doesn't exist.. minting.."
             python3 -m venv --system-site-packages $venv_dir  # inject "--system-site-packages" to the original script
             source "$venv_dir/bin/activate"
             pip install --upgrade pip wheel setuptools
             pip install -r $req_file
         else
             source "$venv_dir/bin/activate"
             if [ "$datahub_version" == "latest" ]; then
                 # in case we are installing latest, we want to always re-install in case latest has changed
                 pip install --upgrade -r $req_file
             fi
         fi
         rm $req_file
 
         echo "venv setup time = $SECONDS"
     ) 200>"$venv_dir.lock"
 
     source "$venv_dir/bin/activate"
 }
```
