### ISSUE TITLE
Airflow lineage plugin's Manual Lineage Integration does not support Jinja template

### ISSUE THREAD

**Issue by hauwenw** [datahub-project/datahub#9305]
**Describe the bug**
Airflow lineage plugin's Manual Lineage Integration does not support Jinja template, when inlets and outlets are written in templates, the lineage data sent to Datahub are not rendered.

**To Reproduce**
1. Follow the [code example](https://airflow.apache.org/docs/apache-airflow/2.2.0/lineage.html#lineage-backend) provided by Airflow
3. Setup Datahub and Airflow Integration using steps provided by [Datahub](https://datahubproject.io/docs/lineage/airflow)
4. Execute DAG on Airflow
5. Check and see unrendered lineage on Datahub UI

**Expected behavior**
Airflow lineage plugin's Manual Lineage Integration should be able to get rendered inlets / outlets information. 

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/22771083/69c84a71-c626-4506-8b3e-fe63d7fd588a)

**Desktop (please complete the following information):**
 - Airflow: 2.7.3
 - Docker images: head

**Additional context**
Below is my sample code:
```python
import datetime
import pendulum

from airflow.models import Param
from airflow.lineage import AUTO
from airflow.lineage.entities import File
from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.empty import EmptyOperator
from datetime import timedelta
from datahub_airflow_plugin.entities import Dataset
Dataset.template_fields = ('name',)

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "email": ["jdoe@example.com"],
    "email_on_failure": False,
    "execution_timeout": timedelta(minutes=5),
}

with DAG(
        dag_id="example_lineage",
        default_args=default_args,
        start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
        schedule="0 0 * * *",
        catchup=False,
        dagrun_timeout=datetime.timedelta(minutes=60),
        params = {
            "raw_db": Param("raw_db", type="string"),
            "raw_table_user_info": Param("user_info", type="string"),
            "raw_table_acct_txn": Param("acct_txn", type="string"),
        },
        default_view="tree",
    ) as dag:

    f_in = [Dataset(platform="glue", name="{{params.raw_db}}.{{params.raw_table_acct_txn}}"), ]
    outlets = [Dataset(platform="glue", name="{{params.raw_db}}.{{ts}}"), ]

    first_task = BashOperator(
        task_id="first_task",
        bash_command="echo 1", dag=dag, inlets=f_in, outlets=outlets)

    f_final = [Dataset(platform="glue", name="{{params.raw_db}}.{{params.raw_table_user_info}}"), ]
    second_task = EmptyOperator(
        task_id="second_task",
        dag=dag,
        inlets=AUTO,
        outlets=f_final)

    first_task >> second_task
```

**Ideas for fixing this issue**
`DataHubListener` is using `TaskHolder` to keep track of tasks, however, the rendering happens after `TaskHolder` stores the tasks, if we update the stored task's inlets/outlets in `on_task_instance_finish`, the rendered data can be sent with the task finished event to Datahub.

**Comment by hsheth2** [comment]
@hauwenw are you using the airflow plugin v1 or v2?

See https://datahubproject.io/docs/next/lineage/airflow/#datahub-plugin-v2

**Comment by hsheth2** [comment]
@hauwenw it seems like you've got a good idea for how to tweak the code to support this. Would you be willing to open a PR?
