### ISSUE TITLE
Redshift Views with No Schema Binding not showing column names in Datahub

### ISSUE THREAD

**Issue by gky249** [datahub-project/datahub#9309]
**Describe the bug**
Datahub doesn't seem to be able to fetch the column info for views created with NO SCHEMA BINDING. There is no column name, description info for views which have been created this way. The Schema tab for such entities is blank. THere are no errors in the ingestion jobs.

It has no issues with views created without "WITH NO SCHEMA BINDING﻿​".

**To Reproduce**
1. Create a view in Redshift with NO SCHEMA BINDING
```
CREATE
or REPLACE VIEW reporting.sales_orders_vw as
with Orders as ()
with no schema binding
```
2. Run the recipe to ingest such views from Redshift into Datahub
3. Check the Schema tab for the dataset
4. No column names, descriptions can be seen

**Expected behavior**
Column field names should be visible under the Schema tab on dataset details page

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/126741157/f888e868-f56a-4c83-b8d8-8410b0d8f4f6)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Chrome 109.0.5414.75
 - currently on release v12, but the problem exists since atleast v9.6

**Additional context**
Other metadata tools have faced this issue and it required code change to fix it.

**Comment by shifanm** [comment]
Hello, Is there anyone who can support or has any insights on this bug? :)

**Comment by shifanm** [comment]
Hello DataHub team, can anyone support in this please?

**Comment by chrijun** [comment]
This is an issue we've been having too running the latest CLI version v0.14.0.2.

**Comment by theresaxx** [comment]
Hi, I am also struggling to ingest late-binding views. How do you give access to pg_get_late_binding_view_cols() function? Would appreciate any help @chrijun :)

**Comment by chrijun** [comment]
> Hi, I am also struggling to ingest late-binding views. How do you give access to pg_get_late_binding_view_cols() function? Would appreciate any help @chrijun :)

For our setup we had setup IAM roles, and [these prerequisites](https://datahubproject.io/docs/generated/ingestion/sources/redshift#prerequisites) had gotten lost in the mix. So make sure that your user for Datahub has these permissions.

Here are some individual schemas that our user has access to: information_schema, pg_catalog, pg_internal, pg_automv, and then any schemas that your user will be reading from e.g. bronze, silver, gold etc.

**Comment by theresaxx** [comment]
Thank youuu for your help! I already granted these permissions... except for pg_automv, which redshift would not allow me...
