### ISSUE TITLE
W3C DCAT

### ISSUE THREAD

**Issue by ricardosouzamorais** [datahub-project/datahub#9342]
Some popular tools in the market use the W3C DCAT v2 or v3 standard to import and export metadata, ontologies and taxonomies.

Is there any plan to embrace it?

https://www.w3.org/TR/vocab-dcat-3/

**Comment by shirshanka** [comment]
Definitely interested in building compatibility with dcat! Would you be willing to provide an suggestion (rfc) for how we would map the DataHub metadata model to the DCAT standard?

**Comment by MatMoore** [comment]
Are you still interested in this @ricardosouzamorais? My organisation is quite likely to need this functionality in the future, so I may be able to collaborate on the RFC, or point you to others who can help.
