### ISSUE TITLE
500 errors during emitting metadata for the chart

### ISSUE THREAD

**Issue by NikPnnK** [datahub-project/datahub#9351]
**Describe the bug**
Im emitting metadata for datasets (using make_dataset_urn) and everything be ok, but when im start emitting chart or dashboard metadata (using make_dashboard_urn and make_chart_urn), im receive "('Unable to emit metadata to DataHub GMS: INTERNAL SERVER ERROR', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': 'INTERNAL SERVER ERROR', 'status': 500})". Idk if this is a bug or the expected behavior, but I decided to write here, since I have not seen a single working example of metadata emitting to the chart. If this is my mistake, please explain what I'm doing wrong

**Comment by samkessaram** [comment]
Hey @NikPnnK, we're seeing this as well. How were you able to resolve this?
