### ISSUE TITLE
Tableau ingestion incrorrectly parses Datasource upstream Clickhouse table

### ISSUE THREAD

**Issue by valeral** [datahub-project/datahub#9457]
Tableau source ingestion sucessfully detects upstream tables for Tableau's datasource but incorrectly parses it to dataset urn leading to absence of lineage due to no match with real tables urns ingested by Clickhouse ingestion.

**To Reproduce**
1. Ingest Clickhouse tables
2. Ingest Tableau Charts with Datasources from tables in Clickhouse
3. Go to lineage of the Tableau's Datasource in DataHub
4. There is no connection between Datasource and upstream table

**Expected behavior**
Lineage should reflect upstream table from datasource

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version 120.0.6099.71

**Additional context**

DataHub: 0.12.0
Tableau Server Version: 2023.3.0 (20233.23.1017.0948) 64-bit Linux
ClickHouse: 21.8.6.15
Clickhouse jdbc driver: clickhouse-jdbc-0.4.0-shaded.jar
Tableau Connector: clickhouse_jdbc_0.2.5.taco

I queried **upstreamLineage** for the datasource via

`datahub get urn --urn 'urn:li:dataset:(urn:li:dataPlatform:tableau,0bf95f1e-80d1-1887-692b-6994fee4453d,PROD)' -a upstreamLineage`

and see that there is a field lineage but in wrong format
```
      {
        "confidenceScore": 1.0,
        "downstreamType": "FIELD",
        "downstreams": [
          "urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0bf95f1e-80d1-1887-692b-6994fee4453d,PROD),store)"
        ],
        "upstreamType": "FIELD_SET",
        "upstreams": [
          "urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:clickhouse_jdbc,plkt:8123.dwh_presentation.active_user_by_day,PROD),store)"
        ]
      },
```

Specifically the urn "urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:clickhouse_jdbc,plkt:8123.dwh_presentation.active_user_by_day,PROD),store)" is wrongly parsed setting platform to **clickhouse_jdbc** and table to **plkt:8123.dwh_presentation.active_user_by_day**. The same error for the rest of upstream tables fields. There should be platform=**clickhouse** and table **dwh_presentation.active_user_by_day**.

**Comment by CodeForContribute** [comment]
Hi @hsheth2 can i take it ?

**Comment by hsheth2** [comment]
@CodeForContribute that'd be great!

**Comment by CodeForContribute** [comment]
@valeral ,
Could u please help me understand how are u ingesting the clickhouse tables and tableau datasets into datahub. Also how are u ingesting the lineage between the clickhouse and tableau datasets ?

**Comment by valeral** [comment]
> @valeral , Could u please help me understand how are u ingesting the clickhouse tables and tableau datasets into datahub. Also how are u ingesting the lineage between the clickhouse and tableau datasets ?

Hi @CodeForContribute,

Thanks for the replay!

The clickhouse tables as well as tableau datasets both ingested via standard ingestion pipelines created via Ingestion UI page. The lineage between the clickhouse and tableau datasources ingested automatically in tableau pipeline (using tableau metadata api under the hood)

**Comment by valeral** [comment]
the issue still remains in newest DataHub 0.13.0. One part with incorrect platform **clickhouse_jdbc** were fixed, but the rest with incorrect table name **plkt:8123.dwh_presentation.active_user_by_day** persists
