### ISSUE TITLE
Looker/Lookml ingestion doesn't support view inheritance

### ISSUE THREAD

**Issue by pedro-iatzky** [datahub-project/datahub#9465]
**Describe the bug**
Looker/Lookml ingestion does not handle inheritance correctly.
When I extract a view that is extending another the child view does not show the parent dimensions/measures.

**To Reproduce**
1. Create the following file in Lookml
```
explore: datahub_test {
  view_name: child_view
}

view: parent_view {
  sql_table_name: `dataset.table` ;;

  dimension: id {
    primary_key: yes
    type: string
    sql: ${TABLE}.id ;;
  }

  dimension: parent_dimension_1 {
    type: string
    sql: ${TABLE}.parent_dimension_1 ;;
  }

  measure: parent_count {
    type: count
  }
}

view: child_view {
  extends: [parent_view]

  dimension: child_dimension_1 {
    type: string
    sql: ${TABLE}.child_dimension_1 ;;
  }
}
```
2. Run Lookml & Looker ingestion

**Expected behavior**
I would expect to see two views extracted. The parent, and the child. Also, the _child_view_ should show the dimensions/measures inherited from parent

**Screenshots**

<img width="527" alt="image" src="https://github.com/datahub-project/datahub/assets/48163706/7b2c43fa-62cb-41b4-beaf-512decf3516e">

**Additional context**
Datahub version: v0.12.0

**Comment by hsheth2** [comment]
This seems like a bug in `get_including_extends` - for "list" fields like dimension/measure/etc, we need to merge with parent views instead of only fetching the value for the child field
