### ISSUE TITLE
[PowerBI] Missing DAX expressions

### ISSUE THREAD

**Issue by lucasfcnunes** [datahub-project/datahub#9489]
**Describe the bug**
Can't find DAX expression in Datahub only M code.

**To Reproduce**
- Follow PowerBI setup guide
- Refresh PowerBI data source
- Search for any `CALCULATE(...` that is defined in the datasets you fetched

**Expected behavior**
Find DAX expressions in Datahub search.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro 10.0.19045 Build 19045
 - Browser: Microsoft Edge 121.0.2256.2 (Official build) dev (64-bit)

**Additional context**

Log Info:

```json5
# Cli report:
{'cli_version': '0.12.0',
 'cli_entry_location': '/tmp/datahub/ingest/venv-powerbi-0.12.0/lib/python3.10/site-packages/datahub/__init__.py',
 'py_version': '3.10.11 (main, May 23 2023, 13:58:30) [GCC 10.2.1 20210110]',
 'py_exec_path': '/tmp/datahub/ingest/venv-powerbi-0.12.0/bin/python3',
 'os_details': 'Linux-5.15.120+-x86_64-with-glibc2.31',
 'peak_memory_usage': '162.49 MB',
 'mem_info': '162.49 MB',
 'peak_disk_usage': '65.54 GB',
 'disk_info': {'total': '101.2 GB', 'used': '65.49 GB', 'free': '35.7 GB'}}
```

**Comment by Sule26** [comment]
Same issue here

**Comment by gabriel-suela** [comment]
Same...
