### ISSUE TITLE
Datahub ingest uses external connections for upgrade checks

### ISSUE THREAD

**Issue by fackyhigh** [datahub-project/datahub#9522]
**Describe the bug**
Hello. My company has a requirement that all software should use only internal network. Our network software spotted that datahub connects to pypi.org and api.github.com. I found it in the code and it happens when the program tries to check new versions.
https://github.com/datahub-project/datahub/blob/651998de44afcac6efce44aadac6b04cb5e0ff30/metadata-ingestion/src/datahub/upgrade/upgrade.py#L54
https://github.com/datahub-project/datahub/blob/651998de44afcac6efce44aadac6b04cb5e0ff30/metadata-ingestion/src/datahub/upgrade/upgrade.py#L96
https://github.com/datahub-project/datahub/blob/651998de44afcac6efce44aadac6b04cb5e0ff30/metadata-ingestion/src/datahub/upgrade/upgrade.py#L152

**To Reproduce**
1. run Wireshark
2. run datahub ingest run
3. find the traffic to pypi and github

**Expected behavior**
Have a flag for CLI to disable updates checks or a configuration parameter.

**Comment by hsheth2** [comment]
@fackyhigh this is intended behavior. We'd accept a PR that adds an environment variable which disables the version checks, but it's not particularly high priority for us at the moment.
