### ISSUE TITLE
Platform tile and logo missing in the homepage 

### ISSUE THREAD

**Issue by ics1963** [datahub-project/datahub#9546]
I am using is 0.12.0 v, datahub is deployed using Kubernetes.

I have 2 issues,
1.  I have custom platform which is displaying in Homepage under platform, how do i add the logo to this ?
2. I have Dremio platform, but the platform tile is not displaying in the home page platform section.

does anybody know to solution for the above 2 issues.

**Comment by hsheth2** [comment]
@ics1963 you can use the `datahub put platform` command, as documented here https://datahubproject.io/docs/next/cli/#put-platform
