### ISSUE TITLE
Redash ingestion logs overwhelming on large Redash deployments

### ISSUE THREAD

**Issue by atjones0011** [datahub-project/datahub#9575]
**Describe the issue**
The [RedashSourceReport](https://github.com/datahub-project/datahub/blob/f4b05a892fb455651dba77c02dc5de07f37721b4/metadata-ingestion/src/datahub/ingestion/source/redash.py#L283) used to report the progress of a Redash ingestion job may result in very large reports on large Redash deployments that contain many items to scan or when filtering out a large number of items. These massive reports occur due to the data structure used for the [filtered](https://github.com/datahub-project/datahub/blob/f4b05a892fb455651dba77c02dc5de07f37721b4/metadata-ingestion/src/datahub/ingestion/source/redash.py#L285) and [timing](https://github.com/datahub-project/datahub/blob/f4b05a892fb455651dba77c02dc5de07f37721b4/metadata-ingestion/src/datahub/ingestion/source/redash.py#L298) fields. With the [default configuration of skipping draft items](https://github.com/datahub-project/datahub/blob/f4b05a892fb455651dba77c02dc5de07f37721b4/metadata-ingestion/src/datahub/ingestion/source/redash.py#L254-L256) and Redash's configuration to save drafts for any query run, the number of filtered items is expected to grow over time while the List data structure reports each item in the list on a separate line. With my team's ingestion job filtering hundreds of thousands of queries and this report being printed frequently, the log greatly impacts the performance of our ingestion job.

**Expected behavior**
As has been applied on other ingestion jobs, I propose we switch `filtered` to a LossyList and `timing` to a LossyDict. This will allow users to observe how many queries have been filtered and where the ingestion job is in its processing without printing many extra lines.

**Comment by hsheth2** [comment]
>  I propose we switch filtered to a LossyList and timing to a LossyDict

I agree, this seems like a pretty reasonable way to solve it.

Would you be willing to open a PR?

**Comment by atjones0011** [comment]
PR #9873 has been created to resolve this problem
