### ISSUE TITLE
An unknown error occurred code 500

### ISSUE THREAD

**Issue by rsrinivasaauto** [datahub-project/datahub#9583]
**Describe the bug**
Hi team, 
i am using docker quickstart 0.12.1, on aws ec2 - so a linux
Please help me on this issue
1. on the UI i get code 500 error
2. i cant see all metadata on UI, its available when searched with text or urn
3. on elastic search logs i see 
```
"stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:568) [elasticsearch-7.10.1.jar:7.10.1]",
```
4. on datahub gms i see lot of different errors like
- Failed to get entity counts
- Caused by: org.opensearch.OpenSearchStatusException: OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]
-  ERROR c.datahub.graphql.GraphQLController:110 - Errors while executing graphQL query: "query getEntityCounts-Error feeding bulk request. No retries left. Request: Failed to perform bulk request: index

[
<img width="1427" alt="Screenshot 2024-01-08 at 11 47 46" src="https://github.com/datahub-project/datahub/assets/103025795/b3222e3d-f986-4678-8ae7-668fbde77416">
](url)

**Comment by aLikan-jpg** [comment]
Hi, mate!
Faced the same problem. How did you solve this problem?
