### ISSUE TITLE
build gms failed in jdk1.8

### ISSUE THREAD

**Issue by LittleBird0616** [datahub-project/datahub#9586]
When I try to build the gms service in the jdk1.8 environment, I get the following error message：
`D:\0Code\99.openSource\datahub-0.12.0\buildSrc\src\main\java\io\datahubproject\OpenApiEntities.java:281: error: incompatible types: inference variable T has incompatible bounds
                .collect(Collectors.toSet());
                        ^
    equality constraints: String
    lower bounds: Object
  where T is a type-variable:
    T extends Object declared in method <T>toSet()`
This error is not reported in JDK11.

But，according to [https://github.com/datahub-project/datahub/tree/master/metadata-service#pre-requisites ](https://github.com/datahub-project/datahub/tree/master/metadata-service#pre-requisites )
JDK 1.8 is supposed to work properly.

**Comment by hsheth2** [comment]
@LittleBird0616 looks like those docs are outdated. We require Java 17.

I'll fix the docs shortly.

**Comment by LittleBird0616** [comment]
> @LittleBird0616 looks like those docs are outdated. We require Java 17.
> 
> I'll fix the docs shortly.

It seems that gms cannot be built using jdk17 until version 0.12.1. (The lombok version is earlier and does not adapt to the JDK of a later version.) Will the new version support JDK17? When will the new version be released?

**Comment by hsheth2** [comment]
The next release (0.13.0) will require JDK 17. I can't give a hard timeline, but we'll probably be releasing it in the next few weeks.
