### ISSUE TITLE
Metabase ingestion is using an old dashboard URL

### ISSUE THREAD

**Issue by 7onn** [datahub-project/datahub#9588]
**Describe the bug**
Metabase ingestion is [using an old dashboard URL](https://github.com/datahub-project/datahub/blob/ade7b61bdc89c355f887c57906e46923c4ca317d/metadata-ingestion/src/datahub/ingestion/source/metabase.py#L188). I'm running Metabase on v0.48.1 and for this version, the [dashboard endpoint](https://www.metabase.com/docs/latest/api/dashboard#get-apidashboardpublic) changed a little and it requires a /public added on the aforementioned URL in DataHub's code.

**To Reproduce**
1. Setup Metabase v0.48.1
2. Setup the latest version of DataHub
3. Add some dashboard with public sharing enabled
4. Run DataHub Ingestion sourcing it
5. See error

**Expected behavior**
I'd expect DataHub ingestions'code to be on sync with the source's modern version

**Additional context**
I'd be willing to contribute on the fix. I just want to understand if we need to "just fix it" or make it backward compatible e.g. by making the dashboard endpoint configurable in the [source](https://datahubproject.io/docs/generated/ingestion/sources/metabase/#config-details).

**Comment by evgeniybobok** [comment]
Metabase removed GET /api/dashboard from their API in 0.48.0 https://github.com/metabase/metabase/issues/35365

> To list all the dashboards using the API, third parties can still use GET /api/collection to get the list of collections, and for each collection use GET /api/collection/:id/items?models=dashboard, and finally GET /api/dashboard/:id to get a specific dashboard

**Comment by evgeniybobok** [comment]
And they are [going to restore](https://github.com/metabase/metabase/pull/37458) GET /api/dashboard for backwards compatibility, but
> No guarantees will be made to keep it up-to-date with the officially supported alternative, which is to use GET /api/collection
Also, this is just a temporary fix: https://github.com/metabase/metabase/issues/37455
> We should restore it for the next release of 48, with a deprecation notice to remove in the next release.

**Comment by lopezco** [comment]
metabase team restored the dashboard endpoint on version `v0.48.3` (https://github.com/metabase/metabase/pull/37458)
However, I think the the API response changed format as the `ordered_cards` doesn't exist anymore replaced by `dashcards`.

A quick patch could be something like: https://github.com/datahub-project/datahub/commit/d45c680bd2960f3ae208ac5207df146f06f05293

I still think that the ingestion via their new API should also be implemented.

**Comment by 7onn** [comment]
@lopezco my PR is taking care of that: https://github.com/datahub-project/datahub/pull/9631/files#diff-f7b9a31becd260463b7d2a4670f5c1ce000be42f0a35fc4128cf9efce90fdf05R271
