### ISSUE TITLE
TypeError using json_schema.JsonSchemaSourceConfig

### ISSUE THREAD

**Issue by jakobhanna** [datahub-project/datahub#9616]
**Describe the bug**
To ingestion json-schema metadata with our own emitter (using the python sdk) we use the `datahub.ingestion.source.schema.json_schema.JsonSchemaSourceConfig` class. Until now we could emit `*.json` files easily with the json-schema source (files, url schemas etc). Actually we used `JsonSchemaSource` with `JsonSchemaSourceConfig`. From the pypy package version `12.1.1` to `12.1.2` now an `TypeError` is thrown.

**To Reproduce**
1. Install `pip install acryl-datahub[datahub-rest] >= 12.1.2`
2. Import `datahub.ingestion.source.schema.json_schema.JsonSchemaSourceConfig`
3. Instantiate class object:
```
JsonSchemaSourceConfig(
            path="https://json-schema.org/draft/2020-12/schema",
            platform="json-schema")
```

**Error**
```
>       source=json_schema.JsonSchemaSourceConfig(
            path="https://json-schema.org/draft/2020-12/schema",
            platform="json-schema")

src/tests/events_test.py:279: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../micromamba/envs/datahub-management/lib/python3.10/site-packages/pydantic/_internal/_decorators_v1.py:107: in wrapper2
    return val2(value)
../../micromamba/envs/datahub-management/lib/python3.10/site-packages/datahub/ingestion/source/schema/json_schema.py:95: in download_http_url_to_temp_file
    if isinstance(v, AnyHttpUrl):
../../micromamba/envs/datahub-management/lib/python3.10/typing.py:994: in __instancecheck__
    return self.__subclasscheck__(type(obj))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = typing.Annotated[pydantic_core._pydantic_core.Url, UrlConstraints(max_length=None, allowed_schemes=['http', 'https'], host_required=None, default_host=None, default_port=None, default_path=None)]
cls = <class 'pydantic_core._pydantic_core.Url'>

    def __subclasscheck__(self, cls):
>       raise TypeError("Subscripted generics cannot be used with"
                        " class and instance checks")
E       TypeError: Subscripted generics cannot be used with class and instance checks

../../micromamba/envs/datahub-management/lib/python3.10/typing.py:997: TypeError
```

**Expected behavior**
Until version 12.1.1 the `JsonSchemaSourceConfig` Object was created with no hussle. Class should be usable, type is `AnyHttpUrl` so the path link should work.

**Desktop (please complete the following information):**
 - pypy `acryl-datahub[datahub-rest]` Version 0.12.2.
 - Datahub Version 12.0

**Comment by shonigbaum** [comment]
Any news on this? Facing the same problem.

**Comment by hsheth2** [comment]
Please make sure to use `pip install acryl-datahub[datahub-rest,json-schema]`. This looks like it's missing some dependencies.

Going to close this issue for now, but feel free to ping if the above approach doesn't work.
