### ISSUE TITLE
Unknown aspect browsePathsV2 for entity dataset

### ISSUE THREAD

**Issue by HaoXuAI** [datahub-project/datahub#9723]
**Describe the bug**
Error while doing ingestion from Athena to Datahub.

Source: Athena
Sink: datahub-rest
Error log:

`failed to write record with workunit urn:li:dataset:(urn:li:dataPlatform:athena,analytic.dau_v1_0,PROD)-browsePathsV2 with ('Unable to emit metadata to DataHub GMS: java.lang.RuntimeException: Unknown aspect browsePathsV2 for entity dataset', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': 'java.lang.RuntimeException: Unknown aspect browsePathsV2 for entity dataset', 'status': 500, 'id': 'urn:li:dataset:(urn:li:dataPlatform:athena,analytic.dau_v1_0,PROD)'}) and info {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': 'java.lang.RuntimeException: Unknown aspect browsePathsV2 for entity dataset', 'status': 500, 'id': 'urn:li:dataset:(urn:li:dataPlatform:athena,analytic.dau_v1_0,PROD)'}`

**To Reproduce**

**Expected behavior**
Successfully finished the ingestion.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Version 0.11.0.4

**Additional context**

**Comment by hsheth2** [comment]
This means your cli version is too new for the version of backend that you're using. Please upgrade your datahub setup to the latest version. If the issue persists, please let us know!
