### ISSUE TITLE
Error for ingesting Oracle metadata in CLI > 0.10.5

### ISSUE THREAD

**Issue by lima-renan** [datahub-project/datahub#9752]
I'm using DataHub v0.12.0 on Azure AKS. I have this error when ingesting Oracle metadata via cronjob using the CLI in version 0.12.1.1(Docker tag: acryldata/datahub-ingestion:v0.12.1).: sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so : cannot open shared obejct file: No such file or directory". 

This error does not occur with the CLI in version 0.10.5 (Docker tag: acryldata/datahub-ingestion:v0.10.5).

**To Reproduce**

 1. Set up an Oracle Database;
 2. Run ingestion for this database through the cronjob on AKS or K8s using docker tag acryldata/datahub-ingestion:v0.12.1.

**Comment by david-leifker** [comment]
Definitely not finding this in the image. I would have expected it to be included with [this](https://github.com/datahub-project/datahub/blob/master/docker/datahub-ingestion-base/Dockerfile#L79C5-L79C142) step in the docker build.

**Comment by lima-renan** [comment]
Possibly related to following alredy reported issue:  #4486

**Comment by lima-renan** [comment]
@david-leifker , I opened a PR for this: https://github.com/datahub-project/datahub/pull/11001
