### ISSUE TITLE
Error: No such option: --arch when issuing datahub docker quickstart --arch m1

### ISSUE THREAD

**Issue by JxKim** [datahub-project/datahub#9755]
**Describe the bug**
there is no option: --arch for sub command datahub docker quickstart 

**To Reproduce**
python 3.6.8

**Expected behavior**

**Screenshots**

**Desktop 
 - OS:  mac os apple m1 chip

**Additional context**

**Comment by hsheth2** [comment]
@JxKim have you verified that you're on the latest datahub cli?

`datahub --version` should show 0.12.1.5

Note that we dropped support for Python 3.6 a while ago (and dropped python 3.7 a month ago), which might be why you're getting an outdated CLI version.
