### ISSUE TITLE
"total" value does not match the actual number of objects in GraphQL query result

### ISSUE THREAD

**Issue by Stefs-2142** [datahub-project/datahub#9775]
**Describe the bug**

**To Reproduce**
1. Go to 'https://datahub-instance/api/graphiql'
2. Run next query 
```
query listIngestionSources($input: ListIngestionSourcesInput!) {
                  listIngestionSources(input: $input) {
                    start
                    count
                    total
                    ingestionSources {
                      urn
                      name
                      schedule {
                        interval
                        timezone
                      }
                      platform {
                        name
                      }
                      type
                      config {
                        version
                        executorId
                        recipe
                      }
                    }
                  }
                }
```
with variables:
`{"input": {"start": 0, "count": 1000}}`
          
3. Check length of resulted collection - ingestionSources. Compare it with value from total
4. In my case In my case, the total differs by 1 more than the actual number of elements.
808 in total, 807 - actual

**Expected behavior**
total == actual 

**Screenshots**
![ingestions](https://github.com/datahub-project/datahub/assets/23437843/1b7ae6f3-158e-47f1-b2db-e3435699124e)

**Desktop (please complete the following information):**
 - Version DataHub 0.12

**Comment by YuriyGavrilov** [comment]
+1

**Comment by Stefs-2142** [comment]
Also noticed mismatch in result with next query properties: 
```
result = datahub_prod._get_ingestion_sources(start=0, count=753)
len(result['listIngestionSources']['ingestionSources'])
752
```

**Comment by YuriyGavrilov** [comment]
It is actual

**Comment by trialiya** [comment]
@Stefs-2142 @YuriyGavrilov 
Your problem may be due to data inconsistency between elasticsearch and ebean. You need to compare the document count in datahubingestionsourceindex_v2 index with the result of this select:
```sql
select count(*)
from metadata_aspect_v2
where aspect = 'dataHubIngestionSourceKey' and version = 0;
```
If `select count(*)` returns a smaller number, it will mean a few dataHubIngestionSource entities has been deleted from your database.

**Comment by trialiya** [comment]
@YuriyGavrilov 
There are two options:
1. If you can identify the excess documents in datahubingestionsourceindex_v2, you can simply delete them, for example using `Delete API`.
2. !!!Before using this option, make sure you know how to use [Restore Indices](https://datahubproject.io/docs/api/restli/restore-indices)!!!

Clear datahubingestionsourceindex_v2 by `Delete by query API`: 
```
POST datahubingestionsourceindex_v2/_delete_by_query
{
  "query": {
     "match_all" : {}
  }
}

```
and then use [Restore Indices](https://datahubproject.io/docs/api/restli/restore-indices) with this body:
```json
{
	"urnLike": "urn:li:dataHubIngestionSource:%",
	"start": 0,
	"batchSize": 10000
}
```
