### ISSUE TITLE
Dynamo DB IAM Role (STS) support

### ISSUE THREAD

**Issue by sappusaketh** [datahub-project/datahub#9815]
The current [DynamoDB integration in Datahub relies on static credentials](https://datahubproject.io/docs/generated/ingestion/sources/dynamodb#config-details), which may not be the most secure or flexible solution in some environments. To enhance the security posture and flexibility of the integration, I suggest adding support for IAM roles. By leveraging the AWS Security Token Service (STS), Datahub could assume IAM roles dynamically, obtaining temporary credentials that provide a more secure way to interact with DynamoDB

[Source code link](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/dynamodb/dynamodb.py#L226:L231)

**Comment by darnaut** [comment]
Fixed by #10419
