### ISSUE TITLE
Sql Parsing incorrect when Hive variables are used

### ISSUE THREAD

**Issue by travis-cook-sfdc** [datahub-project/datahub#9830]
**Describe the bug**
When using the airflow plugin to parse SQL that includes Hive variables, the inlets and outlet tables end up as `None.hiveconf`.

**To Reproduce**
```python
from datahub.utilities.sqlglot_lineage import sqlglot_lineage

sql = """
set src_table=dw.foo;
set dest_table=dw.bar; 

insert overwrite table ${hiveconf:dest_table}
partition (ds='2024-01-01')
select
    bat
    , baz
from
    ${hiveconf:src_table};
"""

sqlglot_lineage(sql, ...)
```

**Expected behavior**
This function should return an inlet of `dw.foo` and an outlet of `dw.bar`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: `121.0.6167.160`

Datahub Version: `0.12.0`

**Additional context**

**Comment by travis-cook-sfdc** [comment]
@hsheth2 - I think you've been doing a bunch of work on the sql lineage, so wanted to make you aware of this

**Comment by travis-cook-sfdc** [comment]
I've raised this with the sqlglot team, and they don't intend to support it: https://github.com/tobymao/sqlglot/issues/2958

**Comment by hsheth2** [comment]
We recently added the "sql parsing aggregator", whose purpose is to process a sequence of SQL statements and aggregate lineage/usage info across them https://github.com/datahub-project/datahub/pull/9786

This sort of variable resolution logic probably belongs in the aggregator, and the underlying `sqlglot_lineage` method should continue to only process one SQL statement.

While I'd be open to a PR here, this isn't something that's particularly high priority for us at the moment.

**Comment by travis-cook-sfdc** [comment]
Ah, that makes sense.  I'll look into using & supporting the aggregator.

Is the aggregator stuff released yet?  Looks like it was merged in ~4 days ago
