### ISSUE TITLE
DataHub CLI import Error 

### ISSUE THREAD

**Issue by KaYunKIM** [datahub-project/datahub#9909]
**Describe the bug**
There is an error when running metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py, which fails to import:

1. 'TableauUpstreamReference' from 'datahub.ingestion.source.tableau_common'.

```ImportError: cannot import name 'TableauUpstreamReference' from 'datahub.ingestion.source.tableau_common' ```

However, when I comment out this module and rerun it works fine which means another module 'TableauLineageOverrides' from the same file is imported well.

2. 'from datahub.sql_parsing.sqlglot_lineage import SqlParsingResult'
```
ModuleNotFoundError: No module named 'datahub.sql_parsing'
```

3. 'from tests.test_helpers import mce_helpers, test_connection_helpers'
```
ModuleNotFoundError: No module named 'tests'
```

**To Reproduce**
1. Go to 'metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py'
2. Run the file
5. See error

**Expected behavior**
Import Class works well

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a
 - Python Version: 3.9

**Additional context**

**Comment by hsheth2** [comment]
The tests aren't run directly

If you've activated the metadata-ingestion venv and run the tests files as `pytest tests/...`, things should resolve correctly.

I'm going to close this for now, but let us know if you still have issues.
