### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by nevo11** [datahub-project/datahub#9981]
i can not load the ur lof <datahub-dns>/api/graghql in close network because it try to get resources from "https://unpkg.com"

i will want i way to configure if i want to get that from internt or already pull that to the code.

**Comment by hsheth2** [comment]
@nevo11 can you provide a stack trace for this?

**Comment by nevo11** [comment]
https://unpkg.com/react@16/umd/react.development.js net::ERR_NAME_NOT_RESOLVED
https://unpkg.com/react-dom@16/umd/react-dom.development.js net::ERR_NAME_NOT_RESOLVED
https://unpkg.com/graphiql/graphiql.min.css net::ERR_NAME_NOT_RESOLVED
https://unpkg.com/graphiql/graphiql.min.js net::ERR_NAME_NOT_RESOLVED
Uncaught RefrenceError: ReactDOM is not defined at graphiql:65:5

**Comment by hsheth2** [comment]
@nevo11 sounds like an issue with your network's DNS setup. We depend on a CDN for that, and you're not able to resolve the hostname correctly.
